# Fase 2 (paso 2) — Entrenamiento y evaluación de YOLOv8

## Configuración
- Dataset: `dataset_split/` con split original de Roboflow (198 train / 8 valid / 8 test, 5 clases).
- Modelo: **YOLOv8n** preentrenado en COCO.
- 200 épocas, `patience=50`, `imgsz=640`, `batch=8`.
- Augmentations conservadoras: HSV moderado, fliplr, sin mosaic ni mixup (perjudican datasets pequeños con escenas heterogéneas).
- Dispositivo: auto (MPS si Apple Silicon) con `PYTORCH_ENABLE_MPS_FALLBACK=1`.

## Salidas
- `runs/detect/coins_v4/` — pesos, métricas, gráficos generados por Ultralytics.
- `model/best.pt` — copia del mejor checkpoint para uso posterior.
- `reports/metrics_summary.csv`, `reports/metrics_per_class_valid.csv`.

In [1]:
from __future__ import annotations
import os
os.environ.setdefault("PYTORCH_ENABLE_MPS_FALLBACK", "1")

import shutil
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import torch
from ultralytics import YOLO

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
DATA_YAML = ROOT / "dataset_split" / "data.yaml"
MODEL_DIR = ROOT / "model"; MODEL_DIR.mkdir(exist_ok=True)
REPORTS = ROOT / "reports"; REPORTS.mkdir(exist_ok=True)
RUNS_DIR = ROOT / "runs"
RUN_NAME = "coins_v4"

DEVICE = "mps" if torch.backends.mps.is_available() else ("cuda" if torch.cuda.is_available() else "cpu")
print(f"DATA   = {DATA_YAML}")
print(f"DEVICE = {DEVICE}")
print(f"RUN    = {RUNS_DIR / 'detect' / RUN_NAME}")

DATA   = /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_split/data.yaml
DEVICE = mps
RUN    = /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/detect/coins_v4

## 1. Entrenamiento

In [2]:
prev = RUNS_DIR / "detect" / RUN_NAME
if prev.exists():
    shutil.rmtree(prev)

model = YOLO("yolov8n.pt")
results = model.train(
    data=str(DATA_YAML),
    epochs=200,
    patience=50,
    imgsz=640,
    batch=8,
    device=DEVICE,
    project=str(RUNS_DIR / "detect"),
    name=RUN_NAME,
    exist_ok=True,
    seed=42,
    deterministic=True,
    plots=True,
    verbose=True,
    # Augmentations conservadoras para dataset pequeño y heterogéneo
    hsv_h=0.015, hsv_s=0.5, hsv_v=0.3,
    degrees=5.0, translate=0.05, scale=0.3,
    fliplr=0.5, flipud=0.0,
    mosaic=0.0, mixup=0.0,
    erasing=0.0,
)
print("Entrenamiento finalizado.")

Ultralytics 8.4.47 🚀 Python-3.12.7 torch-2.11.0 MPS (Apple M3 Pro)

engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_split/data.yaml, degrees=5.0, deterministic=True, device=mps, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=200, erasing=0.0, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.5, hsv_v=0.3, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=0.0, multi_scale=0.0, name=coins_v4, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=50, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/detect, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/detect/coins_v4, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.3, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.05, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None

Overriding model.yaml nc=80 with nc=5

                   from  n    params  module                                       arguments

  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]

  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]

  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]

  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]

  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]

  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]

  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]

  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]

  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]

  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]

 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']

 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]

 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']

 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]

 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]

 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]

 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]

 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]

 22        [15, 18, 21]  1    752287  ultralytics.nn.modules.head.Detect           [5, 16, None, [64, 128, 256]]

Model summary: 130 layers, 3,011,823 parameters, 3,011,807 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights

Freezing layer 'model.22.dfl.conv.weight'

train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 108.6±45.8 MB/s, size: 25.7 KB)

train: Scanning /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_split/train/labels... 198 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 198/198 6.3Kit/s 0.0s

train: New cache created: /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_split/train/labels.cache

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 452.4±217.5 MB/s, size: 31.8 KB)

val: Scanning /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_split/valid/labels... 8 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 8/8 5.6Kit/s 0.0s

val: New cache created: /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_split/valid/labels.cache

optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...

optimizer: AdamW(lr=0.001111, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)

Plotting labels to /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/detect/coins_v4/labels.jpg...

Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/detect/coins_v4
Starting training for 200 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      1/200      2.24G       1.82       3.97      2.356         15        640: 0% ──────────── 0/25  1.4s

      1/200      2.24G      1.571      3.958      1.949         27        640: 4% ──────────── 1/25 1.6s/it 1.8s<37.5s

      1/200      2.24G      1.391      3.911      1.716         33        640: 8% ╸─────────── 2/25 1.1it/s 2.3s<20.8s

      1/200      2.24G      1.355      3.806      1.698         25        640: 12% ━─────────── 3/25 1.4it/s 2.8s<16.0s

      1/200      2.24G      1.381       3.81      1.834         30        640: 16% ━╸────────── 4/25 1.6it/s 3.2s<12.8s

      1/200      2.24G      1.369      3.797       1.89         14        640: 20% ━━────────── 5/25 1.9it/s 3.6s<10.8s

      1/200      2.24G      1.336      3.744       1.81         31        640: 24% ━━╸───────── 6/25 2.0it/s 4.0s<9.3s

      1/200      2.24G      1.258      3.699      1.706         38        640: 28% ━━━───────── 7/25 2.2it/s 4.4s<8.3s

      1/200      2.24G      1.229      3.722      1.698         19        640: 32% ━━━╸──────── 8/25 2.3it/s 4.8s<7.3s

      1/200      2.26G      1.197      3.696      1.674         22        640: 36% ━━━━──────── 9/25 2.3it/s 5.3s<6.9s

      1/200      2.26G      1.156       3.67      1.622         18        640: 40% ━━━━╸─────── 10/25 2.3it/s 5.7s<6.5s

      1/200      2.26G      1.124      3.635      1.585         14        640: 44% ━━━━━─────── 11/25 2.4it/s 6.1s<5.9s

      1/200      2.26G      1.099      3.606      1.565         14        640: 48% ━━━━━╸────── 12/25 2.5it/s 6.4s<5.2s

      1/200      2.26G      1.071      3.589      1.555          8        640: 52% ━━━━━━────── 13/25 2.4it/s 6.9s<5.0s

      1/200      2.26G      1.052      3.543      1.524         30        640: 56% ━━━━━━╸───── 14/25 2.4it/s 7.3s<4.6s

      1/200      2.26G      1.035      3.546      1.533          8        640: 60% ━━━━━━━───── 15/25 2.5it/s 7.7s<4.0s

      1/200      2.26G      1.034      3.528      1.517         22        640: 64% ━━━━━━━╸──── 16/25 2.5it/s 8.1s<3.6s

      1/200      2.26G      1.021      3.495      1.506         15        640: 68% ━━━━━━━━──── 17/25 2.5it/s 8.5s<3.2s

      1/200      2.26G      1.012      3.463      1.484         30        640: 72% ━━━━━━━━╸─── 18/25 2.5it/s 8.9s<2.8s

      1/200      2.26G      1.012      3.448      1.482         20        640: 76% ━━━━━━━━━─── 19/25 2.5it/s 9.3s<2.4s

      1/200      2.26G      1.002      3.411      1.462         23        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 9.8s<2.1s

      1/200      2.26G      1.005      3.386      1.462         21        640: 84% ━━━━━━━━━━── 21/25 2.4it/s 10.2s<1.7s

      1/200      2.26G     0.9972      3.357       1.47          9        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 10.9s<1.5s

      1/200      2.26G     0.9928      3.343      1.452         57        640: 92% ━━━━━━━━━━━─ 23/25 2.2it/s 11.3s<0.9s

      1/200      2.27G     0.9846      3.316      1.439         15        640: 96% ━━━━━━━━━━━╸ 24/25 2.0it/s 12.0s<0.5s

      1/200      2.27G     0.9846      3.316      1.439         15        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 12.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.8it/s 0.5s

                   all          8          8    0.00451          1      0.576      0.384

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      2/200      2.28G     0.6921      3.033      1.328         20        640: 0% ──────────── 0/25  0.6s

      2/200       2.3G     0.6948      2.724      1.123         14        640: 4% ──────────── 1/25 1.1s/it 0.9s<26.4s

      2/200       2.3G     0.7345      2.719      1.128         34        640: 8% ╸─────────── 2/25 1.3it/s 1.3s<17.8s

      2/200       2.3G     0.7513      2.627      1.094         24        640: 12% ━─────────── 3/25 1.6it/s 1.8s<13.4s

      2/200       2.3G      0.769      2.553      1.216          8        640: 16% ━╸────────── 4/25 1.9it/s 2.1s<10.8s

      2/200       2.3G     0.7969      2.504       1.23         23        640: 20% ━━────────── 5/25 2.0it/s 2.6s<9.8s

      2/200       2.3G     0.7812      2.536      1.234         17        640: 24% ━━╸───────── 6/25 2.1it/s 3.0s<9.1s

      2/200       2.3G     0.7868       2.58      1.261         20        640: 28% ━━━───────── 7/25 2.2it/s 3.5s<8.4s

      2/200       2.3G     0.8039      2.575      1.253         32        640: 32% ━━━╸──────── 8/25 2.2it/s 3.9s<7.8s

      2/200       2.3G     0.7922       2.59      1.251          8        640: 36% ━━━━──────── 9/25 2.4it/s 4.3s<6.7s

      2/200       2.3G     0.8089      2.539      1.231         32        640: 40% ━━━━╸─────── 10/25 2.4it/s 4.6s<6.2s

      2/200       2.3G     0.8142      2.532      1.232         14        640: 44% ━━━━━─────── 11/25 2.5it/s 5.0s<5.6s

      2/200       2.3G     0.8097      2.484      1.211         34        640: 48% ━━━━━╸────── 12/25 2.5it/s 5.4s<5.2s

      2/200       2.3G      0.805      2.444        1.2         30        640: 52% ━━━━━━────── 13/25 2.5it/s 5.8s<4.9s

      2/200       2.3G     0.8112      2.432      1.207         20        640: 56% ━━━━━━╸───── 14/25 2.5it/s 6.2s<4.4s

      2/200       2.3G     0.8124      2.432      1.207         27        640: 60% ━━━━━━━───── 15/25 2.5it/s 6.6s<4.0s

      2/200       2.3G     0.8139      2.463      1.219         19        640: 64% ━━━━━━━╸──── 16/25 2.4it/s 7.1s<3.7s

      2/200       2.3G     0.8142      2.468      1.224         14        640: 68% ━━━━━━━━──── 17/25 2.4it/s 7.5s<3.3s

      2/200       2.3G     0.8084      2.458      1.214         27        640: 72% ━━━━━━━━╸─── 18/25 2.4it/s 7.9s<2.9s

      2/200       2.3G     0.8234      2.439      1.228         23        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.3s<2.5s

      2/200       2.3G     0.8217      2.468      1.244          8        640: 80% ━━━━━━━━━╸── 20/25 2.5it/s 8.7s<2.0s

      2/200       2.3G     0.8301      2.465      1.242         36        640: 84% ━━━━━━━━━━── 21/25 2.5it/s 9.1s<1.6s

      2/200       2.3G     0.8294      2.461      1.233         46        640: 88% ━━━━━━━━━━╸─ 22/25 2.4it/s 9.5s<1.2s

      2/200       2.3G     0.8251      2.459      1.244          8        640: 92% ━━━━━━━━━━━─ 23/25 2.5it/s 9.9s<0.8s

      2/200       2.3G     0.8247      2.464      1.239         20        640: 96% ━━━━━━━━━━━╸ 24/25 2.7it/s 10.2s<0.4s

      2/200       2.3G     0.8247      2.464      1.239         20        640: 100% ━━━━━━━━━━━━ 25/25 2.4it/s 10.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.8it/s 0.3s

                   all          8          8      0.689        0.2      0.499      0.354

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      3/200      2.28G     0.7614      1.778      1.017         42        640: 0% ──────────── 0/25  0.5s

      3/200       2.3G     0.8191      2.311       1.34          8        640: 4% ──────────── 1/25 1.2s/it 0.9s<28.9s

      3/200       2.3G     0.8726      2.357      1.282         28        640: 8% ╸─────────── 2/25 1.3it/s 1.3s<17.9s

      3/200       2.3G     0.9096      2.299       1.27         17        640: 12% ━─────────── 3/25 1.7it/s 1.7s<12.7s

      3/200      2.29G     0.8988      2.279      1.311         15        640: 16% ━╸────────── 4/25 1.9it/s 2.1s<10.8s

      3/200      2.29G     0.8937      2.298      1.286         31        640: 20% ━━────────── 5/25 2.1it/s 2.5s<9.6s

      3/200      2.29G     0.8866      2.295      1.276         33        640: 24% ━━╸───────── 6/25 2.2it/s 2.9s<8.8s

      3/200      2.29G     0.8631      2.284       1.25         33        640: 28% ━━━───────── 7/25 2.2it/s 3.3s<8.1s

      3/200      2.29G     0.8557      2.362       1.25         30        640: 32% ━━━╸──────── 8/25 2.3it/s 3.7s<7.4s

      3/200      2.29G     0.8487      2.411      1.266         14        640: 36% ━━━━──────── 9/25 2.3it/s 4.2s<6.9s

      3/200      2.29G     0.8478      2.389      1.264         24        640: 40% ━━━━╸─────── 10/25 2.4it/s 4.5s<6.3s

      3/200      2.29G     0.8397       2.43      1.272         19        640: 44% ━━━━━─────── 11/25 2.4it/s 5.0s<5.8s

      3/200      2.29G     0.8295      2.404      1.249         37        640: 48% ━━━━━╸────── 12/25 2.4it/s 5.4s<5.5s

      3/200      2.29G     0.8288      2.372      1.234         30        640: 52% ━━━━━━────── 13/25 2.5it/s 5.7s<4.8s

      3/200      2.29G     0.8335      2.383      1.262          8        640: 56% ━━━━━━╸───── 14/25 2.5it/s 6.1s<4.4s

      3/200      2.29G       0.83       2.37      1.251         22        640: 60% ━━━━━━━───── 15/25 2.6it/s 6.5s<3.9s

      3/200      2.29G     0.8356      2.394      1.271          8        640: 64% ━━━━━━━╸──── 16/25 2.7it/s 6.9s<3.4s

      3/200      2.29G     0.8378      2.401      1.293          9        640: 68% ━━━━━━━━──── 17/25 2.7it/s 7.2s<3.0s

      3/200      2.29G     0.8277      2.398      1.296          8        640: 72% ━━━━━━━━╸─── 18/25 2.7it/s 7.6s<2.6s

      3/200      2.29G     0.8317      2.408      1.299         15        640: 76% ━━━━━━━━━─── 19/25 2.6it/s 8.0s<2.3s

      3/200      2.29G     0.8352      2.396      1.296         36        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 8.5s<2.0s

      3/200      2.29G     0.8324      2.374      1.288         23        640: 84% ━━━━━━━━━━── 21/25 2.5it/s 8.9s<1.6s

      3/200      2.29G     0.8293      2.371      1.283         28        640: 88% ━━━━━━━━━━╸─ 22/25 2.4it/s 9.4s<1.3s

      3/200      2.29G     0.8414      2.382        1.3         26        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 9.9s<0.9s

      3/200       2.3G     0.8362      2.365      1.294         14        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 10.2s<0.4s

      3/200       2.3G     0.8362      2.365      1.294         14        640: 100% ━━━━━━━━━━━━ 25/25 2.5it/s 10.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.7it/s 0.6s

                   all          8          8      0.705      0.521      0.492      0.297

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      4/200      2.29G      1.067      2.541      1.677         21        640: 0% ──────────── 0/25  0.5s

      4/200      2.29G       0.96      2.474      1.458         16        640: 4% ──────────── 1/25 1.4s/it 0.9s<32.7s

      4/200      2.29G     0.9279      2.345      1.379         16        640: 8% ╸─────────── 2/25 1.3it/s 1.3s<17.7s

      4/200      2.29G     0.9352      2.412      1.371         15        640: 12% ━─────────── 3/25 1.7it/s 1.7s<13.2s

      4/200      2.29G     0.9631      2.469      1.409         20        640: 16% ━╸────────── 4/25 1.9it/s 2.1s<11.3s

      4/200      2.29G     0.9387      2.427      1.341         20        640: 20% ━━────────── 5/25 2.0it/s 2.5s<10.0s

      4/200      2.29G     0.9038      2.351      1.289         35        640: 24% ━━╸───────── 6/25 2.1it/s 3.0s<9.2s

      4/200      2.29G     0.8954      2.345      1.266         38        640: 28% ━━━───────── 7/25 2.1it/s 3.4s<8.4s

      4/200      2.29G     0.8898      2.306      1.258         26        640: 32% ━━━╸──────── 8/25 2.2it/s 3.9s<7.9s

      4/200      2.29G     0.9029      2.286      1.244         25        640: 36% ━━━━──────── 9/25 2.2it/s 4.3s<7.3s

      4/200      2.29G     0.8893      2.292      1.244          8        640: 40% ━━━━╸─────── 10/25 2.4it/s 4.7s<6.2s

      4/200      2.29G     0.8923       2.26      1.229         47        640: 44% ━━━━━─────── 11/25 2.4it/s 5.1s<5.9s

      4/200      2.29G      0.893      2.223      1.236         17        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.6s<5.7s

      4/200      2.29G     0.8777      2.241      1.235          8        640: 52% ━━━━━━────── 13/25 2.5it/s 5.9s<4.8s

      4/200      2.29G     0.8787      2.224      1.227         16        640: 56% ━━━━━━╸───── 14/25 2.6it/s 6.3s<4.3s

      4/200      2.29G     0.8765      2.206      1.219         33        640: 60% ━━━━━━━───── 15/25 2.6it/s 6.7s<3.9s

      4/200      2.29G     0.8911      2.216      1.258         17        640: 64% ━━━━━━━╸──── 16/25 2.6it/s 7.1s<3.5s

      4/200      2.29G     0.8865      2.179      1.247         28        640: 68% ━━━━━━━━──── 17/25 2.6it/s 7.4s<3.1s

      4/200      2.29G     0.8868      2.165      1.255         23        640: 72% ━━━━━━━━╸─── 18/25 2.5it/s 7.8s<2.7s

      4/200      2.29G     0.8892      2.141      1.247         39        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.3s<2.5s

      4/200      2.29G     0.8918       2.14      1.243         28        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 8.7s<2.1s

      4/200      2.29G     0.8877      2.133      1.234         27        640: 84% ━━━━━━━━━━── 21/25 2.4it/s 9.1s<1.7s

      4/200      2.29G      0.878       2.14      1.245          8        640: 88% ━━━━━━━━━━╸─ 22/25 2.5it/s 9.5s<1.2s

      4/200      2.29G     0.8849      2.173      1.267         21        640: 92% ━━━━━━━━━━━─ 23/25 2.4it/s 10.0s<0.8s

      4/200      2.29G     0.8791      2.183      1.272          6        640: 96% ━━━━━━━━━━━╸ 24/25 2.4it/s 10.4s<0.4s

      4/200      2.29G     0.8791      2.183      1.272          6        640: 100% ━━━━━━━━━━━━ 25/25 2.4it/s 10.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.6it/s 0.4s

                   all          8          8      0.487      0.596       0.58      0.452

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      5/200      2.23G     0.7567       1.86     0.9892         42        640: 0% ──────────── 0/25  0.4s

      5/200      2.23G     0.7961      1.971      1.047         38        640: 4% ──────────── 1/25 1.2s/it 0.7s<28.6s

      5/200      2.23G     0.7557      2.055      1.122          9        640: 8% ╸─────────── 2/25 1.3it/s 1.2s<18.3s

      5/200      2.23G     0.7395       1.94      1.115         24        640: 12% ━─────────── 3/25 1.5it/s 1.6s<14.3s

      5/200      2.23G     0.7697      1.866      1.109         24        640: 16% ━╸────────── 4/25 1.9it/s 2.0s<11.0s

      5/200      2.23G     0.7491      1.914      1.118          8        640: 20% ━━────────── 5/25 2.2it/s 2.3s<9.1s

      5/200      2.23G     0.7739      1.979      1.179         19        640: 24% ━━╸───────── 6/25 2.3it/s 2.7s<8.1s

      5/200      2.23G     0.7732      1.964      1.168         28        640: 28% ━━━───────── 7/25 2.4it/s 3.1s<7.5s

      5/200      2.23G      0.764      1.928      1.143         41        640: 32% ━━━╸──────── 8/25 2.4it/s 3.5s<7.1s

      5/200      2.23G     0.7574      1.928      1.163          9        640: 36% ━━━━──────── 9/25 2.4it/s 3.9s<6.6s

      5/200      2.23G     0.7669      1.957      1.162         14        640: 40% ━━━━╸─────── 10/25 2.5it/s 4.3s<6.0s

      5/200      2.23G     0.7692      1.971      1.168         17        640: 44% ━━━━━─────── 11/25 2.5it/s 4.7s<5.5s

      5/200      2.23G     0.7809      2.018      1.207          8        640: 48% ━━━━━╸────── 12/25 2.6it/s 5.1s<5.1s

      5/200      2.23G     0.7865       2.02      1.207         14        640: 52% ━━━━━━────── 13/25 2.7it/s 5.4s<4.5s

      5/200      2.23G     0.7889      2.012      1.198         22        640: 56% ━━━━━━╸───── 14/25 2.6it/s 5.8s<4.2s

      5/200      2.23G     0.7854      2.048      1.217          9        640: 60% ━━━━━━━───── 15/25 2.6it/s 6.2s<3.8s

      5/200      2.23G     0.7937       2.09      1.222         25        640: 64% ━━━━━━━╸──── 16/25 2.5it/s 6.6s<3.6s

      5/200      2.23G     0.8078      2.108      1.222         37        640: 68% ━━━━━━━━──── 17/25 2.5it/s 7.0s<3.1s

      5/200      2.23G      0.802      2.107      1.214         20        640: 72% ━━━━━━━━╸─── 18/25 2.6it/s 7.4s<2.7s

      5/200      2.23G     0.8039      2.088      1.205         29        640: 76% ━━━━━━━━━─── 19/25 2.5it/s 7.8s<2.4s

      5/200      2.23G     0.7928      2.067      1.194         25        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 8.3s<2.0s

      5/200      2.23G     0.7979      2.066      1.187         37        640: 84% ━━━━━━━━━━── 21/25 2.5it/s 8.6s<1.6s

      5/200      2.23G      0.798      2.041      1.183         25        640: 88% ━━━━━━━━━━╸─ 22/25 2.5it/s 9.0s<1.2s

      5/200      2.23G      0.796       2.05       1.19         20        640: 92% ━━━━━━━━━━━─ 23/25 2.5it/s 9.4s<0.8s

      5/200      2.23G     0.7975      2.031      1.186         14        640: 96% ━━━━━━━━━━━╸ 24/25 2.8it/s 9.7s<0.4s

      5/200      2.23G     0.7975      2.031      1.186         14        640: 100% ━━━━━━━━━━━━ 25/25 2.6it/s 9.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.8it/s 0.6s

                   all          8          8      0.535      0.748      0.609      0.447

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      6/200      2.23G      0.666      2.485      1.262         16        640: 0% ──────────── 0/25  0.4s

      6/200      2.23G     0.7398      2.592      1.292         19        640: 4% ──────────── 1/25 1.3s/it 0.8s<30.2s

      6/200      2.23G     0.7317      2.295      1.215         24        640: 8% ╸─────────── 2/25 1.3it/s 1.2s<17.2s

      6/200      2.23G     0.7144      2.169      1.139         41        640: 12% ━─────────── 3/25 1.7it/s 1.6s<13.2s

      6/200      2.23G     0.7268      2.094      1.096         41        640: 16% ━╸────────── 4/25 1.9it/s 2.0s<11.1s

      6/200      2.23G     0.7358      2.161      1.138          8        640: 20% ━━────────── 5/25 2.1it/s 2.4s<9.4s

      6/200      2.23G     0.7643      2.146       1.15         25        640: 24% ━━╸───────── 6/25 2.2it/s 2.8s<8.5s

      6/200      2.23G      0.766      2.115       1.16         22        640: 28% ━━━───────── 7/25 2.2it/s 3.2s<8.0s

      6/200      2.23G     0.7644      2.112      1.211          9        640: 32% ━━━╸──────── 8/25 2.3it/s 3.6s<7.4s

      6/200      2.23G     0.7807      2.079      1.244         16        640: 36% ━━━━──────── 9/25 2.3it/s 4.1s<6.8s

      6/200      2.23G     0.7763      2.083      1.231         22        640: 40% ━━━━╸─────── 10/25 2.4it/s 4.4s<6.2s

      6/200      2.23G     0.7591      2.108      1.221         20        640: 44% ━━━━━─────── 11/25 2.5it/s 4.8s<5.7s

      6/200      2.23G     0.7725      2.074      1.217         20        640: 48% ━━━━━╸────── 12/25 2.6it/s 5.2s<5.0s

      6/200      2.23G     0.7692      2.043      1.205         33        640: 52% ━━━━━━────── 13/25 2.5it/s 5.6s<4.8s

      6/200      2.23G     0.7708       2.06      1.211         25        640: 56% ━━━━━━╸───── 14/25 2.5it/s 6.0s<4.5s

      6/200      2.23G      0.773       2.08      1.232          8        640: 60% ━━━━━━━───── 15/25 2.6it/s 6.4s<3.9s

      6/200      2.23G     0.7571      2.076      1.231          8        640: 64% ━━━━━━━╸──── 16/25 2.6it/s 6.8s<3.5s

      6/200      2.23G     0.7451      2.061      1.221         36        640: 68% ━━━━━━━━──── 17/25 2.6it/s 7.1s<3.1s

      6/200      2.23G     0.7427       2.04      1.212         16        640: 72% ━━━━━━━━╸─── 18/25 2.6it/s 7.5s<2.7s

      6/200      2.23G     0.7565      2.024      1.213         22        640: 76% ━━━━━━━━━─── 19/25 2.6it/s 7.9s<2.3s

      6/200      2.23G     0.7558      2.002      1.204         28        640: 80% ━━━━━━━━━╸── 20/25 2.5it/s 8.3s<2.0s

      6/200      2.23G      0.761      2.009      1.199         34        640: 84% ━━━━━━━━━━── 21/25 2.5it/s 8.7s<1.6s

      6/200      2.23G     0.7592      1.997      1.195         25        640: 88% ━━━━━━━━━━╸─ 22/25 2.5it/s 9.1s<1.2s

      6/200      2.23G     0.7749      2.002      1.193         34        640: 92% ━━━━━━━━━━━─ 23/25 2.5it/s 9.5s<0.8s

      6/200      2.23G     0.7676      2.005      1.195          6        640: 96% ━━━━━━━━━━━╸ 24/25 2.7it/s 9.8s<0.4s

      6/200      2.23G     0.7676      2.005      1.195          6        640: 100% ━━━━━━━━━━━━ 25/25 2.5it/s 9.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.9it/s 0.5s

                   all          8          8      0.433      0.961      0.829      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      7/200       2.3G     0.9036      2.158      1.499         14        640: 0% ──────────── 0/25  0.4s

      7/200       2.3G      0.859       1.98      1.297         34        640: 4% ──────────── 1/25 1.3s/it 0.8s<31.4s

      7/200       2.3G     0.7994      1.954       1.22         36        640: 8% ╸─────────── 2/25 1.3it/s 1.2s<17.3s

      7/200       2.3G     0.8149      1.862      1.179         36        640: 12% ━─────────── 3/25 1.6it/s 1.6s<13.6s

      7/200       2.3G     0.7876      1.809      1.172         16        640: 16% ━╸────────── 4/25 1.9it/s 2.0s<10.9s

      7/200       2.3G     0.8134      1.874      1.207         14        640: 20% ━━────────── 5/25 2.2it/s 2.3s<9.1s

      7/200       2.3G     0.7964       1.85      1.198         23        640: 24% ━━╸───────── 6/25 2.2it/s 2.8s<8.6s

      7/200       2.3G     0.8069      1.816      1.179         22        640: 28% ━━━───────── 7/25 2.3it/s 3.2s<7.7s

      7/200       2.3G     0.7965      1.786      1.177         16        640: 32% ━━━╸──────── 8/25 2.5it/s 3.5s<6.9s

      7/200       2.3G     0.7844      1.809      1.186          8        640: 36% ━━━━──────── 9/25 2.5it/s 3.9s<6.3s

      7/200       2.3G     0.7957      1.777      1.179         46        640: 40% ━━━━╸─────── 10/25 2.5it/s 4.3s<6.1s

      7/200       2.3G     0.7942      1.779      1.182         22        640: 44% ━━━━━─────── 11/25 2.4it/s 4.8s<5.9s

      7/200       2.3G     0.7905      1.767      1.168         22        640: 48% ━━━━━╸────── 12/25 2.4it/s 5.2s<5.5s

      7/200       2.3G     0.7754      1.757      1.161         17        640: 52% ━━━━━━────── 13/25 2.5it/s 5.6s<4.9s

      7/200       2.3G     0.7722      1.802       1.17          8        640: 56% ━━━━━━╸───── 14/25 2.6it/s 6.0s<4.3s

      7/200       2.3G     0.7669      1.781       1.15         39        640: 60% ━━━━━━━───── 15/25 2.6it/s 6.3s<3.8s

      7/200       2.3G     0.7559      1.817      1.162         10        640: 64% ━━━━━━━╸──── 16/25 2.5it/s 6.7s<3.5s

      7/200       2.3G     0.7595      1.821      1.163         31        640: 68% ━━━━━━━━──── 17/25 2.5it/s 7.2s<3.2s

      7/200      2.29G     0.7527      1.793      1.154         24        640: 72% ━━━━━━━━╸─── 18/25 2.5it/s 7.6s<2.8s

      7/200      2.29G     0.7471      1.789      1.148         15        640: 76% ━━━━━━━━━─── 19/25 2.5it/s 8.0s<2.4s

      7/200      2.29G     0.7531        1.8      1.146         26        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 8.4s<2.1s

      7/200      2.29G     0.7501      1.817      1.146         30        640: 84% ━━━━━━━━━━── 21/25 2.5it/s 8.8s<1.6s

      7/200      2.29G     0.7504      1.811      1.141         28        640: 88% ━━━━━━━━━━╸─ 22/25 2.4it/s 9.3s<1.3s

      7/200      2.29G     0.7471       1.81      1.144         14        640: 92% ━━━━━━━━━━━─ 23/25 2.4it/s 9.7s<0.8s

      7/200      2.29G     0.7527      1.823      1.163          7        640: 96% ━━━━━━━━━━━╸ 24/25 2.3it/s 10.2s<0.4s

      7/200      2.29G     0.7527      1.823      1.163          7        640: 100% ━━━━━━━━━━━━ 25/25 2.5it/s 10.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.6it/s 0.6s

                   all          8          8      0.275        0.9       0.77      0.591

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      8/200      2.29G     0.8771      2.014      1.433         19        640: 0% ──────────── 0/25  0.4s

      8/200      2.29G     0.8065      1.958      1.304         19        640: 4% ──────────── 1/25 1.5s/it 0.9s<35.2s

      8/200      2.29G     0.7517      2.003      1.245         20        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<19.0s

      8/200      2.29G     0.7697      1.895      1.214         16        640: 12% ━─────────── 3/25 1.6it/s 1.7s<13.6s

      8/200      2.29G     0.7488      1.824       1.17         23        640: 16% ━╸────────── 4/25 1.9it/s 2.0s<11.0s

      8/200      2.29G     0.7279       1.81      1.162         25        640: 20% ━━────────── 5/25 2.1it/s 2.5s<9.7s

      8/200      2.29G     0.7334      1.769      1.169         21        640: 24% ━━╸───────── 6/25 2.1it/s 2.9s<9.1s

      8/200      2.29G      0.744      1.788      1.164         25        640: 28% ━━━───────── 7/25 2.2it/s 3.3s<8.2s

      8/200      2.29G     0.7273      1.814      1.175          9        640: 32% ━━━╸──────── 8/25 2.3it/s 3.7s<7.4s

      8/200      2.29G     0.7346      1.834      1.183         14        640: 36% ━━━━──────── 9/25 2.2it/s 4.2s<7.2s

      8/200      2.29G     0.7354      1.809      1.167         26        640: 40% ━━━━╸─────── 10/25 2.2it/s 4.7s<6.7s

      8/200      2.29G     0.7341      1.813      1.155         33        640: 44% ━━━━━─────── 11/25 2.4it/s 5.0s<5.9s

      8/200      2.29G     0.7436      1.801      1.147         26        640: 48% ━━━━━╸────── 12/25 2.5it/s 5.4s<5.2s

      8/200      2.29G     0.7434      1.823      1.146         14        640: 52% ━━━━━━────── 13/25 2.6it/s 5.7s<4.6s

      8/200      2.29G     0.7319      1.842      1.149          8        640: 56% ━━━━━━╸───── 14/25 2.5it/s 6.2s<4.5s

      8/200      2.29G     0.7286      1.847       1.17         10        640: 60% ━━━━━━━───── 15/25 2.4it/s 6.6s<4.1s

      8/200      2.29G     0.7296      1.832      1.157         22        640: 64% ━━━━━━━╸──── 16/25 2.5it/s 7.0s<3.5s

      8/200      2.29G     0.7321      1.835      1.167         19        640: 68% ━━━━━━━━──── 17/25 2.5it/s 7.4s<3.2s

      8/200      2.29G     0.7354      1.829      1.161         32        640: 72% ━━━━━━━━╸─── 18/25 2.4it/s 7.9s<2.9s

      8/200      2.29G     0.7311        1.8      1.151         30        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.3s<2.5s

      8/200      2.29G     0.7329      1.797      1.149         22        640: 80% ━━━━━━━━━╸── 20/25 2.5it/s 8.7s<2.0s

      8/200      2.29G     0.7297      1.792      1.139         46        640: 84% ━━━━━━━━━━── 21/25 2.4it/s 9.1s<1.6s

      8/200      2.29G     0.7242      1.804      1.153          9        640: 88% ━━━━━━━━━━╸─ 22/25 2.4it/s 9.5s<1.2s

      8/200      2.29G     0.7288       1.79      1.147         30        640: 92% ━━━━━━━━━━━─ 23/25 2.5it/s 9.9s<0.8s

      8/200      2.29G      0.732      1.772      1.142         40        640: 96% ━━━━━━━━━━━╸ 24/25 2.4it/s 10.3s<0.4s

      8/200      2.29G      0.732      1.772      1.142         40        640: 100% ━━━━━━━━━━━━ 25/25 2.4it/s 10.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.4it/s 0.7s

                   all          8          8      0.641        0.6      0.619      0.461

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      9/200      2.23G     0.7182      2.027      1.387          9        640: 0% ──────────── 0/25  0.4s

      9/200      2.23G     0.7165      2.006      1.273         14        640: 4% ──────────── 1/25 1.2s/it 0.8s<29.6s

      9/200      2.23G     0.8112      1.946      1.257         14        640: 8% ╸─────────── 2/25 1.3it/s 1.2s<17.1s

      9/200      2.23G     0.7955      1.972      1.283         20        640: 12% ━─────────── 3/25 1.7it/s 1.6s<13.2s

      9/200      2.23G     0.8149      1.868      1.239         22        640: 16% ━╸────────── 4/25 2.0it/s 1.9s<10.6s

      9/200      2.23G     0.8428      1.809      1.205         41        640: 20% ━━────────── 5/25 2.0it/s 2.4s<10.0s

      9/200      2.23G     0.8347      1.799      1.214         25        640: 24% ━━╸───────── 6/25 2.0it/s 2.9s<9.4s

      9/200      2.23G     0.8261      1.725      1.188         22        640: 28% ━━━───────── 7/25 2.2it/s 3.3s<8.2s

      9/200      2.23G     0.8141      1.763      1.185         15        640: 32% ━━━╸──────── 8/25 2.2it/s 3.7s<7.6s

      9/200      2.23G     0.8075      1.775      1.207          8        640: 36% ━━━━──────── 9/25 2.3it/s 4.1s<6.8s

      9/200      2.23G     0.8199      1.741      1.202         24        640: 40% ━━━━╸─────── 10/25 2.4it/s 4.5s<6.2s

      9/200      2.23G     0.8179      1.732      1.191         31        640: 44% ━━━━━─────── 11/25 2.4it/s 4.9s<6.0s

      9/200      2.23G     0.8185        1.7      1.177         28        640: 48% ━━━━━╸────── 12/25 2.4it/s 5.3s<5.4s

      9/200      2.23G     0.8006      1.707      1.191          9        640: 52% ━━━━━━────── 13/25 2.4it/s 5.7s<4.9s

      9/200      2.23G      0.813      1.701      1.216         14        640: 56% ━━━━━━╸───── 14/25 2.3it/s 6.2s<4.8s

      9/200      2.23G     0.8035      1.676      1.216         29        640: 60% ━━━━━━━───── 15/25 2.2it/s 6.8s<4.6s

      9/200      2.23G     0.8043      1.662      1.213         27        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.2s<3.9s

      9/200      2.23G     0.7994      1.654      1.207         34        640: 68% ━━━━━━━━──── 17/25 2.3it/s 7.6s<3.4s

      9/200      2.23G     0.8014      1.637      1.202         24        640: 72% ━━━━━━━━╸─── 18/25 2.4it/s 7.9s<2.9s

      9/200      2.23G     0.7912      1.627       1.19         35        640: 76% ━━━━━━━━━─── 19/25 2.3it/s 8.4s<2.6s

      9/200      2.23G     0.7942      1.627      1.199         14        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 8.8s<2.0s

      9/200      2.23G     0.7907      1.606       1.19         29        640: 84% ━━━━━━━━━━── 21/25 2.4it/s 9.2s<1.6s

      9/200      2.23G     0.7852      1.594      1.182         29        640: 88% ━━━━━━━━━━╸─ 22/25 2.5it/s 9.6s<1.2s

      9/200      2.23G       0.78      1.583      1.177         24        640: 92% ━━━━━━━━━━━─ 23/25 2.5it/s 10.0s<0.8s

      9/200      2.23G     0.7773      1.583      1.177         17        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 10.4s<0.4s

      9/200      2.23G     0.7773      1.583      1.177         17        640: 100% ━━━━━━━━━━━━ 25/25 2.4it/s 10.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.3it/s 0.7s

                   all          8          8      0.793        0.5      0.617      0.418

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     10/200      2.23G     0.8274      1.032     0.9634         32        640: 0% ──────────── 0/25  0.5s

     10/200      2.23G     0.7461      1.333      1.136          8        640: 4% ──────────── 1/25 1.3s/it 0.9s<30.5s

     10/200      2.23G       0.72      1.346      1.153         17        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<18.4s

     10/200      2.23G     0.7159      1.353      1.157         17        640: 12% ━─────────── 3/25 1.6it/s 1.7s<13.7s

     10/200      2.23G     0.7194      1.469      1.143         20        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<11.4s

     10/200      2.23G     0.7171       1.46      1.118         34        640: 20% ━━────────── 5/25 1.9it/s 2.6s<10.5s

     10/200      2.23G     0.6959      1.512      1.128          8        640: 24% ━━╸───────── 6/25 2.1it/s 3.0s<8.8s

     10/200      2.23G     0.7046      1.501      1.107         42        640: 28% ━━━───────── 7/25 2.1it/s 3.4s<8.4s

     10/200      2.23G     0.7146      1.468      1.096         35        640: 32% ━━━╸──────── 8/25 2.2it/s 3.9s<7.9s

     10/200      2.23G     0.7257      1.447      1.088         39        640: 36% ━━━━──────── 9/25 2.3it/s 4.3s<7.1s

     10/200      2.23G     0.7332      1.441      1.088         32        640: 40% ━━━━╸─────── 10/25 2.2it/s 4.8s<6.8s

     10/200      2.23G     0.7298      1.413      1.086         22        640: 44% ━━━━━─────── 11/25 2.3it/s 5.2s<6.0s

     10/200      2.23G     0.7223      1.406      1.078         17        640: 48% ━━━━━╸────── 12/25 2.4it/s 5.6s<5.5s

     10/200      2.23G     0.7415      1.445      1.117         14        640: 52% ━━━━━━────── 13/25 2.4it/s 5.9s<4.9s

     10/200      2.23G     0.7445      1.436      1.114         27        640: 56% ━━━━━━╸───── 14/25 2.5it/s 6.3s<4.4s

     10/200      2.23G     0.7415      1.438      1.116         16        640: 60% ━━━━━━━───── 15/25 2.5it/s 6.7s<4.0s

     10/200      2.23G     0.7381      1.418      1.107         30        640: 64% ━━━━━━━╸──── 16/25 2.5it/s 7.1s<3.6s

     10/200      2.23G      0.734      1.415      1.101         31        640: 68% ━━━━━━━━──── 17/25 2.4it/s 7.6s<3.4s

     10/200      2.23G     0.7363      1.432      1.114         15        640: 72% ━━━━━━━━╸─── 18/25 2.4it/s 8.0s<2.9s

     10/200      2.23G     0.7286      1.419      1.106         22        640: 76% ━━━━━━━━━─── 19/25 2.5it/s 8.4s<2.4s

     10/200      2.23G     0.7307       1.41      1.103         16        640: 80% ━━━━━━━━━╸── 20/25 2.6it/s 8.7s<1.9s

     10/200      2.23G     0.7383        1.4      1.109         14        640: 84% ━━━━━━━━━━── 21/25 2.6it/s 9.1s<1.6s

     10/200      2.23G     0.7369      1.395      1.107         25        640: 88% ━━━━━━━━━━╸─ 22/25 2.4it/s 9.6s<1.2s

     10/200      2.23G     0.7388      1.407      1.113         19        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 10.1s<0.9s

     10/200      2.23G     0.7404      1.415      1.125          6        640: 96% ━━━━━━━━━━━╸ 24/25 2.6it/s 10.4s<0.4s

     10/200      2.23G     0.7404      1.415      1.125          6        640: 100% ━━━━━━━━━━━━ 25/25 2.4it/s 10.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.3it/s 0.8s

                   all          8          8      0.724      0.735       0.73      0.542

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     11/200      2.23G     0.8497      1.405       1.23         24        640: 0% ──────────── 0/25  0.4s

     11/200      2.23G     0.7719      1.321      1.164         20        640: 4% ──────────── 1/25 1.4s/it 0.8s<32.6s

     11/200      2.23G     0.7281      1.261      1.105         39        640: 8% ╸─────────── 2/25 1.3it/s 1.2s<18.3s

     11/200      2.23G      0.715      1.248      1.107         15        640: 12% ━─────────── 3/25 1.7it/s 1.6s<13.2s

     11/200      2.23G     0.7305      1.368      1.122         14        640: 16% ━╸────────── 4/25 2.0it/s 2.0s<10.6s

     11/200      2.23G     0.7025      1.386      1.144          9        640: 20% ━━────────── 5/25 2.1it/s 2.4s<9.5s

     11/200      2.23G     0.7023       1.36       1.15         21        640: 24% ━━╸───────── 6/25 2.2it/s 2.8s<8.5s

     11/200      2.23G     0.7034       1.35      1.133         31        640: 28% ━━━───────── 7/25 2.2it/s 3.3s<8.2s

     11/200      2.23G     0.7068      1.335      1.135         20        640: 32% ━━━╸──────── 8/25 2.3it/s 3.7s<7.4s

     11/200      2.23G     0.7236      1.324      1.132         25        640: 36% ━━━━──────── 9/25 2.3it/s 4.1s<6.9s

     11/200      2.23G     0.7217      1.326      1.122         35        640: 40% ━━━━╸─────── 10/25 2.4it/s 4.5s<6.2s

     11/200      2.23G     0.7012      1.367      1.116          8        640: 44% ━━━━━─────── 11/25 2.5it/s 4.8s<5.6s

     11/200      2.23G     0.6968        1.4      1.113         16        640: 48% ━━━━━╸────── 12/25 2.5it/s 5.2s<5.2s

     11/200      2.23G     0.6963      1.399      1.138          8        640: 52% ━━━━━━────── 13/25 2.5it/s 5.6s<4.8s

     11/200      2.23G     0.7018      1.391      1.133         16        640: 56% ━━━━━━╸───── 14/25 2.5it/s 6.0s<4.3s

     11/200      2.23G     0.6923      1.399       1.13         19        640: 60% ━━━━━━━───── 15/25 2.5it/s 6.4s<4.0s

     11/200      2.23G     0.6845      1.397      1.127         15        640: 64% ━━━━━━━╸──── 16/25 2.5it/s 6.8s<3.6s

     11/200      2.23G     0.6901      1.393      1.122         34        640: 68% ━━━━━━━━──── 17/25 2.3it/s 7.3s<3.4s

     11/200      2.23G     0.6893      1.408      1.118         30        640: 72% ━━━━━━━━╸─── 18/25 2.4it/s 7.7s<2.9s

     11/200      2.23G     0.6885      1.415      1.117         20        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.1s<2.5s

     11/200      2.23G     0.6919      1.426      1.114         36        640: 80% ━━━━━━━━━╸── 20/25 2.3it/s 8.6s<2.1s

     11/200      2.23G     0.6923      1.444      1.119         16        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.1s<1.7s

     11/200      2.23G     0.6902      1.426      1.116         24        640: 88% ━━━━━━━━━━╸─ 22/25 2.4it/s 9.4s<1.3s

     11/200      2.23G     0.6893      1.406      1.108         32        640: 92% ━━━━━━━━━━━─ 23/25 2.5it/s 9.8s<0.8s

     11/200      2.23G     0.6886      1.429      1.109         31        640: 96% ━━━━━━━━━━━╸ 24/25 2.4it/s 10.3s<0.4s

     11/200      2.23G     0.6886      1.429      1.109         31        640: 100% ━━━━━━━━━━━━ 25/25 2.4it/s 10.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.2it/s 0.8s

                   all          8          8      0.822      0.673      0.945        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     12/200      2.21G     0.6527      1.401      1.118         26        640: 0% ──────────── 0/25  0.5s

     12/200      2.23G     0.6994      1.346       1.08         22        640: 4% ──────────── 1/25 1.6s/it 1.0s<38.0s

     12/200      2.23G     0.6709      1.358       1.11         19        640: 8% ╸─────────── 2/25 1.0it/s 1.5s<22.0s

     12/200      2.23G     0.6612      1.332      1.096         20        640: 12% ━─────────── 3/25 1.4it/s 2.0s<16.2s

     12/200      2.23G     0.6643      1.357      1.156          8        640: 16% ━╸────────── 4/25 1.7it/s 2.4s<12.3s

     12/200      2.23G     0.6723      1.394      1.141         37        640: 20% ━━────────── 5/25 1.8it/s 2.9s<11.1s

     12/200      2.23G     0.6644      1.346      1.116         24        640: 24% ━━╸───────── 6/25 2.0it/s 3.3s<9.5s

     12/200      2.23G     0.6966       1.31      1.102         31        640: 28% ━━━───────── 7/25 2.1it/s 3.7s<8.5s

     12/200      2.23G     0.6912      1.335       1.11         20        640: 32% ━━━╸──────── 8/25 2.2it/s 4.1s<7.7s

     12/200      2.23G     0.6994      1.314      1.105         14        640: 36% ━━━━──────── 9/25 2.4it/s 4.5s<6.8s

     12/200      2.23G     0.7003      1.348      1.122         16        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.9s<6.4s

     12/200      2.23G     0.6894      1.375      1.123          9        640: 44% ━━━━━─────── 11/25 2.4it/s 5.3s<5.8s

     12/200      2.23G     0.6985      1.349      1.113         33        640: 48% ━━━━━╸────── 12/25 2.5it/s 5.7s<5.2s

     12/200      2.23G      0.698       1.33      1.102         43        640: 52% ━━━━━━────── 13/25 2.5it/s 6.1s<4.9s

     12/200      2.23G     0.6896      1.337      1.098         19        640: 56% ━━━━━━╸───── 14/25 2.5it/s 6.5s<4.4s

     12/200      2.23G     0.6939       1.33       1.11         17        640: 60% ━━━━━━━───── 15/25 2.4it/s 6.9s<4.1s

     12/200      2.23G     0.7016      1.348      1.118         14        640: 64% ━━━━━━━╸──── 16/25 2.5it/s 7.3s<3.6s

     12/200      2.23G     0.6985      1.375      1.127          8        640: 68% ━━━━━━━━──── 17/25 2.5it/s 7.7s<3.2s

     12/200      2.23G     0.7106      1.385      1.141         14        640: 72% ━━━━━━━━╸─── 18/25 2.5it/s 8.1s<2.8s

     12/200      2.23G      0.716      1.383      1.137         28        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.6s<2.5s

     12/200      2.23G     0.7267      1.362      1.134         30        640: 80% ━━━━━━━━━╸── 20/25 2.5it/s 8.9s<2.0s

     12/200      2.23G     0.7288      1.346      1.127         36        640: 84% ━━━━━━━━━━── 21/25 2.4it/s 9.4s<1.7s

     12/200      2.23G     0.7328      1.336      1.118         39        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 9.9s<1.3s

     12/200      2.23G     0.7296      1.325      1.117         25        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 10.3s<0.9s

     12/200      2.23G     0.7309      1.337      1.135          6        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 10.6s<0.4s

     12/200      2.23G     0.7309      1.337      1.135          6        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 10.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.3it/s 0.8s

                   all          8          8      0.744      0.709      0.785      0.598

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     13/200       2.3G     0.6017      2.035     0.9718         41        640: 0% ──────────── 0/25  0.5s

     13/200       2.3G     0.6538      1.688      1.116          8        640: 4% ──────────── 1/25 1.3s/it 0.9s<32.0s

     13/200       2.3G     0.6988      1.415      1.105         28        640: 8% ╸─────────── 2/25 1.2it/s 1.4s<19.9s

     13/200       2.3G     0.7288       1.61      1.111         31        640: 12% ━─────────── 3/25 1.6it/s 1.8s<13.8s

     13/200       2.3G     0.7979      1.505      1.141         24        640: 16% ━╸────────── 4/25 1.8it/s 2.2s<11.5s

     13/200       2.3G      0.797      1.445      1.145         15        640: 20% ━━────────── 5/25 2.0it/s 2.6s<10.0s

     13/200       2.3G     0.7668      1.454      1.131         38        640: 24% ━━╸───────── 6/25 2.1it/s 3.0s<9.0s

     13/200       2.3G     0.7569      1.413      1.125         14        640: 28% ━━━───────── 7/25 2.3it/s 3.4s<7.9s

     13/200       2.3G     0.7632      1.434      1.141         19        640: 32% ━━━╸──────── 8/25 2.4it/s 3.8s<7.1s

     13/200       2.3G     0.7694      1.407      1.141         31        640: 36% ━━━━──────── 9/25 2.4it/s 4.2s<6.6s

     13/200       2.3G     0.7629      1.391      1.138         17        640: 40% ━━━━╸─────── 10/25 2.4it/s 4.6s<6.4s

     13/200       2.3G     0.7539      1.396      1.157          9        640: 44% ━━━━━─────── 11/25 2.3it/s 5.1s<6.1s

     13/200       2.3G     0.7609      1.404      1.168         14        640: 48% ━━━━━╸────── 12/25 2.4it/s 5.5s<5.4s

     13/200       2.3G     0.7482      1.369      1.151         24        640: 52% ━━━━━━────── 13/25 2.4it/s 5.9s<5.0s

     13/200       2.3G     0.7497      1.344      1.144         28        640: 56% ━━━━━━╸───── 14/25 2.4it/s 6.3s<4.6s

     13/200       2.3G     0.7373      1.338      1.139         16        640: 60% ━━━━━━━───── 15/25 2.4it/s 6.7s<4.1s

     13/200       2.3G     0.7367      1.322      1.129         36        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.2s<3.8s

     13/200       2.3G     0.7268      1.343      1.126          9        640: 68% ━━━━━━━━──── 17/25 2.4it/s 7.6s<3.3s

     13/200       2.3G     0.7292      1.348       1.12         31        640: 72% ━━━━━━━━╸─── 18/25 2.5it/s 8.0s<2.9s

     13/200       2.3G     0.7318      1.343      1.119         24        640: 76% ━━━━━━━━━─── 19/25 2.5it/s 8.4s<2.4s

     13/200       2.3G     0.7243      1.346      1.117         17        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 8.8s<2.0s

     13/200       2.3G     0.7299      1.343      1.122         21        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.3s<1.7s

     13/200       2.3G     0.7273      1.334      1.122         16        640: 88% ━━━━━━━━━━╸─ 22/25 2.4it/s 9.7s<1.3s

     13/200       2.3G      0.733      1.325      1.124         24        640: 92% ━━━━━━━━━━━─ 23/25 2.5it/s 10.1s<0.8s

     13/200       2.3G     0.7304       1.32      1.123         23        640: 96% ━━━━━━━━━━━╸ 24/25 2.6it/s 10.4s<0.4s

     13/200       2.3G     0.7304       1.32      1.123         23        640: 100% ━━━━━━━━━━━━ 25/25 2.4it/s 10.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.3it/s 0.8s

                   all          8          8      0.911        0.8      0.962      0.585

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     14/200      2.24G     0.6714      1.085      1.075         28        640: 0% ──────────── 0/25  0.4s

     14/200      2.24G     0.7224      1.263      1.156         20        640: 4% ──────────── 1/25 1.3s/it 0.8s<31.9s

     14/200      2.24G     0.6873      1.215      1.141         28        640: 8% ╸─────────── 2/25 1.2it/s 1.2s<18.6s

     14/200      2.24G     0.6538      1.152      1.099         14        640: 12% ━─────────── 3/25 1.7it/s 1.6s<13.2s

     14/200      2.24G     0.7012       1.18      1.083         30        640: 16% ━╸────────── 4/25 1.9it/s 2.0s<10.8s

     14/200      2.24G     0.7231       1.22      1.097         15        640: 20% ━━────────── 5/25 2.1it/s 2.4s<9.5s

     14/200      2.24G     0.7261      1.218      1.081         27        640: 24% ━━╸───────── 6/25 2.2it/s 2.8s<8.5s

     14/200      2.24G     0.7185      1.235      1.087         26        640: 28% ━━━───────── 7/25 2.3it/s 3.2s<7.9s

     14/200      2.24G     0.7186      1.227      1.084         30        640: 32% ━━━╸──────── 8/25 2.3it/s 3.6s<7.3s

     14/200      2.24G     0.7167      1.233      1.107         14        640: 36% ━━━━──────── 9/25 2.4it/s 4.0s<6.7s

     14/200      2.24G     0.7075      1.222      1.098         22        640: 40% ━━━━╸─────── 10/25 2.4it/s 4.4s<6.2s

     14/200      2.24G     0.7016      1.252      1.089         41        640: 44% ━━━━━─────── 11/25 2.5it/s 4.8s<5.7s

     14/200      2.24G     0.7026      1.282      1.094         14        640: 48% ━━━━━╸────── 12/25 2.5it/s 5.2s<5.2s

     14/200      2.24G     0.6955       1.26      1.087         16        640: 52% ━━━━━━────── 13/25 2.5it/s 5.6s<4.8s

     14/200      2.24G     0.6989      1.255      1.094         27        640: 56% ━━━━━━╸───── 14/25 2.4it/s 6.0s<4.5s

     14/200      2.24G     0.6879      1.233      1.091         24        640: 60% ━━━━━━━───── 15/25 2.4it/s 6.4s<4.2s

     14/200      2.24G     0.7122      1.263      1.116         15        640: 64% ━━━━━━━╸──── 16/25 2.4it/s 6.8s<3.7s

     14/200      2.24G     0.7229      1.246      1.113         31        640: 68% ━━━━━━━━──── 17/25 2.5it/s 7.2s<3.2s

     14/200      2.24G     0.7198      1.255      1.133          9        640: 72% ━━━━━━━━╸─── 18/25 2.5it/s 7.6s<2.8s

     14/200      2.24G     0.7166      1.251      1.127         14        640: 76% ━━━━━━━━━─── 19/25 2.5it/s 8.0s<2.4s

     14/200      2.24G     0.7143      1.237      1.119         32        640: 80% ━━━━━━━━━╸── 20/25 2.5it/s 8.4s<2.0s

     14/200      2.24G     0.7181      1.244      1.126          8        640: 84% ━━━━━━━━━━── 21/25 2.6it/s 8.8s<1.5s

     14/200      2.24G     0.7153      1.224      1.118         30        640: 88% ━━━━━━━━━━╸─ 22/25 2.4it/s 9.2s<1.2s

     14/200      2.24G     0.7184       1.23      1.116         20        640: 92% ━━━━━━━━━━━─ 23/25 2.5it/s 9.6s<0.8s

     14/200      2.24G     0.7194      1.229      1.112         23        640: 96% ━━━━━━━━━━━╸ 24/25 2.7it/s 10.0s<0.4s

     14/200      2.24G     0.7194      1.229      1.112         23        640: 100% ━━━━━━━━━━━━ 25/25 2.5it/s 10.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.3it/s 0.8s

                   all          8          8      0.732        0.8      0.813      0.604

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     15/200      2.24G     0.6006     0.9401      1.113         16        640: 0% ──────────── 0/25  0.4s

     15/200      2.24G     0.6086      1.463      1.066         30        640: 4% ──────────── 1/25 1.5s/it 0.8s<36.7s

     15/200      2.24G     0.6603      1.391      1.068         33        640: 8% ╸─────────── 2/25 1.2it/s 1.2s<18.6s

     15/200      2.24G      0.658      1.438      1.082          9        640: 12% ━─────────── 3/25 1.7it/s 1.6s<13.2s

     15/200      2.24G     0.6927      1.368      1.074         31        640: 16% ━╸────────── 4/25 1.9it/s 2.0s<11.3s

     15/200      2.24G     0.6789      1.282      1.054         22        640: 20% ━━────────── 5/25 2.1it/s 2.4s<9.5s

     15/200      2.24G     0.6652      1.274      1.048         28        640: 24% ━━╸───────── 6/25 2.1it/s 2.9s<9.2s

     15/200      2.24G     0.6573       1.24      1.044         24        640: 28% ━━━───────── 7/25 2.2it/s 3.3s<8.2s

     15/200      2.24G     0.6565      1.234      1.033         20        640: 32% ━━━╸──────── 8/25 2.3it/s 3.7s<7.3s

     15/200      2.24G     0.6709      1.237      1.034         28        640: 36% ━━━━──────── 9/25 2.2it/s 4.2s<7.2s

     15/200      2.24G     0.6672      1.241      1.046         14        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.6s<6.5s

     15/200      2.24G     0.6908      1.208      1.056         23        640: 44% ━━━━━─────── 11/25 2.4it/s 5.0s<5.9s

     15/200      2.24G     0.6871      1.181      1.052         22        640: 48% ━━━━━╸────── 12/25 2.4it/s 5.4s<5.4s

     15/200      2.24G      0.691      1.179      1.053         32        640: 52% ━━━━━━────── 13/25 2.4it/s 5.8s<5.0s

     15/200      2.24G     0.6956      1.171      1.058         17        640: 56% ━━━━━━╸───── 14/25 2.4it/s 6.2s<4.6s

     15/200      2.24G     0.6951      1.209      1.061         27        640: 60% ━━━━━━━───── 15/25 2.3it/s 6.7s<4.3s

     15/200      2.24G     0.6993      1.216      1.058         37        640: 64% ━━━━━━━╸──── 16/25 2.2it/s 7.2s<4.1s

     15/200      2.24G     0.6997      1.221      1.057         20        640: 68% ━━━━━━━━──── 17/25 2.3it/s 7.6s<3.5s

     15/200      2.24G      0.705      1.213      1.058         33        640: 72% ━━━━━━━━╸─── 18/25 2.2it/s 8.1s<3.1s

     15/200      2.24G     0.7038        1.2      1.053         30        640: 76% ━━━━━━━━━─── 19/25 2.2it/s 8.6s<2.7s

     15/200      2.24G     0.7098      1.195      1.062         14        640: 80% ━━━━━━━━━╸── 20/25 2.3it/s 9.0s<2.2s

     15/200      2.24G     0.7018      1.206      1.066          9        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.4s<1.7s

     15/200      2.24G     0.6988      1.196      1.062         24        640: 88% ━━━━━━━━━━╸─ 22/25 2.4it/s 9.8s<1.3s

     15/200      2.24G     0.6919        1.2      1.064          9        640: 92% ━━━━━━━━━━━─ 23/25 2.5it/s 10.2s<0.8s

     15/200      2.24G     0.6907      1.204      1.072          6        640: 96% ━━━━━━━━━━━╸ 24/25 2.7it/s 10.5s<0.4s

     15/200      2.24G     0.6907      1.204      1.072          6        640: 100% ━━━━━━━━━━━━ 25/25 2.4it/s 10.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.2it/s 0.8s

                   all          8          8      0.714      0.755      0.667      0.534

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     16/200      2.24G     0.7091       0.86      1.021         35        640: 0% ──────────── 0/25  0.5s

     16/200      2.24G     0.7168     0.8692     0.9871         36        640: 4% ──────────── 1/25 1.3s/it 0.9s<31.6s

     16/200      2.24G      0.709     0.9328     0.9882         33        640: 8% ╸─────────── 2/25 1.2it/s 1.4s<19.8s

     16/200      2.24G     0.6744     0.9469     0.9873         17        640: 12% ━─────────── 3/25 1.6it/s 1.8s<14.1s

     16/200      2.24G     0.6802      1.013      1.046          8        640: 16% ━╸────────── 4/25 1.9it/s 2.1s<11.0s

     16/200      2.24G     0.7025        1.1      1.069         20        640: 20% ━━────────── 5/25 2.1it/s 2.5s<9.4s

     16/200      2.24G     0.7131      1.073      1.073         28        640: 24% ━━╸───────── 6/25 2.2it/s 2.9s<8.6s

     16/200      2.24G     0.7166       1.12      1.069         36        640: 28% ━━━───────── 7/25 2.3it/s 3.3s<7.7s

     16/200      2.24G     0.7128      1.121      1.071         17        640: 32% ━━━╸──────── 8/25 2.3it/s 3.7s<7.3s

     16/200      2.24G     0.7186      1.096       1.06         24        640: 36% ━━━━──────── 9/25 2.4it/s 4.1s<6.5s

     16/200      2.24G     0.7141      1.074      1.055         23        640: 40% ━━━━╸─────── 10/25 2.5it/s 4.5s<6.1s

     16/200      2.24G     0.7042      1.081      1.049         20        640: 44% ━━━━━─────── 11/25 2.5it/s 4.9s<5.7s

     16/200      2.24G     0.6876      1.066      1.043         17        640: 48% ━━━━━╸────── 12/25 2.5it/s 5.3s<5.2s

     16/200      2.24G     0.6748      1.077       1.05          8        640: 52% ━━━━━━────── 13/25 2.5it/s 5.7s<4.8s

     16/200      2.24G     0.6721      1.095      1.057          9        640: 56% ━━━━━━╸───── 14/25 2.5it/s 6.1s<4.3s

     16/200      2.24G     0.6707      1.088      1.054         24        640: 60% ━━━━━━━───── 15/25 2.5it/s 6.5s<3.9s

     16/200      2.24G     0.6667      1.079      1.049         25        640: 64% ━━━━━━━╸──── 16/25 2.6it/s 6.9s<3.5s

     16/200      2.24G     0.6659      1.075      1.052         14        640: 68% ━━━━━━━━──── 17/25 2.6it/s 7.3s<3.1s

     16/200      2.24G     0.6748      1.084      1.049         37        640: 72% ━━━━━━━━╸─── 18/25 2.6it/s 7.6s<2.7s

     16/200      2.24G     0.6658      1.093      1.052          8        640: 76% ━━━━━━━━━─── 19/25 2.6it/s 8.0s<2.3s

     16/200      2.24G     0.6679      1.086       1.05         23        640: 80% ━━━━━━━━━╸── 20/25 2.6it/s 8.4s<2.0s

     16/200      2.24G     0.6669        1.1      1.053         20        640: 84% ━━━━━━━━━━── 21/25 2.6it/s 8.8s<1.6s

     16/200      2.24G     0.6759      1.094      1.055         20        640: 88% ━━━━━━━━━━╸─ 22/25 2.6it/s 9.2s<1.2s

     16/200      2.24G     0.6748      1.084      1.055         22        640: 92% ━━━━━━━━━━━─ 23/25 2.5it/s 9.6s<0.8s

     16/200      2.24G     0.6781      1.097      1.054         34        640: 96% ━━━━━━━━━━━╸ 24/25 2.7it/s 9.9s<0.4s

     16/200      2.24G     0.6781      1.097      1.054         34        640: 100% ━━━━━━━━━━━━ 25/25 2.5it/s 9.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.3it/s 0.7s

                   all          8          8      0.466      0.683      0.761      0.525

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     17/200      2.24G     0.5768      1.073     0.9915         16        640: 0% ──────────── 0/25  0.4s

     17/200      2.24G     0.6344      1.219      1.147         19        640: 4% ──────────── 1/25 1.2s/it 0.8s<28.5s

     17/200      2.24G     0.6022      1.242      1.083         30        640: 8% ╸─────────── 2/25 1.2it/s 1.2s<19.0s

     17/200      2.24G     0.6111      1.188      1.058         33        640: 12% ━─────────── 3/25 1.6it/s 1.6s<13.6s

     17/200      2.24G     0.6381      1.211      1.114         20        640: 16% ━╸────────── 4/25 1.9it/s 2.0s<11.3s

     17/200      2.24G     0.6207      1.253      1.123          8        640: 20% ━━────────── 5/25 2.1it/s 2.4s<9.6s

     17/200      2.24G     0.6234      1.188      1.111         25        640: 24% ━━╸───────── 6/25 2.2it/s 2.8s<8.6s

     17/200      2.23G     0.6313      1.146      1.093         36        640: 28% ━━━───────── 7/25 2.3it/s 3.2s<7.8s

     17/200      2.24G     0.6496      1.131      1.098         20        640: 32% ━━━╸──────── 8/25 2.4it/s 3.6s<7.1s

     17/200      2.24G     0.6545      1.143      1.092         21        640: 36% ━━━━──────── 9/25 2.5it/s 4.0s<6.5s

     17/200      2.24G     0.6481      1.146      1.093         16        640: 40% ━━━━╸─────── 10/25 2.5it/s 4.4s<6.1s

     17/200      2.24G     0.6548      1.153      1.104         16        640: 44% ━━━━━─────── 11/25 2.4it/s 4.8s<5.7s

     17/200      2.24G     0.6616      1.141      1.094         25        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.3s<5.5s

     17/200      2.24G     0.6575      1.119      1.083         17        640: 52% ━━━━━━────── 13/25 2.4it/s 5.7s<5.0s

     17/200      2.24G     0.6599       1.14       1.08         42        640: 56% ━━━━━━╸───── 14/25 2.5it/s 6.1s<4.5s

     17/200      2.24G     0.6604      1.142      1.098         10        640: 60% ━━━━━━━───── 15/25 2.4it/s 6.5s<4.1s

     17/200      2.24G     0.6714      1.135       1.09         32        640: 64% ━━━━━━━╸──── 16/25 2.5it/s 6.9s<3.6s

     17/200      2.24G     0.6715      1.141      1.088         33        640: 68% ━━━━━━━━──── 17/25 2.5it/s 7.3s<3.2s

     17/200      2.24G      0.665      1.128      1.084         16        640: 72% ━━━━━━━━╸─── 18/25 2.5it/s 7.7s<2.8s

     17/200      2.24G     0.6726      1.126      1.082         34        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.1s<2.5s

     17/200      2.24G     0.6896      1.159      1.086         28        640: 80% ━━━━━━━━━╸── 20/25 2.3it/s 8.6s<2.2s

     17/200      2.23G     0.6852       1.16      1.083          9        640: 84% ━━━━━━━━━━── 21/25 2.4it/s 9.0s<1.7s

     17/200      2.23G     0.6773      1.149       1.08         16        640: 88% ━━━━━━━━━━╸─ 22/25 2.5it/s 9.4s<1.2s

     17/200      2.23G     0.6706      1.152      1.085          9        640: 92% ━━━━━━━━━━━─ 23/25 2.4it/s 9.8s<0.8s

     17/200      2.24G     0.6738      1.139      1.083         27        640: 96% ━━━━━━━━━━━╸ 24/25 2.7it/s 10.1s<0.4s

     17/200      2.24G     0.6738      1.139      1.083         27        640: 100% ━━━━━━━━━━━━ 25/25 2.5it/s 10.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.4it/s 0.7s

                   all          8          8       0.71        0.5      0.666      0.492

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     18/200      2.25G     0.8371      1.007      1.042         27        640: 0% ──────────── 0/25  0.4s

     18/200      2.25G     0.7086      1.112      1.085         26        640: 4% ──────────── 1/25 1.7s/it 0.9s<39.9s

     18/200      2.25G     0.7189      1.094      1.067         23        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<19.8s

     18/200      2.25G     0.6924      1.018      1.023         30        640: 12% ━─────────── 3/25 1.6it/s 1.7s<13.7s

     18/200      2.25G       0.68       1.04      1.023         25        640: 16% ━╸────────── 4/25 1.9it/s 2.1s<11.1s

     18/200      2.25G     0.6833      1.032      1.022         24        640: 20% ━━────────── 5/25 2.1it/s 2.5s<9.7s

     18/200      2.25G     0.7097      1.013      1.015         39        640: 24% ━━╸───────── 6/25 2.2it/s 2.8s<8.5s

     18/200      2.25G     0.6859      1.041      1.032          8        640: 28% ━━━───────── 7/25 2.4it/s 3.2s<7.6s

     18/200      2.25G     0.6794      1.061      1.035         14        640: 32% ━━━╸──────── 8/25 2.4it/s 3.6s<7.0s

     18/200      2.25G     0.6745      1.045      1.031         26        640: 36% ━━━━──────── 9/25 2.4it/s 4.0s<6.6s

     18/200      2.25G     0.6679       1.06      1.049         19        640: 40% ━━━━╸─────── 10/25 2.4it/s 4.5s<6.2s

     18/200      2.25G     0.6662      1.052      1.054         29        640: 44% ━━━━━─────── 11/25 2.4it/s 4.9s<5.9s

     18/200      2.25G     0.6817       1.04      1.056         28        640: 48% ━━━━━╸────── 12/25 2.4it/s 5.3s<5.4s

     18/200      2.25G     0.6844       1.04       1.05         33        640: 52% ━━━━━━────── 13/25 2.4it/s 5.7s<4.9s

     18/200      2.25G     0.6819      1.053      1.053          8        640: 56% ━━━━━━╸───── 14/25 2.6it/s 6.0s<4.3s

     18/200      2.25G     0.6758      1.064      1.046         25        640: 60% ━━━━━━━───── 15/25 2.5it/s 6.4s<3.9s

     18/200      2.25G      0.681      1.057      1.046         16        640: 64% ━━━━━━━╸──── 16/25 2.7it/s 6.8s<3.4s

     18/200      2.25G      0.695      1.073      1.074          8        640: 68% ━━━━━━━━──── 17/25 2.6it/s 7.2s<3.0s

     18/200      2.25G     0.6991      1.072      1.075         24        640: 72% ━━━━━━━━╸─── 18/25 2.4it/s 7.7s<2.9s

     18/200      2.25G     0.6978      1.069      1.077         14        640: 76% ━━━━━━━━━─── 19/25 2.5it/s 8.1s<2.4s

     18/200      2.25G     0.6967       1.06      1.073         22        640: 80% ━━━━━━━━━╸── 20/25 2.5it/s 8.5s<2.0s

     18/200      2.25G     0.6994       1.06      1.068         36        640: 84% ━━━━━━━━━━── 21/25 2.5it/s 8.9s<1.6s

     18/200      2.25G     0.6987      1.052      1.067         20        640: 88% ━━━━━━━━━━╸─ 22/25 2.5it/s 9.3s<1.2s

     18/200      2.25G     0.6923      1.054      1.069         19        640: 92% ━━━━━━━━━━━─ 23/25 2.5it/s 9.7s<0.8s

     18/200      2.25G     0.6921      1.045      1.071         15        640: 96% ━━━━━━━━━━━╸ 24/25 2.7it/s 10.0s<0.4s

     18/200      2.25G     0.6921      1.045      1.071         15        640: 100% ━━━━━━━━━━━━ 25/25 2.5it/s 10.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.5it/s 0.7s

                   all          8          8      0.854      0.419      0.744      0.523

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     19/200      2.25G     0.7561      1.152     0.9967         25        640: 0% ──────────── 0/25  0.4s

     19/200      2.25G      0.727      1.291      1.052         20        640: 4% ──────────── 1/25 1.6s/it 0.9s<37.6s

     19/200      2.25G     0.6931      1.125      1.009         24        640: 8% ╸─────────── 2/25 1.3it/s 1.2s<18.3s

     19/200      2.25G     0.6726       1.08      1.019         27        640: 12% ━─────────── 3/25 1.5it/s 1.7s<14.8s

     19/200      2.25G     0.6587      1.088      1.023         23        640: 16% ━╸────────── 4/25 1.6it/s 2.2s<12.8s

     19/200      2.25G     0.6565      1.105      1.054         20        640: 20% ━━────────── 5/25 1.9it/s 2.6s<10.6s

     19/200      2.25G     0.6475      1.069      1.056         25        640: 24% ━━╸───────── 6/25 2.1it/s 3.0s<9.2s

     19/200      2.25G     0.6468      1.047      1.066         27        640: 28% ━━━───────── 7/25 2.2it/s 3.4s<8.2s

     19/200      2.25G     0.6436      1.033      1.064         14        640: 32% ━━━╸──────── 8/25 2.3it/s 3.8s<7.4s

     19/200      2.25G     0.6422      1.024      1.059         14        640: 36% ━━━━──────── 9/25 2.4it/s 4.2s<6.7s

     19/200      2.25G      0.633      1.038      1.063         15        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.7s<6.6s

     19/200      2.25G       0.64      1.018      1.054         35        640: 44% ━━━━━─────── 11/25 2.3it/s 5.1s<6.0s

     19/200      2.23G     0.6276      1.026      1.063         10        640: 48% ━━━━━╸────── 12/25 2.4it/s 5.5s<5.5s

     19/200      2.24G     0.6279      1.056      1.072         15        640: 52% ━━━━━━────── 13/25 2.4it/s 5.9s<5.0s

     19/200      2.24G     0.6265      1.059      1.067         28        640: 56% ━━━━━━╸───── 14/25 2.4it/s 6.3s<4.5s

     19/200      2.24G     0.6259      1.065      1.076          8        640: 60% ━━━━━━━───── 15/25 2.5it/s 6.7s<4.0s

     19/200      2.24G     0.6239      1.048      1.071         24        640: 64% ━━━━━━━╸──── 16/25 2.5it/s 7.1s<3.6s

     19/200      2.22G       0.62      1.027      1.065         22        640: 68% ━━━━━━━━──── 17/25 2.6it/s 7.5s<3.1s

     19/200      2.25G     0.6193      1.014       1.06         26        640: 72% ━━━━━━━━╸─── 18/25 2.5it/s 7.9s<2.8s

     19/200      2.25G     0.6337      1.007      1.058         47        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.3s<2.5s

     19/200      2.25G     0.6434      1.034       1.06         20        640: 80% ━━━━━━━━━╸── 20/25 2.5it/s 8.7s<2.0s

     19/200      2.25G     0.6397      1.028      1.059         14        640: 84% ━━━━━━━━━━── 21/25 2.5it/s 9.1s<1.6s

     19/200      2.25G      0.644      1.027       1.06         14        640: 88% ━━━━━━━━━━╸─ 22/25 2.6it/s 9.5s<1.2s

     19/200      2.25G      0.643      1.022       1.06         22        640: 92% ━━━━━━━━━━━─ 23/25 2.6it/s 9.9s<0.8s

     19/200      2.24G     0.6405       1.02      1.056         39        640: 96% ━━━━━━━━━━━╸ 24/25 2.7it/s 10.2s<0.4s

     19/200      2.24G     0.6405       1.02      1.056         39        640: 100% ━━━━━━━━━━━━ 25/25 2.4it/s 10.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.7it/s 0.6s

                   all          8          8      0.694      0.795      0.802      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     20/200      2.35G     0.4897     0.9265      1.012         26        640: 0% ──────────── 0/25  0.4s

     20/200      2.37G     0.6083     0.9626      1.083         26        640: 4% ──────────── 1/25 1.4s/it 0.8s<32.9s

     20/200      2.37G     0.6222      1.006      1.053         36        640: 8% ╸─────────── 2/25 1.3it/s 1.2s<18.0s

     20/200      2.37G     0.6253      1.008      1.031         30        640: 12% ━─────────── 3/25 1.5it/s 1.7s<14.3s

     20/200      2.37G     0.6574     0.9963       1.05         28        640: 16% ━╸────────── 4/25 1.9it/s 2.1s<11.2s

     20/200      2.37G     0.6465      1.027      1.068          8        640: 20% ━━────────── 5/25 2.1it/s 2.4s<9.4s

     20/200      2.37G     0.6632       1.06      1.114         19        640: 24% ━━╸───────── 6/25 2.2it/s 2.8s<8.5s

     20/200      2.37G     0.6642      1.083      1.111         21        640: 28% ━━━───────── 7/25 2.3it/s 3.2s<7.8s

     20/200      2.37G     0.6623      1.069      1.103         27        640: 32% ━━━╸──────── 8/25 2.4it/s 3.6s<7.0s

     20/200      2.37G     0.6923      1.044      1.103         28        640: 36% ━━━━──────── 9/25 2.5it/s 4.0s<6.5s

     20/200      2.35G      0.686      1.046      1.127          9        640: 40% ━━━━╸─────── 10/25 2.5it/s 4.4s<6.1s

     20/200      2.35G     0.6848      1.033      1.137         14        640: 44% ━━━━━─────── 11/25 2.5it/s 4.8s<5.6s

     20/200      2.35G     0.6836      1.028      1.125         25        640: 48% ━━━━━╸────── 12/25 2.6it/s 5.2s<5.1s

     20/200      2.35G     0.6808      1.062      1.118         38        640: 52% ━━━━━━────── 13/25 2.5it/s 5.6s<4.7s

     20/200      2.35G     0.6828       1.08      1.131          8        640: 56% ━━━━━━╸───── 14/25 2.6it/s 6.0s<4.3s

     20/200      2.35G     0.6784       1.08       1.12         37        640: 60% ━━━━━━━───── 15/25 2.6it/s 6.3s<3.9s

     20/200      2.35G     0.6735      1.074      1.111         24        640: 64% ━━━━━━━╸──── 16/25 2.6it/s 6.7s<3.5s

     20/200      2.35G      0.677      1.074       1.11         15        640: 68% ━━━━━━━━──── 17/25 2.6it/s 7.1s<3.1s

     20/200      2.35G     0.6809       1.09      1.105         16        640: 72% ━━━━━━━━╸─── 18/25 2.6it/s 7.5s<2.7s

     20/200      2.35G     0.6797      1.084      1.097         24        640: 76% ━━━━━━━━━─── 19/25 2.6it/s 7.9s<2.3s

     20/200      2.35G     0.6787      1.086      1.107          8        640: 80% ━━━━━━━━━╸── 20/25 2.6it/s 8.3s<1.9s

     20/200      2.35G     0.6689      1.087      1.103          9        640: 84% ━━━━━━━━━━── 21/25 2.6it/s 8.6s<1.5s

     20/200      2.34G     0.6725      1.078      1.108         21        640: 88% ━━━━━━━━━━╸─ 22/25 2.6it/s 9.0s<1.2s

     20/200      2.34G     0.6734      1.065      1.101         41        640: 92% ━━━━━━━━━━━─ 23/25 2.6it/s 9.4s<0.8s

     20/200      2.28G     0.6776      1.053      1.095         20        640: 96% ━━━━━━━━━━━╸ 24/25 2.8it/s 9.7s<0.4s

     20/200      2.28G     0.6776      1.053      1.095         20        640: 100% ━━━━━━━━━━━━ 25/25 2.6it/s 9.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.8it/s 0.6s

                   all          8          8      0.878        0.6      0.805      0.581

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     21/200      2.26G      0.535      1.047      1.111         19        640: 0% ──────────── 0/25  0.4s

     21/200      2.26G     0.5082      1.149      1.101          8        640: 4% ──────────── 1/25 1.2s/it 0.8s<29.3s

     21/200      2.26G     0.5489     0.9955      1.059         30        640: 8% ╸─────────── 2/25 1.4it/s 1.1s<17.0s

     21/200      2.26G      0.558     0.9049      1.019         39        640: 12% ━─────────── 3/25 1.7it/s 1.6s<13.2s

     21/200      2.26G     0.5712     0.9014      1.023         16        640: 16% ━╸────────── 4/25 1.9it/s 1.9s<10.9s

     21/200      2.26G     0.5666     0.8849      1.014         27        640: 20% ━━────────── 5/25 2.1it/s 2.3s<9.3s

     21/200      2.26G     0.5682     0.9113      1.031          8        640: 24% ━━╸───────── 6/25 2.3it/s 2.7s<8.3s

     21/200      2.26G     0.5927     0.8987       1.03         34        640: 28% ━━━───────── 7/25 2.3it/s 3.1s<7.7s

     21/200      2.26G     0.6004     0.9206      1.022         27        640: 32% ━━━╸──────── 8/25 2.5it/s 3.5s<6.9s

     21/200      2.26G     0.6105      0.948      1.025         22        640: 36% ━━━━──────── 9/25 2.4it/s 4.0s<6.8s

     21/200      2.25G     0.6102     0.9711      1.016         33        640: 40% ━━━━╸─────── 10/25 2.5it/s 4.3s<6.1s

     21/200      2.25G     0.6377     0.9749      1.022         36        640: 44% ━━━━━─────── 11/25 2.5it/s 4.7s<5.7s

     21/200      2.25G     0.6437     0.9776       1.03         17        640: 48% ━━━━━╸────── 12/25 2.5it/s 5.1s<5.2s

     21/200      2.25G     0.6345     0.9701      1.026         14        640: 52% ━━━━━━────── 13/25 2.5it/s 5.5s<4.8s

     21/200      2.25G     0.6389     0.9723      1.021         30        640: 56% ━━━━━━╸───── 14/25 2.5it/s 5.9s<4.4s

     21/200      2.21G     0.6375     0.9626      1.017         46        640: 60% ━━━━━━━───── 15/25 2.5it/s 6.3s<4.0s

     21/200      2.21G     0.6402     0.9745      1.015         14        640: 64% ━━━━━━━╸──── 16/25 2.6it/s 6.7s<3.5s

     21/200       2.2G     0.6382     0.9879       1.02          8        640: 68% ━━━━━━━━──── 17/25 2.6it/s 7.0s<3.1s

     21/200       2.2G     0.6295     0.9916      1.023          9        640: 72% ━━━━━━━━╸─── 18/25 2.6it/s 7.4s<2.7s

     21/200      2.26G     0.6257     0.9896      1.023         14        640: 76% ━━━━━━━━━─── 19/25 2.6it/s 7.8s<2.3s

     21/200      2.26G     0.6243     0.9922      1.025         16        640: 80% ━━━━━━━━━╸── 20/25 2.6it/s 8.2s<1.9s

     21/200      2.26G     0.6292      1.001      1.022         31        640: 84% ━━━━━━━━━━── 21/25 2.6it/s 8.6s<1.5s

     21/200      2.26G     0.6356      1.015      1.032         15        640: 88% ━━━━━━━━━━╸─ 22/25 2.6it/s 9.0s<1.2s

     21/200      2.26G     0.6299      1.011      1.034         19        640: 92% ━━━━━━━━━━━─ 23/25 2.6it/s 9.4s<0.8s

     21/200       2.2G     0.6338      1.004       1.03         26        640: 96% ━━━━━━━━━━━╸ 24/25 2.8it/s 9.7s<0.4s

     21/200       2.2G     0.6338      1.004       1.03         26        640: 100% ━━━━━━━━━━━━ 25/25 2.6it/s 9.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.5it/s 0.7s

                   all          8          8      0.884      0.567      0.624      0.453

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     22/200      2.25G     0.6532     0.8159     0.9642         41        640: 0% ──────────── 0/25  0.4s

     22/200      2.25G     0.6215     0.7583      0.936         42        640: 4% ──────────── 1/25 1.3s/it 0.8s<31.5s

     22/200      2.25G     0.6275     0.7984     0.9812         27        640: 8% ╸─────────── 2/25 1.3it/s 1.2s<17.8s

     22/200      2.26G     0.5944     0.8969     0.9957         17        640: 12% ━─────────── 3/25 1.6it/s 1.6s<13.6s

     22/200      2.26G     0.6152      0.904     0.9967         20        640: 16% ━╸────────── 4/25 1.9it/s 2.0s<10.8s

     22/200      2.26G     0.6066     0.9306       1.03          8        640: 20% ━━────────── 5/25 2.2it/s 2.4s<9.3s

     22/200      2.26G     0.6098     0.9041      1.023         22        640: 24% ━━╸───────── 6/25 2.3it/s 2.8s<8.4s

     22/200      2.26G     0.5913     0.9113      1.017         15        640: 28% ━━━───────── 7/25 2.4it/s 3.1s<7.6s

     22/200      2.26G     0.6062     0.9138      1.035         38        640: 32% ━━━╸──────── 8/25 2.3it/s 3.6s<7.5s

     22/200      2.25G     0.5975     0.9156      1.036         16        640: 36% ━━━━──────── 9/25 2.4it/s 4.0s<6.8s

     22/200      2.25G     0.6026     0.9117      1.031         35        640: 40% ━━━━╸─────── 10/25 2.4it/s 4.4s<6.2s

     22/200      2.25G     0.6123     0.9435      1.041         14        640: 44% ━━━━━─────── 11/25 2.5it/s 4.8s<5.6s

     22/200      2.25G     0.6126     0.9355      1.039         14        640: 48% ━━━━━╸────── 12/25 2.6it/s 5.2s<5.1s

     22/200      2.25G     0.6125     0.9457      1.048         19        640: 52% ━━━━━━────── 13/25 2.5it/s 5.6s<4.7s

     22/200      2.25G     0.6159     0.9531      1.039         36        640: 56% ━━━━━━╸───── 14/25 2.6it/s 5.9s<4.3s

     22/200      2.25G     0.6085     0.9655      1.045          8        640: 60% ━━━━━━━───── 15/25 2.6it/s 6.3s<3.8s

     22/200      2.25G     0.6109      0.953      1.043         20        640: 64% ━━━━━━━╸──── 16/25 2.6it/s 6.7s<3.4s

     22/200      2.25G     0.6042     0.9559      1.046          9        640: 68% ━━━━━━━━──── 17/25 2.6it/s 7.1s<3.1s

     22/200      2.25G     0.6053     0.9722      1.055          8        640: 72% ━━━━━━━━╸─── 18/25 2.7it/s 7.4s<2.6s

     22/200      2.25G     0.6137     0.9717      1.051         38        640: 76% ━━━━━━━━━─── 19/25 2.5it/s 7.9s<2.4s

     22/200      2.25G     0.6216     0.9641      1.048         22        640: 80% ━━━━━━━━━╸── 20/25 2.5it/s 8.3s<2.0s

     22/200      2.25G     0.6261     0.9718      1.061         14        640: 84% ━━━━━━━━━━── 21/25 2.4it/s 8.8s<1.7s

     22/200      2.25G     0.6251     0.9658      1.057         26        640: 88% ━━━━━━━━━━╸─ 22/25 2.2it/s 9.4s<1.4s

     22/200       2.2G     0.6239     0.9608      1.056         16        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 9.8s<0.9s

     22/200      2.24G     0.6227     0.9575      1.049         33        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 10.1s<0.4s

     22/200      2.24G     0.6227     0.9575      1.049         33        640: 100% ━━━━━━━━━━━━ 25/25 2.5it/s 10.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.0it/s 1.0s

                   all          8          8      0.859        0.6      0.797      0.593

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     23/200      2.29G     0.5434     0.8588     0.9364         25        640: 0% ──────────── 0/25  0.4s

     23/200      2.29G     0.5904      0.838     0.9678         20        640: 4% ──────────── 1/25 1.9s/it 1.0s<44.9s

     23/200      2.29G     0.6707     0.8756     0.9665         28        640: 8% ╸─────────── 2/25 1.1it/s 1.4s<20.3s

     23/200      2.29G     0.6883     0.8837     0.9664         32        640: 12% ━─────────── 3/25 1.7it/s 1.7s<13.0s

     23/200      2.29G     0.6633     0.9162      1.009          8        640: 16% ━╸────────── 4/25 2.1it/s 2.0s<10.2s

     23/200      2.29G     0.6653      0.913      1.017         15        640: 20% ━━────────── 5/25 2.2it/s 2.5s<9.2s

     23/200       2.2G     0.6491     0.9192      1.018         17        640: 24% ━━╸───────── 6/25 2.2it/s 2.9s<8.6s

     23/200      2.25G     0.6303     0.9368      1.014         16        640: 28% ━━━───────── 7/25 2.3it/s 3.3s<8.0s

     23/200      2.25G     0.6407     0.9629      1.048         30        640: 32% ━━━╸──────── 8/25 2.1it/s 3.9s<8.1s

     23/200      2.26G     0.6277     0.9398      1.038         14        640: 36% ━━━━──────── 9/25 2.2it/s 4.3s<7.2s

     23/200      2.26G     0.6261     0.9297      1.033         33        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.7s<6.6s

     23/200      2.21G     0.6318     0.9345      1.035         22        640: 44% ━━━━━─────── 11/25 2.1it/s 5.3s<6.6s

     23/200      2.21G     0.6339     0.9484      1.048         26        640: 48% ━━━━━╸────── 12/25 2.0it/s 5.9s<6.6s

     23/200      2.26G     0.6274     0.9379      1.042         17        640: 52% ━━━━━━────── 13/25 2.1it/s 6.3s<5.7s

     23/200      2.26G     0.6342     0.9665      1.041         48        640: 56% ━━━━━━╸───── 14/25 2.1it/s 6.8s<5.3s

     23/200      2.26G     0.6436     0.9856      1.062         14        640: 60% ━━━━━━━───── 15/25 2.2it/s 7.2s<4.6s

     23/200      2.26G     0.6373       0.97      1.064         17        640: 64% ━━━━━━━╸──── 16/25 2.2it/s 7.6s<4.1s

     23/200      2.26G     0.6368     0.9813      1.075          9        640: 68% ━━━━━━━━──── 17/25 2.2it/s 8.1s<3.6s

     23/200      2.26G     0.6446     0.9865      1.075         20        640: 72% ━━━━━━━━╸─── 18/25 2.3it/s 8.5s<3.0s

     23/200      2.26G     0.6454     0.9791      1.065         30        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.9s<2.5s

     23/200       2.2G     0.6371     0.9798      1.067          8        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 9.3s<2.1s

     23/200      2.25G     0.6396     0.9781      1.074         16        640: 84% ━━━━━━━━━━── 21/25 2.4it/s 9.7s<1.7s

     23/200      2.25G     0.6451     0.9734      1.069         31        640: 88% ━━━━━━━━━━╸─ 22/25 2.2it/s 10.3s<1.4s

     23/200      2.25G     0.6443     0.9645      1.064         31        640: 92% ━━━━━━━━━━━─ 23/25 2.2it/s 10.7s<0.9s

     23/200      2.25G     0.6486     0.9667      1.059         31        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 11.1s<0.4s

     23/200      2.25G     0.6486     0.9667      1.059         31        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 11.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.0s/it 1.0s

                   all          8          8      0.967      0.594      0.862      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     24/200      2.25G     0.6456     0.6809      1.015         25        640: 0% ──────────── 0/25  0.5s

     24/200      2.26G     0.6169      1.052      0.979         26        640: 4% ──────────── 1/25 1.3s/it 0.9s<32.0s

     24/200      2.22G     0.6262      1.001       1.02         24        640: 8% ╸─────────── 2/25 1.1it/s 1.4s<20.5s

     24/200      2.25G     0.6542      1.089      1.029         25        640: 12% ━─────────── 3/25 1.5it/s 1.8s<15.1s

     24/200      2.24G     0.6381      1.086      1.046         15        640: 16% ━╸────────── 4/25 1.7it/s 2.2s<12.2s

     24/200      2.24G      0.664      1.034      1.049         22        640: 20% ━━────────── 5/25 2.0it/s 2.6s<10.2s

     24/200       2.2G     0.6571      0.987      1.037         28        640: 24% ━━╸───────── 6/25 2.1it/s 3.1s<9.1s

     24/200       2.2G     0.6702     0.9973      1.059          8        640: 28% ━━━───────── 7/25 2.2it/s 3.4s<8.1s

     24/200      2.25G     0.6654     0.9921      1.085          8        640: 32% ━━━╸──────── 8/25 2.3it/s 3.9s<7.4s

     24/200      2.22G      0.653     0.9901       1.07         27        640: 36% ━━━━──────── 9/25 2.3it/s 4.3s<6.9s

     24/200      2.26G     0.6701      1.016      1.083         14        640: 40% ━━━━╸─────── 10/25 2.4it/s 4.7s<6.4s

     24/200      2.26G     0.6599     0.9872      1.069         25        640: 44% ━━━━━─────── 11/25 2.3it/s 5.1s<6.0s

     24/200      2.26G     0.6567     0.9866      1.073         27        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.6s<5.6s

     24/200      2.26G     0.6544     0.9916      1.069         22        640: 52% ━━━━━━────── 13/25 2.3it/s 6.0s<5.2s

     24/200      2.26G     0.6581     0.9766      1.073         27        640: 56% ━━━━━━╸───── 14/25 2.3it/s 6.4s<4.7s

     24/200      2.26G     0.6505     0.9616      1.064         28        640: 60% ━━━━━━━───── 15/25 2.4it/s 6.8s<4.2s

     24/200      2.26G     0.6523     0.9538      1.065         23        640: 64% ━━━━━━━╸──── 16/25 2.2it/s 7.4s<4.2s

     24/200      2.22G      0.652     0.9534      1.065         22        640: 68% ━━━━━━━━──── 17/25 2.2it/s 7.8s<3.6s

     24/200      2.27G     0.6484     0.9636      1.071         14        640: 72% ━━━━━━━━╸─── 18/25 2.3it/s 8.3s<3.1s

     24/200      2.27G     0.6465     0.9691      1.064         39        640: 76% ━━━━━━━━━─── 19/25 2.1it/s 8.8s<2.8s

     24/200      2.27G     0.6439     0.9614      1.063         22        640: 80% ━━━━━━━━━╸── 20/25 2.3it/s 9.2s<2.1s

     24/200      2.27G     0.6419     0.9585       1.06         38        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 9.9s<2.0s

     24/200      2.27G     0.6424     0.9547      1.059         14        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 10.4s<1.4s

     24/200      2.27G     0.6507     0.9561      1.063         20        640: 92% ━━━━━━━━━━━─ 23/25 2.2it/s 10.8s<0.9s

     24/200      2.27G     0.6457     0.9484      1.058         15        640: 96% ━━━━━━━━━━━╸ 24/25 2.4it/s 11.1s<0.4s

     24/200      2.27G     0.6457     0.9484      1.058         15        640: 100% ━━━━━━━━━━━━ 25/25 2.2it/s 11.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.1s/it 1.1s

                   all          8          8       0.74      0.684      0.758      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     25/200      2.22G     0.6134     0.7171      0.955         41        640: 0% ──────────── 0/25  0.4s

     25/200       2.2G     0.6138     0.8815      0.969         35        640: 4% ──────────── 1/25 1.9s/it 1.0s<46.2s

     25/200      2.24G     0.6066          1     0.9307         41        640: 8% ╸─────────── 2/25 1.1s/it 1.6s<25.8s

     25/200      2.24G     0.6078     0.9215      0.955         29        640: 12% ━─────────── 3/25 1.3it/s 2.0s<16.8s

     25/200      2.24G     0.6061      0.945      0.984         15        640: 16% ━╸────────── 4/25 1.7it/s 2.4s<12.7s

     25/200      2.24G     0.5959     0.9492     0.9804         26        640: 20% ━━────────── 5/25 1.9it/s 2.8s<10.6s

     25/200      2.24G     0.6068     0.9256     0.9925         21        640: 24% ━━╸───────── 6/25 2.0it/s 3.3s<9.4s

     25/200      2.24G      0.604     0.9196     0.9973         14        640: 28% ━━━───────── 7/25 2.2it/s 3.7s<8.3s

     25/200      2.24G     0.6092     0.9451     0.9934         39        640: 32% ━━━╸──────── 8/25 2.2it/s 4.1s<7.6s

     25/200      2.21G      0.604     0.9348      1.001         20        640: 36% ━━━━──────── 9/25 2.3it/s 4.5s<6.9s

     25/200      2.21G     0.6067     0.9327      1.002         27        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.9s<6.4s

     25/200      2.26G     0.6042      0.924     0.9985         22        640: 44% ━━━━━─────── 11/25 2.3it/s 5.3s<6.0s

     25/200       2.2G     0.6085     0.9136      0.999         33        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.8s<5.6s

     25/200      2.25G     0.6014     0.8951      1.003         16        640: 52% ━━━━━━────── 13/25 2.3it/s 6.2s<5.2s

     25/200      2.25G     0.6171     0.8887      1.005         16        640: 56% ━━━━━━╸───── 14/25 2.3it/s 6.6s<4.7s

     25/200      2.25G     0.6214     0.8852      1.012         14        640: 60% ━━━━━━━───── 15/25 2.4it/s 7.0s<4.2s

     25/200      2.25G     0.6112     0.8776       1.01         17        640: 64% ━━━━━━━╸──── 16/25 2.4it/s 7.5s<3.8s

     25/200      2.25G     0.6139      0.884      1.015          8        640: 68% ━━━━━━━━──── 17/25 2.4it/s 7.9s<3.3s

     25/200      2.25G     0.6121     0.8914      1.029          9        640: 72% ━━━━━━━━╸─── 18/25 2.3it/s 8.3s<3.0s

     25/200      2.25G      0.612      0.888       1.03         15        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.7s<2.5s

     25/200      2.25G     0.6096     0.8912      1.022         43        640: 80% ━━━━━━━━━╸── 20/25 2.2it/s 9.3s<2.3s

     25/200      2.25G     0.6096     0.9042      1.025         25        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.7s<1.8s

     25/200      2.25G     0.6121     0.9079       1.04          8        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 10.1s<1.3s

     25/200      2.25G     0.6088     0.9005      1.038         18        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 10.6s<0.9s

     25/200      2.25G     0.5996     0.9095       1.04          6        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 10.9s<0.4s

     25/200      2.25G     0.5996     0.9095       1.04          6        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 10.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.2it/s 0.8s

                   all          8          8      0.729      0.793      0.809      0.612

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     26/200      2.25G      0.581     0.7738       1.06         14        640: 0% ──────────── 0/25  0.4s

     26/200      2.25G     0.5889      0.768      1.018         24        640: 4% ──────────── 1/25 1.4s/it 0.8s<33.4s

     26/200      2.25G     0.5796     0.7443     0.9957         24        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<19.2s

     26/200      2.25G     0.5623     0.7232     0.9669         35        640: 12% ━─────────── 3/25 1.5it/s 1.7s<14.3s

     26/200      2.25G     0.5789     0.7212     0.9687         23        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<12.0s

     26/200      2.25G      0.593     0.7392     0.9671         39        640: 20% ━━────────── 5/25 1.8it/s 2.7s<11.0s

     26/200      2.25G      0.601     0.7661      0.984         16        640: 24% ━━╸───────── 6/25 2.0it/s 3.1s<9.6s

     26/200      2.22G     0.5977      0.767     0.9866         22        640: 28% ━━━───────── 7/25 2.1it/s 3.5s<8.7s

     26/200       2.2G      0.595     0.7581     0.9836         23        640: 32% ━━━╸──────── 8/25 2.2it/s 3.9s<7.9s

     26/200      2.25G     0.5982     0.7767     0.9956         17        640: 36% ━━━━──────── 9/25 2.2it/s 4.4s<7.3s

     26/200      2.25G     0.5953     0.7774      0.996         22        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.8s<6.6s

     26/200      2.25G     0.5976     0.8069      1.003         20        640: 44% ━━━━━─────── 11/25 2.3it/s 5.2s<6.0s

     26/200      2.25G     0.6035     0.8317     0.9974         31        640: 48% ━━━━━╸────── 12/25 2.4it/s 5.6s<5.5s

     26/200      2.25G     0.6079     0.8177     0.9943         24        640: 52% ━━━━━━────── 13/25 2.4it/s 6.0s<5.1s

     26/200      2.25G     0.6134     0.8377     0.9992         32        640: 56% ━━━━━━╸───── 14/25 2.4it/s 6.5s<4.7s

     26/200      2.25G     0.6172     0.8313      1.004         16        640: 60% ━━━━━━━───── 15/25 2.3it/s 6.9s<4.3s

     26/200      2.25G     0.6113     0.8191      1.005         28        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.4s<4.0s

     26/200      2.25G     0.6159     0.8129      1.006         16        640: 68% ━━━━━━━━──── 17/25 2.3it/s 7.8s<3.5s

     26/200      2.25G     0.6206     0.8102      1.008         20        640: 72% ━━━━━━━━╸─── 18/25 2.3it/s 8.2s<3.0s

     26/200      2.25G     0.6255      0.811       1.01         26        640: 76% ━━━━━━━━━─── 19/25 2.2it/s 8.8s<2.8s

     26/200      2.25G     0.6342      0.835      1.017         25        640: 80% ━━━━━━━━━╸── 20/25 2.2it/s 9.2s<2.2s

     26/200      2.25G     0.6291      0.849      1.021          8        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.6s<1.8s

     26/200      2.25G     0.6297     0.8551      1.028          8        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 10.0s<1.3s

     26/200      2.25G     0.6278     0.8561      1.032         19        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 10.4s<0.9s

     26/200      2.25G     0.6245     0.8519      1.025         26        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 10.8s<0.4s

     26/200      2.25G     0.6245     0.8519      1.025         26        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 10.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.0it/s 1.0s

                   all          8          8      0.859        0.8      0.995      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     27/200      2.25G     0.4865     0.7514     0.8582         54        640: 0% ──────────── 0/25  0.6s

     27/200      2.25G     0.4961     0.7667     0.9084         17        640: 4% ──────────── 1/25 1.5s/it 1.1s<35.8s

     27/200      2.25G     0.5696     0.8777      1.038          9        640: 8% ╸─────────── 2/25 1.2it/s 1.5s<18.8s

     27/200      2.22G      0.577      0.841      1.028         16        640: 12% ━─────────── 3/25 1.5it/s 1.9s<14.3s

     27/200      2.27G      0.582     0.8207      1.001         39        640: 16% ━╸────────── 4/25 1.6it/s 2.5s<13.1s

     27/200      2.27G     0.5658     0.8536      1.001         20        640: 20% ━━────────── 5/25 1.8it/s 2.9s<11.1s

     27/200      2.27G     0.5976     0.8616      1.043         14        640: 24% ━━╸───────── 6/25 1.9it/s 3.4s<9.7s

     27/200      2.27G      0.615       0.85      1.034         29        640: 28% ━━━───────── 7/25 2.1it/s 3.8s<8.5s

     27/200      2.27G     0.6164     0.8486      1.028         22        640: 32% ━━━╸──────── 8/25 2.2it/s 4.2s<7.9s

     27/200      2.27G     0.6084     0.8214      1.023         26        640: 36% ━━━━──────── 9/25 2.2it/s 4.7s<7.3s

     27/200      2.27G     0.6039     0.8049      1.022         36        640: 40% ━━━━╸─────── 10/25 2.2it/s 5.1s<6.8s

     27/200      2.27G     0.6019     0.7977      1.016         28        640: 44% ━━━━━─────── 11/25 2.2it/s 5.5s<6.2s

     27/200      2.27G     0.5902     0.7988      1.021          8        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.9s<5.6s

     27/200      2.27G     0.5988     0.8122      1.033         14        640: 52% ━━━━━━────── 13/25 2.4it/s 6.3s<5.1s

     27/200      2.27G     0.6091     0.8083      1.033         20        640: 56% ━━━━━━╸───── 14/25 2.4it/s 6.8s<4.6s

     27/200      2.27G     0.6083     0.8036      1.029         23        640: 60% ━━━━━━━───── 15/25 2.4it/s 7.2s<4.3s

     27/200      2.27G      0.619     0.8072      1.039         17        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.6s<3.9s

     27/200      2.27G     0.6194      0.809      1.045          8        640: 68% ━━━━━━━━──── 17/25 2.4it/s 8.0s<3.3s

     27/200      2.27G     0.6211     0.8201      1.042         36        640: 72% ━━━━━━━━╸─── 18/25 2.4it/s 8.4s<2.9s

     27/200      2.27G     0.6253      0.815      1.042         22        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.8s<2.5s

     27/200      2.27G     0.6242     0.8117      1.037         36        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 9.2s<2.1s

     27/200      2.27G     0.6253     0.8136      1.037         14        640: 84% ━━━━━━━━━━── 21/25 2.4it/s 9.7s<1.6s

     27/200      2.27G     0.6221     0.8134      1.032         22        640: 88% ━━━━━━━━━━╸─ 22/25 2.2it/s 10.2s<1.4s

     27/200      2.27G      0.628     0.8115      1.033         22        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 10.7s<0.9s

     27/200      2.27G     0.6304     0.8255      1.048          6        640: 96% ━━━━━━━━━━━╸ 24/25 2.4it/s 11.0s<0.4s

     27/200      2.27G     0.6304     0.8255      1.048          6        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 11.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.3s/it 1.3s

                   all          8          8      0.917      0.709      0.862      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     28/200      2.24G     0.4744     0.8456     0.9556         19        640: 0% ──────────── 0/25  0.4s

     28/200      2.26G     0.5315     0.7432     0.9356         35        640: 4% ──────────── 1/25 1.3s/it 0.8s<32.4s

     28/200      2.26G     0.5037     0.7655     0.9418         19        640: 8% ╸─────────── 2/25 1.2it/s 1.2s<18.6s

     28/200      2.26G     0.4762     0.7921     0.9845          8        640: 12% ━─────────── 3/25 1.6it/s 1.6s<13.8s

     28/200      2.26G     0.5433     0.7829     0.9825         22        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<11.5s

     28/200      2.26G     0.5415     0.8183     0.9972         19        640: 20% ━━────────── 5/25 2.0it/s 2.5s<10.2s

     28/200      2.25G     0.5636     0.8191      1.021         14        640: 24% ━━╸───────── 6/25 2.1it/s 2.9s<9.2s

     28/200      2.25G     0.5669     0.8338      1.023         30        640: 28% ━━━───────── 7/25 2.1it/s 3.4s<8.6s

     28/200      2.25G     0.5755     0.8175      1.026         20        640: 32% ━━━╸──────── 8/25 2.2it/s 3.8s<7.9s

     28/200      2.25G     0.5749      0.805      1.028         25        640: 36% ━━━━──────── 9/25 2.2it/s 4.3s<7.3s

     28/200      2.25G       0.58     0.7956       1.02         30        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.7s<6.6s

     28/200      2.25G     0.5859     0.7979       1.03         18        640: 44% ━━━━━─────── 11/25 2.2it/s 5.2s<6.3s

     28/200      2.25G     0.6028     0.7986      1.029         39        640: 48% ━━━━━╸────── 12/25 2.1it/s 5.7s<6.3s

     28/200      2.25G     0.6117     0.8135      1.034         20        640: 52% ━━━━━━────── 13/25 2.2it/s 6.2s<5.5s

     28/200       2.2G     0.6062     0.8062      1.036         16        640: 56% ━━━━━━╸───── 14/25 2.2it/s 6.6s<5.1s

     28/200      2.26G     0.6041     0.8046      1.032         15        640: 60% ━━━━━━━───── 15/25 2.2it/s 7.0s<4.5s

     28/200      2.26G     0.6074     0.7977      1.032         22        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.5s<3.9s

     28/200      2.26G     0.6071     0.7971      1.028         27        640: 68% ━━━━━━━━──── 17/25 2.3it/s 7.9s<3.5s

     28/200      2.26G     0.6086     0.7991       1.03         23        640: 72% ━━━━━━━━╸─── 18/25 2.3it/s 8.3s<3.0s

     28/200      2.26G     0.6146     0.7921      1.028         16        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.7s<2.5s

     28/200      2.21G     0.6259     0.7885      1.024         36        640: 80% ━━━━━━━━━╸── 20/25 2.1it/s 9.4s<2.4s

     28/200      2.21G     0.6305     0.7915      1.022         22        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 10.0s<2.0s

     28/200       2.2G     0.6284     0.7854      1.019         24        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 10.4s<1.4s

     28/200      2.25G     0.6239      0.801      1.016         31        640: 92% ━━━━━━━━━━━─ 23/25 2.1it/s 10.8s<0.9s

     28/200      2.22G     0.6181     0.8013       1.02          8        640: 96% ━━━━━━━━━━━╸ 24/25 2.1it/s 11.3s<0.5s

     28/200      2.22G     0.6181     0.8013       1.02          8        640: 100% ━━━━━━━━━━━━ 25/25 2.2it/s 11.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.2s/it 1.2s

                   all          8          8      0.881        0.7      0.796      0.494

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     29/200      2.26G     0.5262      0.585     0.9254         24        640: 0% ──────────── 0/25  0.4s

     29/200      2.26G     0.5218     0.6733     0.9528         16        640: 4% ──────────── 1/25 1.5s/it 0.9s<34.8s

     29/200      2.22G     0.5459     0.6712     0.9713         25        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<19.7s

     29/200      2.25G     0.5487     0.7227      1.027         19        640: 12% ━─────────── 3/25 1.5it/s 1.8s<14.6s

     29/200      2.25G     0.5629     0.7572      1.099          8        640: 16% ━╸────────── 4/25 1.7it/s 2.2s<12.2s

     29/200      2.25G     0.5816      0.745      1.111         17        640: 20% ━━────────── 5/25 1.9it/s 2.7s<10.7s

     29/200      2.25G     0.5773     0.7681      1.112          8        640: 24% ━━╸───────── 6/25 2.0it/s 3.1s<9.3s

     29/200      2.25G     0.5889     0.7654      1.094         34        640: 28% ━━━───────── 7/25 2.1it/s 3.5s<8.5s

     29/200      2.25G     0.6045     0.7811      1.094         26        640: 32% ━━━╸──────── 8/25 2.2it/s 3.9s<7.8s

     29/200      2.26G     0.6054     0.7725      1.093         21        640: 36% ━━━━──────── 9/25 2.2it/s 4.4s<7.3s

     29/200      2.26G     0.6123      0.771      1.089         20        640: 40% ━━━━╸─────── 10/25 2.2it/s 4.8s<6.7s

     29/200      2.26G     0.6105     0.7688      1.083         33        640: 44% ━━━━━─────── 11/25 2.3it/s 5.2s<6.2s

     29/200      2.25G     0.6072     0.7558      1.069         31        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.7s<5.8s

     29/200      2.25G     0.6251     0.7531      1.071         16        640: 52% ━━━━━━────── 13/25 2.3it/s 6.1s<5.2s

     29/200      2.21G     0.6363     0.7614      1.075         15        640: 56% ━━━━━━╸───── 14/25 2.3it/s 6.5s<4.8s

     29/200      2.26G     0.6562     0.7722      1.086         26        640: 60% ━━━━━━━───── 15/25 2.3it/s 7.0s<4.3s

     29/200       2.2G     0.6563      0.775      1.086         17        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.4s<3.9s

     29/200      2.25G     0.6565     0.7686       1.08         30        640: 68% ━━━━━━━━──── 17/25 2.3it/s 7.8s<3.4s

     29/200      2.22G     0.6488      0.763      1.075         33        640: 72% ━━━━━━━━╸─── 18/25 2.1it/s 8.4s<3.3s

     29/200      2.27G      0.643      0.771      1.069         30        640: 76% ━━━━━━━━━─── 19/25 2.2it/s 8.9s<2.8s

     29/200      2.27G     0.6516     0.7737      1.068         14        640: 80% ━━━━━━━━━╸── 20/25 2.3it/s 9.2s<2.2s

     29/200      2.27G     0.6502     0.7797      1.066         15        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.7s<1.7s

     29/200      2.27G      0.648     0.7735      1.061         41        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 10.2s<1.4s

     29/200      2.27G     0.6416     0.7694      1.056         22        640: 92% ━━━━━━━━━━━─ 23/25 2.2it/s 10.7s<0.9s

     29/200      2.27G      0.637     0.7698      1.057         17        640: 96% ━━━━━━━━━━━╸ 24/25 2.1it/s 11.2s<0.5s

     29/200      2.27G      0.637     0.7698      1.057         17        640: 100% ━━━━━━━━━━━━ 25/25 2.2it/s 11.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.1s/it 1.1s

                   all          8          8      0.635        0.7      0.738      0.507

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     30/200      2.27G     0.5684     0.5947     0.9175         30        640: 0% ──────────── 0/25  0.4s

     30/200      2.27G     0.5826     0.6136     0.9256         33        640: 4% ──────────── 1/25 1.4s/it 0.8s<32.8s

     30/200      2.27G     0.5996     0.6524     0.9619         26        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<19.3s

     30/200      2.27G     0.6495     0.7266      1.006         28        640: 12% ━─────────── 3/25 1.3it/s 1.9s<16.9s

     30/200      2.27G     0.6452     0.7536      1.057          9        640: 16% ━╸────────── 4/25 1.6it/s 2.4s<13.2s

     30/200      2.27G     0.6204     0.7167       1.03         24        640: 20% ━━────────── 5/25 1.8it/s 2.8s<11.1s

     30/200      2.27G     0.6186     0.7136      1.028         36        640: 24% ━━╸───────── 6/25 2.0it/s 3.2s<9.6s

     30/200      2.27G     0.6042     0.7001      1.021         16        640: 28% ━━━───────── 7/25 2.1it/s 3.6s<8.6s

     30/200      2.27G     0.5985     0.6934      1.016         34        640: 32% ━━━╸──────── 8/25 2.0it/s 4.2s<8.6s

     30/200      2.22G     0.5947     0.6897      1.009         33        640: 36% ━━━━──────── 9/25 1.9it/s 4.8s<8.3s

     30/200      2.27G     0.5893     0.7132      1.015          8        640: 40% ━━━━╸─────── 10/25 2.1it/s 5.2s<7.2s

     30/200       2.2G     0.5939     0.7199      1.026         16        640: 44% ━━━━━─────── 11/25 2.2it/s 5.6s<6.5s

     30/200       2.2G     0.5916     0.7212      1.021         17        640: 48% ━━━━━╸────── 12/25 2.2it/s 6.1s<5.9s

     30/200       2.2G     0.5954      0.714      1.018         22        640: 52% ━━━━━━────── 13/25 2.2it/s 6.5s<5.4s

     30/200       2.2G     0.5863      0.723      1.021          8        640: 56% ━━━━━━╸───── 14/25 2.3it/s 6.9s<4.9s

     30/200      2.25G       0.58     0.7338      1.019         19        640: 60% ━━━━━━━───── 15/25 2.3it/s 7.3s<4.4s

     30/200      2.25G     0.5737     0.7251      1.012         27        640: 64% ━━━━━━━╸──── 16/25 2.2it/s 7.8s<4.0s

     30/200      2.26G     0.5716     0.7196      1.011         20        640: 68% ━━━━━━━━──── 17/25 2.3it/s 8.2s<3.5s

     30/200      2.26G     0.5715     0.7199       1.01         22        640: 72% ━━━━━━━━╸─── 18/25 2.3it/s 8.7s<3.0s

     30/200      2.26G     0.5703     0.7229      1.013         14        640: 76% ━━━━━━━━━─── 19/25 2.3it/s 9.1s<2.6s

     30/200      2.26G     0.5738     0.7213      1.011         27        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 9.5s<2.1s

     30/200      2.26G     0.5805     0.7248      1.019         16        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.9s<1.7s

     30/200      2.26G     0.5826      0.733      1.017         44        640: 88% ━━━━━━━━━━╸─ 22/25 2.2it/s 10.4s<1.3s

     30/200      2.26G     0.5869     0.7305      1.019         22        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 10.9s<0.9s

     30/200      2.26G     0.5839     0.7337      1.023          7        640: 96% ━━━━━━━━━━━╸ 24/25 2.4it/s 11.2s<0.4s

     30/200      2.26G     0.5839     0.7337      1.023          7        640: 100% ━━━━━━━━━━━━ 25/25 2.2it/s 11.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.0it/s 1.0s

                   all          8          8      0.643        0.8      0.716      0.521

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     31/200      2.32G     0.4968     0.6374     0.9729         16        640: 0% ──────────── 0/25  0.4s

     31/200      2.32G     0.5164     0.7054      1.031         16        640: 4% ──────────── 1/25 1.5s/it 0.9s<35.1s

     31/200      2.32G     0.5125      0.717       1.06          9        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<19.5s

     31/200      2.32G     0.5423      0.736      1.023         33        640: 12% ━─────────── 3/25 1.5it/s 1.7s<14.3s

     31/200      2.32G     0.5556     0.7549      1.007         22        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<11.6s

     31/200      2.32G     0.5971     0.7409      1.017         24        640: 20% ━━────────── 5/25 2.0it/s 2.6s<10.2s

     31/200      2.32G     0.6113     0.7296      1.009         22        640: 24% ━━╸───────── 6/25 2.1it/s 3.0s<9.2s

     31/200      2.27G     0.6185     0.7284      1.008         33        640: 28% ━━━───────── 7/25 2.2it/s 3.4s<8.3s

     31/200      2.32G      0.601     0.7293      1.009         31        640: 32% ━━━╸──────── 8/25 2.2it/s 3.8s<7.7s

     31/200      2.28G      0.616     0.7279      1.008         30        640: 36% ━━━━──────── 9/25 2.2it/s 4.3s<7.2s

     31/200      2.33G     0.6187     0.7383      1.026          8        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.7s<6.6s

     31/200      2.33G     0.6223     0.7341       1.03         33        640: 44% ━━━━━─────── 11/25 2.3it/s 5.1s<6.1s

     31/200      2.33G     0.6177     0.7264      1.026         22        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.6s<5.7s

     31/200      2.33G     0.6147     0.7201      1.025         23        640: 52% ━━━━━━────── 13/25 2.3it/s 6.0s<5.2s

     31/200      2.33G     0.6117     0.7169      1.026         25        640: 56% ━━━━━━╸───── 14/25 2.1it/s 6.6s<5.2s

     31/200      2.33G     0.6176      0.726      1.058          9        640: 60% ━━━━━━━───── 15/25 2.1it/s 7.1s<4.7s

     31/200      2.33G     0.6268     0.7246      1.055         21        640: 64% ━━━━━━━╸──── 16/25 2.2it/s 7.5s<4.1s

     31/200      2.33G     0.6268     0.7268      1.048         37        640: 68% ━━━━━━━━──── 17/25 2.0it/s 8.1s<3.9s

     31/200      2.33G     0.6297     0.7251      1.057         15        640: 72% ━━━━━━━━╸─── 18/25 2.1it/s 8.5s<3.3s

     31/200      2.33G     0.6265     0.7196      1.055         23        640: 76% ━━━━━━━━━─── 19/25 2.2it/s 9.0s<2.7s

     31/200      2.33G     0.6249     0.7143      1.052         17        640: 80% ━━━━━━━━━╸── 20/25 2.2it/s 9.4s<2.3s

     31/200      2.33G     0.6224     0.7092      1.047         22        640: 84% ━━━━━━━━━━── 21/25 2.2it/s 9.8s<1.8s

     31/200      2.33G     0.6352     0.7055      1.048         22        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 10.2s<1.3s

     31/200      2.33G     0.6291     0.7073      1.044         39        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 10.7s<0.9s

     31/200      2.33G     0.6314     0.7091      1.051          6        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 11.0s<0.4s

     31/200      2.33G     0.6314     0.7091      1.051          6        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 11.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.0s/it 1.0s

                   all          8          8      0.609        0.8      0.749      0.554

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     32/200      2.33G     0.4463      0.697     0.9543          8        640: 0% ──────────── 0/25  0.4s

     32/200      2.33G     0.5188     0.8797      1.021         15        640: 4% ──────────── 1/25 1.4s/it 0.9s<34.4s

     32/200      2.33G     0.5388      0.786     0.9844         16        640: 8% ╸─────────── 2/25 1.3it/s 1.2s<18.2s

     32/200      2.29G     0.5999     0.8089       1.02         32        640: 12% ━─────────── 3/25 1.6it/s 1.7s<14.2s

     32/200      2.33G     0.6072     0.7858      1.029         17        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<11.9s

     32/200      2.33G     0.6497     0.7568      1.042         24        640: 20% ━━────────── 5/25 2.0it/s 2.6s<10.2s

     32/200      2.33G     0.6544     0.7563      1.036         21        640: 24% ━━╸───────── 6/25 2.1it/s 3.0s<9.2s

     32/200      2.33G     0.6501       0.76      1.024         22        640: 28% ━━━───────── 7/25 2.1it/s 3.4s<8.4s

     32/200      2.33G     0.6674     0.7519       1.01         42        640: 32% ━━━╸──────── 8/25 2.0it/s 4.0s<8.4s

     32/200      2.33G     0.6553     0.7354      1.004         25        640: 36% ━━━━──────── 9/25 2.1it/s 4.4s<7.6s

     32/200      2.33G     0.6568     0.7621      1.013         30        640: 40% ━━━━╸─────── 10/25 2.2it/s 4.8s<6.9s

     32/200      2.33G     0.6494     0.7667      1.028          8        640: 44% ━━━━━─────── 11/25 2.2it/s 5.3s<6.2s

     32/200      2.33G     0.6428     0.7692      1.039         20        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.7s<5.8s

     32/200      2.33G     0.6464       0.76      1.036         22        640: 52% ━━━━━━────── 13/25 2.1it/s 6.3s<5.7s

     32/200      2.33G     0.6497     0.7592      1.052         15        640: 56% ━━━━━━╸───── 14/25 2.1it/s 6.7s<5.2s

     32/200      2.33G     0.6395     0.7592      1.049         16        640: 60% ━━━━━━━───── 15/25 2.2it/s 7.2s<4.5s

     32/200      2.33G     0.6295     0.7581      1.043         14        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.6s<4.0s

     32/200      2.33G     0.6311     0.7564      1.042         27        640: 68% ━━━━━━━━──── 17/25 2.3it/s 8.0s<3.5s

     32/200      2.33G     0.6315     0.7578      1.043         14        640: 72% ━━━━━━━━╸─── 18/25 2.4it/s 8.4s<3.0s

     32/200      2.33G     0.6341     0.7615      1.041         24        640: 76% ━━━━━━━━━─── 19/25 2.5it/s 8.8s<2.4s

     32/200      2.33G     0.6315     0.7547      1.037         16        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 9.2s<2.1s

     32/200      2.33G     0.6282      0.754      1.033         42        640: 84% ━━━━━━━━━━── 21/25 2.2it/s 9.8s<1.8s

     32/200      2.33G     0.6251     0.7502      1.031         38        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 10.2s<1.3s

     32/200      2.33G     0.6272      0.751      1.028         35        640: 92% ━━━━━━━━━━━─ 23/25 2.1it/s 10.8s<1.0s

     32/200      2.27G     0.6226     0.7463      1.028         15        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 11.2s<0.4s

     32/200      2.27G     0.6226     0.7463      1.028         15        640: 100% ━━━━━━━━━━━━ 25/25 2.2it/s 11.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.3s/it 1.3s

                   all          8          8       0.65      0.692      0.847      0.656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     33/200      2.26G     0.5585     0.6366      1.079         17        640: 0% ──────────── 0/25  0.4s

     33/200      2.26G     0.5519     0.6708      1.001         22        640: 4% ──────────── 1/25 1.4s/it 0.9s<33.9s

     33/200      2.26G     0.5368     0.6406     0.9799         24        640: 8% ╸─────────── 2/25 1.1it/s 1.3s<20.4s

     33/200      2.26G      0.567     0.6777      1.001         14        640: 12% ━─────────── 3/25 1.5it/s 1.7s<14.3s

     33/200      2.26G     0.6021     0.6696     0.9989         41        640: 16% ━╸────────── 4/25 1.8it/s 2.2s<11.8s

     33/200      2.21G     0.6163     0.6859      1.019         14        640: 20% ━━────────── 5/25 1.9it/s 2.6s<10.5s

     33/200      2.26G     0.6083     0.6928     0.9995         21        640: 24% ━━╸───────── 6/25 2.1it/s 3.0s<9.2s

     33/200      2.21G     0.5935      0.703      1.003          8        640: 28% ━━━───────── 7/25 2.2it/s 3.4s<8.2s

     33/200      2.26G      0.591     0.7103          1         14        640: 32% ━━━╸──────── 8/25 2.2it/s 3.9s<7.6s

     33/200      2.26G     0.6106     0.7129      1.001         44        640: 36% ━━━━──────── 9/25 2.1it/s 4.4s<7.6s

     33/200      2.26G     0.6148     0.7173      1.026          9        640: 40% ━━━━╸─────── 10/25 2.1it/s 4.9s<7.0s

     33/200      2.26G      0.615     0.7126      1.019         43        640: 44% ━━━━━─────── 11/25 2.0it/s 5.5s<6.9s

     33/200      2.26G     0.6361     0.7187      1.021         20        640: 48% ━━━━━╸────── 12/25 2.2it/s 5.8s<6.0s

     33/200      2.26G     0.6417     0.7123      1.026         16        640: 52% ━━━━━━────── 13/25 2.2it/s 6.3s<5.4s

     33/200      2.22G     0.6316     0.7129      1.028         20        640: 56% ━━━━━━╸───── 14/25 2.2it/s 6.7s<4.9s

     33/200      2.26G     0.6235       0.71      1.022         14        640: 60% ━━━━━━━───── 15/25 2.3it/s 7.1s<4.3s

     33/200      2.22G     0.6227     0.7038      1.021         41        640: 64% ━━━━━━━╸──── 16/25 2.2it/s 7.7s<4.2s

     33/200      2.27G     0.6391      0.703      1.026         16        640: 68% ━━━━━━━━──── 17/25 2.2it/s 8.1s<3.6s

     33/200      2.22G     0.6371     0.6956      1.026         24        640: 72% ━━━━━━━━╸─── 18/25 2.2it/s 8.5s<3.2s

     33/200      2.22G     0.6323     0.6955      1.021         22        640: 76% ━━━━━━━━━─── 19/25 2.3it/s 9.0s<2.6s

     33/200      2.21G     0.6297     0.6964      1.029          9        640: 80% ━━━━━━━━━╸── 20/25 2.3it/s 9.4s<2.2s

     33/200      2.22G     0.6275     0.6991      1.027         24        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.8s<1.7s

     33/200       2.2G     0.6204     0.6983      1.026         31        640: 88% ━━━━━━━━━━╸─ 22/25 2.4it/s 10.2s<1.3s

     33/200       2.2G     0.6303     0.6951      1.029         25        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 10.7s<0.9s

     33/200      2.24G     0.6248     0.6933      1.025         25        640: 96% ━━━━━━━━━━━╸ 24/25 2.4it/s 11.0s<0.4s

     33/200      2.24G     0.6248     0.6933      1.025         25        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 11.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.5s/it 1.5s

                   all          8          8      0.788        0.8      0.969      0.763

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     34/200      2.26G     0.8337     0.7759       1.26         22        640: 0% ──────────── 0/25  0.4s

     34/200      2.21G     0.7988     0.7198      1.159         14        640: 4% ──────────── 1/25 1.4s/it 0.8s<33.2s

     34/200      2.26G     0.7361      0.696      1.098         20        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<18.6s

     34/200      2.26G     0.7038     0.6756      1.069         35        640: 12% ━─────────── 3/25 1.6it/s 1.7s<14.0s

     34/200      2.26G     0.6972     0.7183      1.086         20        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<11.9s

     34/200      2.26G     0.6475     0.6893      1.055         17        640: 20% ━━────────── 5/25 1.9it/s 2.6s<10.5s

     34/200      2.26G     0.6608     0.6912      1.044         24        640: 24% ━━╸───────── 6/25 2.2it/s 2.9s<8.6s

     34/200      2.26G      0.643     0.6752      1.036         16        640: 28% ━━━───────── 7/25 2.3it/s 3.3s<7.8s

     34/200      2.22G     0.6445     0.6702       1.03         30        640: 32% ━━━╸──────── 8/25 2.3it/s 3.8s<7.4s

     34/200      2.22G     0.6323     0.6677      1.022         26        640: 36% ━━━━──────── 9/25 2.3it/s 4.2s<7.1s

     34/200      2.22G     0.6266     0.6689      1.028         27        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.6s<6.6s

     34/200      2.26G     0.6215     0.6713      1.022         16        640: 44% ━━━━━─────── 11/25 2.3it/s 5.1s<6.1s

     34/200       2.2G     0.6186     0.6678      1.019         29        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.5s<5.7s

     34/200       2.2G     0.6141     0.6726      1.033         20        640: 52% ━━━━━━────── 13/25 2.1it/s 6.1s<5.8s

     34/200      2.21G     0.6141     0.6758      1.036         20        640: 56% ━━━━━━╸───── 14/25 2.2it/s 6.6s<5.1s

     34/200      2.26G      0.622     0.6747      1.035         34        640: 60% ━━━━━━━───── 15/25 2.2it/s 7.0s<4.5s

     34/200       2.2G     0.6192     0.6731      1.035         17        640: 64% ━━━━━━━╸──── 16/25 2.2it/s 7.5s<4.2s

     34/200      2.25G      0.621     0.6827      1.041         20        640: 68% ━━━━━━━━──── 17/25 2.2it/s 7.9s<3.6s

     34/200      2.26G     0.6141     0.6866      1.038         15        640: 72% ━━━━━━━━╸─── 18/25 2.2it/s 8.4s<3.2s

     34/200      2.26G     0.6131     0.6832      1.036         28        640: 76% ━━━━━━━━━─── 19/25 2.2it/s 8.8s<2.7s

     34/200      2.26G     0.6183     0.6816      1.037         16        640: 80% ━━━━━━━━━╸── 20/25 2.2it/s 9.2s<2.2s

     34/200      2.26G     0.6213     0.6818      1.035         28        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.7s<1.8s

     34/200      2.26G     0.6213     0.6843      1.044         19        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 10.1s<1.3s

     34/200      2.26G     0.6273     0.6844      1.039         33        640: 92% ━━━━━━━━━━━─ 23/25 2.4it/s 10.5s<0.8s

     34/200      2.25G     0.6213     0.6835      1.037         12        640: 96% ━━━━━━━━━━━╸ 24/25 2.0it/s 11.4s<0.5s

     34/200      2.25G     0.6213     0.6835      1.037         12        640: 100% ━━━━━━━━━━━━ 25/25 2.2it/s 11.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.3s/it 1.3s

                   all          8          8      0.922        0.8      0.979      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     35/200      2.24G     0.5153      0.826      1.088          8        640: 0% ──────────── 0/25  0.4s

     35/200       2.2G     0.5293     0.6818      1.025         31        640: 4% ──────────── 1/25 1.5s/it 0.9s<35.3s

     35/200      2.25G     0.5316     0.7057     0.9901         31        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<19.5s

     35/200      2.26G     0.5884     0.7182      1.007         15        640: 12% ━─────────── 3/25 1.5it/s 1.7s<14.4s

     35/200      2.26G     0.6188     0.7028      1.004         22        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<11.8s

     35/200      2.26G     0.6259     0.6941     0.9902         33        640: 20% ━━────────── 5/25 2.0it/s 2.5s<10.1s

     35/200      2.26G     0.6002     0.6773     0.9826         23        640: 24% ━━╸───────── 6/25 2.1it/s 3.0s<9.2s

     35/200      2.21G     0.5816     0.6827          1          9        640: 28% ━━━───────── 7/25 2.1it/s 3.5s<8.6s

     35/200      2.26G     0.5798     0.6811      1.008         25        640: 32% ━━━╸──────── 8/25 2.2it/s 3.9s<7.8s

     35/200      2.26G     0.5883     0.6714      1.004         33        640: 36% ━━━━──────── 9/25 2.2it/s 4.3s<7.2s

     35/200      2.21G     0.5909     0.6711     0.9995         21        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.7s<6.5s

     35/200      2.21G     0.5858     0.6656     0.9903         44        640: 44% ━━━━━─────── 11/25 2.3it/s 5.1s<6.0s

     35/200       2.2G     0.5859     0.6688      1.001          8        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.6s<5.6s

     35/200      2.25G     0.5797     0.6623     0.9946         38        640: 52% ━━━━━━────── 13/25 2.1it/s 6.1s<5.6s

     35/200      2.25G     0.5915     0.6658     0.9974         23        640: 56% ━━━━━━╸───── 14/25 2.2it/s 6.6s<5.0s

     35/200      2.25G     0.5931     0.6632     0.9948         28        640: 60% ━━━━━━━───── 15/25 2.2it/s 7.0s<4.5s

     35/200      2.26G     0.6007     0.6719      1.004         14        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.4s<4.0s

     35/200      2.26G     0.5922     0.6909      1.006         10        640: 68% ━━━━━━━━──── 17/25 2.3it/s 7.9s<3.5s

     35/200      2.26G     0.5914     0.7106      1.015          8        640: 72% ━━━━━━━━╸─── 18/25 2.3it/s 8.3s<3.0s

     35/200      2.26G      0.592     0.7039      1.011         30        640: 76% ━━━━━━━━━─── 19/25 2.3it/s 8.7s<2.6s

     35/200      2.26G     0.5895     0.7002      1.006         24        640: 80% ━━━━━━━━━╸── 20/25 2.3it/s 9.1s<2.2s

     35/200      2.26G     0.5875     0.6924      1.003         41        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.6s<1.7s

     35/200      2.26G     0.5922     0.6992      1.015         19        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 10.0s<1.3s

     35/200      2.26G     0.5914     0.7005      1.019          8        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 10.4s<0.9s

     35/200      2.26G     0.5934     0.6995      1.021         12        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 11.0s<0.5s

     35/200      2.26G     0.5934     0.6995      1.021         12        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 11.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.5s/it 1.5s

                   all          8          8      0.889        0.6      0.784      0.607

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     36/200       2.2G     0.8206     0.8528      1.469         14        640: 0% ──────────── 0/25  0.4s

     36/200      2.22G     0.7281     0.7334      1.223         33        640: 4% ──────────── 1/25 1.5s/it 0.9s<35.2s

     36/200      2.26G     0.6516     0.7055      1.128         14        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<18.8s

     36/200      2.26G     0.6269     0.6919      1.104         18        640: 12% ━─────────── 3/25 1.5it/s 1.7s<14.7s

     36/200      2.24G     0.6144     0.6713      1.064         28        640: 16% ━╸────────── 4/25 1.7it/s 2.2s<12.0s

     36/200      2.24G     0.6418     0.6977      1.077         16        640: 20% ━━────────── 5/25 1.9it/s 2.6s<10.3s

     36/200      2.24G     0.6275     0.6824      1.059         22        640: 24% ━━╸───────── 6/25 2.1it/s 3.0s<9.1s

     36/200       2.2G     0.6189     0.6623      1.058         17        640: 28% ━━━───────── 7/25 2.1it/s 3.5s<8.5s

     36/200      2.25G     0.6283     0.6675       1.06         25        640: 32% ━━━╸──────── 8/25 2.2it/s 3.9s<7.8s

     36/200      2.26G     0.6227     0.6719      1.063         14        640: 36% ━━━━──────── 9/25 2.2it/s 4.3s<7.2s

     36/200      2.26G     0.6235     0.6898      1.072          9        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.7s<6.6s

     36/200      2.26G     0.6254     0.7592      1.085         19        640: 44% ━━━━━─────── 11/25 2.3it/s 5.2s<6.2s

     36/200      2.26G     0.6274     0.7784      1.085         27        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.6s<5.7s

     36/200      2.26G     0.6297     0.7748      1.078         47        640: 52% ━━━━━━────── 13/25 2.3it/s 6.0s<5.2s

     36/200      2.26G     0.6291     0.7748      1.065         30        640: 56% ━━━━━━╸───── 14/25 2.3it/s 6.5s<4.7s

     36/200      2.26G      0.623     0.7673      1.065         15        640: 60% ━━━━━━━───── 15/25 2.3it/s 6.9s<4.3s

     36/200      2.26G     0.6396     0.7655      1.065         20        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.3s<3.8s

     36/200      2.26G     0.6372     0.7562      1.063         16        640: 68% ━━━━━━━━──── 17/25 2.4it/s 7.7s<3.4s

     36/200      2.26G     0.6365     0.7455       1.06         36        640: 72% ━━━━━━━━╸─── 18/25 2.3it/s 8.2s<3.0s

     36/200      2.26G     0.6315     0.7377      1.055         27        640: 76% ━━━━━━━━━─── 19/25 2.3it/s 8.6s<2.6s

     36/200      2.26G     0.6294     0.7464      1.058         14        640: 80% ━━━━━━━━━╸── 20/25 2.3it/s 9.1s<2.2s

     36/200      2.26G     0.6311      0.743      1.059         25        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.5s<1.7s

     36/200      2.26G     0.6347     0.7439      1.056         28        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 9.9s<1.3s

     36/200      2.26G     0.6362     0.7467      1.073         10        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 10.4s<0.9s

     36/200      2.27G     0.6311     0.7398      1.065         34        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 10.9s<0.5s

     36/200      2.27G     0.6311     0.7398      1.065         34        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 10.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.6s/it 1.6s

                   all          8          8       0.86      0.559      0.666      0.455

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     37/200      2.21G     0.5498     0.6289          1         21        640: 0% ──────────── 0/25  0.5s

     37/200      2.25G     0.5513      0.662      1.019         30        640: 4% ──────────── 1/25 1.4s/it 0.9s<34.5s

     37/200      2.25G     0.5613     0.7047      1.075          8        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<19.0s

     37/200      2.26G     0.5766     0.7459       1.06         16        640: 12% ━─────────── 3/25 1.5it/s 1.7s<14.2s

     37/200      2.26G     0.5988     0.7818      1.093          8        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<11.5s

     37/200      2.26G     0.5896     0.7593      1.086         15        640: 20% ━━────────── 5/25 2.0it/s 2.6s<10.2s

     37/200      2.26G     0.5831     0.7612      1.064         47        640: 24% ━━╸───────── 6/25 2.1it/s 3.0s<9.1s

     37/200      2.26G     0.6003     0.7509      1.055         34        640: 28% ━━━───────── 7/25 2.2it/s 3.4s<8.4s

     37/200      2.26G     0.6023      0.743      1.055         24        640: 32% ━━━╸──────── 8/25 2.2it/s 3.9s<7.8s

     37/200      2.26G     0.6072      0.792      1.052         24        640: 36% ━━━━──────── 9/25 2.2it/s 4.3s<7.2s

     37/200      2.26G     0.6139      0.793      1.054         25        640: 40% ━━━━╸─────── 10/25 2.2it/s 4.8s<6.8s

     37/200      2.26G     0.6205     0.7846      1.064         16        640: 44% ━━━━━─────── 11/25 2.3it/s 5.2s<6.2s

     37/200      2.26G     0.6126     0.7909      1.084          8        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.6s<5.7s

     37/200      2.26G     0.6064     0.7838      1.076         42        640: 52% ━━━━━━────── 13/25 2.2it/s 6.1s<5.3s

     37/200      2.26G     0.6175     0.8015      1.074         24        640: 56% ━━━━━━╸───── 14/25 2.3it/s 6.5s<4.8s

     37/200      2.26G     0.6179     0.7994      1.075         27        640: 60% ━━━━━━━───── 15/25 2.3it/s 7.0s<4.4s

     37/200      2.26G     0.6267     0.8289      1.088          8        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.4s<3.9s

     37/200      2.26G     0.6272     0.8373      1.094         20        640: 68% ━━━━━━━━──── 17/25 2.3it/s 7.8s<3.5s

     37/200      2.26G       0.63     0.8291       1.09         27        640: 72% ━━━━━━━━╸─── 18/25 2.3it/s 8.2s<3.0s

     37/200      2.26G     0.6335     0.8304      1.102          8        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.6s<2.5s

     37/200      2.26G     0.6327     0.8183      1.094         41        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 9.0s<2.1s

     37/200      2.26G     0.6422     0.8131      1.092         22        640: 84% ━━━━━━━━━━── 21/25 2.4it/s 9.4s<1.7s

     37/200      2.26G     0.6433     0.8105      1.089         27        640: 88% ━━━━━━━━━━╸─ 22/25 2.4it/s 9.9s<1.3s

     37/200      2.26G     0.6523      0.811      1.092         22        640: 92% ━━━━━━━━━━━─ 23/25 2.4it/s 10.3s<0.8s

     37/200      2.26G     0.6477     0.8023      1.088         14        640: 96% ━━━━━━━━━━━╸ 24/25 2.6it/s 10.6s<0.4s

     37/200      2.26G     0.6477     0.8023      1.088         14        640: 100% ━━━━━━━━━━━━ 25/25 2.4it/s 10.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.8s/it 1.8s

                   all          8          8      0.664        0.8      0.764      0.469

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     38/200      2.26G     0.6506      0.581     0.9643         16        640: 0% ──────────── 0/25  0.4s

     38/200      2.26G     0.6727      0.568     0.9846         30        640: 4% ──────────── 1/25 1.4s/it 0.9s<34.2s

     38/200      2.26G     0.6049     0.5647     0.9643         16        640: 8% ╸─────────── 2/25 1.3it/s 1.3s<18.3s

     38/200      2.26G     0.6474     0.6939       1.02         15        640: 12% ━─────────── 3/25 1.6it/s 1.7s<13.8s

     38/200      2.26G     0.6416     0.6863      1.019         27        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<11.6s

     38/200      2.21G     0.6265     0.6873      1.002         44        640: 20% ━━────────── 5/25 1.8it/s 2.7s<11.4s

     38/200      2.26G     0.6443     0.6791      1.019         23        640: 24% ━━╸───────── 6/25 1.9it/s 3.2s<10.3s

     38/200      2.26G     0.6382     0.6916      1.019         26        640: 28% ━━━───────── 7/25 2.0it/s 3.7s<9.2s

     38/200      2.24G     0.6365     0.6886      1.018         16        640: 32% ━━━╸──────── 8/25 2.1it/s 4.1s<8.1s

     38/200      2.24G     0.6237     0.6765      1.006         28        640: 36% ━━━━──────── 9/25 2.2it/s 4.5s<7.3s

     38/200      2.24G     0.6293       0.68       1.01         33        640: 40% ━━━━╸─────── 10/25 2.4it/s 4.8s<6.3s

     38/200      2.24G     0.6268       0.69      1.018          8        640: 44% ━━━━━─────── 11/25 2.4it/s 5.2s<5.8s

     38/200      2.24G     0.6197     0.6979      1.021          8        640: 48% ━━━━━╸────── 12/25 2.4it/s 5.6s<5.3s

     38/200      2.24G     0.6261     0.6978      1.015         29        640: 52% ━━━━━━────── 13/25 2.4it/s 6.1s<5.0s

     38/200      2.24G     0.6242     0.6911      1.008         30        640: 56% ━━━━━━╸───── 14/25 2.4it/s 6.5s<4.6s

     38/200      2.24G     0.6257     0.6879      1.008         28        640: 60% ━━━━━━━───── 15/25 2.4it/s 6.9s<4.2s

     38/200      2.21G     0.6196      0.688      1.005         34        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.4s<3.9s

     38/200      2.25G     0.6203     0.6949      1.002         25        640: 68% ━━━━━━━━──── 17/25 2.3it/s 7.8s<3.4s

     38/200      2.25G     0.6177     0.7058      1.015         10        640: 72% ━━━━━━━━╸─── 18/25 2.3it/s 8.3s<3.0s

     38/200      2.21G     0.6134      0.702      1.017         14        640: 76% ━━━━━━━━━─── 19/25 2.3it/s 8.7s<2.6s

     38/200      2.26G     0.6279     0.7018      1.026         22        640: 80% ━━━━━━━━━╸── 20/25 2.3it/s 9.1s<2.1s

     38/200      2.21G     0.6303     0.7118      1.037         15        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.6s<1.7s

     38/200      2.25G     0.6277     0.7114      1.032         31        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 10.0s<1.3s

     38/200      2.25G       0.63     0.7057      1.026         24        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 10.4s<0.9s

     38/200      2.25G     0.6295     0.7063      1.034          6        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 10.7s<0.4s

     38/200      2.25G     0.6295     0.7063      1.034          6        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 10.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.7s/it 1.7s

                   all          8          8      0.789        0.6      0.729      0.518

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     39/200      2.25G     0.6343     0.6615      0.983         28        640: 0% ──────────── 0/25  0.4s

     39/200      2.21G     0.6383     0.7883      1.016         25        640: 4% ──────────── 1/25 2.0s/it 1.0s<48.6s

     39/200      2.25G     0.5665     0.8018     0.9965         20        640: 8% ╸─────────── 2/25 1.2s/it 1.7s<27.3s

     39/200      2.25G     0.5858     0.7415     0.9942         28        640: 12% ━─────────── 3/25 1.3it/s 2.1s<16.7s

     39/200      2.25G     0.6284     0.7239      1.022         25        640: 16% ━╸────────── 4/25 1.6it/s 2.5s<12.9s

     39/200      2.26G      0.641     0.7166      1.037         15        640: 20% ━━────────── 5/25 1.8it/s 2.9s<11.1s

     39/200      2.26G     0.6203     0.6999      1.021         16        640: 24% ━━╸───────── 6/25 2.0it/s 3.4s<9.6s

     39/200      2.26G     0.6234     0.6896      1.035         17        640: 28% ━━━───────── 7/25 2.0it/s 3.8s<8.9s

     39/200      2.26G     0.6146     0.6941      1.059          9        640: 32% ━━━╸──────── 8/25 2.1it/s 4.3s<8.2s

     39/200      2.26G     0.6075      0.693      1.051         19        640: 36% ━━━━──────── 9/25 2.2it/s 4.7s<7.4s

     39/200      2.26G     0.6097     0.6958      1.046         28        640: 40% ━━━━╸─────── 10/25 2.0it/s 5.4s<7.6s

     39/200      2.26G     0.5999     0.6916      1.032         30        640: 44% ━━━━━─────── 11/25 2.1it/s 5.8s<6.6s

     39/200      2.26G     0.5906     0.6811      1.033         16        640: 48% ━━━━━╸────── 12/25 2.2it/s 6.2s<6.0s

     39/200      2.21G     0.5909     0.6757      1.038         22        640: 52% ━━━━━━────── 13/25 2.2it/s 6.7s<5.5s

     39/200      2.26G     0.5992     0.6863      1.043         14        640: 56% ━━━━━━╸───── 14/25 2.2it/s 7.1s<4.9s

     39/200      2.26G     0.5976     0.6759      1.035         30        640: 60% ━━━━━━━───── 15/25 2.3it/s 7.5s<4.4s

     39/200      2.26G     0.5959     0.6713      1.033         24        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.9s<3.9s

     39/200      2.26G     0.5889     0.6636      1.028         22        640: 68% ━━━━━━━━──── 17/25 2.4it/s 8.3s<3.3s

     39/200      2.26G     0.5875     0.6581      1.023         28        640: 72% ━━━━━━━━╸─── 18/25 2.4it/s 8.7s<2.9s

     39/200      2.26G     0.5836     0.6532      1.016         41        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 9.2s<2.5s

     39/200      2.26G     0.5788     0.6471      1.013         35        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 9.6s<2.1s

     39/200      2.26G     0.5769     0.6443      1.014         18        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 10.1s<1.7s

     39/200      2.26G     0.5749     0.6406      1.014         22        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 10.7s<1.4s

     39/200      2.26G     0.5849     0.6532      1.027          8        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 11.0s<0.9s

     39/200      2.22G     0.5883     0.6526      1.025         18        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 11.4s<0.4s

     39/200      2.22G     0.5883     0.6526      1.025         18        640: 100% ━━━━━━━━━━━━ 25/25 2.2it/s 11.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.7s/it 1.7s

                   all          8          8      0.674        0.8      0.836      0.588

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     40/200      2.24G     0.4965     0.8584      1.133          9        640: 0% ──────────── 0/25  0.4s

     40/200      2.24G     0.5234      0.719      1.117         15        640: 4% ──────────── 1/25 1.5s/it 0.9s<35.7s

     40/200      2.21G     0.5089     0.6685      1.074         15        640: 8% ╸─────────── 2/25 1.1it/s 1.3s<20.1s

     40/200      2.26G     0.4994     0.6409      1.045         14        640: 12% ━─────────── 3/25 1.5it/s 1.8s<14.6s

     40/200      2.21G     0.5213     0.6488      1.029         33        640: 16% ━╸────────── 4/25 1.8it/s 2.2s<12.0s

     40/200      2.26G     0.5203     0.6483      1.012         14        640: 20% ━━────────── 5/25 2.0it/s 2.6s<10.2s

     40/200      2.26G     0.5433     0.7034      1.034         21        640: 24% ━━╸───────── 6/25 2.1it/s 3.0s<9.2s

     40/200      2.26G     0.5435     0.6887      1.019         16        640: 28% ━━━───────── 7/25 2.2it/s 3.4s<8.3s

     40/200      2.26G      0.534     0.6841      1.019         20        640: 32% ━━━╸──────── 8/25 2.2it/s 3.9s<7.6s

     40/200      2.22G     0.5595     0.6842      1.033         15        640: 36% ━━━━──────── 9/25 2.2it/s 4.3s<7.2s

     40/200      2.26G     0.5634     0.7067      1.042         14        640: 40% ━━━━╸─────── 10/25 2.4it/s 4.7s<6.2s

     40/200      2.26G     0.5618     0.6991      1.039         26        640: 44% ━━━━━─────── 11/25 2.4it/s 5.1s<5.9s

     40/200      2.26G     0.5666     0.7021      1.039         42        640: 48% ━━━━━╸────── 12/25 2.4it/s 5.5s<5.5s

     40/200      2.26G     0.5682     0.6891      1.034         27        640: 52% ━━━━━━────── 13/25 2.4it/s 5.9s<5.1s

     40/200      2.26G     0.5644      0.702       1.03         28        640: 56% ━━━━━━╸───── 14/25 2.3it/s 6.4s<4.8s

     40/200      2.26G     0.5664     0.6994      1.049          8        640: 60% ━━━━━━━───── 15/25 2.3it/s 6.8s<4.3s

     40/200      2.26G     0.5742     0.6946      1.044         30        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.3s<3.9s

     40/200      2.26G     0.5773      0.686      1.043         22        640: 68% ━━━━━━━━──── 17/25 2.4it/s 7.7s<3.4s

     40/200      2.26G     0.5729     0.6757      1.033         41        640: 72% ━━━━━━━━╸─── 18/25 2.4it/s 8.1s<2.9s

     40/200      2.26G     0.5753     0.6769      1.035         25        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.5s<2.5s

     40/200      2.26G     0.5818     0.6749      1.033         20        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 8.9s<2.1s

     40/200      2.26G     0.5766     0.6751       1.04          8        640: 84% ━━━━━━━━━━── 21/25 2.4it/s 9.4s<1.7s

     40/200      2.21G     0.5872     0.6737       1.04         43        640: 88% ━━━━━━━━━━╸─ 22/25 2.4it/s 9.8s<1.3s

     40/200      2.22G     0.5926     0.6756      1.042         22        640: 92% ━━━━━━━━━━━─ 23/25 2.4it/s 10.2s<0.8s

     40/200      2.24G     0.5926     0.6698      1.037         30        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 10.5s<0.4s

     40/200      2.24G     0.5926     0.6698      1.037         30        640: 100% ━━━━━━━━━━━━ 25/25 2.4it/s 10.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.8s/it 1.8s

                   all          8          8      0.613        0.8      0.786      0.619

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     41/200      2.26G     0.4911     0.6462     0.9386         27        640: 0% ──────────── 0/25  0.4s

     41/200      2.26G      0.516     0.5877     0.9659         16        640: 4% ──────────── 1/25 1.2s/it 0.8s<27.6s

     41/200      2.26G     0.5421     0.5968     0.9653         21        640: 8% ╸─────────── 2/25 1.3it/s 1.2s<17.8s

     41/200      2.23G     0.5305      0.594     0.9816         20        640: 12% ━─────────── 3/25 1.7it/s 1.6s<13.2s

     41/200      2.27G      0.511     0.6134      1.013          8        640: 16% ━╸────────── 4/25 1.9it/s 2.1s<11.3s

     41/200      2.21G      0.547     0.6167      1.037         28        640: 20% ━━────────── 5/25 1.9it/s 2.5s<10.4s

     41/200      2.26G     0.5411      0.617       1.03         25        640: 24% ━━╸───────── 6/25 2.0it/s 3.0s<9.4s

     41/200      2.26G     0.5753     0.6522       1.08          8        640: 28% ━━━───────── 7/25 2.2it/s 3.4s<8.3s

     41/200      2.26G     0.5707     0.6429      1.059         33        640: 32% ━━━╸──────── 8/25 2.2it/s 3.8s<7.9s

     41/200      2.26G     0.5623     0.6303      1.045         34        640: 36% ━━━━──────── 9/25 2.0it/s 4.4s<7.9s

     41/200      2.26G     0.5506     0.6364      1.049          8        640: 40% ━━━━╸─────── 10/25 2.1it/s 4.8s<7.0s

     41/200      2.26G      0.545     0.6295      1.041         15        640: 44% ━━━━━─────── 11/25 2.2it/s 5.3s<6.3s

     41/200      2.26G     0.5425     0.6298      1.037         20        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.7s<5.7s

     41/200      2.26G     0.5518     0.6367      1.042         33        640: 52% ━━━━━━────── 13/25 2.2it/s 6.1s<5.3s

     41/200      2.26G     0.5498     0.6324      1.035         23        640: 56% ━━━━━━╸───── 14/25 2.3it/s 6.6s<4.9s

     41/200      2.26G     0.5527      0.637      1.043         15        640: 60% ━━━━━━━───── 15/25 2.2it/s 7.0s<4.5s

     41/200      2.26G     0.5571     0.6329       1.04         30        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.5s<4.0s

     41/200      2.26G     0.5613     0.6376       1.06          8        640: 68% ━━━━━━━━──── 17/25 2.3it/s 7.9s<3.5s

     41/200      2.26G     0.5644     0.6324      1.052         34        640: 72% ━━━━━━━━╸─── 18/25 2.3it/s 8.3s<3.0s

     41/200      2.26G     0.5592     0.6349      1.045         38        640: 76% ━━━━━━━━━─── 19/25 2.3it/s 8.7s<2.6s

     41/200      2.26G      0.553     0.6358      1.041         25        640: 80% ━━━━━━━━━╸── 20/25 2.3it/s 9.1s<2.1s

     41/200      2.26G     0.5526     0.6382      1.048          9        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.6s<1.7s

     41/200      2.26G     0.5564     0.6332      1.044         22        640: 88% ━━━━━━━━━━╸─ 22/25 2.4it/s 10.0s<1.3s

     41/200      2.26G     0.5592     0.6296      1.039         30        640: 92% ━━━━━━━━━━━─ 23/25 2.4it/s 10.4s<0.8s

     41/200      2.26G     0.5574     0.6346      1.033         28        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 10.7s<0.4s

     41/200      2.26G     0.5574     0.6346      1.033         28        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 10.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.9s/it 1.9s

                   all          8          8      0.561      0.815      0.829      0.624

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     42/200      2.26G     0.6409     0.6027      1.025         16        640: 0% ──────────── 0/25  0.4s

     42/200      2.26G     0.7028     0.5974      1.042         23        640: 4% ──────────── 1/25 1.5s/it 0.9s<36.7s

     42/200      2.26G     0.6672     0.6567      1.096          8        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<19.3s

     42/200      2.26G     0.6416     0.6378      1.062         20        640: 12% ━─────────── 3/25 1.6it/s 1.7s<14.0s

     42/200      2.26G     0.6299      0.629      1.049         21        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<11.6s

     42/200      2.26G     0.6304     0.6207      1.037         20        640: 20% ━━────────── 5/25 2.0it/s 2.5s<9.9s

     42/200      2.26G     0.6275     0.6428      1.045         20        640: 24% ━━╸───────── 6/25 2.1it/s 3.0s<9.2s

     42/200      2.26G     0.6223     0.6368      1.044         33        640: 28% ━━━───────── 7/25 2.2it/s 3.4s<8.3s

     42/200      2.26G     0.6175     0.6283       1.04         22        640: 32% ━━━╸──────── 8/25 2.2it/s 3.8s<7.6s

     42/200      2.26G     0.6111     0.6344      1.045          8        640: 36% ━━━━──────── 9/25 2.3it/s 4.2s<7.0s

     42/200      2.26G     0.6127     0.6247      1.039         25        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.7s<6.5s

     42/200      2.26G     0.6176     0.6249      1.035         30        640: 44% ━━━━━─────── 11/25 2.3it/s 5.1s<6.1s

     42/200      2.26G     0.6052     0.6292       1.03         20        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.5s<5.7s

     42/200      2.26G     0.6137     0.6279      1.026         54        640: 52% ━━━━━━────── 13/25 2.1it/s 6.1s<5.7s

     42/200      2.26G     0.6042     0.6261      1.024         14        640: 56% ━━━━━━╸───── 14/25 2.2it/s 6.5s<4.9s

     42/200      2.26G     0.5955      0.624      1.021         31        640: 60% ━━━━━━━───── 15/25 2.3it/s 6.9s<4.4s

     42/200      2.26G     0.5876     0.6177      1.015         35        640: 64% ━━━━━━━╸──── 16/25 2.1it/s 7.5s<4.3s

     42/200      2.26G     0.5892     0.6156      1.016         16        640: 68% ━━━━━━━━──── 17/25 2.2it/s 7.9s<3.6s

     42/200      2.26G     0.5947     0.6143      1.021         17        640: 72% ━━━━━━━━╸─── 18/25 2.3it/s 8.4s<3.1s

     42/200      2.26G     0.5987     0.6124      1.022         20        640: 76% ━━━━━━━━━─── 19/25 2.3it/s 8.8s<2.6s

     42/200      2.26G      0.593     0.6137       1.03         10        640: 80% ━━━━━━━━━╸── 20/25 2.2it/s 9.2s<2.2s

     42/200      2.26G     0.5958     0.6102      1.027         28        640: 84% ━━━━━━━━━━── 21/25 2.1it/s 9.8s<1.9s

     42/200      2.23G     0.5906      0.613      1.025         20        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 10.3s<1.4s

     42/200      2.21G     0.5904     0.6121      1.025         16        640: 92% ━━━━━━━━━━━─ 23/25 2.1it/s 10.8s<0.9s

     42/200      2.24G     0.5913     0.6144       1.02         31        640: 96% ━━━━━━━━━━━╸ 24/25 2.3it/s 11.1s<0.4s

     42/200      2.24G     0.5913     0.6144       1.02         31        640: 100% ━━━━━━━━━━━━ 25/25 2.2it/s 11.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.6s/it 1.6s

                   all          8          8      0.832        0.7      0.763       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     43/200      2.29G     0.6946     0.8023      1.147         19        640: 0% ──────────── 0/25  0.4s

     43/200      2.29G     0.6664     0.7298      1.056         34        640: 4% ──────────── 1/25 1.2s/it 0.7s<29.1s

     43/200      2.29G      0.627      0.696      1.042         31        640: 8% ╸─────────── 2/25 1.4it/s 1.1s<16.6s

     43/200      2.29G     0.6129     0.6434      1.009         30        640: 12% ━─────────── 3/25 1.7it/s 1.5s<12.9s

     43/200      2.29G     0.5936     0.6335      1.007         27        640: 16% ━╸────────── 4/25 2.0it/s 1.9s<10.4s

     43/200       2.3G     0.5858     0.6517      1.012         15        640: 20% ━━────────── 5/25 2.1it/s 2.3s<9.5s

     43/200       2.3G     0.5838     0.6523      1.027         10        640: 24% ━━╸───────── 6/25 2.2it/s 2.7s<8.8s

     43/200      2.26G      0.592     0.6579      1.022         31        640: 28% ━━━───────── 7/25 2.4it/s 3.1s<7.6s

     43/200      2.26G     0.5855     0.6371       1.02         23        640: 32% ━━━╸──────── 8/25 2.3it/s 3.6s<7.3s

     43/200      2.26G     0.5738     0.6432      1.046          9        640: 36% ━━━━──────── 9/25 2.3it/s 4.0s<6.9s

     43/200      2.26G     0.5886     0.6346      1.038         47        640: 40% ━━━━╸─────── 10/25 2.4it/s 4.4s<6.4s

     43/200      2.26G     0.5839     0.6291      1.029         20        640: 44% ━━━━━─────── 11/25 2.4it/s 4.8s<5.9s

     43/200      2.21G     0.5812     0.6207      1.026         24        640: 48% ━━━━━╸────── 12/25 2.4it/s 5.2s<5.5s

     43/200      2.25G     0.5895     0.6443      1.038          8        640: 52% ━━━━━━────── 13/25 2.4it/s 5.6s<5.0s

     43/200      2.25G     0.5862     0.6396      1.028         35        640: 56% ━━━━━━╸───── 14/25 2.3it/s 6.2s<4.9s

     43/200      2.25G     0.5803     0.6482      1.023         30        640: 60% ━━━━━━━───── 15/25 2.3it/s 6.6s<4.4s

     43/200      2.25G     0.5754     0.6402      1.023         16        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.0s<3.9s

     43/200      2.25G     0.5718     0.6357       1.02         16        640: 68% ━━━━━━━━──── 17/25 2.3it/s 7.4s<3.4s

     43/200      2.26G     0.5669     0.6439      1.015         19        640: 72% ━━━━━━━━╸─── 18/25 2.3it/s 7.8s<3.0s

     43/200      2.26G     0.5729     0.6372      1.012         30        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.3s<2.5s

     43/200      2.26G     0.5706     0.6369      1.023          8        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 8.7s<2.1s

     43/200      2.26G     0.5762     0.6308       1.02         28        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.2s<1.8s

     43/200      2.26G     0.5786     0.6329      1.029         10        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 9.6s<1.3s

     43/200      2.26G     0.5852     0.6298       1.03         24        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 10.1s<0.9s

     43/200      2.26G     0.5838     0.6282      1.033         14        640: 96% ━━━━━━━━━━━╸ 24/25 2.4it/s 10.4s<0.4s

     43/200      2.26G     0.5838     0.6282      1.033         14        640: 100% ━━━━━━━━━━━━ 25/25 2.4it/s 10.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.7s/it 1.7s

                   all          8          8      0.874        0.7      0.945       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     44/200      2.25G     0.7168     0.7582      1.165          8        640: 0% ──────────── 0/25  0.4s

     44/200      2.23G     0.6567     0.6761       1.07         31        640: 4% ──────────── 1/25 1.4s/it 0.8s<34.2s

     44/200      2.26G      0.639     0.6263       1.02         37        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<19.6s

     44/200      2.26G     0.6366     0.6141      0.991         54        640: 12% ━─────────── 3/25 1.5it/s 1.7s<14.3s

     44/200      2.26G     0.6376     0.6063      1.002         20        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<11.7s

     44/200      2.26G     0.6191     0.6482      1.019         19        640: 20% ━━────────── 5/25 2.0it/s 2.6s<10.3s

     44/200      2.26G     0.6209     0.6386      1.006         24        640: 24% ━━╸───────── 6/25 2.1it/s 3.0s<9.2s

     44/200      2.26G     0.6391     0.6315      1.009         22        640: 28% ━━━───────── 7/25 2.1it/s 3.4s<8.4s

     44/200      2.26G     0.6369     0.6348      1.009         25        640: 32% ━━━╸──────── 8/25 2.2it/s 3.8s<7.6s

     44/200      2.26G     0.6505     0.6313      1.024         20        640: 36% ━━━━──────── 9/25 2.3it/s 4.2s<7.0s

     44/200      2.26G     0.6396     0.6273      1.021         15        640: 40% ━━━━╸─────── 10/25 2.4it/s 4.6s<6.2s

     44/200      2.21G     0.6351      0.635      1.033          8        640: 44% ━━━━━─────── 11/25 2.4it/s 5.0s<5.7s

     44/200      2.26G      0.659     0.6399      1.041         25        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.5s<5.6s

     44/200      2.26G     0.6478       0.63       1.03         40        640: 52% ━━━━━━────── 13/25 2.1it/s 6.1s<5.7s

     44/200      2.26G      0.642     0.6198      1.022         24        640: 56% ━━━━━━╸───── 14/25 2.2it/s 6.6s<5.1s

     44/200      2.26G     0.6389     0.6186      1.024         21        640: 60% ━━━━━━━───── 15/25 2.2it/s 7.0s<4.5s

     44/200      2.26G     0.6389     0.6171      1.025         25        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.4s<4.0s

     44/200      2.26G     0.6305     0.6095       1.02         22        640: 68% ━━━━━━━━──── 17/25 2.3it/s 7.8s<3.5s

     44/200      2.26G     0.6296     0.6136      1.029         21        640: 72% ━━━━━━━━╸─── 18/25 2.2it/s 8.3s<3.2s

     44/200      2.26G     0.6233     0.6151      1.029         26        640: 76% ━━━━━━━━━─── 19/25 2.2it/s 8.8s<2.7s

     44/200      2.26G     0.6156       0.61      1.023         17        640: 80% ━━━━━━━━━╸── 20/25 2.2it/s 9.2s<2.2s

     44/200      2.26G     0.6131     0.6119      1.026         17        640: 84% ━━━━━━━━━━── 21/25 2.2it/s 9.6s<1.8s

     44/200      2.26G     0.6044     0.6074      1.022         14        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 10.1s<1.3s

     44/200      2.26G     0.6069      0.626      1.032          9        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 10.5s<0.9s

     44/200      2.27G     0.6105     0.6232      1.029         14        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 10.8s<0.4s

     44/200      2.27G     0.6105     0.6232      1.029         14        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 10.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.5s/it 1.5s

                   all          8          8      0.778        0.7      0.812      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     45/200      2.23G     0.6111     0.5107     0.8486         31        640: 0% ──────────── 0/25  0.4s

     45/200      2.26G     0.6099     0.6596      1.069          9        640: 4% ──────────── 1/25 1.4s/it 0.9s<34.5s

     45/200      2.26G     0.6433     0.6235      1.028         44        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<19.2s

     45/200      2.26G     0.6082     0.6095     0.9835         47        640: 12% ━─────────── 3/25 1.4it/s 1.9s<16.1s

     45/200      2.26G     0.5946     0.5842     0.9784         23        640: 16% ━╸────────── 4/25 1.7it/s 2.3s<12.7s

     45/200      2.26G     0.6091     0.5711     0.9883         16        640: 20% ━━────────── 5/25 1.9it/s 2.7s<10.6s

     45/200      2.23G     0.5912     0.5925      1.001         19        640: 24% ━━╸───────── 6/25 2.1it/s 3.1s<9.0s

     45/200      2.23G     0.5938     0.5968      1.001         26        640: 28% ━━━───────── 7/25 2.1it/s 3.5s<8.5s

     45/200      2.28G     0.5884      0.594     0.9945         25        640: 32% ━━━╸──────── 8/25 2.2it/s 4.0s<7.8s

     45/200      2.28G     0.5839     0.5819     0.9901         28        640: 36% ━━━━──────── 9/25 2.2it/s 4.4s<7.1s

     45/200      2.28G     0.5832     0.5863      1.002         16        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.8s<6.6s

     45/200      2.28G     0.5878     0.5886      1.008         27        640: 44% ━━━━━─────── 11/25 2.2it/s 5.3s<6.2s

     45/200      2.28G     0.5831     0.5868      1.004         20        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.7s<5.6s

     45/200      2.28G     0.5757     0.5895      1.009         20        640: 52% ━━━━━━────── 13/25 2.3it/s 6.1s<5.3s

     45/200      2.28G     0.5754     0.5864      1.009         15        640: 56% ━━━━━━╸───── 14/25 2.2it/s 6.6s<4.9s

     45/200      2.28G     0.5765     0.5829      1.005         23        640: 60% ━━━━━━━───── 15/25 2.2it/s 7.1s<4.5s

     45/200      2.28G     0.5836     0.5904      1.018          8        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.5s<3.9s

     45/200      2.28G      0.581     0.5853      1.018         14        640: 68% ━━━━━━━━──── 17/25 2.3it/s 7.9s<3.4s

     45/200      2.28G     0.5851     0.5858      1.019         15        640: 72% ━━━━━━━━╸─── 18/25 2.4it/s 8.3s<3.0s

     45/200      2.28G     0.5803     0.5879      1.021          9        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.7s<2.5s

     45/200      2.28G      0.573     0.5867      1.016         27        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 9.1s<2.1s

     45/200      2.28G     0.5719     0.5903       1.02         30        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.6s<1.7s

     45/200      2.28G     0.5772     0.5861      1.023         24        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 10.0s<1.3s

     45/200      2.28G     0.5753      0.581      1.019         28        640: 92% ━━━━━━━━━━━─ 23/25 2.4it/s 10.4s<0.8s

     45/200      2.28G     0.5743     0.5774      1.014         14        640: 96% ━━━━━━━━━━━╸ 24/25 2.6it/s 10.7s<0.4s

     45/200      2.28G     0.5743     0.5774      1.014         14        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 10.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.3s/it 1.3s

                   all          8          8      0.828      0.594      0.763      0.531

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     46/200      2.26G      0.552     0.5639     0.9221         46        640: 0% ──────────── 0/25  0.4s

     46/200      2.23G     0.5676     0.5595     0.9918         16        640: 4% ──────────── 1/25 1.4s/it 0.8s<34.0s

     46/200      2.22G     0.5452     0.5712     0.9822         20        640: 8% ╸─────────── 2/25 1.2it/s 1.2s<19.6s

     46/200      2.27G     0.5345     0.5485     0.9805         16        640: 12% ━─────────── 3/25 1.5it/s 1.7s<14.3s

     46/200      2.27G     0.5564     0.5738      1.044          8        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<11.6s

     46/200      2.27G     0.5637     0.5692      1.049         15        640: 20% ━━────────── 5/25 2.0it/s 2.5s<10.2s

     46/200      2.27G     0.5816     0.5698      1.041         36        640: 24% ━━╸───────── 6/25 2.1it/s 2.9s<9.1s

     46/200      2.27G     0.5803     0.5747      1.047          8        640: 28% ━━━───────── 7/25 2.2it/s 3.3s<8.1s

     46/200      2.27G     0.5836     0.5698      1.035         41        640: 32% ━━━╸──────── 8/25 2.3it/s 3.7s<7.4s

     46/200      2.27G      0.574     0.5624      1.022         16        640: 36% ━━━━──────── 9/25 2.3it/s 4.1s<6.9s

     46/200      2.27G     0.5694     0.5735      1.027         15        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.6s<6.6s

     46/200      2.27G     0.5748      0.576      1.028         14        640: 44% ━━━━━─────── 11/25 2.3it/s 5.0s<6.1s

     46/200      2.27G     0.5696     0.5694      1.019         33        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.4s<5.6s

     46/200      2.27G     0.5666     0.5646      1.023         18        640: 52% ━━━━━━────── 13/25 2.2it/s 5.9s<5.4s

     46/200      2.27G     0.5636     0.5611       1.02         15        640: 56% ━━━━━━╸───── 14/25 2.3it/s 6.4s<4.8s

     46/200      2.27G     0.5653     0.5695      1.027         17        640: 60% ━━━━━━━───── 15/25 2.2it/s 6.8s<4.5s

     46/200      2.27G     0.5711     0.5676      1.021         33        640: 64% ━━━━━━━╸──── 16/25 2.1it/s 7.4s<4.3s

     46/200      2.27G      0.581     0.5778      1.037         19        640: 68% ━━━━━━━━──── 17/25 2.2it/s 7.8s<3.7s

     46/200      2.27G     0.5837     0.5808      1.035         31        640: 72% ━━━━━━━━╸─── 18/25 2.2it/s 8.2s<3.1s

     46/200      2.27G     0.5856     0.5782      1.037         16        640: 76% ━━━━━━━━━─── 19/25 2.3it/s 8.6s<2.6s

     46/200      2.27G     0.5819     0.5754      1.034         16        640: 80% ━━━━━━━━━╸── 20/25 2.3it/s 9.1s<2.2s

     46/200      2.27G     0.5779     0.5703       1.03         24        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.5s<1.7s

     46/200      2.27G     0.5823      0.566      1.028         24        640: 88% ━━━━━━━━━━╸─ 22/25 2.4it/s 9.9s<1.3s

     46/200      2.27G     0.5843     0.5627      1.022         38        640: 92% ━━━━━━━━━━━─ 23/25 2.4it/s 10.3s<0.8s

     46/200      2.27G     0.5794     0.5602      1.016         23        640: 96% ━━━━━━━━━━━╸ 24/25 2.3it/s 10.8s<0.4s

     46/200      2.27G     0.5794     0.5602      1.016         23        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 10.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.4s/it 1.4s

                   all          8          8      0.685        0.8       0.72      0.502

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     47/200      2.26G      0.442     0.5556          1         19        640: 0% ──────────── 0/25  0.4s

     47/200      2.26G     0.5334     0.5104      1.016         25        640: 4% ──────────── 1/25 1.6s/it 0.9s<37.4s

     47/200      2.26G     0.5118     0.5118      1.019         22        640: 8% ╸─────────── 2/25 1.0it/s 1.4s<22.9s

     47/200      2.23G     0.5241      0.532      1.062         26        640: 12% ━─────────── 3/25 1.4it/s 1.9s<15.9s

     47/200      2.28G      0.508     0.5457      1.058          8        640: 16% ━╸────────── 4/25 1.8it/s 2.2s<11.4s

     47/200      2.28G     0.5063     0.5485      1.064         20        640: 20% ━━────────── 5/25 2.0it/s 2.7s<10.1s

     47/200      2.28G     0.5024     0.5568       1.07         19        640: 24% ━━╸───────── 6/25 2.1it/s 3.1s<9.2s

     47/200      2.28G     0.5101      0.545      1.067         17        640: 28% ━━━───────── 7/25 2.1it/s 3.5s<8.5s

     47/200      2.28G     0.5121     0.5414      1.045         41        640: 32% ━━━╸──────── 8/25 2.0it/s 4.1s<8.4s

     47/200      2.28G     0.5146     0.5332      1.031         23        640: 36% ━━━━──────── 9/25 2.1it/s 4.5s<7.5s

     47/200      2.28G     0.5146     0.5378      1.026         19        640: 40% ━━━━╸─────── 10/25 2.2it/s 4.9s<6.8s

     47/200      2.28G     0.5153     0.5326      1.016         36        640: 44% ━━━━━─────── 11/25 2.1it/s 5.5s<6.7s

     47/200      2.28G     0.5136      0.533      1.012         23        640: 48% ━━━━━╸────── 12/25 2.1it/s 5.9s<6.1s

     47/200      2.28G     0.5119     0.5295       1.01         22        640: 52% ━━━━━━────── 13/25 2.3it/s 6.3s<5.1s

     47/200      2.21G     0.5207     0.5349      1.021         25        640: 56% ━━━━━━╸───── 14/25 2.1it/s 6.9s<5.2s

     47/200      2.23G     0.5219      0.531      1.017         23        640: 60% ━━━━━━━───── 15/25 2.2it/s 7.3s<4.6s

     47/200      2.21G     0.5269     0.5279      1.018         27        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.7s<3.9s

     47/200      2.21G     0.5285     0.5246      1.017         22        640: 68% ━━━━━━━━──── 17/25 2.4it/s 8.1s<3.4s

     47/200      2.26G     0.5558     0.5385      1.034         33        640: 72% ━━━━━━━━╸─── 18/25 2.5it/s 8.5s<2.8s

     47/200      2.21G     0.5597     0.5402      1.044          9        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.9s<2.5s

     47/200      2.21G     0.5612     0.5388       1.04         28        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 9.3s<2.1s

     47/200      2.26G     0.5603     0.5376      1.035         16        640: 84% ━━━━━━━━━━── 21/25 2.4it/s 9.8s<1.7s

     47/200      2.26G     0.5677     0.5421      1.047         20        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 10.2s<1.3s

     47/200      2.26G     0.5656     0.5372      1.044         23        640: 92% ━━━━━━━━━━━─ 23/25 2.4it/s 10.6s<0.8s

     47/200      2.26G     0.5642     0.5403      1.042         12        640: 96% ━━━━━━━━━━━╸ 24/25 2.3it/s 11.1s<0.4s

     47/200      2.26G     0.5642     0.5403      1.042         12        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 11.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.1s/it 1.1s

                   all          8          8      0.812      0.788      0.792      0.613

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     48/200      2.22G     0.5185     0.5496      1.037         14        640: 0% ──────────── 0/25  0.4s

     48/200      2.26G      0.545     0.5542      1.092         14        640: 4% ──────────── 1/25 1.4s/it 0.8s<33.4s

     48/200      2.23G     0.5981     0.5573      1.067         29        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<19.2s

     48/200      2.28G     0.6016     0.5328      1.036         33        640: 12% ━─────────── 3/25 1.5it/s 1.7s<14.2s

     48/200      2.28G     0.5934     0.5352      1.001         28        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<11.5s

     48/200      2.28G     0.5814     0.5227     0.9894         25        640: 20% ━━────────── 5/25 2.0it/s 2.5s<10.2s

     48/200      2.28G      0.584     0.5255     0.9852         22        640: 24% ━━╸───────── 6/25 2.0it/s 3.0s<9.3s

     48/200      2.25G     0.5868     0.5263     0.9951         15        640: 28% ━━━───────── 7/25 2.1it/s 3.4s<8.6s

     48/200      2.22G     0.5703      0.532     0.9874         16        640: 32% ━━━╸──────── 8/25 2.2it/s 3.9s<7.8s

     48/200      2.26G     0.5905     0.5348      1.002         14        640: 36% ━━━━──────── 9/25 2.3it/s 4.3s<7.1s

     48/200      2.26G     0.5881      0.531          1         22        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.7s<6.6s

     48/200      2.22G     0.5764     0.5308     0.9935         28        640: 44% ━━━━━─────── 11/25 2.3it/s 5.1s<6.2s

     48/200      2.26G     0.5804     0.5345     0.9999         19        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.6s<5.6s

     48/200      2.26G     0.5737     0.5342     0.9969         26        640: 52% ━━━━━━────── 13/25 2.1it/s 6.1s<5.6s

     48/200      2.26G     0.5737     0.5362     0.9979         19        640: 56% ━━━━━━╸───── 14/25 2.2it/s 6.5s<4.9s

     48/200      2.23G     0.5655     0.5305     0.9922         46        640: 60% ━━━━━━━───── 15/25 2.2it/s 7.0s<4.5s

     48/200      2.28G     0.5619     0.5271     0.9871         36        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.4s<3.9s

     48/200      2.28G     0.5702     0.5387      1.005         15        640: 68% ━━━━━━━━──── 17/25 2.2it/s 7.9s<3.6s

     48/200      2.28G     0.5766      0.537      1.003         23        640: 72% ━━━━━━━━╸─── 18/25 2.3it/s 8.3s<3.1s

     48/200      2.28G     0.5774     0.5405      1.011          8        640: 76% ━━━━━━━━━─── 19/25 2.3it/s 8.7s<2.6s

     48/200      2.28G      0.574     0.5422      1.007         22        640: 80% ━━━━━━━━━╸── 20/25 2.3it/s 9.1s<2.1s

     48/200      2.28G     0.5711     0.5427      1.004         31        640: 84% ━━━━━━━━━━── 21/25 2.1it/s 9.7s<1.9s

     48/200      2.28G     0.5763     0.5455      1.005         30        640: 88% ━━━━━━━━━━╸─ 22/25 2.2it/s 10.1s<1.3s

     48/200      2.28G     0.5759     0.5419      1.009         17        640: 92% ━━━━━━━━━━━─ 23/25 2.2it/s 10.6s<0.9s

     48/200      2.28G     0.5834     0.5461      1.019          6        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 10.9s<0.4s

     48/200      2.28G     0.5834     0.5461      1.019          6        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 10.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.1it/s 0.9s

                   all          8          8      0.942      0.736      0.995      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     49/200      2.25G     0.5289     0.4753     0.8529         34        640: 0% ──────────── 0/25  0.4s

     49/200      2.24G     0.5224     0.4612     0.9055         17        640: 4% ──────────── 1/25 1.4s/it 0.8s<34.4s

     49/200      2.25G     0.5087     0.4795     0.9374         14        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<19.2s

     49/200      2.25G     0.5076      0.507     0.9626         19        640: 12% ━─────────── 3/25 1.5it/s 1.7s<14.2s

     49/200      2.25G     0.5796     0.5201     0.9871         22        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<11.5s

     49/200      2.25G     0.5782     0.5159      0.993         30        640: 20% ━━────────── 5/25 2.0it/s 2.5s<10.0s

     49/200      2.21G     0.5739     0.5069      0.984         22        640: 24% ━━╸───────── 6/25 2.1it/s 2.9s<9.0s

     49/200      2.26G     0.5737     0.5074     0.9894         27        640: 28% ━━━───────── 7/25 2.2it/s 3.4s<8.4s

     49/200      2.26G     0.5707     0.5009     0.9905         20        640: 32% ━━━╸──────── 8/25 2.2it/s 3.8s<7.6s

     49/200      2.26G     0.5732     0.4999     0.9988         17        640: 36% ━━━━──────── 9/25 2.2it/s 4.2s<7.1s

     49/200      2.26G     0.5765     0.5147      1.016         25        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.7s<6.6s

     49/200      2.24G      0.571     0.5154       1.02         27        640: 44% ━━━━━─────── 11/25 2.3it/s 5.1s<6.2s

     49/200      2.21G     0.5657     0.5291      1.026         10        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.5s<5.8s

     49/200      2.24G     0.5567     0.5362      1.022          8        640: 52% ━━━━━━────── 13/25 2.4it/s 5.9s<5.1s

     49/200      2.24G     0.5567     0.5344      1.021         27        640: 56% ━━━━━━╸───── 14/25 2.3it/s 6.4s<4.7s

     49/200      2.24G     0.5599     0.5317      1.016         23        640: 60% ━━━━━━━───── 15/25 2.3it/s 6.8s<4.3s

     49/200      2.24G     0.5576     0.5283      1.009         22        640: 64% ━━━━━━━╸──── 16/25 2.4it/s 7.2s<3.7s

     49/200      2.25G     0.5642     0.5328      1.013         14        640: 68% ━━━━━━━━──── 17/25 2.5it/s 7.6s<3.3s

     49/200      2.25G      0.563     0.5313       1.01         14        640: 72% ━━━━━━━━╸─── 18/25 2.5it/s 8.0s<2.9s

     49/200      2.25G     0.5609     0.5263      1.003         32        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.4s<2.5s

     49/200      2.25G     0.5678     0.5275      1.011         22        640: 80% ━━━━━━━━━╸── 20/25 2.3it/s 8.9s<2.1s

     49/200      2.25G     0.5625     0.5405      1.014         20        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.3s<1.7s

     49/200      2.25G     0.5645     0.5403      1.009         47        640: 88% ━━━━━━━━━━╸─ 22/25 2.4it/s 9.7s<1.3s

     49/200      2.25G     0.5636     0.5376      1.003         22        640: 92% ━━━━━━━━━━━─ 23/25 2.4it/s 10.1s<0.8s

     49/200      2.25G     0.5589     0.5368      0.999         23        640: 96% ━━━━━━━━━━━╸ 24/25 2.6it/s 10.4s<0.4s

     49/200      2.25G     0.5589     0.5368      0.999         23        640: 100% ━━━━━━━━━━━━ 25/25 2.4it/s 10.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.0it/s 1.0s

                   all          8          8      0.923      0.712      0.808      0.614

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     50/200      2.25G      0.607     0.6271      1.122          8        640: 0% ──────────── 0/25  0.4s

     50/200      2.25G     0.5526     0.5288      1.032         40        640: 4% ──────────── 1/25 2.0s/it 1.0s<48.2s

     50/200      2.24G     0.5724     0.5212      1.023         22        640: 8% ╸─────────── 2/25 1.1it/s 1.4s<21.1s

     50/200      2.21G     0.5662     0.5291     0.9985         33        640: 12% ━─────────── 3/25 1.3it/s 2.0s<17.1s

     50/200      2.26G     0.5296     0.5052     0.9913         17        640: 16% ━╸────────── 4/25 1.6it/s 2.4s<13.4s

     50/200      2.26G     0.5216     0.5042      0.982         20        640: 20% ━━────────── 5/25 1.8it/s 2.8s<10.8s

     50/200      2.22G     0.5203     0.5165     0.9982         14        640: 24% ━━╸───────── 6/25 2.0it/s 3.3s<9.6s

     50/200      2.27G     0.5273     0.5112     0.9964         24        640: 28% ━━━───────── 7/25 2.1it/s 3.7s<8.7s

     50/200      2.25G     0.5155     0.5103     0.9898          9        640: 32% ━━━╸──────── 8/25 2.1it/s 4.1s<8.0s

     50/200      2.25G     0.5105     0.5129     0.9862         14        640: 36% ━━━━──────── 9/25 2.2it/s 4.5s<7.2s

     50/200      2.25G     0.5088     0.5208     0.9807         25        640: 40% ━━━━╸─────── 10/25 2.3it/s 5.0s<6.6s

     50/200      2.25G     0.5062     0.5185     0.9747         24        640: 44% ━━━━━─────── 11/25 2.3it/s 5.4s<6.1s

     50/200      2.25G      0.512     0.5158     0.9786         14        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.8s<5.6s

     50/200      2.25G     0.5092     0.5181     0.9811         14        640: 52% ━━━━━━────── 13/25 2.3it/s 6.3s<5.2s

     50/200      2.25G     0.5103     0.5117     0.9806         24        640: 56% ━━━━━━╸───── 14/25 2.3it/s 6.7s<4.7s

     50/200      2.25G     0.5164     0.5144     0.9781         44        640: 60% ━━━━━━━───── 15/25 2.1it/s 7.3s<4.7s

     50/200      2.25G     0.5115     0.5132     0.9768         17        640: 64% ━━━━━━━╸──── 16/25 2.2it/s 7.7s<4.1s

     50/200      2.25G     0.5122     0.5152     0.9803         14        640: 68% ━━━━━━━━──── 17/25 2.2it/s 8.1s<3.6s

     50/200      2.25G     0.5167     0.5106     0.9776         34        640: 72% ━━━━━━━━╸─── 18/25 2.2it/s 8.6s<3.1s

     50/200      2.25G     0.5213     0.5129     0.9765         36        640: 76% ━━━━━━━━━─── 19/25 2.3it/s 9.0s<2.6s

     50/200      2.25G     0.5236     0.5161      0.978         34        640: 80% ━━━━━━━━━╸── 20/25 2.3it/s 9.4s<2.2s

     50/200      2.25G      0.527     0.5174     0.9831         15        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 9.9s<1.7s

     50/200      2.22G     0.5215     0.5215     0.9804         19        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 10.3s<1.3s

     50/200      2.26G     0.5269     0.5217     0.9804         23        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 10.7s<0.9s

     50/200      2.26G     0.5338     0.5195     0.9787         20        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 11.0s<0.4s

     50/200      2.26G     0.5338     0.5195     0.9787         20        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 11.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.1s/it 1.1s

                   all          8          8      0.841      0.749      0.816      0.614

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     51/200      2.23G     0.5075      0.511     0.9997         25        640: 0% ──────────── 0/25  0.4s

     51/200      2.26G     0.5438     0.5065     0.9504         32        640: 4% ──────────── 1/25 1.2s/it 0.8s<28.6s

     51/200      2.26G     0.5333     0.5153     0.9628         17        640: 8% ╸─────────── 2/25 1.3it/s 1.2s<17.9s

     51/200      2.26G     0.5773     0.5237     0.9753         25        640: 12% ━─────────── 3/25 1.6it/s 1.6s<13.5s

     51/200      2.26G     0.5855     0.5375     0.9787         31        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<11.4s

     51/200      2.25G     0.6208     0.5601      1.057         10        640: 20% ━━────────── 5/25 1.9it/s 2.6s<10.5s

     51/200      2.25G     0.6188     0.5645      1.081         14        640: 24% ━━╸───────── 6/25 2.0it/s 3.0s<9.3s

     51/200      2.25G     0.6108     0.5551      1.075         17        640: 28% ━━━───────── 7/25 2.1it/s 3.4s<8.6s

     51/200      2.25G     0.6011     0.5444      1.053         30        640: 32% ━━━╸──────── 8/25 2.1it/s 3.9s<7.9s

     51/200      2.25G     0.6063     0.5456      1.058         14        640: 36% ━━━━──────── 9/25 2.2it/s 4.3s<7.2s

     51/200      2.25G     0.6133     0.5383      1.047         36        640: 40% ━━━━╸─────── 10/25 2.3it/s 4.7s<6.6s

     51/200      2.25G     0.6072     0.5339      1.053         16        640: 44% ━━━━━─────── 11/25 2.3it/s 5.2s<6.2s

     51/200      2.25G     0.5992     0.5281      1.042         25        640: 48% ━━━━━╸────── 12/25 2.3it/s 5.6s<5.8s

     51/200      2.25G     0.5912     0.5213      1.031         23        640: 52% ━━━━━━────── 13/25 2.3it/s 6.0s<5.3s

     51/200      2.25G     0.5916     0.5169      1.025         35        640: 56% ━━━━━━╸───── 14/25 2.3it/s 6.5s<4.8s

     51/200      2.25G     0.5888     0.5157      1.023         15        640: 60% ━━━━━━━───── 15/25 2.3it/s 6.9s<4.4s

     51/200      2.25G     0.6024      0.521      1.028         27        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.3s<3.9s

     51/200      2.25G     0.6014     0.5194      1.026         27        640: 68% ━━━━━━━━──── 17/25 2.3it/s 7.8s<3.4s

     51/200      2.25G     0.6036     0.5205      1.022         25        640: 72% ━━━━━━━━╸─── 18/25 2.4it/s 8.2s<3.0s

     51/200      2.25G     0.6098     0.5268      1.038          8        640: 76% ━━━━━━━━━─── 19/25 2.4it/s 8.6s<2.6s

     51/200      2.25G     0.6087     0.5232      1.035         16        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 9.0s<2.1s

     51/200      2.25G     0.6079     0.5235      1.036         32        640: 84% ━━━━━━━━━━── 21/25 2.4it/s 9.4s<1.7s

     51/200      2.25G     0.6021     0.5237      1.033         15        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 9.9s<1.3s

     51/200      2.25G     0.6028      0.523      1.032         20        640: 92% ━━━━━━━━━━━─ 23/25 2.4it/s 10.3s<0.8s

     51/200      2.25G     0.6001     0.5252      1.029         23        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 10.6s<0.4s

     51/200      2.25G     0.6001     0.5252      1.029         23        640: 100% ━━━━━━━━━━━━ 25/25 2.4it/s 10.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.6s/it 1.6s

                   all          8          8      0.745        0.8      0.798      0.588

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     52/200      2.25G     0.4451     0.4226     0.9425         22        640: 0% ──────────── 0/25  0.4s

     52/200      2.26G     0.5023      0.487     0.9743         26        640: 4% ──────────── 1/25 1.4s/it 0.8s<33.4s

     52/200      2.26G     0.5238     0.5279       1.03         14        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<19.3s

     52/200      2.26G       0.54      0.522      1.048         17        640: 12% ━─────────── 3/25 1.5it/s 1.7s<14.5s

     52/200      2.26G     0.5889     0.5506      1.148          8        640: 16% ━╸────────── 4/25 1.8it/s 2.1s<11.9s

     52/200      2.26G     0.5957     0.5493      1.121         42        640: 20% ━━────────── 5/25 2.0it/s 2.6s<10.2s

     52/200      2.26G     0.5887     0.5286      1.091         24        640: 24% ━━╸───────── 6/25 2.1it/s 3.0s<9.1s

     52/200      2.26G     0.5891     0.5273      1.065         34        640: 28% ━━━───────── 7/25 2.2it/s 3.4s<8.3s

     52/200      2.26G     0.5877     0.5339      1.093          9        640: 32% ━━━╸──────── 8/25 2.2it/s 3.9s<7.8s

     52/200      2.26G     0.5932     0.5442      1.094         19        640: 36% ━━━━──────── 9/25 2.3it/s 4.3s<7.0s

     52/200      2.23G     0.5832     0.5433      1.089         16        640: 40% ━━━━╸─────── 10/25 2.0it/s 4.9s<7.4s

     52/200      2.23G     0.5879     0.5379      1.075         38        640: 44% ━━━━━─────── 11/25 2.1it/s 5.4s<6.6s

     52/200      2.24G     0.5819     0.5379      1.078          8        640: 48% ━━━━━╸────── 12/25 2.2it/s 5.8s<5.9s

     52/200      2.24G     0.5859     0.5311      1.069         28        640: 52% ━━━━━━────── 13/25 2.2it/s 6.2s<5.4s

     52/200      2.22G     0.5804     0.5276       1.07         15        640: 56% ━━━━━━╸───── 14/25 2.2it/s 6.7s<5.0s

     52/200      2.27G     0.5779     0.5212      1.056         24        640: 60% ━━━━━━━───── 15/25 2.3it/s 7.1s<4.4s

     52/200      2.27G     0.5782     0.5223      1.063         25        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 7.5s<3.9s

     52/200      2.23G     0.5844     0.5228      1.062         33        640: 68% ━━━━━━━━──── 17/25 2.3it/s 7.9s<3.5s

     52/200      2.26G     0.5789      0.523      1.058         17        640: 72% ━━━━━━━━╸─── 18/25 2.3it/s 8.4s<3.1s

     52/200      2.26G     0.5776      0.525      1.055         25        640: 76% ━━━━━━━━━─── 19/25 2.1it/s 9.0s<2.8s

     52/200      2.26G     0.5773     0.5216       1.05         22        640: 80% ━━━━━━━━━╸── 20/25 2.2it/s 9.4s<2.3s

     52/200      2.21G     0.5712     0.5242      1.054         10        640: 84% ━━━━━━━━━━── 21/25 2.4it/s 9.7s<1.7s

     52/200      2.23G     0.5711     0.5236      1.054         27        640: 88% ━━━━━━━━━━╸─ 22/25 2.3it/s 10.2s<1.3s

     52/200      2.21G     0.5696     0.5196      1.049         30        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 10.6s<0.9s

     52/200      2.26G     0.5676     0.5181      1.045         25        640: 96% ━━━━━━━━━━━╸ 24/25 2.5it/s 11.0s<0.4s

     52/200      2.26G     0.5676     0.5181      1.045         25        640: 100% ━━━━━━━━━━━━ 25/25 2.3it/s 11.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.5s/it 1.5s

                   all          8          8      0.862      0.489       0.73      0.545

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     53/200       2.3G     0.5569     0.4085     0.9204         16        640: 0% ──────────── 0/25  0.5s

     53/200       2.3G     0.5383     0.4959      1.016          8        640: 4% ──────────── 1/25 1.6s/it 0.9s<38.0s

     53/200       2.3G     0.5608     0.5227      1.043         20        640: 8% ╸─────────── 2/25 1.1it/s 1.4s<21.5s

     53/200       2.3G      0.547     0.5207      1.093         11        640: 12% ━─────────── 3/25 1.2it/s 2.1s<18.4s

     53/200       2.3G     0.5851     0.5152      1.074         26        640: 16% ━╸────────── 4/25 1.5it/s 2.6s<14.4s

     53/200      2.27G     0.5767     0.5106      1.083         17        640: 20% ━━────────── 5/25 1.6it/s 3.1s<12.4s

     53/200      2.27G     0.5728     0.5096      1.074         19        640: 24% ━━╸───────── 6/25 1.7it/s 3.6s<11.0s

     53/200      2.27G     0.5903     0.5029      1.068         36        640: 28% ━━━───────── 7/25 1.9it/s 4.0s<9.7s

     53/200      2.25G     0.5885     0.5068      1.048         52        640: 32% ━━━╸──────── 8/25 1.8it/s 4.6s<9.3s

     53/200      2.25G     0.5877     0.5135      1.043         22        640: 36% ━━━━──────── 9/25 1.9it/s 5.1s<8.5s

     53/200      2.25G     0.5835     0.5148      1.046         16        640: 40% ━━━━╸─────── 10/25 1.9it/s 5.6s<7.8s

     53/200      2.25G     0.5816     0.5125      1.037         24        640: 44% ━━━━━─────── 11/25 2.0it/s 6.1s<7.0s

     53/200      2.25G     0.5762     0.5052      1.028         22        640: 48% ━━━━━╸────── 12/25 2.1it/s 6.5s<6.3s

     53/200      2.25G     0.5765     0.5015      1.021         28        640: 52% ━━━━━━────── 13/25 2.3it/s 6.9s<5.2s

     53/200      2.24G     0.5802     0.5101      1.034          9        640: 56% ━━━━━━╸───── 14/25 2.2it/s 7.3s<4.9s

     53/200      2.23G     0.5922     0.5094      1.038         25        640: 60% ━━━━━━━───── 15/25 2.1it/s 7.9s<4.7s

     53/200      2.28G     0.5851     0.5047      1.034         25        640: 64% ━━━━━━━╸──── 16/25 2.1it/s 8.4s<4.2s

     53/200      2.28G     0.6017     0.5181      1.047         25        640: 68% ━━━━━━━━──── 17/25 2.1it/s 8.8s<3.7s

     53/200      2.28G     0.5998     0.5282      1.043         32        640: 72% ━━━━━━━━╸─── 18/25 2.2it/s 9.3s<3.2s

     53/200      2.28G     0.5985     0.5448      1.042         30        640: 76% ━━━━━━━━━─── 19/25 2.1it/s 9.7s<2.8s

     53/200      2.28G     0.5981     0.5465      1.036         27        640: 80% ━━━━━━━━━╸── 20/25 2.1it/s 10.2s<2.3s

     53/200      2.28G     0.5931     0.5472      1.035          8        640: 84% ━━━━━━━━━━── 21/25 2.2it/s 10.7s<1.8s

     53/200      2.28G     0.5915     0.5431      1.032         24        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 11.2s<1.4s

     53/200      2.28G     0.5858     0.5391      1.026         24        640: 92% ━━━━━━━━━━━─ 23/25 2.1it/s 11.7s<1.0s

     53/200      2.28G     0.5846     0.5413      1.023         12        640: 96% ━━━━━━━━━━━╸ 24/25 1.9it/s 12.3s<0.5s

     53/200      2.28G     0.5846     0.5413      1.023         12        640: 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.8s/it 1.8s

                   all          8          8      0.886      0.542      0.743        0.5

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     54/200      2.26G     0.6562     0.4576      1.094         25        640: 0% ──────────── 0/25  0.5s

     54/200      2.26G     0.5835     0.5429      1.033         30        640: 4% ──────────── 1/25 1.6s/it 1.0s<37.3s

     54/200      2.23G     0.5698     0.5511      1.081         19        640: 8% ╸─────────── 2/25 1.1it/s 1.5s<21.7s

     54/200      2.26G     0.5673      0.536      1.044         22        640: 12% ━─────────── 3/25 1.4it/s 1.9s<15.6s

     54/200      2.26G     0.5701     0.5221      1.046         22        640: 16% ━╸────────── 4/25 1.8it/s 2.3s<11.6s

     54/200      2.26G     0.5534     0.5033      1.027         16        640: 20% ━━────────── 5/25 1.9it/s 2.7s<10.4s

     54/200      2.23G     0.5637     0.5151      1.025         33        640: 24% ━━╸───────── 6/25 1.9it/s 3.3s<9.9s

     54/200      2.28G     0.5656     0.5157      1.012         20        640: 28% ━━━───────── 7/25 2.0it/s 3.7s<9.1s

     54/200      2.28G     0.5485     0.5196      1.016          8        640: 32% ━━━╸──────── 8/25 2.0it/s 4.2s<8.4s

     54/200      2.28G     0.5417     0.5087      1.008         23        640: 36% ━━━━──────── 9/25 2.0it/s 4.7s<7.9s

     54/200      2.28G     0.5476     0.5108      1.004         36        640: 40% ━━━━╸─────── 10/25 2.1it/s 5.2s<7.3s

     54/200      2.28G     0.5511     0.5117      1.007         27        640: 44% ━━━━━─────── 11/25 2.1it/s 5.7s<6.8s

     54/200      2.28G      0.559     0.5098      1.004         35        640: 48% ━━━━━╸────── 12/25 2.1it/s 6.1s<6.3s

     54/200      2.28G     0.5557     0.5079      1.005         15        640: 52% ━━━━━━────── 13/25 2.0it/s 6.6s<5.9s

     54/200      2.28G     0.5611     0.5099      1.006         15        640: 56% ━━━━━━╸───── 14/25 2.0it/s 7.1s<5.4s

     54/200      2.23G     0.5626     0.5112     0.9972         44        640: 60% ━━━━━━━───── 15/25 1.8it/s 7.9s<5.5s

     54/200      2.27G     0.5576     0.5111     0.9945         21        640: 64% ━━━━━━━╸──── 16/25 1.9it/s 8.4s<4.8s

     54/200      2.27G     0.5721     0.5118     0.9977         16        640: 68% ━━━━━━━━──── 17/25 2.0it/s 8.9s<4.1s

     54/200      2.21G     0.5776     0.5334     0.9973         22        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.4s<3.6s

     54/200      2.26G     0.5809      0.534      1.009          8        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 9.8s<3.0s

     54/200      2.22G     0.5825     0.5323      1.007         27        640: 80% ━━━━━━━━━╸── 20/25 2.0it/s 10.3s<2.5s

     54/200      2.26G     0.5924     0.5337      1.012         22        640: 84% ━━━━━━━━━━── 21/25 2.1it/s 10.8s<1.9s

     54/200      2.25G     0.5921     0.5351      1.023          9        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 11.3s<1.4s

     54/200      2.25G      0.596     0.5325      1.021         23        640: 92% ━━━━━━━━━━━─ 23/25 2.1it/s 11.8s<1.0s

     54/200      2.22G     0.5948     0.5323      1.023         20        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 12.2s<0.5s

     54/200      2.22G     0.5948     0.5323      1.023         20        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 12.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.4s/it 1.4s

                   all          8          8      0.889      0.534      0.767      0.545

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     55/200      2.29G     0.7036     0.4327      1.019         41        640: 0% ──────────── 0/25  0.9s

     55/200      2.29G     0.5862     0.4582      1.051         20        640: 4% ──────────── 1/25 1.8s/it 1.4s<43.4s

     55/200      2.28G     0.5588     0.4477      1.006         35        640: 8% ╸─────────── 2/25 1.0s/it 1.9s<23.1s

     55/200      2.32G      0.558     0.4501      0.972         25        640: 12% ━─────────── 3/25 1.3it/s 2.4s<16.4s

     55/200      2.32G      0.535     0.4527     0.9516         27        640: 16% ━╸────────── 4/25 1.6it/s 2.8s<13.2s

     55/200      2.28G     0.5259     0.4644     0.9807          8        640: 20% ━━────────── 5/25 1.8it/s 3.3s<11.4s

     55/200      2.32G     0.5268     0.4664     0.9722         16        640: 24% ━━╸───────── 6/25 1.9it/s 3.8s<10.0s

     55/200      2.29G     0.5316     0.4702     0.9691         22        640: 28% ━━━───────── 7/25 2.0it/s 4.2s<9.1s

     55/200      2.33G     0.5489     0.4972     0.9827         14        640: 32% ━━━╸──────── 8/25 2.0it/s 4.7s<8.5s

     55/200      2.33G     0.5417     0.4936     0.9769         31        640: 36% ━━━━──────── 9/25 2.0it/s 5.2s<8.1s

     55/200      2.32G     0.5414     0.4916     0.9664         33        640: 40% ━━━━╸─────── 10/25 2.2it/s 5.6s<6.7s

     55/200      2.32G     0.5443     0.4881     0.9625         33        640: 44% ━━━━━─────── 11/25 2.2it/s 6.1s<6.4s

     55/200      2.32G     0.5438     0.4912     0.9694          9        640: 48% ━━━━━╸────── 12/25 2.2it/s 6.5s<6.0s

     55/200      2.32G     0.5492     0.4897     0.9713         22        640: 52% ━━━━━━────── 13/25 2.4it/s 6.9s<5.1s

     55/200      2.33G     0.5507     0.4926     0.9683         21        640: 56% ━━━━━━╸───── 14/25 2.3it/s 7.4s<4.9s

     55/200      2.33G     0.5554     0.4923       0.99          9        640: 60% ━━━━━━━───── 15/25 2.2it/s 7.9s<4.6s

     55/200      2.27G     0.5626     0.4973     0.9929         20        640: 64% ━━━━━━━╸──── 16/25 2.2it/s 8.4s<4.2s

     55/200      2.27G     0.5671     0.4948     0.9963         16        640: 68% ━━━━━━━━──── 17/25 2.2it/s 8.8s<3.7s

     55/200      2.32G      0.569     0.4932     0.9997         23        640: 72% ━━━━━━━━╸─── 18/25 2.1it/s 9.3s<3.3s

     55/200      2.32G     0.5646     0.4923     0.9953         41        640: 76% ━━━━━━━━━─── 19/25 2.1it/s 9.8s<2.9s

     55/200      2.32G     0.5662     0.4951     0.9965         22        640: 80% ━━━━━━━━━╸── 20/25 2.1it/s 10.3s<2.4s

     55/200      2.32G     0.5697     0.4978      1.021         10        640: 84% ━━━━━━━━━━── 21/25 2.1it/s 10.8s<1.9s

     55/200      2.29G     0.5678     0.4987      1.024         26        640: 88% ━━━━━━━━━━╸─ 22/25 2.0it/s 11.3s<1.5s

     55/200      2.34G     0.5664     0.4986      1.019         20        640: 92% ━━━━━━━━━━━─ 23/25 2.1it/s 11.7s<1.0s

     55/200      2.34G     0.5729     0.5013      1.023         14        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 12.2s<0.5s

     55/200      2.34G     0.5729     0.5013      1.023         14        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 12.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.0s/it 2.0s

                   all          8          8      0.798      0.571      0.756      0.551

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     56/200      2.33G     0.5744     0.3946      1.084         16        640: 0% ──────────── 0/25  0.6s

     56/200      2.33G     0.6053     0.4597      1.086         20        640: 4% ──────────── 1/25 1.6s/it 1.1s<38.2s

     56/200      2.33G     0.5814     0.5186      1.045         30        640: 8% ╸─────────── 2/25 1.1it/s 1.5s<21.0s

     56/200      2.33G     0.5683     0.5072      1.048         14        640: 12% ━─────────── 3/25 1.4it/s 2.0s<16.1s

     56/200      2.29G     0.6093     0.5018      1.053         24        640: 16% ━╸────────── 4/25 1.6it/s 2.5s<13.2s

     56/200      2.32G     0.5976     0.5062      1.029         44        640: 20% ━━────────── 5/25 1.5it/s 3.3s<13.4s

     56/200      2.27G     0.5997     0.5103      1.023         20        640: 24% ━━╸───────── 6/25 1.7it/s 3.8s<11.4s

     56/200      2.32G     0.6004     0.5003      1.008         22        640: 28% ━━━───────── 7/25 1.8it/s 4.2s<9.9s

     56/200      2.29G     0.5897     0.4951      1.001         38        640: 32% ━━━╸──────── 8/25 1.9it/s 4.7s<9.2s

     56/200      2.34G     0.5832      0.494      1.007         16        640: 36% ━━━━──────── 9/25 1.9it/s 5.2s<8.5s

     56/200      2.28G      0.583     0.4954      1.014          9        640: 40% ━━━━╸─────── 10/25 1.9it/s 5.8s<7.9s

     56/200      2.29G     0.5806     0.4989      1.007         27        640: 44% ━━━━━─────── 11/25 2.0it/s 6.2s<7.2s

     56/200      2.28G     0.5907     0.5095      1.021         14        640: 48% ━━━━━╸────── 12/25 2.0it/s 6.7s<6.6s

     56/200      2.33G     0.5899      0.507      1.016         24        640: 52% ━━━━━━────── 13/25 2.0it/s 7.2s<6.0s

     56/200      2.33G     0.5872     0.5011      1.013         25        640: 56% ━━━━━━╸───── 14/25 2.0it/s 7.7s<5.6s

     56/200      2.33G     0.5869     0.4956      1.009         25        640: 60% ━━━━━━━───── 15/25 2.0it/s 8.3s<5.1s

     56/200      2.27G     0.5838     0.5061      1.011         26        640: 64% ━━━━━━━╸──── 16/25 2.0it/s 8.7s<4.4s

     56/200      2.28G     0.5732     0.5043      1.013         19        640: 68% ━━━━━━━━──── 17/25 2.0it/s 9.2s<4.0s

     56/200      2.27G      0.564     0.5001      1.008         20        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.7s<3.5s

     56/200      2.32G      0.562     0.5004      1.005         28        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 10.2s<3.0s

     56/200      2.28G     0.5624     0.5027      1.009         16        640: 80% ━━━━━━━━━╸── 20/25 2.0it/s 10.7s<2.5s

     56/200      2.33G     0.5628     0.5058      1.006         24        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 11.2s<2.0s

     56/200      2.33G     0.5597     0.5061      1.008         18        640: 88% ━━━━━━━━━━╸─ 22/25 1.9it/s 11.8s<1.5s

     56/200      2.33G     0.5569     0.5084      1.005         22        640: 92% ━━━━━━━━━━━─ 23/25 2.0it/s 12.3s<1.0s

     56/200      2.28G     0.5633     0.5077      1.015         17        640: 96% ━━━━━━━━━━━╸ 24/25 1.8it/s 12.9s<0.5s

     56/200      2.28G     0.5633     0.5077      1.015         17        640: 100% ━━━━━━━━━━━━ 25/25 1.9it/s 12.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.2s/it 1.2s

                   all          8          8      0.817      0.574      0.751      0.504

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     57/200      2.21G     0.6012     0.4268     0.9446         23        640: 0% ──────────── 0/25  0.5s

     57/200      2.22G     0.6006     0.4425     0.9349         46        640: 4% ──────────── 1/25 1.6s/it 1.0s<38.1s

     57/200      2.26G     0.5906      0.445     0.9517         17        640: 8% ╸─────────── 2/25 1.0it/s 1.5s<22.0s

     57/200      2.21G     0.5496      0.439     0.9542         16        640: 12% ━─────────── 3/25 1.4it/s 1.9s<16.1s

     57/200      2.26G     0.5677     0.4463     0.9437         28        640: 16% ━╸────────── 4/25 1.6it/s 2.4s<13.1s

     57/200      2.22G     0.5878      0.456     0.9862         14        640: 20% ━━────────── 5/25 1.7it/s 3.0s<12.0s

     57/200      2.27G     0.5943     0.4626     0.9878         22        640: 24% ━━╸───────── 6/25 1.8it/s 3.4s<10.6s

     57/200      2.27G     0.5886      0.462     0.9772         36        640: 28% ━━━───────── 7/25 1.9it/s 3.9s<9.6s

     57/200      2.27G     0.5887     0.4579      0.982         22        640: 32% ━━━╸──────── 8/25 2.0it/s 4.4s<8.7s

     57/200      2.27G     0.5935     0.4596     0.9856         31        640: 36% ━━━━──────── 9/25 2.0it/s 4.8s<7.9s

     57/200      2.27G     0.5908     0.4599     0.9837         26        640: 40% ━━━━╸─────── 10/25 2.0it/s 5.3s<7.5s

     57/200      2.27G     0.5971     0.4617     0.9844         17        640: 44% ━━━━━─────── 11/25 2.0it/s 5.8s<6.9s

     57/200      2.27G     0.5927      0.468      1.005          9        640: 48% ━━━━━╸────── 12/25 2.0it/s 6.4s<6.5s

     57/200      2.27G     0.5855     0.4759      1.007         19        640: 52% ━━━━━━────── 13/25 2.2it/s 6.7s<5.3s

     57/200      2.27G     0.5798     0.4766     0.9992         42        640: 56% ━━━━━━╸───── 14/25 2.2it/s 7.2s<5.0s

     57/200      2.27G     0.5878     0.4783      1.009         17        640: 60% ━━━━━━━───── 15/25 2.1it/s 7.7s<4.7s

     57/200      2.26G     0.5834     0.4759      1.001         30        640: 64% ━━━━━━━╸──── 16/25 2.1it/s 8.1s<4.2s

     57/200      2.26G     0.5806      0.477      0.998         27        640: 68% ━━━━━━━━──── 17/25 2.1it/s 8.6s<3.8s

     57/200      2.26G     0.5888     0.4785      1.002         28        640: 72% ━━━━━━━━╸─── 18/25 2.1it/s 9.1s<3.3s

     57/200      2.26G     0.5867     0.4811     0.9984         18        640: 76% ━━━━━━━━━─── 19/25 2.1it/s 9.6s<2.9s

     57/200      2.25G     0.5813     0.4821      1.004          9        640: 80% ━━━━━━━━━╸── 20/25 2.1it/s 10.1s<2.4s

     57/200      2.22G     0.5756     0.4798      1.001         25        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 10.5s<1.8s

     57/200      2.26G     0.5708     0.4826     0.9977         16        640: 88% ━━━━━━━━━━╸─ 22/25 2.2it/s 10.9s<1.3s

     57/200      2.26G     0.5719     0.4829      1.009         14        640: 92% ━━━━━━━━━━━─ 23/25 2.2it/s 11.4s<0.9s

     57/200      2.22G       0.58     0.4885      1.029          6        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 11.8s<0.4s

     57/200      2.22G       0.58     0.4885      1.029          6        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 11.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.2s/it 1.2s

                   all          8          8      0.902       0.79       0.78      0.582

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     58/200      2.27G     0.8367     0.4856      1.028         27        640: 0% ──────────── 0/25  0.5s

     58/200      2.27G     0.7251     0.4841      0.995         16        640: 4% ──────────── 1/25 1.6s/it 1.0s<38.8s

     58/200      2.27G      0.635     0.4849      1.006         20        640: 8% ╸─────────── 2/25 1.1it/s 1.5s<21.7s

     58/200      2.27G     0.6232     0.4816      1.027         22        640: 12% ━─────────── 3/25 1.4it/s 1.9s<16.2s

     58/200      2.27G     0.6631     0.5017      1.036         24        640: 16% ━╸────────── 4/25 1.8it/s 2.3s<11.4s

     58/200      2.27G     0.6664     0.4938      1.024         22        640: 20% ━━────────── 5/25 2.0it/s 2.7s<10.2s

     58/200      2.27G     0.6459     0.4909      1.028         21        640: 24% ━━╸───────── 6/25 2.0it/s 3.2s<9.7s

     58/200      2.27G      0.625     0.4942      1.027         21        640: 28% ━━━───────── 7/25 1.9it/s 3.8s<9.3s

     58/200      2.27G     0.6078     0.4965      1.018         20        640: 32% ━━━╸──────── 8/25 2.0it/s 4.3s<8.6s

     58/200      2.27G     0.5893     0.5058      1.023          8        640: 36% ━━━━──────── 9/25 2.0it/s 4.7s<8.0s

     58/200      2.27G     0.5811     0.5041      1.017         25        640: 40% ━━━━╸─────── 10/25 2.0it/s 5.2s<7.4s

     58/200      2.27G      0.572        0.5      1.011         29        640: 44% ━━━━━─────── 11/25 2.0it/s 5.7s<7.0s

     58/200      2.27G     0.5683     0.4982      1.007         31        640: 48% ━━━━━╸────── 12/25 2.0it/s 6.2s<6.4s

     58/200      2.27G      0.564     0.4958      1.008         20        640: 52% ━━━━━━────── 13/25 2.0it/s 6.7s<5.9s

     58/200      2.27G     0.5663     0.4905      1.006         32        640: 56% ━━━━━━╸───── 14/25 2.0it/s 7.2s<5.5s

     58/200      2.27G     0.5646     0.4922      1.006         27        640: 60% ━━━━━━━───── 15/25 2.0it/s 7.7s<4.9s

     58/200      2.27G     0.5575     0.4871      1.002         22        640: 64% ━━━━━━━╸──── 16/25 2.1it/s 8.2s<4.4s

     58/200      2.23G     0.5563     0.4858     0.9992         22        640: 68% ━━━━━━━━──── 17/25 2.1it/s 8.6s<3.9s

     58/200      2.27G      0.559     0.4842     0.9969         20        640: 72% ━━━━━━━━╸─── 18/25 2.1it/s 9.1s<3.4s

     58/200      2.27G     0.5527     0.4836     0.9988          9        640: 76% ━━━━━━━━━─── 19/25 2.1it/s 9.6s<2.9s

     58/200      2.27G     0.5496     0.4852      1.002         20        640: 80% ━━━━━━━━━╸── 20/25 2.0it/s 10.1s<2.4s

     58/200      2.27G     0.5527     0.4834      1.001         25        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 10.6s<2.0s

     58/200      2.27G      0.552      0.489     0.9977         37        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 11.1s<1.5s

     58/200      2.27G     0.5494     0.4897     0.9961         16        640: 92% ━━━━━━━━━━━─ 23/25 2.0it/s 11.6s<1.0s

     58/200      2.27G     0.5467      0.486     0.9941         22        640: 96% ━━━━━━━━━━━╸ 24/25 2.1it/s 12.0s<0.5s

     58/200      2.27G     0.5467      0.486     0.9941         22        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 12.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.0s/it 1.0s

                   all          8          8      0.938      0.776      0.796       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     59/200      2.27G      0.472     0.4516     0.9746         23        640: 0% ──────────── 0/25  0.5s

     59/200      2.25G     0.6227     0.4826     0.9842         16        640: 4% ──────────── 1/25 1.6s/it 1.0s<37.9s

     59/200      2.25G     0.6724     0.5107       1.01         25        640: 8% ╸─────────── 2/25 1.1it/s 1.5s<21.1s

     59/200      2.23G     0.6569     0.4992      1.008         17        640: 12% ━─────────── 3/25 1.4it/s 2.0s<16.0s

     59/200      2.26G     0.6161     0.4896      1.009         25        640: 16% ━╸────────── 4/25 1.6it/s 2.4s<13.1s

     59/200      2.27G     0.6199     0.4931      1.027         14        640: 20% ━━────────── 5/25 1.8it/s 2.9s<11.4s

     59/200      2.27G     0.6061     0.4827      1.004         41        640: 24% ━━╸───────── 6/25 1.6it/s 3.6s<11.6s

     59/200      2.27G     0.5898     0.4704     0.9958         16        640: 28% ━━━───────── 7/25 1.8it/s 4.1s<10.0s

     59/200      2.27G     0.5809     0.4622     0.9877         41        640: 32% ━━━╸──────── 8/25 2.1it/s 4.5s<8.2s

     59/200      2.27G     0.5799     0.4695          1         16        640: 36% ━━━━──────── 9/25 2.0it/s 5.0s<7.9s

     59/200      2.27G       0.57     0.4635     0.9931         30        640: 40% ━━━━╸─────── 10/25 2.0it/s 5.5s<7.4s

     59/200      2.22G     0.5678     0.4617     0.9859         44        640: 44% ━━━━━─────── 11/25 1.8it/s 6.2s<7.7s

     59/200      2.27G     0.5639     0.4666     0.9899         16        640: 48% ━━━━━╸────── 12/25 1.9it/s 6.7s<7.0s

     59/200      2.21G     0.5672     0.4661     0.9898         22        640: 52% ━━━━━━────── 13/25 1.9it/s 7.2s<6.2s

     59/200      2.21G     0.5626     0.4639     0.9911         15        640: 56% ━━━━━━╸───── 14/25 1.9it/s 7.8s<5.9s

     59/200      2.26G     0.5628     0.4646     0.9957         16        640: 60% ━━━━━━━───── 15/25 1.9it/s 8.3s<5.2s

     59/200      2.26G     0.5615     0.4611     0.9885         23        640: 64% ━━━━━━━╸──── 16/25 1.9it/s 8.8s<4.6s

     59/200      2.26G     0.5755     0.4666     0.9936         16        640: 68% ━━━━━━━━──── 17/25 2.0it/s 9.2s<4.0s

     59/200      2.26G       0.57      0.468     0.9939         27        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.7s<3.5s

     59/200      2.26G     0.5758      0.473      1.004          8        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 10.2s<2.9s

     59/200      2.26G     0.5641     0.4714      1.002          9        640: 80% ━━━━━━━━━╸── 20/25 2.0it/s 10.7s<2.5s

     59/200      2.26G     0.5578     0.4699          1         25        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 11.2s<2.0s

     59/200      2.26G     0.5535     0.4682     0.9958         33        640: 88% ━━━━━━━━━━╸─ 22/25 2.0it/s 11.7s<1.5s

     59/200      2.26G     0.5532     0.4653     0.9917         22        640: 92% ━━━━━━━━━━━─ 23/25 2.1it/s 12.2s<1.0s

     59/200      2.27G     0.5528     0.4676     0.9895         18        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 12.5s<0.5s

     59/200      2.27G     0.5528     0.4676     0.9895         18        640: 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.2s/it 1.2s

                   all          8          8      0.857      0.786      0.763      0.565

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     60/200      2.25G     0.4683     0.5392      0.912         25        640: 0% ──────────── 0/25  0.4s

     60/200      2.27G     0.5106     0.4901     0.9797         16        640: 4% ──────────── 1/25 1.7s/it 0.9s<41.6s

     60/200      2.27G     0.5164     0.5587     0.9736         41        640: 8% ╸─────────── 2/25 1.0it/s 1.4s<22.1s

     60/200      2.27G     0.5072      0.532     0.9797         20        640: 12% ━─────────── 3/25 1.3it/s 1.9s<16.6s

     60/200      2.27G     0.5151     0.5219     0.9663         31        640: 16% ━╸────────── 4/25 1.3it/s 2.6s<15.6s

     60/200      2.27G     0.5111     0.5088     0.9651         16        640: 20% ━━────────── 5/25 1.6it/s 3.1s<12.7s

     60/200      2.21G     0.4984     0.4919     0.9637         22        640: 24% ━━╸───────── 6/25 1.7it/s 3.6s<11.2s

     60/200      2.26G     0.4956     0.4851     0.9502         22        640: 28% ━━━───────── 7/25 1.8it/s 4.1s<10.1s

     60/200      2.26G     0.5085     0.4865     0.9677         16        640: 32% ━━━╸──────── 8/25 1.9it/s 4.5s<9.1s

     60/200      2.26G     0.4981     0.4897      0.975          8        640: 36% ━━━━──────── 9/25 1.9it/s 5.0s<8.3s

     60/200      2.26G     0.4952     0.4922     0.9686         25        640: 40% ━━━━╸─────── 10/25 2.0it/s 5.5s<7.6s

     60/200      2.26G     0.5002     0.4923      0.967         35        640: 44% ━━━━━─────── 11/25 2.0it/s 6.0s<7.0s

     60/200      2.26G     0.4962     0.4929     0.9699          9        640: 48% ━━━━━╸────── 12/25 2.0it/s 6.5s<6.4s

     60/200      2.26G     0.4987     0.4881     0.9692         25        640: 52% ━━━━━━────── 13/25 2.0it/s 7.0s<6.0s

     60/200      2.26G     0.5124     0.4874     0.9814         17        640: 56% ━━━━━━╸───── 14/25 2.2it/s 7.3s<5.0s

     60/200      2.27G     0.5145     0.4865     0.9813         20        640: 60% ━━━━━━━───── 15/25 2.2it/s 7.8s<4.6s

     60/200      2.27G     0.5134     0.4872     0.9962          9        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 8.2s<4.0s

     60/200      2.27G     0.5152      0.485     0.9918         26        640: 68% ━━━━━━━━──── 17/25 2.0it/s 9.0s<4.0s

     60/200      2.27G      0.514     0.4853     0.9957          8        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.4s<3.4s

     60/200      2.27G     0.5124     0.4832          1          8        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 9.9s<2.9s

     60/200      2.27G     0.5196     0.4862     0.9958         31        640: 80% ━━━━━━━━━╸── 20/25 2.0it/s 10.4s<2.5s

     60/200      2.27G     0.5169     0.4848     0.9917         40        640: 84% ━━━━━━━━━━── 21/25 1.8it/s 11.2s<2.2s

     60/200      2.21G     0.5281     0.4854     0.9937         22        640: 88% ━━━━━━━━━━╸─ 22/25 1.8it/s 11.8s<1.7s

     60/200      2.21G      0.533     0.4858     0.9907         36        640: 92% ━━━━━━━━━━━─ 23/25 1.6it/s 12.6s<1.2s

     60/200      2.23G     0.5336     0.4858      0.987         30        640: 96% ━━━━━━━━━━━╸ 24/25 1.7it/s 13.1s<0.6s

     60/200      2.23G     0.5336     0.4858      0.987         30        640: 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.0it/s 1.0s

                   all          8          8      0.828        0.6      0.748      0.531

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     61/200      2.26G     0.4326     0.4606     0.9919         15        640: 0% ──────────── 0/25  0.5s

     61/200      2.26G     0.4452     0.4603      1.001          8        640: 4% ──────────── 1/25 1.1s/it 0.8s<26.7s

     61/200      2.26G     0.4462     0.4792     0.9571         32        640: 8% ╸─────────── 2/25 1.2it/s 1.4s<19.0s

     61/200      2.26G     0.4746     0.4811     0.9707         16        640: 12% ━─────────── 3/25 1.4it/s 1.9s<15.2s

     61/200      2.26G      0.471     0.4737     0.9653         23        640: 16% ━╸────────── 4/25 1.8it/s 2.2s<11.5s

     61/200      2.26G     0.4678     0.4595     0.9536         22        640: 20% ━━────────── 5/25 2.1it/s 2.6s<9.4s

     61/200      2.26G     0.4837      0.468     0.9754         19        640: 24% ━━╸───────── 6/25 2.1it/s 3.1s<9.1s

     61/200      2.25G     0.5013     0.4628      0.985         21        640: 28% ━━━───────── 7/25 2.1it/s 3.6s<8.6s

     61/200      2.24G     0.4953       0.46      0.972         31        640: 32% ━━━╸──────── 8/25 2.3it/s 3.9s<7.4s

     61/200      2.27G     0.4862     0.4512     0.9622         23        640: 36% ━━━━──────── 9/25 2.2it/s 4.4s<7.2s

     61/200      2.27G     0.4963     0.4526     0.9974         14        640: 40% ━━━━╸─────── 10/25 2.1it/s 4.9s<7.0s

     61/200      2.27G     0.4984     0.4508     0.9951         22        640: 44% ━━━━━─────── 11/25 2.1it/s 5.4s<6.6s

     61/200      2.22G     0.5083     0.4586      1.009         25        640: 48% ━━━━━╸────── 12/25 2.1it/s 5.9s<6.1s

     61/200      2.27G     0.5058     0.4564      1.003         25        640: 52% ━━━━━━────── 13/25 2.1it/s 6.4s<5.7s

     61/200      2.23G     0.5118     0.4607          1         28        640: 56% ━━━━━━╸───── 14/25 2.1it/s 6.9s<5.4s

     61/200      2.23G      0.517     0.4611     0.9981         33        640: 60% ━━━━━━━───── 15/25 2.0it/s 7.4s<4.9s

     61/200      2.26G     0.5197     0.4646     0.9962         22        640: 64% ━━━━━━━╸──── 16/25 2.0it/s 7.9s<4.5s

     61/200      2.21G     0.5271     0.4644     0.9924         27        640: 68% ━━━━━━━━──── 17/25 2.0it/s 8.4s<3.9s

     61/200      2.21G     0.5305     0.4744     0.9961         19        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 8.9s<3.4s

     61/200      2.26G     0.5329     0.4721     0.9987         16        640: 76% ━━━━━━━━━─── 19/25 2.1it/s 9.3s<2.9s

     61/200      2.23G     0.5331     0.4711     0.9942         42        640: 80% ━━━━━━━━━╸── 20/25 2.1it/s 9.8s<2.4s

     61/200      2.23G     0.5287     0.4669     0.9897         23        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 10.3s<2.0s

     61/200      2.28G     0.5312     0.4684     0.9917         28        640: 88% ━━━━━━━━━━╸─ 22/25 2.0it/s 10.9s<1.5s

     61/200      2.28G     0.5317     0.4661     0.9949         17        640: 92% ━━━━━━━━━━━─ 23/25 2.0it/s 11.4s<1.0s

     61/200      2.28G     0.5266     0.4666      0.994          7        640: 96% ━━━━━━━━━━━╸ 24/25 2.1it/s 11.8s<0.5s

     61/200      2.28G     0.5266     0.4666      0.994          7        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 11.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.2it/s 0.8s

                   all          8          8       0.87        0.6      0.743      0.567

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     62/200      2.28G     0.4757     0.4351     0.8714         28        640: 0% ──────────── 0/25  0.5s

     62/200      2.28G      0.574     0.4582     0.9784         16        640: 4% ──────────── 1/25 1.7s/it 1.0s<39.9s

     62/200      2.28G      0.552     0.4619     0.9581         31        640: 8% ╸─────────── 2/25 1.0it/s 1.5s<22.2s

     62/200      2.28G     0.5421     0.4466     0.9344         36        640: 12% ━─────────── 3/25 1.4it/s 2.0s<16.3s

     62/200      2.28G     0.5216     0.4541     0.9459         31        640: 16% ━╸────────── 4/25 1.5it/s 2.5s<13.6s

     62/200      2.28G     0.5053      0.451     0.9454         16        640: 20% ━━────────── 5/25 1.7it/s 3.0s<12.0s

     62/200      2.28G     0.5161     0.4445     0.9355         23        640: 24% ━━╸───────── 6/25 1.8it/s 3.5s<10.7s

     62/200      2.28G     0.5153       0.44     0.9498         17        640: 28% ━━━───────── 7/25 1.8it/s 4.0s<9.8s

     62/200      2.28G     0.5394     0.4497      1.008          8        640: 32% ━━━╸──────── 8/25 1.9it/s 4.5s<8.9s

     62/200      2.28G     0.5714     0.4531      1.025         24        640: 36% ━━━━──────── 9/25 1.9it/s 5.0s<8.4s

     62/200      2.28G     0.5783     0.4531      1.023         30        640: 40% ━━━━╸─────── 10/25 2.0it/s 5.5s<7.7s

     62/200      2.23G     0.5797     0.4518      1.016         24        640: 44% ━━━━━─────── 11/25 2.0it/s 6.0s<7.1s

     62/200      2.27G     0.5711     0.4486       1.01         16        640: 48% ━━━━━╸────── 12/25 2.0it/s 6.4s<6.5s

     62/200      2.22G     0.5648     0.4452     0.9983         35        640: 52% ━━━━━━────── 13/25 2.0it/s 6.9s<5.9s

     62/200      2.26G     0.5748     0.4513      1.006         20        640: 56% ━━━━━━╸───── 14/25 2.0it/s 7.4s<5.4s

     62/200      2.26G      0.568     0.4532      1.003         19        640: 60% ━━━━━━━───── 15/25 2.0it/s 7.9s<4.9s

     62/200      2.26G     0.5748     0.4554          1         22        640: 64% ━━━━━━━╸──── 16/25 2.0it/s 8.4s<4.4s

     62/200      2.26G     0.5663     0.4545     0.9979         26        640: 68% ━━━━━━━━──── 17/25 2.0it/s 8.9s<3.9s

     62/200      2.26G     0.5686     0.4597      1.005          8        640: 72% ━━━━━━━━╸─── 18/25 2.1it/s 9.4s<3.4s

     62/200      2.26G     0.5638     0.4633      1.008         19        640: 76% ━━━━━━━━━─── 19/25 2.1it/s 9.9s<2.9s

     62/200      2.26G     0.5576     0.4587      1.003         28        640: 80% ━━━━━━━━━╸── 20/25 2.1it/s 10.3s<2.4s

     62/200      2.26G     0.5523       0.46     0.9985         25        640: 84% ━━━━━━━━━━── 21/25 2.1it/s 10.8s<1.9s

     62/200      2.26G      0.555     0.4578      1.001         14        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 11.3s<1.4s

     62/200      2.26G     0.5575     0.4609     0.9977         36        640: 92% ━━━━━━━━━━━─ 23/25 2.1it/s 11.8s<1.0s

     62/200      2.26G     0.5574      0.465      1.003          6        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 12.2s<0.5s

     62/200      2.26G     0.5574      0.465      1.003          6        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 12.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.4it/s 0.7s

                   all          8          8      0.923        0.8      0.763      0.537

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     63/200      2.26G     0.4348      0.404     0.9703         23        640: 0% ──────────── 0/25  0.4s

     63/200      2.26G     0.5485     0.4394     0.9448         14        640: 4% ──────────── 1/25 1.5s/it 0.9s<37.1s

     63/200      2.26G       0.54     0.4462     0.9428         22        640: 8% ╸─────────── 2/25 1.1it/s 1.3s<21.0s

     63/200      2.26G     0.5196     0.4781     0.9373         14        640: 12% ━─────────── 3/25 1.4it/s 1.8s<16.0s

     63/200      2.23G     0.5154     0.4676     0.9488         33        640: 16% ━╸────────── 4/25 1.5it/s 2.3s<13.6s

     63/200      2.26G     0.5013     0.4581     0.9365         30        640: 20% ━━────────── 5/25 1.7it/s 2.8s<11.8s

     63/200      2.26G     0.5123     0.4625     0.9468         44        640: 24% ━━╸───────── 6/25 2.0it/s 3.2s<9.3s

     63/200      2.21G     0.5051     0.4548     0.9501         15        640: 28% ━━━───────── 7/25 2.0it/s 3.7s<9.0s

     63/200      2.26G     0.5115     0.4546     0.9442         23        640: 32% ━━━╸──────── 8/25 2.0it/s 4.2s<8.5s

     63/200      2.26G     0.5082     0.4662     0.9483         16        640: 36% ━━━━──────── 9/25 2.0it/s 4.7s<8.0s

     63/200      2.26G     0.5047     0.4638     0.9445         24        640: 40% ━━━━╸─────── 10/25 2.0it/s 5.2s<7.4s

     63/200      2.26G     0.5076     0.4628      0.943         26        640: 44% ━━━━━─────── 11/25 2.0it/s 5.7s<6.9s

     63/200      2.27G     0.5205     0.4682     0.9508         20        640: 48% ━━━━━╸────── 12/25 2.1it/s 6.1s<6.3s

     63/200      2.27G     0.5283     0.4686     0.9605         16        640: 52% ━━━━━━────── 13/25 2.1it/s 6.6s<5.8s

     63/200      2.27G     0.5302     0.4697      0.958         33        640: 56% ━━━━━━╸───── 14/25 2.1it/s 7.1s<5.3s

     63/200      2.27G     0.5287     0.4673     0.9582         33        640: 60% ━━━━━━━───── 15/25 2.1it/s 7.6s<4.8s

     63/200      2.27G     0.5255     0.4632     0.9588         16        640: 64% ━━━━━━━╸──── 16/25 2.1it/s 8.0s<4.3s

     63/200      2.27G      0.523     0.4642     0.9672          8        640: 68% ━━━━━━━━──── 17/25 2.1it/s 8.5s<3.8s

     63/200      2.27G      0.521     0.4616     0.9731          9        640: 72% ━━━━━━━━╸─── 18/25 2.1it/s 9.0s<3.4s

     63/200      2.27G     0.5245      0.464     0.9777         14        640: 76% ━━━━━━━━━─── 19/25 2.1it/s 9.5s<2.9s

     63/200      2.27G     0.5311      0.469     0.9791         25        640: 80% ━━━━━━━━━╸── 20/25 2.1it/s 10.0s<2.4s

     63/200      2.27G     0.5316     0.4687     0.9856         19        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 10.5s<2.0s

     63/200      2.21G     0.5321     0.4676     0.9849         16        640: 88% ━━━━━━━━━━╸─ 22/25 1.9it/s 11.1s<1.6s

     63/200      2.21G     0.5332     0.4673     0.9868         31        640: 92% ━━━━━━━━━━━─ 23/25 1.8it/s 11.7s<1.1s

     63/200      2.22G     0.5355     0.4675     0.9838         34        640: 96% ━━━━━━━━━━━╸ 24/25 1.9it/s 12.2s<0.5s

     63/200      2.22G     0.5355     0.4675     0.9838         34        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 12.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.1it/s 0.9s

                   all          8          8      0.918        0.8      0.763      0.557

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     64/200      2.31G     0.6722      0.514      1.198          8        640: 0% ──────────── 0/25  0.5s

     64/200      2.28G     0.7255     0.5093      1.091         22        640: 4% ──────────── 1/25 1.6s/it 1.0s<39.6s

     64/200       2.3G     0.6365     0.4857      1.038         26        640: 8% ╸─────────── 2/25 1.0it/s 1.5s<22.8s

     64/200      2.34G     0.5949     0.4717     0.9987         34        640: 12% ━─────────── 3/25 1.3it/s 2.0s<16.8s

     64/200      2.34G     0.5557     0.4688      0.979         30        640: 16% ━╸────────── 4/25 1.5it/s 2.5s<13.7s

     64/200      2.34G     0.5558     0.4637      0.968         22        640: 20% ━━────────── 5/25 1.7it/s 3.0s<11.7s

     64/200      2.34G      0.558     0.4656     0.9841         14        640: 24% ━━╸───────── 6/25 1.8it/s 3.5s<10.5s

     64/200      2.34G      0.556     0.4605     0.9818         21        640: 28% ━━━───────── 7/25 1.9it/s 4.0s<9.6s

     64/200      2.34G     0.5474     0.4545     0.9811         22        640: 32% ━━━╸──────── 8/25 1.9it/s 4.4s<8.8s

     64/200      2.34G     0.5395     0.4569     0.9761         24        640: 36% ━━━━──────── 9/25 2.0it/s 4.9s<8.1s

     64/200      2.34G     0.5394     0.4498     0.9727         41        640: 40% ━━━━╸─────── 10/25 2.0it/s 5.4s<7.5s

     64/200      2.34G     0.5388     0.4536     0.9757          8        640: 44% ━━━━━─────── 11/25 2.0it/s 5.9s<6.9s

     64/200      2.34G     0.5442     0.4519     0.9825         27        640: 48% ━━━━━╸────── 12/25 2.0it/s 6.4s<6.5s

     64/200      2.34G     0.5499     0.4498     0.9835         23        640: 52% ━━━━━━────── 13/25 2.0it/s 6.9s<6.0s

     64/200      2.34G     0.5522     0.4623     0.9898          9        640: 56% ━━━━━━╸───── 14/25 2.0it/s 7.4s<5.4s

     64/200      2.34G     0.5451      0.459      0.992         16        640: 60% ━━━━━━━───── 15/25 2.0it/s 7.9s<5.0s

     64/200      2.34G     0.5416      0.453     0.9897         24        640: 64% ━━━━━━━╸──── 16/25 2.0it/s 8.4s<4.5s

     64/200      2.34G     0.5338     0.4527     0.9829         27        640: 68% ━━━━━━━━──── 17/25 2.0it/s 8.9s<4.0s

     64/200      2.34G     0.5357     0.4501     0.9791         30        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.3s<3.4s

     64/200      2.34G     0.5356       0.45     0.9801         22        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 9.9s<3.0s

     64/200      2.34G     0.5348     0.4527     0.9784         19        640: 80% ━━━━━━━━━╸── 20/25 2.1it/s 10.3s<2.4s

     64/200      2.34G     0.5351     0.4486     0.9768         22        640: 84% ━━━━━━━━━━── 21/25 2.1it/s 10.8s<1.9s

     64/200      2.28G     0.5344     0.4544     0.9795         30        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 11.3s<1.5s

     64/200      2.33G     0.5341     0.4523     0.9781         15        640: 92% ━━━━━━━━━━━─ 23/25 2.1it/s 11.8s<1.0s

     64/200      2.33G     0.5354      0.453     0.9764         22        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 12.2s<0.4s

     64/200      2.33G     0.5354      0.453     0.9764         22        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 12.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.8it/s 0.6s

                   all          8          8      0.914        0.8      0.783      0.613

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     65/200      2.27G     0.4416     0.5752     0.8739         47        640: 0% ──────────── 0/25  0.5s

     65/200      2.27G     0.4263     0.4709     0.8783         33        640: 4% ──────────── 1/25 1.6s/it 1.0s<38.8s

     65/200      2.27G     0.4471      0.448     0.8961         30        640: 8% ╸─────────── 2/25 1.1it/s 1.5s<21.7s

     65/200      2.27G     0.4636     0.4545     0.8832         33        640: 12% ━─────────── 3/25 1.4it/s 1.9s<15.5s

     65/200      2.27G     0.4825     0.4465     0.8952         31        640: 16% ━╸────────── 4/25 1.6it/s 2.4s<13.2s

     65/200      2.27G     0.4904     0.4451     0.9066         28        640: 20% ━━────────── 5/25 1.7it/s 2.9s<11.6s

     65/200      2.27G     0.4969     0.4653     0.9562          8        640: 24% ━━╸───────── 6/25 1.8it/s 3.4s<10.3s

     65/200      2.27G      0.501     0.4667     0.9545         26        640: 28% ━━━───────── 7/25 1.9it/s 3.9s<9.6s

     65/200      2.26G      0.535     0.4676     0.9752         16        640: 32% ━━━╸──────── 8/25 1.9it/s 4.4s<8.9s

     65/200      2.26G     0.5367     0.4731     0.9822         15        640: 36% ━━━━──────── 9/25 1.8it/s 5.0s<8.8s

     65/200      2.26G      0.533     0.4691       0.97         29        640: 40% ━━━━╸─────── 10/25 1.9it/s 5.5s<8.1s

     65/200      2.21G      0.536     0.4765     0.9821          8        640: 44% ━━━━━─────── 11/25 1.9it/s 6.0s<7.2s

     65/200      2.26G     0.5283     0.4716     0.9811         21        640: 48% ━━━━━╸────── 12/25 1.9it/s 6.5s<6.8s

     65/200      2.27G     0.5221     0.4753     0.9763         16        640: 52% ━━━━━━────── 13/25 2.0it/s 7.0s<6.1s

     65/200      2.21G     0.5198     0.4714     0.9769         16        640: 56% ━━━━━━╸───── 14/25 2.0it/s 7.5s<5.5s

     65/200      2.27G     0.5181     0.4662     0.9761         21        640: 60% ━━━━━━━───── 15/25 2.0it/s 8.0s<5.0s

     65/200      2.27G     0.5207     0.4638      0.973         26        640: 64% ━━━━━━━╸──── 16/25 2.1it/s 8.4s<4.4s

     65/200      2.23G     0.5279     0.4625     0.9781         17        640: 68% ━━━━━━━━──── 17/25 2.0it/s 9.0s<4.0s

     65/200      2.21G     0.5286     0.4638     0.9802          8        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.4s<3.4s

     65/200      2.26G     0.5295     0.4608     0.9757         35        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 9.9s<2.9s

     65/200      2.26G       0.53     0.4582      0.973         24        640: 80% ━━━━━━━━━╸── 20/25 2.3it/s 10.3s<2.2s

     65/200      2.26G     0.5316     0.4575     0.9772         16        640: 84% ━━━━━━━━━━── 21/25 2.2it/s 10.8s<1.8s

     65/200      2.26G       0.53     0.4578     0.9772         16        640: 88% ━━━━━━━━━━╸─ 22/25 2.2it/s 11.3s<1.4s

     65/200      2.26G     0.5344     0.4573      0.976         31        640: 92% ━━━━━━━━━━━─ 23/25 2.1it/s 11.8s<0.9s

     65/200      2.26G     0.5317     0.4577     0.9791          7        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 12.2s<0.5s

     65/200      2.26G     0.5317     0.4577     0.9791          7        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 12.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.0s/it 1.0s

                   all          8          8      0.891        0.8      0.813      0.593

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     66/200      2.25G     0.5141     0.4279      1.021         19        640: 0% ──────────── 0/25  0.5s

     66/200      2.25G     0.4588     0.4844       1.04          9        640: 4% ──────────── 1/25 1.7s/it 1.0s<40.2s

     66/200      2.25G      0.451     0.4742     0.9949         31        640: 8% ╸─────────── 2/25 1.0it/s 1.5s<22.1s

     66/200      2.25G     0.4757     0.4536     0.9674         28        640: 12% ━─────────── 3/25 1.4it/s 2.0s<16.2s

     66/200      2.26G     0.4939     0.4542     0.9806         14        640: 16% ━╸────────── 4/25 1.6it/s 2.4s<13.1s

     66/200      2.26G     0.5178     0.4629      1.008         26        640: 20% ━━────────── 5/25 1.7it/s 2.9s<11.8s

     66/200      2.24G     0.5337     0.4499     0.9926         33        640: 24% ━━╸───────── 6/25 1.6it/s 3.6s<11.7s

     66/200      2.22G     0.5231     0.4408     0.9777         24        640: 28% ━━━───────── 7/25 1.8it/s 4.1s<10.1s

     66/200      2.26G     0.5162     0.4372     0.9734         16        640: 32% ━━━╸──────── 8/25 1.9it/s 4.6s<9.1s

     66/200      2.26G     0.5169     0.4383     0.9841         15        640: 36% ━━━━──────── 9/25 2.1it/s 5.0s<7.7s

     66/200      2.21G     0.5285     0.4374      0.978         24        640: 40% ━━━━╸─────── 10/25 2.1it/s 5.5s<7.2s

     66/200      2.26G     0.5311     0.4424     0.9847         14        640: 44% ━━━━━─────── 11/25 2.1it/s 6.0s<6.8s

     66/200      2.26G     0.5298     0.4382     0.9782         41        640: 48% ━━━━━╸────── 12/25 2.1it/s 6.4s<6.2s

     66/200      2.26G     0.5233     0.4364     0.9753         15        640: 52% ━━━━━━────── 13/25 2.0it/s 6.9s<5.9s

     66/200      2.26G     0.5258     0.4355     0.9842         14        640: 56% ━━━━━━╸───── 14/25 2.0it/s 7.4s<5.4s

     66/200      2.26G     0.5254      0.439      0.999          8        640: 60% ━━━━━━━───── 15/25 2.1it/s 7.9s<4.9s

     66/200      2.26G       0.53     0.4369      1.003         15        640: 64% ━━━━━━━╸──── 16/25 2.0it/s 8.4s<4.5s

     66/200      2.26G     0.5301     0.4394      1.002         38        640: 68% ━━━━━━━━──── 17/25 2.2it/s 8.8s<3.7s

     66/200      2.26G     0.5353      0.439      1.001         17        640: 72% ━━━━━━━━╸─── 18/25 2.2it/s 9.3s<3.2s

     66/200      2.27G     0.5444     0.4499      1.005         23        640: 76% ━━━━━━━━━─── 19/25 2.1it/s 9.8s<2.9s

     66/200      2.27G     0.5492     0.4538      1.007         20        640: 80% ━━━━━━━━━╸── 20/25 2.1it/s 10.3s<2.4s

     66/200      2.27G     0.5508     0.4522      1.001         30        640: 84% ━━━━━━━━━━── 21/25 2.3it/s 10.6s<1.7s

     66/200      2.27G     0.5509     0.4501      1.001         24        640: 88% ━━━━━━━━━━╸─ 22/25 2.2it/s 11.2s<1.4s

     66/200      2.27G     0.5505     0.4481     0.9963         35        640: 92% ━━━━━━━━━━━─ 23/25 2.2it/s 11.6s<0.9s

     66/200      2.27G     0.5482      0.447     0.9934         25        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 12.0s<0.4s

     66/200      2.27G     0.5482      0.447     0.9934         25        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 12.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.2it/s 0.8s

                   all          8          8      0.875        0.8      0.772      0.564

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     67/200      2.26G     0.5725     0.4401     0.9075         36        640: 0% ──────────── 0/25  0.5s

     67/200      2.24G      0.513     0.4333     0.9075         33        640: 4% ──────────── 1/25 1.6s/it 1.0s<39.3s

     67/200      2.24G     0.5409     0.4222      0.927         25        640: 8% ╸─────────── 2/25 1.0it/s 1.5s<22.5s

     67/200      2.24G     0.5432     0.4504     0.9709         14        640: 12% ━─────────── 3/25 1.3it/s 2.0s<16.8s

     67/200      2.26G     0.5551     0.4433     0.9683         16        640: 16% ━╸────────── 4/25 1.5it/s 2.5s<13.7s

     67/200      2.26G     0.5567     0.4446     0.9574         24        640: 20% ━━────────── 5/25 1.7it/s 3.0s<11.8s

     67/200      2.26G     0.5468     0.4322     0.9545         22        640: 24% ━━╸───────── 6/25 1.8it/s 3.4s<10.5s

     67/200      2.26G     0.5508     0.4253      0.952         22        640: 28% ━━━───────── 7/25 1.9it/s 3.9s<9.5s

     67/200      2.26G     0.5393     0.4175      0.955         23        640: 32% ━━━╸──────── 8/25 1.9it/s 4.4s<8.9s

     67/200      2.26G     0.5528     0.4251     0.9685         14        640: 36% ━━━━──────── 9/25 2.0it/s 4.9s<8.1s

     67/200      2.26G     0.5442     0.4283     0.9637         33        640: 40% ━━━━╸─────── 10/25 2.0it/s 5.4s<7.6s

     67/200      2.26G     0.5431     0.4269     0.9648         21        640: 44% ━━━━━─────── 11/25 2.0it/s 5.9s<6.9s

     67/200      2.26G     0.5429     0.4376      0.965         41        640: 48% ━━━━━╸────── 12/25 2.1it/s 6.4s<6.3s

     67/200      2.26G      0.539     0.4526     0.9772         20        640: 52% ━━━━━━────── 13/25 2.0it/s 6.9s<6.0s

     67/200      2.26G     0.5373     0.4528     0.9747         27        640: 56% ━━━━━━╸───── 14/25 2.0it/s 7.4s<5.4s

     67/200      2.26G     0.5269     0.4515     0.9704          9        640: 60% ━━━━━━━───── 15/25 2.0it/s 7.8s<4.9s

     67/200      2.22G     0.5311     0.4535     0.9779         15        640: 64% ━━━━━━━╸──── 16/25 2.0it/s 8.4s<4.5s

     67/200      2.27G     0.5234     0.4493     0.9743         14        640: 68% ━━━━━━━━──── 17/25 2.0it/s 8.9s<4.0s

     67/200      2.27G     0.5217     0.4459      0.972         20        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.3s<3.4s

     67/200      2.27G     0.5234     0.4475     0.9701         22        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 9.8s<3.0s

     67/200      2.27G       0.52     0.4475     0.9683         27        640: 80% ━━━━━━━━━╸── 20/25 2.0it/s 10.3s<2.5s

     67/200      2.21G     0.5178     0.4477     0.9725         16        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 10.9s<2.0s

     67/200      2.26G     0.5233     0.4462     0.9703         22        640: 88% ━━━━━━━━━━╸─ 22/25 2.2it/s 11.3s<1.4s

     67/200      2.22G     0.5267     0.4478     0.9686         36        640: 92% ━━━━━━━━━━━─ 23/25 2.1it/s 11.7s<0.9s

     67/200      2.26G     0.5226     0.4478     0.9774          6        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 12.2s<0.5s

     67/200      2.26G     0.5226     0.4478     0.9774          6        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 12.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.1s/it 1.1s

                   all          8          8      0.841        0.8      0.813      0.599

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     68/200      2.27G     0.6031     0.4658      1.027         24        640: 0% ──────────── 0/25  0.6s

     68/200      2.29G     0.5778     0.4577     0.9957         36        640: 4% ──────────── 1/25 1.6s/it 1.0s<38.5s

     68/200      2.34G     0.5431     0.4536       1.05          8        640: 8% ╸─────────── 2/25 1.1it/s 1.5s<21.7s

     68/200       2.3G     0.5558     0.4423      1.024         41        640: 12% ━─────────── 3/25 1.1it/s 2.3s<19.8s

     68/200      2.33G     0.5351     0.4336      1.004         14        640: 16% ━╸────────── 4/25 1.4it/s 2.8s<15.0s

     68/200      2.33G     0.5309     0.4385      1.003         38        640: 20% ━━────────── 5/25 1.6it/s 3.3s<12.8s

     68/200      2.33G     0.5337     0.4557     0.9991         25        640: 24% ━━╸───────── 6/25 1.7it/s 3.8s<11.2s

     68/200      2.33G     0.5314     0.4627     0.9986         20        640: 28% ━━━───────── 7/25 2.0it/s 4.2s<9.1s

     68/200      2.28G     0.5254     0.4547     0.9936         20        640: 32% ━━━╸──────── 8/25 2.0it/s 4.7s<8.6s

     68/200       2.3G      0.525     0.4537     0.9883         33        640: 36% ━━━━──────── 9/25 2.2it/s 5.1s<7.3s

     68/200      2.33G     0.5337      0.452     0.9869         15        640: 40% ━━━━╸─────── 10/25 2.2it/s 5.6s<6.9s

     68/200      2.33G     0.5389     0.4533     0.9877         27        640: 44% ━━━━━─────── 11/25 2.1it/s 6.0s<6.5s

     68/200      2.33G     0.5369     0.4499     0.9837         25        640: 48% ━━━━━╸────── 12/25 2.1it/s 6.5s<6.1s

     68/200      2.28G      0.531     0.4474     0.9848         14        640: 52% ━━━━━━────── 13/25 2.3it/s 6.9s<5.2s

     68/200      2.33G     0.5279     0.4488     0.9841         27        640: 56% ━━━━━━╸───── 14/25 2.2it/s 7.4s<4.9s

     68/200      2.33G     0.5231     0.4443     0.9781         18        640: 60% ━━━━━━━───── 15/25 2.1it/s 7.9s<4.7s

     68/200      2.33G     0.5272     0.4435     0.9824         14        640: 64% ━━━━━━━╸──── 16/25 2.1it/s 8.4s<4.2s

     68/200      2.28G     0.5245     0.4446     0.9823         14        640: 68% ━━━━━━━━──── 17/25 2.1it/s 8.9s<3.8s

     68/200      2.33G     0.5229      0.446     0.9845         20        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.4s<3.4s

     68/200      2.33G     0.5239     0.4437     0.9817         23        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 9.9s<3.0s

     68/200      2.28G     0.5182     0.4421     0.9815          8        640: 80% ━━━━━━━━━╸── 20/25 2.0it/s 10.4s<2.5s

     68/200      2.33G     0.5222     0.4423     0.9932          8        640: 84% ━━━━━━━━━━── 21/25 2.1it/s 10.8s<1.9s

     68/200      2.33G     0.5212     0.4418     0.9877         36        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 11.3s<1.4s

     68/200      2.33G     0.5234     0.4402     0.9844         32        640: 92% ━━━━━━━━━━━─ 23/25 2.3it/s 11.7s<0.9s

     68/200      2.33G     0.5286     0.4403      0.992         18        640: 96% ━━━━━━━━━━━╸ 24/25 2.3it/s 12.1s<0.4s

     68/200      2.33G     0.5286     0.4403      0.992         18        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 12.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.6it/s 0.6s

                   all          8          8      0.706        0.8       0.77      0.602

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     69/200      2.33G     0.3785     0.3977     0.9433         25        640: 0% ──────────── 0/25  0.5s

     69/200      2.33G     0.4349     0.4034     0.9283         22        640: 4% ──────────── 1/25 1.6s/it 1.0s<38.5s

     69/200      2.33G     0.4837      0.401     0.9542         28        640: 8% ╸─────────── 2/25 1.0it/s 1.5s<22.4s

     69/200      2.33G     0.4982     0.4267     0.9455         27        640: 12% ━─────────── 3/25 1.3it/s 2.0s<16.7s

     69/200      2.33G     0.4924     0.4163      0.957         16        640: 16% ━╸────────── 4/25 1.5it/s 2.5s<13.8s

     69/200      2.33G     0.4862     0.4265     0.9651          9        640: 20% ━━────────── 5/25 1.7it/s 3.0s<11.8s

     69/200      2.33G     0.5072     0.4246     0.9538         30        640: 24% ━━╸───────── 6/25 1.8it/s 3.5s<10.4s

     69/200      2.33G     0.5182     0.4229     0.9555         26        640: 28% ━━━───────── 7/25 1.9it/s 4.0s<9.7s

     69/200      2.33G     0.5066     0.4226      0.957         19        640: 32% ━━━╸──────── 8/25 1.9it/s 4.4s<8.8s

     69/200      2.33G     0.5042     0.4217      0.956         16        640: 36% ━━━━──────── 9/25 2.0it/s 4.9s<8.2s

     69/200      2.33G     0.5173     0.4214     0.9544         17        640: 40% ━━━━╸─────── 10/25 2.0it/s 5.4s<7.6s

     69/200       2.3G     0.5233     0.4193     0.9512         30        640: 44% ━━━━━─────── 11/25 2.0it/s 5.9s<6.9s

     69/200      2.29G     0.5369     0.4195     0.9636         18        640: 48% ━━━━━╸────── 12/25 2.0it/s 6.4s<6.5s

     69/200      2.34G     0.5432       0.43     0.9712         25        640: 52% ━━━━━━────── 13/25 2.0it/s 6.9s<6.0s

     69/200      2.29G      0.547     0.4357     0.9818         14        640: 56% ━━━━━━╸───── 14/25 2.0it/s 7.4s<5.5s

     69/200      2.34G     0.5443     0.4381     0.9881          8        640: 60% ━━━━━━━───── 15/25 2.0it/s 7.9s<4.9s

     69/200      2.34G     0.5509     0.4361     0.9913         33        640: 64% ━━━━━━━╸──── 16/25 2.0it/s 8.4s<4.5s

     69/200      2.34G     0.5477     0.4352      0.985         42        640: 68% ━━━━━━━━──── 17/25 1.8it/s 9.2s<4.5s

     69/200      2.34G     0.5355     0.4362     0.9861          9        640: 72% ━━━━━━━━╸─── 18/25 1.8it/s 9.7s<3.8s

     69/200      2.34G       0.54     0.4363     0.9876         26        640: 76% ━━━━━━━━━─── 19/25 1.9it/s 10.2s<3.1s

     69/200      2.29G     0.5363     0.4352     0.9852         14        640: 80% ━━━━━━━━━╸── 20/25 1.8it/s 10.9s<2.9s

     69/200      2.28G     0.5375     0.4432     0.9839         35        640: 84% ━━━━━━━━━━── 21/25 1.8it/s 11.5s<2.2s

     69/200      2.28G     0.5318     0.4436     0.9848          8        640: 88% ━━━━━━━━━━╸─ 22/25 1.9it/s 11.9s<1.6s

     69/200       2.3G     0.5304     0.4433     0.9852         28        640: 92% ━━━━━━━━━━━─ 23/25 2.1it/s 12.3s<1.0s

     69/200      2.29G     0.5267     0.4419     0.9814         33        640: 96% ━━━━━━━━━━━╸ 24/25 2.0it/s 12.9s<0.5s

     69/200      2.29G     0.5267     0.4419     0.9814         33        640: 100% ━━━━━━━━━━━━ 25/25 1.9it/s 12.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.1it/s 0.9s

                   all          8          8      0.896      0.717      0.804      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     70/200      2.28G     0.5229     0.4646      1.146          9        640: 0% ──────────── 0/25  0.5s

     70/200      2.28G     0.5895     0.4541      1.104         23        640: 4% ──────────── 1/25 1.7s/it 1.0s<39.9s

     70/200      2.28G     0.5332      0.445      1.107          9        640: 8% ╸─────────── 2/25 1.0s/it 1.6s<23.3s

     70/200      2.33G     0.5507      0.471      1.081         16        640: 12% ━─────────── 3/25 1.6it/s 1.9s<14.2s

     70/200       2.3G     0.5335     0.4549      1.039         25        640: 16% ━╸────────── 4/25 1.7it/s 2.4s<12.3s

     70/200      2.33G     0.5219     0.4408       1.03         17        640: 20% ━━────────── 5/25 1.8it/s 2.9s<11.2s

     70/200      2.28G     0.5171     0.4372       1.04          8        640: 24% ━━╸───────── 6/25 1.9it/s 3.4s<10.1s

     70/200      2.28G     0.5295     0.4516       1.08          9        640: 28% ━━━───────── 7/25 1.9it/s 3.9s<9.5s

     70/200      2.32G     0.5495     0.4523      1.093         14        640: 32% ━━━╸──────── 8/25 2.2it/s 4.3s<7.9s

     70/200      2.32G     0.5586     0.4528      1.094         16        640: 36% ━━━━──────── 9/25 2.1it/s 4.8s<7.5s

     70/200      2.32G     0.5665      0.449      1.093         20        640: 40% ━━━━╸─────── 10/25 2.1it/s 5.3s<7.2s

     70/200      2.32G     0.5658     0.4436      1.074         43        640: 44% ━━━━━─────── 11/25 2.1it/s 5.7s<6.7s

     70/200      2.32G     0.5623     0.4428      1.071         16        640: 48% ━━━━━╸────── 12/25 2.1it/s 6.2s<6.3s

     70/200      2.32G     0.5605     0.4412       1.06         33        640: 52% ━━━━━━────── 13/25 2.0it/s 6.7s<5.9s

     70/200      2.32G     0.5583     0.4509      1.052         37        640: 56% ━━━━━━╸───── 14/25 2.0it/s 7.2s<5.4s

     70/200      2.32G     0.5571      0.453      1.058          8        640: 60% ━━━━━━━───── 15/25 2.0it/s 7.7s<4.9s

     70/200      2.32G      0.564     0.4538       1.05         45        640: 64% ━━━━━━━╸──── 16/25 1.9it/s 8.3s<4.7s

     70/200      2.32G     0.5628     0.4519      1.043         34        640: 68% ━━━━━━━━──── 17/25 2.0it/s 8.8s<4.1s

     70/200      2.32G     0.5617     0.4508      1.037         31        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.3s<3.5s

     70/200      2.32G      0.557     0.4468      1.029         38        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 9.8s<3.0s

     70/200      2.31G     0.5559     0.4484      1.027          9        640: 80% ━━━━━━━━━╸── 20/25 2.0it/s 10.3s<2.5s

     70/200      2.31G     0.5527     0.4485      1.021         49        640: 84% ━━━━━━━━━━── 21/25 1.8it/s 11.2s<2.3s

     70/200      2.31G     0.5541     0.4496      1.027          9        640: 88% ━━━━━━━━━━╸─ 22/25 1.8it/s 11.7s<1.7s

     70/200      2.31G     0.5582     0.4481      1.022         23        640: 92% ━━━━━━━━━━━─ 23/25 1.9it/s 12.2s<1.1s

     70/200      2.31G     0.5541     0.4495      1.017         17        640: 96% ━━━━━━━━━━━╸ 24/25 2.0it/s 12.6s<0.5s

     70/200      2.31G     0.5541     0.4495      1.017         17        640: 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.3it/s 0.8s

                   all          8          8      0.971        0.6      0.816      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     71/200      2.23G     0.7123     0.4747      1.217         24        640: 0% ──────────── 0/25  0.6s

     71/200      2.28G     0.5935     0.4324      1.104         16        640: 4% ──────────── 1/25 1.6s/it 1.0s<38.0s

     71/200      2.28G     0.5299     0.4083      1.025         39        640: 8% ╸─────────── 2/25 1.1it/s 1.5s<21.3s

     71/200      2.28G     0.5249     0.4203      1.039         19        640: 12% ━─────────── 3/25 1.4it/s 2.0s<16.0s

     71/200      2.28G     0.5395     0.4375       1.05          8        640: 16% ━╸────────── 4/25 1.6it/s 2.4s<12.9s

     71/200      2.28G     0.5665      0.449      1.048         31        640: 20% ━━────────── 5/25 1.8it/s 2.9s<11.3s

     71/200      2.28G     0.5555     0.4423       1.04         18        640: 24% ━━╸───────── 6/25 1.8it/s 3.4s<10.4s

     71/200      2.28G     0.5707     0.4479      1.029         23        640: 28% ━━━───────── 7/25 1.9it/s 4.0s<9.7s

     71/200      2.28G     0.5587     0.4473      1.015         30        640: 32% ━━━╸──────── 8/25 1.9it/s 4.4s<8.8s

     71/200      2.28G     0.5698     0.4441      1.003         42        640: 36% ━━━━──────── 9/25 1.7it/s 5.2s<9.1s

     71/200      2.28G     0.5634     0.4394     0.9918         24        640: 40% ━━━━╸─────── 10/25 1.8it/s 5.7s<8.2s

     71/200      2.28G     0.5524     0.4324     0.9879         14        640: 44% ━━━━━─────── 11/25 1.9it/s 6.2s<7.4s

     71/200      2.28G     0.5553     0.4338     0.9955         14        640: 48% ━━━━━╸────── 12/25 2.1it/s 6.5s<6.1s

     71/200      2.28G     0.5556     0.4339     0.9897         22        640: 52% ━━━━━━────── 13/25 2.3it/s 6.9s<5.2s

     71/200      2.28G     0.5576     0.4314     0.9842         32        640: 56% ━━━━━━╸───── 14/25 2.2it/s 7.4s<5.0s

     71/200      2.28G     0.5587     0.4382     0.9924          8        640: 60% ━━━━━━━───── 15/25 2.2it/s 7.9s<4.5s

     71/200      2.28G     0.5538      0.435     0.9846         41        640: 64% ━━━━━━━╸──── 16/25 2.4it/s 8.2s<3.8s

     71/200      2.28G     0.5647     0.4359      0.987         22        640: 68% ━━━━━━━━──── 17/25 2.5it/s 8.6s<3.2s

     71/200      2.28G      0.567      0.442     0.9946          8        640: 72% ━━━━━━━━╸─── 18/25 2.4it/s 9.1s<2.9s

     71/200      2.28G     0.5597     0.4421     0.9892         26        640: 76% ━━━━━━━━━─── 19/25 2.5it/s 9.4s<2.4s

     71/200      2.28G     0.5572     0.4415     0.9868         27        640: 80% ━━━━━━━━━╸── 20/25 2.4it/s 9.9s<2.1s

     71/200      2.23G     0.5572     0.4382     0.9878         23        640: 84% ━━━━━━━━━━── 21/25 2.2it/s 10.4s<1.8s

     71/200      2.28G     0.5551     0.4379     0.9943         16        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 10.9s<1.4s

     71/200      2.28G     0.5525     0.4368     0.9904         25        640: 92% ━━━━━━━━━━━─ 23/25 2.1it/s 11.4s<0.9s

     71/200      2.28G     0.5469     0.4348     0.9885          6        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 11.8s<0.4s

     71/200      2.28G     0.5469     0.4348     0.9885          6        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 11.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.7it/s 0.6s

                   all          8          8      0.821      0.712      0.796       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     72/200      2.27G     0.4658     0.3479      0.993         23        640: 0% ──────────── 0/25  0.5s

     72/200      2.27G     0.5305     0.3865     0.9514         20        640: 4% ──────────── 1/25 1.5s/it 1.0s<36.2s

     72/200      2.27G     0.5135     0.3814     0.9156         24        640: 8% ╸─────────── 2/25 1.1it/s 1.4s<20.8s

     72/200      2.27G      0.542     0.3914     0.9369         20        640: 12% ━─────────── 3/25 1.4it/s 1.9s<15.8s

     72/200      2.27G     0.5735     0.4138     0.9515         14        640: 16% ━╸────────── 4/25 1.6it/s 2.4s<13.0s

     72/200      2.27G     0.5732     0.4125     0.9607         22        640: 20% ━━────────── 5/25 1.8it/s 2.9s<11.4s

     72/200      2.27G      0.562     0.4042      0.954         16        640: 24% ━━╸───────── 6/25 1.9it/s 3.3s<10.0s

     72/200      2.27G     0.5546     0.4064     0.9752          9        640: 28% ━━━───────── 7/25 1.9it/s 3.8s<9.5s

     72/200      2.27G     0.5543     0.4086     0.9884         16        640: 32% ━━━╸──────── 8/25 1.9it/s 4.4s<8.9s

     72/200      2.27G     0.5571     0.4097      0.992         17        640: 36% ━━━━──────── 9/25 1.9it/s 4.8s<8.2s

     72/200      2.27G     0.5491     0.4086     0.9853         31        640: 40% ━━━━╸─────── 10/25 2.0it/s 5.3s<7.6s

     72/200      2.27G     0.5448     0.4073     0.9784         23        640: 44% ━━━━━─────── 11/25 2.0it/s 5.8s<7.0s

     72/200      2.27G     0.5411     0.4101      0.974         26        640: 48% ━━━━━╸────── 12/25 2.0it/s 6.3s<6.5s

     72/200      2.27G     0.5383     0.4095     0.9708         33        640: 52% ━━━━━━────── 13/25 2.2it/s 6.7s<5.4s

     72/200      2.22G      0.539     0.4077     0.9692         36        640: 56% ━━━━━━╸───── 14/25 2.2it/s 7.2s<5.0s

     72/200      2.21G     0.5424      0.416     0.9817          9        640: 60% ━━━━━━━───── 15/25 2.2it/s 7.7s<4.6s

     72/200      2.21G     0.5413     0.4211     0.9869         27        640: 64% ━━━━━━━╸──── 16/25 2.1it/s 8.2s<4.3s

     72/200      2.26G     0.5391     0.4246     0.9907         19        640: 68% ━━━━━━━━──── 17/25 2.1it/s 8.7s<3.8s

     72/200      2.26G     0.5398     0.4254     0.9883         24        640: 72% ━━━━━━━━╸─── 18/25 2.1it/s 9.2s<3.4s

     72/200      2.26G     0.5422     0.4239     0.9868         40        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 9.7s<3.0s

     72/200      2.26G     0.5425     0.4285     0.9891         19        640: 80% ━━━━━━━━━╸── 20/25 2.0it/s 10.2s<2.5s

     72/200      2.27G     0.5398      0.427     0.9891         16        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 10.7s<2.0s

     72/200      2.27G     0.5381     0.4262      0.985         38        640: 88% ━━━━━━━━━━╸─ 22/25 2.0it/s 11.2s<1.5s

     72/200      2.27G     0.5334     0.4255     0.9841         14        640: 92% ━━━━━━━━━━━─ 23/25 2.0it/s 11.7s<1.0s

     72/200      2.27G      0.543      0.425     0.9818         22        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 12.1s<0.5s

     72/200      2.27G      0.543      0.425     0.9818         22        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 12.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.5it/s 0.4s

                   all          8          8      0.914      0.723      0.796      0.604

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     73/200      2.25G     0.3951     0.3434     0.8546         25        640: 0% ──────────── 0/25  0.5s

     73/200      2.25G     0.4174     0.3956      0.915         19        640: 4% ──────────── 1/25 1.2s/it 0.9s<28.5s

     73/200      2.25G     0.4289     0.4078     0.9377         16        640: 8% ╸─────────── 2/25 1.2it/s 1.4s<19.2s

     73/200      2.25G     0.4521     0.4158      1.015          9        640: 12% ━─────────── 3/25 1.4it/s 1.9s<15.5s

     73/200      2.25G     0.4797     0.4101      1.012         22        640: 16% ━╸────────── 4/25 1.6it/s 2.4s<13.0s

     73/200      2.25G      0.481     0.4157      1.037          8        640: 20% ━━────────── 5/25 1.7it/s 2.9s<11.5s

     73/200      2.25G     0.4856     0.4125      1.014         34        640: 24% ━━╸───────── 6/25 1.6it/s 3.6s<11.8s

     73/200      2.24G     0.4902     0.4104          1         30        640: 28% ━━━───────── 7/25 1.8it/s 4.1s<10.2s

     73/200      2.24G     0.5006     0.4101     0.9995         24        640: 32% ━━━╸──────── 8/25 1.8it/s 4.6s<9.2s

     73/200      2.24G     0.4985     0.4097     0.9941         16        640: 36% ━━━━──────── 9/25 1.9it/s 5.1s<8.5s

     73/200      2.24G     0.5105     0.4095     0.9891         34        640: 40% ━━━━╸─────── 10/25 1.9it/s 5.6s<7.7s

     73/200      2.24G     0.5119     0.4087     0.9884         25        640: 44% ━━━━━─────── 11/25 2.0it/s 6.1s<7.1s

     73/200      2.22G     0.5195      0.408      0.988         24        640: 48% ━━━━━╸────── 12/25 2.0it/s 6.6s<6.5s

     73/200      2.27G     0.5327     0.4251      1.005         19        640: 52% ━━━━━━────── 13/25 2.0it/s 7.1s<6.0s

     73/200      2.27G     0.5432     0.4308      1.019         19        640: 56% ━━━━━━╸───── 14/25 2.0it/s 7.6s<5.5s

     73/200      2.27G     0.5339     0.4259       1.01         26        640: 60% ━━━━━━━───── 15/25 2.0it/s 8.0s<5.0s

     73/200      2.27G     0.5287     0.4228      1.005         17        640: 64% ━━━━━━━╸──── 16/25 2.0it/s 8.5s<4.5s

     73/200      2.27G     0.5291     0.4263      1.005         31        640: 68% ━━━━━━━━──── 17/25 2.0it/s 9.1s<4.0s

     73/200      2.27G     0.5447     0.4278      1.009         30        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.6s<3.5s

     73/200      2.27G     0.5461     0.4295      1.016         14        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 10.1s<3.0s

     73/200      2.27G     0.5401     0.4308      1.016         16        640: 80% ━━━━━━━━━╸── 20/25 2.0it/s 10.6s<2.5s

     73/200      2.27G     0.5456     0.4361      1.025          8        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 11.1s<2.0s

     73/200      2.27G     0.5437      0.434      1.019         35        640: 88% ━━━━━━━━━━╸─ 22/25 2.0it/s 11.5s<1.5s

     73/200      2.27G     0.5442     0.4341      1.016         33        640: 92% ━━━━━━━━━━━─ 23/25 2.0it/s 12.0s<1.0s

     73/200      2.28G      0.542     0.4315      1.013         24        640: 96% ━━━━━━━━━━━╸ 24/25 2.1it/s 12.5s<0.5s

     73/200      2.28G      0.542     0.4315      1.013         24        640: 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.9it/s 0.5s

                   all          8          8      0.712        0.8      0.763      0.484

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     74/200      2.27G      0.478     0.4653      1.065         15        640: 0% ──────────── 0/25  0.5s

     74/200      2.27G     0.5128     0.4518      1.075         16        640: 4% ──────────── 1/25 1.7s/it 1.0s<40.8s

     74/200      2.27G     0.5345      0.457      1.066         20        640: 8% ╸─────────── 2/25 1.0it/s 1.5s<22.3s

     74/200      2.27G     0.5387     0.4427       1.05         14        640: 12% ━─────────── 3/25 1.4it/s 2.0s<16.3s

     74/200      2.27G     0.5152     0.4289      1.025         14        640: 16% ━╸────────── 4/25 1.6it/s 2.5s<13.2s

     74/200      2.22G     0.5389     0.4335      1.039         22        640: 20% ━━────────── 5/25 1.7it/s 3.0s<12.0s

     74/200      2.22G     0.5392      0.433      1.021         24        640: 24% ━━╸───────── 6/25 1.6it/s 3.7s<11.9s

     74/200      2.23G     0.5236     0.4228      1.005         41        640: 28% ━━━───────── 7/25 1.7it/s 4.2s<10.5s

     74/200      2.28G     0.5281     0.4299          1         20        640: 32% ━━━╸──────── 8/25 1.8it/s 4.7s<9.4s

     74/200      2.23G     0.5389     0.4327      1.007          9        640: 36% ━━━━──────── 9/25 1.9it/s 5.2s<8.5s

     74/200      2.26G     0.5324     0.4284     0.9956         24        640: 40% ━━━━╸─────── 10/25 1.9it/s 5.7s<7.9s

     74/200      2.26G     0.5267     0.4245     0.9905         23        640: 44% ━━━━━─────── 11/25 1.9it/s 6.2s<7.3s

     74/200      2.26G     0.5154     0.4216     0.9806         22        640: 48% ━━━━━╸────── 12/25 2.0it/s 6.7s<6.6s

     74/200      2.26G     0.5236      0.425      0.987         20        640: 52% ━━━━━━────── 13/25 2.0it/s 7.2s<6.0s

     74/200      2.21G     0.5189     0.4247     0.9795         39        640: 56% ━━━━━━╸───── 14/25 2.0it/s 7.7s<5.5s

     74/200      2.21G     0.5106     0.4239      0.973         18        640: 60% ━━━━━━━───── 15/25 2.0it/s 8.2s<5.1s

     74/200      2.26G      0.511     0.4224     0.9743         24        640: 64% ━━━━━━━╸──── 16/25 2.0it/s 8.7s<4.6s

     74/200      2.26G     0.5148     0.4265     0.9718         38        640: 68% ━━━━━━━━──── 17/25 2.2it/s 9.1s<3.6s

     74/200      2.26G     0.5282     0.4273     0.9714         36        640: 72% ━━━━━━━━╸─── 18/25 2.2it/s 9.6s<3.2s

     74/200      2.24G     0.5235     0.4262     0.9722         20        640: 76% ━━━━━━━━━─── 19/25 2.1it/s 10.1s<2.9s

     74/200      2.26G     0.5256     0.4277     0.9713         25        640: 80% ━━━━━━━━━╸── 20/25 2.1it/s 10.6s<2.4s

     74/200      2.26G     0.5261     0.4258       0.97         34        640: 84% ━━━━━━━━━━── 21/25 1.8it/s 11.3s<2.2s

     74/200      2.26G     0.5216      0.424     0.9656         14        640: 88% ━━━━━━━━━━╸─ 22/25 1.9it/s 11.8s<1.6s

     74/200      2.22G     0.5193     0.4218     0.9634         14        640: 92% ━━━━━━━━━━━─ 23/25 1.9it/s 12.3s<1.0s

     74/200      2.22G     0.5183     0.4189     0.9595         12        640: 96% ━━━━━━━━━━━╸ 24/25 2.1it/s 12.7s<0.5s

     74/200      2.22G     0.5183     0.4189     0.9595         12        640: 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.4it/s 0.7s

                   all          8          8       0.73        0.8       0.73      0.544

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     75/200      2.26G      0.598     0.5732      1.106         25        640: 0% ──────────── 0/25  0.5s

     75/200      2.26G     0.4735     0.4904      1.039          9        640: 4% ──────────── 1/25 1.7s/it 1.0s<40.8s

     75/200      2.26G     0.4798     0.4908      1.018         19        640: 8% ╸─────────── 2/25 1.2s/it 1.7s<27.5s

     75/200      2.24G     0.5545     0.4742      1.003         30        640: 12% ━─────────── 3/25 1.2it/s 2.2s<18.7s

     75/200      2.24G     0.5536     0.4544     0.9843         30        640: 16% ━╸────────── 4/25 1.4it/s 2.7s<14.5s

     75/200      2.21G     0.5509     0.4505      1.031          8        640: 20% ━━────────── 5/25 1.6it/s 3.2s<12.4s

     75/200      2.26G     0.5691     0.4532      1.047         16        640: 24% ━━╸───────── 6/25 1.7it/s 3.7s<10.9s

     75/200      2.26G     0.5789     0.4486      1.044         22        640: 28% ━━━───────── 7/25 1.8it/s 4.2s<9.9s

     75/200      2.26G     0.5586     0.4358      1.025         22        640: 32% ━━━╸──────── 8/25 1.9it/s 4.7s<9.0s

     75/200      2.24G     0.5502      0.436      1.025          9        640: 36% ━━━━──────── 9/25 2.0it/s 5.2s<8.2s

     75/200      2.24G     0.5511     0.4297      1.013         36        640: 40% ━━━━╸─────── 10/25 2.0it/s 5.7s<7.7s

     75/200      2.24G     0.5531     0.4255      1.004         32        640: 44% ━━━━━─────── 11/25 2.0it/s 6.2s<7.1s

     75/200      2.24G     0.5517     0.4261     0.9937         27        640: 48% ━━━━━╸────── 12/25 2.0it/s 6.7s<6.5s

     75/200      2.24G     0.5447     0.4215     0.9833         24        640: 52% ━━━━━━────── 13/25 2.0it/s 7.1s<5.9s

     75/200      2.26G     0.5456     0.4248     0.9953         19        640: 56% ━━━━━━╸───── 14/25 2.0it/s 7.7s<5.5s

     75/200      2.25G      0.554     0.4281      1.006         20        640: 60% ━━━━━━━───── 15/25 2.0it/s 8.1s<4.9s

     75/200      2.25G     0.5503     0.4268      1.005         25        640: 64% ━━━━━━━╸──── 16/25 2.0it/s 8.6s<4.5s

     75/200      2.21G     0.5552     0.4274      1.004         39        640: 68% ━━━━━━━━──── 17/25 2.0it/s 9.1s<4.0s

     75/200      2.26G     0.5501     0.4239     0.9971         36        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.6s<3.5s

     75/200      2.26G     0.5482     0.4258     0.9953         25        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 10.1s<3.0s

     75/200      2.26G     0.5449     0.4245     0.9955         19        640: 80% ━━━━━━━━━╸── 20/25 2.0it/s 10.6s<2.4s

     75/200      2.26G     0.5426     0.4225     0.9913         17        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 11.1s<2.0s

     75/200      2.26G     0.5411     0.4247     0.9921         21        640: 88% ━━━━━━━━━━╸─ 22/25 2.0it/s 11.6s<1.5s

     75/200      2.26G     0.5468      0.426      1.004          8        640: 92% ━━━━━━━━━━━─ 23/25 2.0it/s 12.1s<1.0s

     75/200      2.27G     0.5478     0.4241      1.001         20        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 12.5s<0.5s

     75/200      2.27G     0.5478     0.4241      1.001         20        640: 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.3it/s 0.4s

                   all          8          8      0.774       0.71      0.743      0.561

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     76/200      2.25G     0.3473      0.419      1.042         10        640: 0% ──────────── 0/25  0.5s

     76/200      2.27G     0.4328     0.4403      1.061         20        640: 4% ──────────── 1/25 1.8s/it 1.1s<42.2s

     76/200      2.23G     0.5039     0.4229      1.003         36        640: 8% ╸─────────── 2/25 1.3s/it 1.9s<29.4s

     76/200      2.26G     0.4951     0.4153     0.9993         20        640: 12% ━─────────── 3/25 1.1it/s 2.4s<19.3s

     76/200      2.26G     0.4675     0.4039     0.9711         31        640: 16% ━╸────────── 4/25 1.4it/s 2.8s<14.7s

     76/200      2.26G     0.4573     0.3983     0.9531         33        640: 20% ━━────────── 5/25 1.6it/s 3.3s<12.5s

     76/200      2.26G     0.4672     0.4007     0.9735          8        640: 24% ━━╸───────── 6/25 1.7it/s 3.8s<11.0s

     76/200      2.26G     0.4709     0.4077     0.9822          8        640: 28% ━━━───────── 7/25 1.8it/s 4.3s<9.8s

     76/200      2.21G     0.4744     0.4084     0.9707         49        640: 32% ━━━╸──────── 8/25 1.7it/s 5.1s<10.3s

     76/200      2.26G     0.4777     0.4158     0.9765         19        640: 36% ━━━━──────── 9/25 1.8it/s 5.6s<9.0s

     76/200      2.23G     0.4836     0.4178     0.9691         28        640: 40% ━━━━╸─────── 10/25 1.8it/s 6.1s<8.2s

     76/200      2.28G     0.4855     0.4169     0.9831          9        640: 44% ━━━━━─────── 11/25 1.8it/s 6.7s<7.7s

     76/200      2.28G      0.495     0.4248     0.9852         31        640: 48% ━━━━━╸────── 12/25 1.9it/s 7.1s<6.8s

     76/200      2.28G     0.4917     0.4223     0.9783         37        640: 52% ━━━━━━────── 13/25 2.0it/s 7.6s<6.1s

     76/200      2.28G     0.5094      0.425     0.9817         14        640: 56% ━━━━━━╸───── 14/25 2.0it/s 8.1s<5.5s

     76/200      2.28G     0.5072     0.4247     0.9986          9        640: 60% ━━━━━━━───── 15/25 1.9it/s 8.7s<5.2s

     76/200      2.28G     0.5089     0.4258     0.9927         30        640: 64% ━━━━━━━╸──── 16/25 2.2it/s 9.0s<4.2s

     76/200      2.28G     0.5119      0.426     0.9972         22        640: 68% ━━━━━━━━──── 17/25 2.3it/s 9.4s<3.4s

     76/200      2.28G     0.5104     0.4221     0.9898         30        640: 72% ━━━━━━━━╸─── 18/25 2.2it/s 9.9s<3.1s

     76/200      2.28G     0.5048     0.4179     0.9856         16        640: 76% ━━━━━━━━━─── 19/25 2.2it/s 10.4s<2.7s

     76/200      2.28G     0.5085     0.4173     0.9872         16        640: 80% ━━━━━━━━━╸── 20/25 2.2it/s 10.8s<2.3s

     76/200      2.28G     0.5092     0.4174     0.9872         27        640: 84% ━━━━━━━━━━── 21/25 2.1it/s 11.3s<1.9s

     76/200      2.28G     0.5165     0.4163     0.9876         17        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 11.9s<1.5s

     76/200      2.28G     0.5197     0.4185     0.9896         15        640: 92% ━━━━━━━━━━━─ 23/25 2.0it/s 12.4s<1.0s

     76/200      2.28G     0.5154     0.4165     0.9842         23        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 12.8s<0.5s

     76/200      2.28G     0.5154     0.4165     0.9842         23        640: 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.3it/s 0.3s

                   all          8          8      0.739      0.711      0.748      0.574

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     77/200      2.23G      0.721     0.4444      1.055         31        640: 0% ──────────── 0/25  0.5s

     77/200      2.28G     0.6409     0.4741      1.111          8        640: 4% ──────────── 1/25 1.6s/it 1.0s<39.1s

     77/200      2.28G     0.6208      0.441       1.03         22        640: 8% ╸─────────── 2/25 1.1it/s 1.4s<21.9s

     77/200      2.28G     0.5791     0.4255     0.9914         28        640: 12% ━─────────── 3/25 1.4it/s 1.9s<15.8s

     77/200      2.21G     0.5603     0.4317      1.003         14        640: 16% ━╸────────── 4/25 1.6it/s 2.4s<13.3s

     77/200      2.26G     0.5455     0.4223     0.9901         39        640: 20% ━━────────── 5/25 1.7it/s 2.9s<11.6s

     77/200      2.26G     0.5447     0.4146     0.9866         22        640: 24% ━━╸───────── 6/25 1.8it/s 3.4s<10.6s

     77/200      2.26G     0.5358     0.4173      1.003          8        640: 28% ━━━───────── 7/25 1.9it/s 3.9s<9.7s

     77/200      2.26G     0.5287     0.4234     0.9987         38        640: 32% ━━━╸──────── 8/25 1.9it/s 4.4s<9.0s

     77/200      2.26G     0.5208     0.4289      1.001         19        640: 36% ━━━━──────── 9/25 1.9it/s 4.9s<8.3s

     77/200      2.26G     0.5123      0.427      1.001         20        640: 40% ━━━━╸─────── 10/25 1.9it/s 5.4s<7.7s

     77/200      2.26G     0.5163      0.428       1.02         10        640: 44% ━━━━━─────── 11/25 1.9it/s 5.9s<7.3s

     77/200      2.27G     0.5328     0.4284      1.028         16        640: 48% ━━━━━╸────── 12/25 2.1it/s 6.3s<6.2s

     77/200      2.22G     0.5384     0.4235      1.025         22        640: 52% ━━━━━━────── 13/25 2.1it/s 6.8s<5.8s

     77/200      2.23G     0.5307     0.4214      1.014         24        640: 56% ━━━━━━╸───── 14/25 2.1it/s 7.3s<5.3s

     77/200      2.27G     0.5232     0.4209      1.008         24        640: 60% ━━━━━━━───── 15/25 2.1it/s 7.8s<4.8s

     77/200      2.23G      0.516     0.4171      1.004         20        640: 64% ━━━━━━━╸──── 16/25 2.1it/s 8.3s<4.4s

     77/200      2.28G     0.5221     0.4159      1.003         29        640: 68% ━━━━━━━━──── 17/25 1.8it/s 9.0s<4.3s

     77/200      2.28G     0.5222     0.4171     0.9964         39        640: 72% ━━━━━━━━╸─── 18/25 1.9it/s 9.5s<3.7s

     77/200      2.28G     0.5255     0.4172      0.993         17        640: 76% ━━━━━━━━━─── 19/25 1.9it/s 10.0s<3.1s

     77/200      2.28G     0.5307     0.4156     0.9941         16        640: 80% ━━━━━━━━━╸── 20/25 2.0it/s 10.5s<2.6s

     77/200      2.28G      0.529     0.4161      0.993         27        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 11.0s<2.0s

     77/200      2.28G     0.5245     0.4161     0.9881         28        640: 88% ━━━━━━━━━━╸─ 22/25 2.0it/s 11.5s<1.5s

     77/200      2.28G     0.5264     0.4141     0.9862         30        640: 92% ━━━━━━━━━━━─ 23/25 2.2it/s 11.9s<0.9s

     77/200      2.27G     0.5238     0.4132     0.9927          7        640: 96% ━━━━━━━━━━━╸ 24/25 2.3it/s 12.3s<0.4s

     77/200      2.27G     0.5238     0.4132     0.9927          7        640: 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.6it/s 0.6s

                   all          8          8      0.885      0.719       0.78      0.592

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     78/200      2.33G     0.5289     0.3898      1.004         16        640: 0% ──────────── 0/25  0.7s

     78/200      2.33G     0.5039     0.3648     0.9461         22        640: 4% ──────────── 1/25 1.7s/it 1.2s<39.7s

     78/200      2.33G     0.5238     0.3915     0.9626         22        640: 8% ╸─────────── 2/25 1.0it/s 1.7s<22.6s

     78/200       2.3G      0.515     0.3929     0.9816         25        640: 12% ━─────────── 3/25 1.3it/s 2.2s<16.6s

     78/200      2.35G     0.5013     0.3927     0.9636         33        640: 16% ━╸────────── 4/25 1.5it/s 2.6s<13.6s

     78/200      2.35G     0.4986      0.392     0.9466         32        640: 20% ━━────────── 5/25 1.7it/s 3.2s<12.0s

     78/200      2.35G     0.5069     0.3899     0.9609         16        640: 24% ━━╸───────── 6/25 1.8it/s 3.7s<10.8s

     78/200      2.28G     0.5261     0.3905     0.9676         16        640: 28% ━━━───────── 7/25 2.1it/s 4.0s<8.6s

     78/200      2.28G     0.5158     0.3891     0.9613         27        640: 32% ━━━╸──────── 8/25 2.1it/s 4.5s<8.1s

     78/200      2.29G     0.5142     0.3931     0.9677         20        640: 36% ━━━━──────── 9/25 2.1it/s 5.0s<7.7s

     78/200      2.34G     0.5224     0.3997      0.988         10        640: 40% ━━━━╸─────── 10/25 2.0it/s 5.5s<7.4s

     78/200      2.34G     0.5365     0.4011     0.9868         35        640: 44% ━━━━━─────── 11/25 2.0it/s 6.0s<7.0s

     78/200      2.34G     0.5368     0.3992     0.9845         24        640: 48% ━━━━━╸────── 12/25 2.0it/s 6.5s<6.5s

     78/200      2.34G     0.5311     0.4014     0.9846         30        640: 52% ━━━━━━────── 13/25 2.2it/s 6.9s<5.4s

     78/200      2.34G      0.521     0.3973     0.9785         20        640: 56% ━━━━━━╸───── 14/25 2.2it/s 7.4s<5.0s

     78/200      2.34G     0.5263     0.4024     0.9743         45        640: 60% ━━━━━━━───── 15/25 2.1it/s 7.9s<4.8s

     78/200      2.34G     0.5307     0.4008     0.9781         14        640: 64% ━━━━━━━╸──── 16/25 2.3it/s 8.2s<3.9s

     78/200      2.34G     0.5255     0.3994     0.9788          9        640: 68% ━━━━━━━━──── 17/25 2.2it/s 8.8s<3.7s

     78/200      2.28G     0.5334     0.4034     0.9791         24        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.4s<3.5s

     78/200      2.33G     0.5336     0.4001     0.9773         22        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 9.9s<3.0s

     78/200      2.33G     0.5336     0.4015     0.9744         30        640: 80% ━━━━━━━━━╸── 20/25 2.0it/s 10.4s<2.5s

     78/200      2.28G     0.5352     0.4036     0.9757         28        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 10.9s<2.0s

     78/200      2.33G     0.5323     0.4036     0.9751         14        640: 88% ━━━━━━━━━━╸─ 22/25 2.0it/s 11.4s<1.5s

     78/200      2.33G     0.5341     0.4026     0.9782         17        640: 92% ━━━━━━━━━━━─ 23/25 2.0it/s 11.9s<1.0s

     78/200      2.33G      0.525     0.4014     0.9798          7        640: 96% ━━━━━━━━━━━╸ 24/25 2.1it/s 12.3s<0.5s

     78/200      2.33G      0.525     0.4014     0.9798          7        640: 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.5it/s 0.7s

                   all          8          8      0.776        0.8       0.78      0.595

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     79/200      2.27G     0.5916     0.3988     0.9815         22        640: 0% ──────────── 0/25  0.5s

     79/200      2.27G     0.5754     0.4308      1.134         25        640: 4% ──────────── 1/25 1.8s/it 1.0s<42.1s

     79/200      2.27G     0.5665     0.4051      1.079         22        640: 8% ╸─────────── 2/25 1.3it/s 1.4s<18.2s

     79/200      2.27G     0.5653     0.4214      1.069         25        640: 12% ━─────────── 3/25 1.5it/s 1.9s<14.8s

     79/200      2.27G       0.57     0.4366      1.048         27        640: 16% ━╸────────── 4/25 1.6it/s 2.4s<12.8s

     79/200      2.27G     0.5588     0.4213      1.038         16        640: 20% ━━────────── 5/25 1.8it/s 2.8s<11.2s

     79/200      2.27G     0.5562     0.4126      1.019         27        640: 24% ━━╸───────── 6/25 1.9it/s 3.3s<10.3s

     79/200      2.27G     0.5444     0.4037      1.019         16        640: 28% ━━━───────── 7/25 1.9it/s 3.9s<9.6s

     79/200      2.26G     0.5303      0.397      1.008         24        640: 32% ━━━╸──────── 8/25 1.9it/s 4.4s<9.2s

     79/200      2.26G     0.5419     0.3993      1.018         22        640: 36% ━━━━──────── 9/25 1.9it/s 4.9s<8.5s

     79/200      2.21G     0.5322     0.3984      1.022          9        640: 40% ━━━━╸─────── 10/25 1.9it/s 5.4s<7.9s

     79/200      2.22G     0.5525     0.4043      1.018         40        640: 44% ━━━━━─────── 11/25 1.9it/s 5.9s<7.2s

     79/200      2.23G     0.5395     0.3997      1.008         16        640: 48% ━━━━━╸────── 12/25 2.0it/s 6.4s<6.6s

     79/200      2.27G     0.5394     0.3983      1.005         16        640: 52% ━━━━━━────── 13/25 2.3it/s 6.8s<5.3s

     79/200      2.27G     0.5362     0.4002      0.997         22        640: 56% ━━━━━━╸───── 14/25 2.2it/s 7.3s<5.1s

     79/200      2.23G     0.5464     0.4006     0.9952         24        640: 60% ━━━━━━━───── 15/25 2.1it/s 7.8s<4.7s

     79/200      2.21G     0.5453     0.4021      0.993         19        640: 64% ━━━━━━━╸──── 16/25 2.1it/s 8.3s<4.3s

     79/200      2.27G     0.5413     0.4014     0.9919         20        640: 68% ━━━━━━━━──── 17/25 2.0it/s 8.8s<3.9s

     79/200      2.27G     0.5349     0.4001      0.985         39        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.3s<3.5s

     79/200      2.27G     0.5415     0.3989     0.9821         39        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 9.8s<2.9s

     79/200      2.27G     0.5435     0.3979      0.981         25        640: 80% ━━━━━━━━━╸── 20/25 2.0it/s 10.3s<2.5s

     79/200      2.27G     0.5424     0.3986     0.9833         21        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 10.8s<2.0s

     79/200      2.27G     0.5455     0.4031     0.9907          8        640: 88% ━━━━━━━━━━╸─ 22/25 2.0it/s 11.3s<1.5s

     79/200      2.27G     0.5501     0.4038     0.9943         22        640: 92% ━━━━━━━━━━━─ 23/25 2.0it/s 11.8s<1.0s

     79/200      2.27G      0.549     0.4021     0.9961         12        640: 96% ━━━━━━━━━━━╸ 24/25 2.4it/s 12.1s<0.4s

     79/200      2.27G      0.549     0.4021     0.9961         12        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 12.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.5it/s 0.4s

                   all          8          8      0.749        0.8       0.77      0.562

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     80/200      2.27G     0.4573     0.3464     0.8889         22        640: 0% ──────────── 0/25  0.5s

     80/200      2.27G     0.4212      0.345     0.9389          8        640: 4% ──────────── 1/25 1.6s/it 1.0s<38.6s

     80/200      2.23G     0.4043     0.3743     0.9271         20        640: 8% ╸─────────── 2/25 1.0it/s 1.5s<22.9s

     80/200      2.27G     0.4512     0.3753     0.9393         20        640: 12% ━─────────── 3/25 1.3it/s 2.0s<16.7s

     80/200      2.27G     0.4563     0.3846     0.9566          8        640: 16% ━╸────────── 4/25 1.9it/s 2.3s<11.2s

     80/200      2.27G      0.454     0.3765     0.9578         17        640: 20% ━━────────── 5/25 1.9it/s 2.9s<10.6s

     80/200      2.27G     0.4682     0.3756     0.9457         37        640: 24% ━━╸───────── 6/25 1.9it/s 3.4s<10.0s

     80/200      2.27G     0.4744     0.3797     0.9663         14        640: 28% ━━━───────── 7/25 1.9it/s 3.9s<9.2s

     80/200      2.27G     0.4741     0.3824     0.9766         16        640: 32% ━━━╸──────── 8/25 1.9it/s 4.4s<8.8s

     80/200      2.27G     0.4831     0.3878     0.9862          9        640: 36% ━━━━──────── 9/25 2.0it/s 4.9s<8.2s

     80/200      2.21G     0.4858     0.3873     0.9784         29        640: 40% ━━━━╸─────── 10/25 1.9it/s 5.4s<7.7s

     80/200      2.26G     0.5098     0.3885     0.9931         22        640: 44% ━━━━━─────── 11/25 1.9it/s 5.9s<7.3s

     80/200      2.26G     0.5104     0.3856     0.9844         24        640: 48% ━━━━━╸────── 12/25 2.0it/s 6.4s<6.6s

     80/200      2.26G     0.5148     0.3857     0.9802         22        640: 52% ━━━━━━────── 13/25 2.0it/s 6.9s<6.0s

     80/200      2.26G      0.521     0.3872      0.983         24        640: 56% ━━━━━━╸───── 14/25 2.0it/s 7.4s<5.6s

     80/200      2.26G      0.514     0.3842     0.9743         27        640: 60% ━━━━━━━───── 15/25 2.0it/s 7.9s<5.0s

     80/200      2.27G     0.5238     0.3878     0.9867         14        640: 64% ━━━━━━━╸──── 16/25 2.0it/s 8.4s<4.5s

     80/200      2.27G     0.5319     0.3878     0.9876         17        640: 68% ━━━━━━━━──── 17/25 2.0it/s 8.9s<4.0s

     80/200      2.27G     0.5316     0.4004     0.9851         56        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.4s<3.4s

     80/200      2.27G     0.5304     0.4014     0.9919          8        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 9.9s<2.9s

     80/200      2.27G     0.5295     0.4003      0.993         16        640: 80% ━━━━━━━━━╸── 20/25 2.0it/s 10.4s<2.5s

     80/200      2.27G     0.5205     0.3978     0.9879         26        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 10.9s<2.0s

     80/200      2.27G     0.5156     0.3967      0.982         27        640: 88% ━━━━━━━━━━╸─ 22/25 2.2it/s 11.3s<1.4s

     80/200      2.27G      0.514     0.3962     0.9782         52        640: 92% ━━━━━━━━━━━─ 23/25 2.1it/s 11.8s<0.9s

     80/200      2.27G     0.5121     0.3965     0.9795         23        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 12.2s<0.5s

     80/200      2.27G     0.5121     0.3965     0.9795         23        640: 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.1it/s 0.3s

                   all          8          8      0.675        0.8       0.78      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     81/200      2.27G     0.4512     0.4228      1.053          8        640: 0% ──────────── 0/25  0.5s

     81/200      2.27G     0.5385     0.4811       1.04         24        640: 4% ──────────── 1/25 1.8s/it 1.0s<44.3s

     81/200      2.22G     0.5578     0.4569      1.069         17        640: 8% ╸─────────── 2/25 1.1s/it 1.6s<24.5s

     81/200      2.26G     0.5077     0.4397      1.067          9        640: 12% ━─────────── 3/25 1.3it/s 2.1s<17.5s

     81/200      2.21G     0.4884     0.4279      1.026         39        640: 16% ━╸────────── 4/25 1.7it/s 2.4s<12.1s

     81/200      2.27G     0.5228     0.4289      1.006         49        640: 20% ━━────────── 5/25 1.8it/s 2.9s<11.0s

     81/200      2.27G     0.5098      0.435      1.013         19        640: 24% ━━╸───────── 6/25 1.9it/s 3.4s<10.2s

     81/200      2.27G     0.5191     0.4298      1.006         20        640: 28% ━━━───────── 7/25 1.9it/s 3.9s<9.4s

     81/200      2.27G     0.5349     0.4307      1.022          8        640: 32% ━━━╸──────── 8/25 2.2it/s 4.3s<7.7s

     81/200      2.27G     0.5307     0.4271      1.017         14        640: 36% ━━━━──────── 9/25 2.2it/s 4.8s<7.4s

     81/200      2.27G     0.5224     0.4204      1.008         28        640: 40% ━━━━╸─────── 10/25 2.3it/s 5.1s<6.5s

     81/200      2.27G     0.5498      0.419      1.014         25        640: 44% ━━━━━─────── 11/25 2.2it/s 5.7s<6.4s

     81/200      2.27G     0.5461     0.4128      1.012         22        640: 48% ━━━━━╸────── 12/25 2.1it/s 6.2s<6.1s

     81/200      2.27G     0.5422     0.4243      1.002         47        640: 52% ━━━━━━────── 13/25 2.1it/s 6.7s<5.8s

     81/200      2.27G     0.5349     0.4198     0.9978         14        640: 56% ━━━━━━╸───── 14/25 2.3it/s 7.0s<4.8s

     81/200      2.27G     0.5486     0.4191     0.9966         22        640: 60% ━━━━━━━───── 15/25 2.2it/s 7.5s<4.5s

     81/200      2.27G     0.5483     0.4215      0.994         28        640: 64% ━━━━━━━╸──── 16/25 2.1it/s 8.0s<4.2s

     81/200      2.27G     0.5591     0.4286     0.9979         25        640: 68% ━━━━━━━━──── 17/25 2.1it/s 8.6s<3.8s

     81/200      2.27G     0.5509     0.4259     0.9963         19        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.1s<3.4s

     81/200      2.27G     0.5585     0.4246     0.9949         28        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 9.6s<2.9s

     81/200      2.27G     0.5583     0.4216     0.9953         22        640: 80% ━━━━━━━━━╸── 20/25 2.1it/s 10.0s<2.4s

     81/200      2.23G      0.564     0.4213     0.9943         28        640: 84% ━━━━━━━━━━── 21/25 2.1it/s 10.5s<1.9s

     81/200      2.28G     0.5656     0.4222      1.002          8        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 11.0s<1.5s

     81/200      2.27G     0.5622     0.4214      1.003         21        640: 92% ━━━━━━━━━━━─ 23/25 2.0it/s 11.5s<1.0s

     81/200      2.27G      0.562     0.4211      1.009         14        640: 96% ━━━━━━━━━━━╸ 24/25 2.1it/s 12.0s<0.5s

     81/200      2.27G      0.562     0.4211      1.009         14        640: 100% ━━━━━━━━━━━━ 25/25 2.1it/s 12.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.2it/s 0.4s

                   all          8          8      0.763        0.8      0.768      0.581

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     82/200      2.26G     0.3857     0.3603     0.9404         21        640: 0% ──────────── 0/25  0.5s

     82/200      2.26G      0.381     0.3393     0.9002         22        640: 4% ──────────── 1/25 1.2s/it 0.9s<28.3s

     82/200      2.26G     0.4056     0.3626     0.8846         31        640: 8% ╸─────────── 2/25 1.2it/s 1.3s<18.8s

     82/200      2.26G     0.4299     0.3621     0.8801         57        640: 12% ━─────────── 3/25 1.5it/s 1.8s<14.8s

     82/200      2.26G      0.433     0.3679     0.8837         14        640: 16% ━╸────────── 4/25 1.7it/s 2.3s<12.7s

     82/200      2.26G     0.4386     0.3691     0.8883         16        640: 20% ━━────────── 5/25 1.8it/s 2.8s<11.1s

     82/200      2.26G      0.435     0.3628     0.9007         17        640: 24% ━━╸───────── 6/25 1.9it/s 3.3s<10.2s

     82/200      2.26G     0.4747     0.3665     0.9176         16        640: 28% ━━━───────── 7/25 1.9it/s 3.8s<9.5s

     82/200      2.26G     0.4752     0.3651     0.9101         31        640: 32% ━━━╸──────── 8/25 1.9it/s 4.3s<8.8s

     82/200      2.26G     0.4697     0.3646     0.9117         17        640: 36% ━━━━──────── 9/25 2.1it/s 4.7s<7.6s

     82/200      2.21G     0.4797     0.3679      0.923         23        640: 40% ━━━━╸─────── 10/25 2.1it/s 5.2s<7.3s

     82/200      2.26G     0.4852     0.3744     0.9338         25        640: 44% ━━━━━─────── 11/25 2.0it/s 5.7s<6.9s

     82/200      2.26G     0.5034     0.3806     0.9415         25        640: 48% ━━━━━╸────── 12/25 2.0it/s 6.2s<6.4s

     82/200      2.22G     0.5053     0.3804     0.9467         15        640: 52% ━━━━━━────── 13/25 2.0it/s 6.7s<6.0s

     82/200      2.27G      0.523      0.391     0.9749          8        640: 56% ━━━━━━╸───── 14/25 2.0it/s 7.2s<5.5s

     82/200      2.21G     0.5241     0.3897     0.9689         29        640: 60% ━━━━━━━───── 15/25 2.0it/s 7.7s<5.0s

     82/200      2.26G     0.5205     0.3892     0.9644         30        640: 64% ━━━━━━━╸──── 16/25 2.0it/s 8.2s<4.6s

     82/200      2.26G     0.5191     0.3909     0.9718         19        640: 68% ━━━━━━━━──── 17/25 2.0it/s 8.7s<4.1s

     82/200      2.27G     0.5195     0.3905     0.9759         14        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 9.2s<3.6s

     82/200      2.21G     0.5206     0.3903     0.9736         22        640: 76% ━━━━━━━━━─── 19/25 1.9it/s 9.8s<3.1s

     82/200      2.26G     0.5143     0.3918     0.9715         19        640: 80% ━━━━━━━━━╸── 20/25 1.9it/s 10.3s<2.6s

     82/200      2.27G     0.5156     0.3901     0.9705         15        640: 84% ━━━━━━━━━━── 21/25 2.0it/s 10.8s<2.0s

     82/200      2.27G     0.5156      0.389     0.9711         15        640: 88% ━━━━━━━━━━╸─ 22/25 2.0it/s 11.3s<1.5s

     82/200      2.27G     0.5189     0.3903     0.9695         32        640: 92% ━━━━━━━━━━━─ 23/25 2.0it/s 11.8s<1.0s

     82/200      2.27G     0.5192     0.3893     0.9667         25        640: 96% ━━━━━━━━━━━╸ 24/25 2.1it/s 12.2s<0.5s

     82/200      2.27G     0.5192     0.3893     0.9667         25        640: 100% ━━━━━━━━━━━━ 25/25 2.0it/s 12.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.2it/s 0.8s

                   all          8          8      0.775        0.8      0.763       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     83/200      2.27G     0.4512     0.3897     0.9849          8        640: 0% ──────────── 0/25  0.5s

     83/200      2.27G     0.5332     0.3837       1.03         15        640: 4% ──────────── 1/25 1.7s/it 1.0s<39.7s

     83/200      2.27G     0.4969     0.3922      1.027          9        640: 8% ╸─────────── 2/25 1.0it/s 1.5s<22.2s

     83/200      2.27G     0.4844     0.4006     0.9856         33        640: 12% ━─────────── 3/25 1.3it/s 2.0s<16.4s

     83/200      2.27G     0.4827     0.4213     0.9871         19        640: 16% ━╸────────── 4/25 1.5it/s 2.5s<13.6s

     83/200      2.27G     0.5328     0.4178      1.003         24        640: 20% ━━────────── 5/25 1.7it/s 3.0s<12.1s

     83/200      2.22G     0.5262     0.4108      1.006         17        640: 24% ━━╸───────── 6/25 1.5it/s 3.8s<12.3s

     83/200      2.23G     0.5199     0.4023      1.002         22        640: 28% ━━━───────── 7/25 1.6it/s 4.3s<10.9s

     83/200      2.22G     0.5092     0.3981     0.9859         47        640: 32% ━━━╸──────── 8/25 1.5it/s 5.1s<11.2s

     83/200      2.25G     0.5089     0.3945      1.002          8        640: 36% ━━━━──────── 9/25 1.7it/s 5.6s<9.7s

     83/200      2.25G       0.51     0.3965      1.006         16        640: 40% ━━━━╸─────── 10/25 1.7it/s 6.1s<8.6s

     83/200      2.27G     0.5108      0.403     0.9972         32        640: 44% ━━━━━─────── 11/25 1.8it/s 6.7s<7.8s

     83/200      2.27G     0.5085     0.3996     0.9908         29        640: 48% ━━━━━╸────── 12/25 1.8it/s 7.2s<7.1s

     83/200      2.27G     0.5197     0.3998     0.9977         16        640: 52% ━━━━━━────── 13/25 1.9it/s 7.7s<6.4s

     83/200      2.27G      0.528     0.3987     0.9988         34        640: 56% ━━━━━━╸───── 14/25 1.9it/s 8.2s<5.9s

     83/200      2.27G     0.5343     0.3974     0.9949         28        640: 60% ━━━━━━━───── 15/25 1.9it/s 8.7s<5.2s

     83/200      2.23G     0.5411     0.4003     0.9913         28        640: 64% ━━━━━━━╸──── 16/25 1.9it/s 9.2s<4.6s

     83/200      2.27G     0.5389     0.3978      0.986         20        640: 68% ━━━━━━━━──── 17/25 2.0it/s 9.7s<4.0s

     83/200      2.27G     0.5412     0.4025     0.9965          8        640: 72% ━━━━━━━━╸─── 18/25 2.0it/s 10.2s<3.5s

     83/200      2.27G     0.5389     0.4033      0.994         37        640: 76% ━━━━━━━━━─── 19/25 2.0it/s 10.7s<3.0s

     83/200      2.27G     0.5362     0.4029     0.9956         20        640: 80% ━━━━━━━━━╸── 20/25 2.2it/s 11.1s<2.3s

     83/200      2.27G     0.5317     0.4001     0.9881         27        640: 84% ━━━━━━━━━━── 21/25 2.2it/s 11.6s<1.9s

     83/200      2.27G      0.531     0.4026     0.9903         20        640: 88% ━━━━━━━━━━╸─ 22/25 2.1it/s 12.1s<1.4s

     83/200      2.23G      0.536     0.4021     0.9881         35        640: 92% ━━━━━━━━━━━─ 23/25 2.1it/s 12.6s<1.0s

     83/200      2.22G     0.5411     0.4026      0.994          6        640: 96% ━━━━━━━━━━━╸ 24/25 2.2it/s 13.0s<0.5s

     83/200      2.22G     0.5411     0.4026      0.994          6        640: 100% ━━━━━━━━━━━━ 25/25 1.9it/s 13.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.1s/it 1.1s

                   all          8          8      0.707        0.8      0.763       0.57

EarlyStopping: Training stopped early as no improvement observed in last 50 epochs. Best results observed at epoch 33, best model saved as best.pt.
To update EarlyStopping(patience=50) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

83 epochs completed in 0.293 hours.

Optimizer stripped from /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/detect/coins_v4/weights/last.pt, 6.3MB

Optimizer stripped from /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/detect/coins_v4/weights/best.pt, 6.3MB

Validating /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/detect/coins_v4/weights/best.pt...

Ultralytics 8.4.47 🚀 Python-3.12.7 torch-2.11.0 MPS (Apple M3 Pro)

Model summary (fused): 73 layers, 3,006,623 parameters, 0 gradients, 8.1 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.6s/it 2.6s

                   all          8          8      0.788        0.8      0.969      0.763

                   100          3          3      0.544          1      0.863      0.757

                  1000          1          1      0.656          1      0.995      0.796

                   200          1          1          1          0      0.995      0.796

                    50          1          1      0.942          1      0.995      0.796

                   500          2          2      0.798          1      0.995      0.671

Speed: 0.2ms preprocess, 101.0ms inference, 0.0ms loss, 132.6ms postprocess per image

Results saved to /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/detect/coins_v4

Entrenamiento finalizado.

## 2. Persistencia del mejor checkpoint en `model/`

In [3]:
best_pt = RUNS_DIR / "detect" / RUN_NAME / "weights" / "best.pt"
last_pt = RUNS_DIR / "detect" / RUN_NAME / "weights" / "last.pt"
assert best_pt.exists(), f"No se encontró {best_pt}"
shutil.copy2(best_pt, MODEL_DIR / "best.pt")
if last_pt.exists():
    shutil.copy2(last_pt, MODEL_DIR / "last.pt")
print("Pesos copiados a:", MODEL_DIR)
for p in sorted(MODEL_DIR.iterdir()):
    print("  -", p.name, f"({p.stat().st_size / 1024:.0f} KB)")

Pesos copiados a: /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/model
  - best.pt (6109 KB)
  - last.pt (6109 KB)

## 3. Métricas finales sobre VALID y TEST

In [4]:
best_model = YOLO(str(MODEL_DIR / "best.pt"))

def metrics_to_row(m, split_name):
    return {
        "split": split_name,
        "precision": float(m.box.mp),
        "recall":    float(m.box.mr),
        "mAP@0.5":   float(m.box.map50),
        "mAP@0.5:0.95": float(m.box.map),
    }

val_metrics = best_model.val(data=str(DATA_YAML), split="val",  device=DEVICE,
                              project=str(RUNS_DIR / "detect"), name=f"{RUN_NAME}_val",  exist_ok=True, plots=True)
test_metrics = best_model.val(data=str(DATA_YAML), split="test", device=DEVICE,
                              project=str(RUNS_DIR / "detect"), name=f"{RUN_NAME}_test", exist_ok=True, plots=True)

df_metrics = pd.DataFrame([metrics_to_row(val_metrics, "valid"),
                            metrics_to_row(test_metrics, "test")]).set_index("split")
df_metrics.to_csv(REPORTS / "metrics_summary.csv")
df_metrics.round(4)

Ultralytics 8.4.47 🚀 Python-3.12.7 torch-2.11.0 MPS (Apple M3 Pro)

Model summary (fused): 73 layers, 3,006,623 parameters, 0 gradients, 8.1 GFLOPs

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1536.3±277.0 MB/s, size: 38.1 KB)

val: Scanning /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_split/valid/labels.cache... 8 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 8/8 11.2Mit/s 0.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.1it/s 0.1s

                   all          8          8      0.788        0.8      0.969      0.763

                   100          3          3      0.544          1      0.863      0.757

                  1000          1          1      0.656          1      0.995      0.796

                   200          1          1          1          0      0.995      0.796

                    50          1          1      0.942          1      0.995      0.796

                   500          2          2      0.798          1      0.995      0.671

Speed: 0.2ms preprocess, 6.1ms inference, 0.0ms loss, 2.3ms postprocess per image

Results saved to /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/detect/coins_v4_val

Ultralytics 8.4.47 🚀 Python-3.12.7 torch-2.11.0 MPS (Apple M3 Pro)

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 165.1±44.0 MB/s, size: 38.1 KB)

val: Scanning /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_split/test/labels... 8 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 8/8 4.7Kit/s 0.0s

val: New cache created: /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_split/test/labels.cache

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.3it/s 0.7s

                   all          8          8      0.647      0.661      0.886      0.624

                   100          1          1      0.231          1      0.995      0.796

                  1000          1          1      0.525          1      0.995      0.796

                   200          2          2          1          0      0.995      0.447

                    50          2          2       0.48       0.48      0.448      0.333

                   500          2          2          1      0.823      0.995      0.745

Speed: 0.2ms preprocess, 4.7ms inference, 0.0ms loss, 79.2ms postprocess per image

Results saved to /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/detect/coins_v4_test

       precision  recall  mAP@0.5  mAP@0.5:0.95
split
valid     0.7880  0.8000   0.9686        0.7632
test      0.6474  0.6607   0.8855        0.6235

## 4. Métricas por clase (sobre VALID)

In [5]:
names = best_model.names
p_cls = val_metrics.box.p
r_cls = val_metrics.box.r
ap50 = val_metrics.box.ap50
ap   = val_metrics.box.ap.mean(axis=1) if val_metrics.box.ap.ndim > 1 else val_metrics.box.ap
ids  = val_metrics.box.ap_class_index

df_cls = pd.DataFrame({
    "class": [names[int(i)] for i in ids],
    "precision": np.round(p_cls, 4),
    "recall":    np.round(r_cls, 4),
    "mAP@0.5":   np.round(ap50, 4),
    "mAP@0.5:0.95": np.round(ap, 4),
})
df_cls.to_csv(REPORTS / "metrics_per_class_valid.csv", index=False)
df_cls

  class  precision  recall  mAP@0.5  mAP@0.5:0.95
0   100     0.5435     1.0    0.863        0.7569
1  1000     0.6560     1.0    0.995        0.7960
2   200     1.0000     0.0    0.995        0.7960
3    50     0.9420     1.0    0.995        0.7960
4   500     0.7985     1.0    0.995        0.6712

## 5. Inferencia de ejemplo sobre el split TEST

Tomamos hasta 8 imágenes de test y mostramos detecciones con desglose monetario (sumatoria de denominaciones).

In [6]:
import yaml
with open(DATA_YAML) as f:
    cfg = yaml.safe_load(f)
_names = cfg["names"]
if isinstance(_names, dict):
    _names = [_names[i] for i in sorted(_names)]
VALUE_COP = {i: (int(n) if str(n).isdigit() else 0) for i, n in enumerate(_names)}

test_dir = ROOT / "dataset_split" / "test" / "images"
test_imgs = sorted(test_dir.iterdir())[:8]
n = len(test_imgs)
cols = 2
rows = (n + cols - 1) // cols
fig, axes = plt.subplots(rows, cols, figsize=(12, 5 * rows))
axes = np.array(axes).reshape(-1)
for ax, img_path in zip(axes, test_imgs):
    pred = best_model.predict(source=str(img_path), conf=0.25, device=DEVICE, verbose=False)[0]
    counts = {}
    total_cop = 0
    for cls_id in pred.boxes.cls.cpu().numpy().astype(int):
        nm = pred.names[int(cls_id)]
        counts[nm] = counts.get(nm, 0) + 1
        total_cop += VALUE_COP.get(int(cls_id), 0)
    annotated = pred.plot()
    ax.imshow(annotated[:, :, ::-1])
    summary = " · ".join(f"{k}: {v}" for k, v in sorted(counts.items())) or "(sin detecciones)"
    ax.set_title(f"{img_path.name[:30]}\n{summary}\nTOTAL = {total_cop} COP", fontsize=9)
    ax.axis("off")
for ax in axes[n:]:
    ax.axis("off")
plt.tight_layout()
plt.savefig(REPORTS / "test_inference.png", dpi=120)
plt.show()

## 6. Resumen ejecutivo

Las celdas anteriores generaron:
- `model/best.pt` — pesos finales del modelo (axis-aligned bboxes, 5 clases).
- `reports/metrics_summary.csv` y `reports/metrics_per_class_valid.csv`.
- `reports/test_inference.png` con predicciones de ejemplo.
- `runs/detect/coins_v4/` con curvas de pérdida, matriz de confusión, etc.

Próxima fase: exportar `best.pt` a un formato apto para inferencia móvil (ONNX o TFLite) y arrancar la app Ionic + React + Capacitor.