# v2 · Fase 2 · paso 2 — Entrenamiento YOLOv8

## Configuración

| Parámetro | Valor | Razón |
|-----------|-------|-------|
| Modelo | `yolov8n.pt` (~6 MB) | Tamaño mínimo, mejor para móvil. |
| `imgsz` | **416** | ≈2× más rápido que 640 en móvil; pérdida marginal de mAP. |
| Épocas | 200 | Suficiente con `patience=50` para early stopping. |
| `patience` | 50 | Lecciones v1: dataset chico requiere paciencia alta. |
| `batch` | 8 | Estable en MPS sin saturar memoria. |
| Augmentations | Conservadoras | Sin mosaic ni mixup (lección v1). |
| Device | MPS (auto) | Apple Silicon con `PYTORCH_ENABLE_MPS_FALLBACK=1`. |

## Salidas
- `runs/v2/coins_v2/` — pesos, métricas, gráficos.
- `model/v2/best.pt` — mejor checkpoint para exportar.
- `reports/v2/metrics_*.csv` — tablas resumen.

In [1]:
from __future__ import annotations
import os
os.environ.setdefault("PYTORCH_ENABLE_MPS_FALLBACK", "1")

import shutil
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import torch
from ultralytics import YOLO

ROOT = Path.cwd()
while ROOT.name and not (ROOT / "dataset_v2").exists():
    ROOT = ROOT.parent
DATA_YAML = ROOT / "dataset_v2" / "data_train.yaml"
MODEL_DIR = ROOT / "model" / "v2"; MODEL_DIR.mkdir(parents=True, exist_ok=True)
REPORTS = ROOT / "reports" / "v2"; REPORTS.mkdir(parents=True, exist_ok=True)
RUNS_DIR = ROOT / "runs" / "v2"
RUN_NAME = "coins_v2"
IMG_SIZE = 416

DEVICE = "mps" if torch.backends.mps.is_available() else ("cuda" if torch.cuda.is_available() else "cpu")
print(f"DATA   = {DATA_YAML}")
print(f"DEVICE = {DEVICE}")
print(f"RUN    = {RUNS_DIR / 'detect' / RUN_NAME}")
print(f"IMGSZ  = {IMG_SIZE}")

DATA   = /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_v2/data_train.yaml
DEVICE = mps
RUN    = /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/v2/detect/coins_v2
IMGSZ  = 416

## 1. Entrenamiento

In [2]:
prev = RUNS_DIR / "detect" / RUN_NAME
if prev.exists():
    shutil.rmtree(prev)

model = YOLO("yolov8n.pt")
results = model.train(
    data=str(DATA_YAML),
    epochs=200,
    patience=50,
    imgsz=IMG_SIZE,
    batch=8,
    device=DEVICE,
    project=str(RUNS_DIR / "detect"),
    name=RUN_NAME,
    exist_ok=True,
    seed=42,
    deterministic=True,
    plots=True,
    verbose=True,
    # Augmentations conservadoras (lección v1: mosaic+mixup matan datasets chicos)
    hsv_h=0.015, hsv_s=0.5, hsv_v=0.3,
    degrees=5.0, translate=0.05, scale=0.3,
    fliplr=0.5, flipud=0.0,
    mosaic=0.0, mixup=0.0,
    erasing=0.0,
)
print("Entrenamiento finalizado.")

Ultralytics 8.4.47 🚀 Python-3.12.7 torch-2.11.0 MPS (Apple M3 Pro)

engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_v2/data_train.yaml, degrees=5.0, deterministic=True, device=mps, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=200, erasing=0.0, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.5, hsv_v=0.3, imgsz=416, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=0.0, multi_scale=0.0, name=coins_v2, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=50, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/v2/detect, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/v2/detect/coins_v2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.3, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.05, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None

Overriding model.yaml nc=80 with nc=5

                   from  n    params  module                                       arguments

  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]

  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]

  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]

  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]

  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]

  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]

  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]

  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]

  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]

  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]

 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']

 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]

 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']

 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]

 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]

 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]

 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]

 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]

 22        [15, 18, 21]  1    752287  ultralytics.nn.modules.head.Detect           [5, 16, None, [64, 128, 256]]

Model summary: 130 layers, 3,011,823 parameters, 3,011,807 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights

Freezing layer 'model.22.dfl.conv.weight'

train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2129.3±543.5 MB/s, size: 74.0 KB)

train: Scanning /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_v2/train/labels... 31 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 31/31 4.4Kit/s 0.0s

train: New cache created: /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_v2/train/labels.cache

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1957.6±424.6 MB/s, size: 71.5 KB)

val: Scanning /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_v2/valid/labels.cache... 4 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 4/4 3.4Mit/s 0.0s

optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...

optimizer: AdamW(lr=0.001111, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)

Plotting labels to /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/v2/detect/coins_v2/labels.jpg...

Image sizes 416 train, 416 val
Using 0 dataloader workers
Logging results to /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/v2/detect/coins_v2
Starting training for 200 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      1/200      1.18G     0.7191      4.069     0.9887        121        416: 0% ──────────── 0/4  1.1s

      1/200      1.18G     0.7529      4.033     0.9892         72        416: 25% ━━━───────── 1/4 1.2s/it 1.5s<3.5s

      1/200      1.18G     0.7214      3.984     0.9839         75        416: 50% ━━━━━━────── 2/4 1.6it/s 1.8s<1.2s

      1/200      1.19G      0.707      3.921     0.9797         83        416: 75% ━━━━━━━━━─── 3/4 1.3it/s 3.7s<0.8s

      1/200      1.19G      0.707      3.921     0.9797         83        416: 100% ━━━━━━━━━━━━ 4/4 1.1it/s 3.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.7it/s 0.6s

                   all          4         40    0.00081     0.0667    0.00156    0.00125

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      2/200      1.18G     0.6128      3.777      0.916         74        416: 0% ──────────── 0/4  0.2s

      2/200      1.18G     0.5585      3.691     0.9115         61        416: 25% ━━━───────── 1/4 1.1it/s 0.5s<2.7s

      2/200      1.18G     0.5513      3.742      0.909        111        416: 50% ━━━━━━────── 2/4 1.9it/s 0.8s<1.0s

      2/200      1.19G     0.5543      3.741     0.9044        105        416: 75% ━━━━━━━━━─── 3/4 2.5it/s 1.0s<0.4s

      2/200      1.19G     0.5543      3.741     0.9044        105        416: 100% ━━━━━━━━━━━━ 4/4 3.9it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 8.2it/s 0.1s

                   all          4         40   0.000784     0.0667     0.0112    0.00893

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      3/200      1.18G     0.6443      3.598     0.9018        118        416: 0% ──────────── 0/4  0.2s

      3/200      1.22G     0.6539      3.571     0.9114         93        416: 25% ━━━───────── 1/4 1.2it/s 0.5s<2.4s

      3/200      1.22G     0.6199      3.505     0.8848         73        416: 50% ━━━━━━────── 2/4 1.8it/s 0.8s<1.1s

      3/200      1.22G     0.6201      3.472     0.8816         68        416: 75% ━━━━━━━━━─── 3/4 2.3it/s 1.1s<0.4s

      3/200      1.22G     0.6201      3.472     0.8816         68        416: 100% ━━━━━━━━━━━━ 4/4 3.6it/s 1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.3it/s 0.1s

                   all          4         40    0.00246      0.128     0.0353     0.0316

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      4/200      1.19G     0.4826      3.289     0.8389         78        416: 0% ──────────── 0/4  0.3s

      4/200      1.22G        0.5       3.31     0.8393         85        416: 25% ━━━───────── 1/4 1.2it/s 0.5s<2.6s

      4/200      1.22G     0.5199      3.334     0.8465        137        416: 50% ━━━━━━────── 2/4 2.1it/s 0.8s<0.9s

      4/200      1.22G     0.5248      3.262     0.8403         52        416: 75% ━━━━━━━━━─── 3/4 2.6it/s 1.0s<0.4s

      4/200      1.22G     0.5248      3.262     0.8403         52        416: 100% ━━━━━━━━━━━━ 4/4 3.9it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.2it/s 0.1s

                   all          4         40    0.00398       0.19     0.0464     0.0413

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      5/200      1.19G     0.6229      2.999     0.8157         80        416: 0% ──────────── 0/4  0.2s

      5/200      1.22G     0.5793      2.925     0.8333         48        416: 25% ━━━───────── 1/4 1.1it/s 0.5s<2.8s

      5/200      1.22G     0.5936      2.948     0.8417        114        416: 50% ━━━━━━────── 2/4 2.1it/s 0.7s<1.0s

      5/200      1.22G     0.5788      2.969     0.8456        109        416: 75% ━━━━━━━━━─── 3/4 2.6it/s 1.0s<0.4s

      5/200      1.22G     0.5788      2.969     0.8456        109        416: 100% ━━━━━━━━━━━━ 4/4 4.0it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 5.5it/s 0.2s

                   all          4         40     0.0124      0.329      0.119     0.0907

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      6/200      1.19G     0.5088      2.488     0.8071         73        416: 0% ──────────── 0/4  0.2s

      6/200      1.22G     0.5347      2.674     0.8317        124        416: 25% ━━━───────── 1/4 1.1it/s 0.5s<2.6s

      6/200      1.22G     0.5468       2.58     0.8338         82        416: 50% ━━━━━━────── 2/4 2.1it/s 0.7s<0.9s

      6/200      1.22G      0.554      2.528     0.8334         72        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.9s<0.3s

      6/200      1.22G      0.554      2.528     0.8334         72        416: 100% ━━━━━━━━━━━━ 4/4 4.6it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 5.1it/s 0.2s

                   all          4         40     0.0155      0.446      0.153      0.121

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      7/200      1.22G     0.5926      2.261     0.8351         64        416: 0% ──────────── 0/4  0.3s

      7/200      1.22G     0.5549      2.209      0.829         87        416: 25% ━━━───────── 1/4 1.3it/s 0.5s<2.3s

      7/200      1.22G     0.5742      2.308     0.8311        125        416: 50% ━━━━━━────── 2/4 2.2it/s 0.8s<0.9s

      7/200      1.22G     0.5608        2.3     0.8352         76        416: 75% ━━━━━━━━━─── 3/4 2.9it/s 1.0s<0.3s

      7/200      1.22G     0.5608        2.3     0.8352         76        416: 100% ━━━━━━━━━━━━ 4/4 4.1it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 5.0it/s 0.2s

                   all          4         40     0.0241      0.707      0.208      0.162

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      8/200      1.19G      0.549      1.937     0.8326         72        416: 0% ──────────── 0/4  0.2s

      8/200      1.22G     0.5247      2.005     0.8305         82        416: 25% ━━━───────── 1/4 1.7it/s 0.4s<1.8s

      8/200      1.22G     0.5263      2.125     0.8399        128        416: 50% ━━━━━━────── 2/4 2.1it/s 0.7s<0.9s

      8/200      1.22G     0.5242      2.069      0.839         69        416: 75% ━━━━━━━━━─── 3/4 2.1it/s 1.2s<0.5s

      8/200      1.22G     0.5242      2.069      0.839         69        416: 100% ━━━━━━━━━━━━ 4/4 3.4it/s 1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.7it/s 0.3s

                   all          4         40     0.0298      0.873      0.266      0.209

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      9/200      1.22G     0.6086      1.993     0.8533         92        416: 0% ──────────── 0/4  0.3s

      9/200      1.22G     0.5895       1.98     0.8538         91        416: 25% ━━━───────── 1/4 1.1it/s 0.6s<2.8s

      9/200      1.22G     0.5751      1.946     0.8545        106        416: 50% ━━━━━━────── 2/4 1.8it/s 0.8s<1.1s

      9/200      1.22G     0.5749       1.86     0.8532         63        416: 75% ━━━━━━━━━─── 3/4 2.1it/s 1.2s<0.5s

      9/200      1.22G     0.5749       1.86     0.8532         63        416: 100% ━━━━━━━━━━━━ 4/4 3.3it/s 1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 4.4it/s 0.2s

                   all          4         40     0.0321      0.933       0.35      0.268

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     10/200      1.22G     0.4687      1.821      0.843         70        416: 0% ──────────── 0/4  0.3s

     10/200      1.22G      0.633      2.219       0.85         35        416: 25% ━━━───────── 1/4 1.2it/s 0.5s<2.5s

     10/200      1.22G     0.6167      2.084     0.8588        115        416: 50% ━━━━━━────── 2/4 2.0it/s 0.8s<1.0s

     10/200      1.22G     0.6304      2.071     0.8581        132        416: 75% ━━━━━━━━━─── 3/4 2.6it/s 1.0s<0.4s

     10/200      1.22G     0.6304      2.071     0.8581        132        416: 100% ━━━━━━━━━━━━ 4/4 3.9it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.6it/s 0.3s

                   all          4         40     0.0316      0.933      0.411       0.32

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     11/200      1.22G     0.5094      1.689     0.8373         49        416: 0% ──────────── 0/4  0.3s

     11/200      1.22G     0.5501      1.758     0.8488        116        416: 25% ━━━───────── 1/4 1.1it/s 0.6s<2.8s

     11/200      1.22G     0.5365      1.685     0.8545         98        416: 50% ━━━━━━────── 2/4 2.0it/s 0.8s<1.0s

     11/200      1.22G     0.5369      1.653     0.8564         89        416: 75% ━━━━━━━━━─── 3/4 2.6it/s 1.1s<0.4s

     11/200      1.22G     0.5369      1.653     0.8564         89        416: 100% ━━━━━━━━━━━━ 4/4 3.8it/s 1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.9it/s 0.3s

                   all          4         40      0.623      0.246       0.47       0.39

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     12/200      1.22G     0.5223       1.49     0.8236         57        416: 0% ──────────── 0/4  0.3s

     12/200      1.22G     0.5216      1.416     0.8484         81        416: 25% ━━━───────── 1/4 1.2it/s 0.5s<2.5s

     12/200      1.22G     0.5308      1.471     0.8473        118        416: 50% ━━━━━━────── 2/4 2.5it/s 0.7s<0.8s

     12/200      1.22G     0.5646      1.504     0.8578         96        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 0.9s<0.3s

     12/200      1.22G     0.5646      1.504     0.8578         96        416: 100% ━━━━━━━━━━━━ 4/4 4.3it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.9it/s 0.3s

                   all          4         40      0.568       0.38      0.511      0.467

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     13/200      1.22G     0.5501      1.518     0.8637        103        416: 0% ──────────── 0/4  0.3s

     13/200      1.22G     0.5463      1.557     0.8395         98        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     13/200      1.22G     0.6451      1.482     0.8776         59        416: 50% ━━━━━━────── 2/4 2.3it/s 0.7s<0.9s

     13/200      1.22G     0.6223      1.451       0.87         92        416: 75% ━━━━━━━━━─── 3/4 3.3it/s 0.9s<0.3s

     13/200      1.22G     0.6223      1.451       0.87         92        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.3it/s 0.3s

                   all          4         40      0.561       0.44      0.554      0.501

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     14/200      1.22G     0.6602      1.567     0.8619         81        416: 0% ──────────── 0/4  0.2s

     14/200      1.22G     0.7411      1.435     0.9308         90        416: 25% ━━━───────── 1/4 1.1it/s 0.5s<2.7s

     14/200      1.22G     0.7143      1.362     0.9132         85        416: 50% ━━━━━━────── 2/4 2.3it/s 0.6s<0.9s

     14/200      1.22G     0.6787      1.366     0.8948         95        416: 75% ━━━━━━━━━─── 3/4 2.8it/s 0.9s<0.4s

     14/200      1.22G     0.6787      1.366     0.8948         95        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.7it/s 0.3s

                   all          4         40      0.661      0.473      0.589      0.506

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     15/200      1.22G     0.6965      1.131     0.8943         65        416: 0% ──────────── 0/4  0.3s

     15/200      1.22G     0.6298      1.164     0.8705         89        416: 25% ━━━───────── 1/4 1.6it/s 0.5s<1.8s

     15/200      1.22G     0.5969      1.287     0.8602        136        416: 50% ━━━━━━────── 2/4 2.2it/s 0.8s<0.9s

     15/200      1.22G     0.5956      1.241     0.8644         62        416: 75% ━━━━━━━━━─── 3/4 2.4it/s 1.1s<0.4s

     15/200      1.22G     0.5956      1.241     0.8644         62        416: 100% ━━━━━━━━━━━━ 4/4 3.5it/s 1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.2it/s 0.3s

                   all          4         40       0.77      0.479      0.653      0.528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     16/200      1.19G     0.5717      1.169     0.8824         67        416: 0% ──────────── 0/4  0.3s

     16/200      1.22G     0.5243      1.215     0.8684        114        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.8s

     16/200      1.22G     0.5193      1.145     0.8647         87        416: 50% ━━━━━━────── 2/4 2.8it/s 0.6s<0.7s

     16/200      1.22G     0.5048      1.124     0.8673         83        416: 75% ━━━━━━━━━─── 3/4 3.7it/s 0.8s<0.3s

     16/200      1.22G     0.5048      1.124     0.8673         83        416: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.2it/s 0.1s

                   all          4         40       0.77      0.479      0.653      0.528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     17/200      1.21G     0.5624      1.104     0.8569         89        416: 0% ──────────── 0/4  0.2s

     17/200      1.21G     0.5469      1.024     0.8603         78        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.8s

     17/200      1.21G     0.5303      1.013      0.863         93        416: 50% ━━━━━━────── 2/4 2.8it/s 0.6s<0.7s

     17/200      1.21G     0.5337      1.017     0.8616         92        416: 75% ━━━━━━━━━─── 3/4 3.7it/s 0.7s<0.3s

     17/200      1.21G     0.5337      1.017     0.8616         92        416: 100% ━━━━━━━━━━━━ 4/4 5.5it/s 0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.9it/s 0.3s

                   all          4         40      0.844      0.583      0.745      0.562

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     18/200      1.21G     0.7169      1.003      0.877        106        416: 0% ──────────── 0/4  0.2s

     18/200      1.21G     0.6113      1.014     0.8846         46        416: 25% ━━━───────── 1/4 1.2it/s 0.4s<2.4s

     18/200      1.21G      0.622      1.082     0.8622         56        416: 50% ━━━━━━────── 2/4 2.0it/s 0.7s<1.0s

     18/200      1.21G     0.6287      1.165     0.8686        143        416: 75% ━━━━━━━━━─── 3/4 2.2it/s 1.1s<0.5s

     18/200      1.21G     0.6287      1.165     0.8686        143        416: 100% ━━━━━━━━━━━━ 4/4 3.7it/s 1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 4.2it/s 0.2s

                   all          4         40      0.785       0.75      0.836      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     19/200      1.21G      0.491     0.8952     0.8482         78        416: 0% ──────────── 0/4  0.2s

     19/200      1.21G     0.5639     0.8676     0.8488         76        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.1s

     19/200      1.21G     0.5841     0.9718      0.862        129        416: 50% ━━━━━━────── 2/4 2.1it/s 0.7s<1.0s

     19/200      1.21G     0.5962     0.9738     0.8647         69        416: 75% ━━━━━━━━━─── 3/4 2.8it/s 0.9s<0.4s

     19/200      1.21G     0.5962     0.9738     0.8647         69        416: 100% ━━━━━━━━━━━━ 4/4 4.4it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.1it/s 0.1s

                   all          4         40      0.785       0.75      0.836      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     20/200      1.21G     0.5871      1.043     0.8746        111        416: 0% ──────────── 0/4  0.2s

     20/200      1.21G     0.5771      0.969     0.8787         63        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     20/200      1.21G     0.5819     0.9644     0.8758         60        416: 50% ━━━━━━────── 2/4 2.3it/s 0.6s<0.9s

     20/200      1.21G     0.5944     0.9749     0.8718        118        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.8s<0.3s

     20/200      1.21G     0.5944     0.9749     0.8718        118        416: 100% ━━━━━━━━━━━━ 4/4 4.9it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 4.0it/s 0.2s

                   all          4         40       0.67      0.833      0.873       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     21/200      1.21G      0.514     0.9426     0.8328         60        416: 0% ──────────── 0/4  0.2s

     21/200      1.21G     0.5343     0.9223     0.8404        112        416: 25% ━━━───────── 1/4 1.1it/s 0.4s<2.8s

     21/200      1.21G     0.5258     0.9114     0.8405         91        416: 50% ━━━━━━────── 2/4 2.4it/s 0.6s<0.8s

     21/200      1.21G      0.527     0.8977      0.844         89        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.8s<0.3s

     21/200      1.21G      0.527     0.8977      0.844         89        416: 100% ━━━━━━━━━━━━ 4/4 4.9it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.9it/s 0.3s

                   all          4         40      0.781      0.823      0.908      0.738

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     22/200      1.19G     0.5954     0.7901     0.8563         82        416: 0% ──────────── 0/4  0.2s

     22/200      1.22G     0.5382     0.8696     0.8534        125        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<2.0s

     22/200      1.22G     0.5476     0.8386     0.8498         91        416: 50% ━━━━━━────── 2/4 2.7it/s 0.6s<0.7s

     22/200      1.22G     0.5557      0.839     0.8495         54        416: 75% ━━━━━━━━━─── 3/4 3.1it/s 0.8s<0.3s

     22/200      1.22G     0.5557      0.839     0.8495         54        416: 100% ━━━━━━━━━━━━ 4/4 4.9it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.1it/s 0.1s

                   all          4         40      0.781      0.823      0.908      0.738

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     23/200      1.21G     0.5454     0.9649     0.8905        119        416: 0% ──────────── 0/4  0.3s

     23/200      1.21G     0.5791      1.031     0.9088         36        416: 25% ━━━───────── 1/4 1.2s/it 0.7s<3.7s

     23/200      1.21G     0.5531     0.9455      0.885         95        416: 50% ━━━━━━────── 2/4 2.1it/s 0.8s<0.9s

     23/200      1.22G     0.5484     0.9336     0.8775        102        416: 75% ━━━━━━━━━─── 3/4 2.7it/s 1.1s<0.4s

     23/200      1.22G     0.5484     0.9336     0.8775        102        416: 100% ━━━━━━━━━━━━ 4/4 3.7it/s 1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 4.0it/s 0.2s

                   all          4         40      0.719      0.884      0.892      0.733

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     24/200      1.21G      0.558     0.9908     0.9132         32        416: 0% ──────────── 0/4  0.3s

     24/200      1.21G     0.5329      1.051     0.9032        150        416: 25% ━━━───────── 1/4 1.2it/s 0.5s<2.6s

     24/200      1.21G     0.5266     0.9649     0.8903        113        416: 50% ━━━━━━────── 2/4 1.9it/s 0.8s<1.0s

     24/200      1.21G     0.5289     0.9421     0.8763         57        416: 75% ━━━━━━━━━─── 3/4 3.1it/s 1.0s<0.3s

     24/200      1.21G     0.5289     0.9421     0.8763         57        416: 100% ━━━━━━━━━━━━ 4/4 4.2it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.8it/s 0.1s

                   all          4         40      0.719      0.884      0.892      0.733

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     25/200      1.21G     0.5406     0.8111     0.8811         88        416: 0% ──────────── 0/4  0.3s

     25/200      1.21G     0.5546     0.7745     0.8653         88        416: 25% ━━━───────── 1/4 1.7it/s 0.4s<1.7s

     25/200      1.21G     0.5466     0.7788     0.8634        103        416: 50% ━━━━━━────── 2/4 2.8it/s 0.6s<0.7s

     25/200      1.21G     0.5419     0.7503     0.8635         73        416: 75% ━━━━━━━━━─── 3/4 3.7it/s 0.8s<0.3s

     25/200      1.21G     0.5419     0.7503     0.8635         73        416: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.4it/s 0.3s

                   all          4         40      0.773      0.792       0.85      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     26/200      1.21G     0.6274     0.7073     0.8759         86        416: 0% ──────────── 0/4  0.3s

     26/200      1.21G     0.5836     0.7367     0.8688        115        416: 25% ━━━───────── 1/4 1.5it/s 0.5s<2.0s

     26/200      1.21G     0.5467      0.748     0.8602         83        416: 50% ━━━━━━────── 2/4 2.6it/s 0.7s<0.8s

     26/200      1.21G     0.5774     0.7688     0.8557         68        416: 75% ━━━━━━━━━─── 3/4 3.5it/s 0.9s<0.3s

     26/200      1.21G     0.5774     0.7688     0.8557         68        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.7it/s 0.1s

                   all          4         40      0.773      0.792       0.85      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     27/200      1.21G     0.5438     0.7618     0.8503        113        416: 0% ──────────── 0/4  0.2s

     27/200      1.21G     0.5514     0.7451     0.8766         62        416: 25% ━━━───────── 1/4 1.1s/it 0.5s<3.3s

     27/200      1.21G     0.5579     0.7427     0.8627         77        416: 50% ━━━━━━────── 2/4 1.6it/s 0.8s<1.3s

     27/200      1.21G     0.5437     0.7554     0.8598        100        416: 75% ━━━━━━━━━─── 3/4 2.0it/s 1.2s<0.5s

     27/200      1.21G     0.5437     0.7554     0.8598        100        416: 100% ━━━━━━━━━━━━ 4/4 3.4it/s 1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.8it/s 0.4s

                   all          4         40      0.758      0.778       0.85      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     28/200      1.21G      0.537     0.7601     0.8769         64        416: 0% ──────────── 0/4  0.2s

     28/200      1.21G     0.5188     0.7317     0.8526         98        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     28/200      1.21G     0.5164     0.7012     0.8493         94        416: 50% ━━━━━━────── 2/4 2.0it/s 0.7s<1.0s

     28/200      1.21G     0.5069      0.712     0.8417         95        416: 75% ━━━━━━━━━─── 3/4 3.1it/s 0.9s<0.3s

     28/200      1.21G     0.5069      0.712     0.8417         95        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.2it/s 0.1s

                   all          4         40      0.758      0.778       0.85      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     29/200      1.21G     0.5628     0.7651     0.8549         92        416: 0% ──────────── 0/4  0.2s

     29/200      1.21G     0.5205     0.7071     0.8541         66        416: 25% ━━━───────── 1/4 1.0s/it 0.5s<3.0s

     29/200      1.21G     0.5066     0.6932     0.8468         89        416: 50% ━━━━━━────── 2/4 2.2it/s 0.7s<0.9s

     29/200      1.21G     0.5151     0.7154     0.8521        104        416: 75% ━━━━━━━━━─── 3/4 2.4it/s 1.0s<0.4s

     29/200      1.21G     0.5151     0.7154     0.8521        104        416: 100% ━━━━━━━━━━━━ 4/4 3.9it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.7it/s 0.4s

                   all          4         40      0.776      0.777       0.87      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     30/200      1.21G     0.4389     0.6406      0.843         86        416: 0% ──────────── 0/4  0.2s

     30/200      1.21G      0.444     0.7252     0.8445        129        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<2.0s

     30/200      1.21G     0.4478     0.7157     0.8521         48        416: 50% ━━━━━━────── 2/4 2.6it/s 0.6s<0.8s

     30/200      1.21G     0.4743     0.7121     0.8458         89        416: 75% ━━━━━━━━━─── 3/4 3.5it/s 0.8s<0.3s

     30/200      1.21G     0.4743     0.7121     0.8458         89        416: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.0it/s 0.1s

                   all          4         40      0.776      0.777       0.87      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     31/200      1.21G     0.5462     0.6075     0.8582         86        416: 0% ──────────── 0/4  0.2s

     31/200      1.21G     0.5399     0.6544     0.8348        112        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     31/200      1.21G      0.545     0.6905      0.829         63        416: 50% ━━━━━━────── 2/4 2.6it/s 0.6s<0.8s

     31/200      1.21G     0.5465     0.6885     0.8284         91        416: 75% ━━━━━━━━━─── 3/4 3.5it/s 0.8s<0.3s

     31/200      1.21G     0.5465     0.6885     0.8284         91        416: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.5it/s 0.4s

                   all          4         40      0.814      0.787      0.887      0.696

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     32/200      1.21G     0.4582      0.644     0.8299        107        416: 0% ──────────── 0/4  0.3s

     32/200      1.21G     0.4982     0.7084     0.8408        137        416: 25% ━━━───────── 1/4 1.5it/s 0.5s<2.0s

     32/200      1.21G     0.4912     0.8289     0.8487         25        416: 50% ━━━━━━────── 2/4 1.8it/s 0.9s<1.1s

     32/200      1.21G     0.4735     0.7648      0.835         83        416: 75% ━━━━━━━━━─── 3/4 2.9it/s 1.1s<0.3s

     32/200      1.21G     0.4735     0.7648      0.835         83        416: 100% ━━━━━━━━━━━━ 4/4 3.5it/s 1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.0it/s 0.1s

                   all          4         40      0.814      0.787      0.887      0.696

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     33/200      1.21G       0.57     0.6591      0.841         98        416: 0% ──────────── 0/4  0.2s

     33/200      1.21G      0.545      0.668     0.8414         89        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     33/200      1.21G     0.5333      0.673     0.8443         78        416: 50% ━━━━━━────── 2/4 2.6it/s 0.6s<0.8s

     33/200      1.21G      0.556     0.6687      0.848         87        416: 75% ━━━━━━━━━─── 3/4 3.5it/s 0.8s<0.3s

     33/200      1.21G      0.556     0.6687      0.848         87        416: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.9it/s 0.4s

                   all          4         40      0.829      0.847      0.897      0.727

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     34/200      1.22G     0.5096     0.6977     0.8388         62        416: 0% ──────────── 0/4  0.2s

     34/200      1.22G     0.4871      0.676     0.8317        115        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<2.0s

     34/200      1.22G     0.5079      0.669     0.8393         69        416: 50% ━━━━━━────── 2/4 2.6it/s 0.6s<0.8s

     34/200      1.22G     0.5121     0.6615     0.8414        106        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.8s<0.3s

     34/200      1.22G     0.5121     0.6615     0.8414        106        416: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.0it/s 0.1s

                   all          4         40      0.829      0.847      0.897      0.727

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     35/200      1.22G      0.531     0.6898     0.8684         60        416: 0% ──────────── 0/4  0.2s

     35/200      1.22G     0.5032     0.6703     0.8544         98        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<1.9s

     35/200      1.22G     0.5325      0.695     0.8616        132        416: 50% ━━━━━━────── 2/4 2.5it/s 0.6s<0.8s

     35/200      1.22G     0.5201     0.6853     0.8668         62        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.8s<0.3s

     35/200      1.22G     0.5201     0.6853     0.8668         62        416: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.5it/s 0.4s

                   all          4         40      0.806      0.802      0.873      0.769

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     36/200      1.22G     0.5377     0.7076     0.8449         59        416: 0% ──────────── 0/4  0.2s

     36/200      1.22G     0.5013     0.7187     0.8311         71        416: 25% ━━━───────── 1/4 1.1s/it 0.5s<3.2s

     36/200      1.22G     0.4978     0.6857     0.8377        115        416: 50% ━━━━━━────── 2/4 2.2it/s 0.7s<0.9s

     36/200      1.22G      0.502      0.694     0.8387        105        416: 75% ━━━━━━━━━─── 3/4 3.1it/s 0.9s<0.3s

     36/200      1.22G      0.502      0.694     0.8387        105        416: 100% ━━━━━━━━━━━━ 4/4 4.4it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.3it/s 0.1s

                   all          4         40      0.806      0.802      0.873      0.769

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     37/200      1.22G     0.5424     0.6623     0.8195        110        416: 0% ──────────── 0/4  0.3s

     37/200      1.22G     0.5162     0.6363     0.8546         67        416: 25% ━━━───────── 1/4 1.4it/s 0.5s<2.2s

     37/200      1.22G     0.5376     0.6247       0.86        100        416: 50% ━━━━━━────── 2/4 2.4it/s 0.8s<0.8s

     37/200      1.22G     0.5471     0.6492     0.8573         75        416: 75% ━━━━━━━━━─── 3/4 3.3it/s 0.9s<0.3s

     37/200      1.22G     0.5471     0.6492     0.8573         75        416: 100% ━━━━━━━━━━━━ 4/4 4.2it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.6it/s 0.4s

                   all          4         40      0.842      0.772      0.871      0.759

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     38/200      1.22G     0.4642     0.6134     0.8343         91        416: 0% ──────────── 0/4  0.2s

     38/200      1.22G     0.4909     0.6583      0.835        142        416: 25% ━━━───────── 1/4 1.2s/it 0.6s<3.7s

     38/200      1.22G     0.5135     0.6712     0.8519         73        416: 50% ━━━━━━────── 2/4 2.1it/s 0.8s<1.0s

     38/200      1.22G      0.509     0.6956     0.8386         46        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 1.0s<0.3s

     38/200      1.22G      0.509     0.6956     0.8386         46        416: 100% ━━━━━━━━━━━━ 4/4 4.1it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.1it/s 0.1s

                   all          4         40      0.842      0.772      0.871      0.759

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     39/200      1.22G     0.4888     0.5987     0.8494         88        416: 0% ──────────── 0/4  0.3s

     39/200      1.22G     0.5359     0.6771     0.8616         50        416: 25% ━━━───────── 1/4 1.0s/it 0.6s<3.1s

     39/200      1.22G     0.5276     0.6671     0.8621         91        416: 50% ━━━━━━────── 2/4 2.2it/s 0.8s<0.9s

     39/200      1.22G     0.5228     0.6777     0.8569        121        416: 75% ━━━━━━━━━─── 3/4 3.1it/s 1.0s<0.3s

     39/200      1.22G     0.5228     0.6777     0.8569        121        416: 100% ━━━━━━━━━━━━ 4/4 3.9it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.4it/s 0.4s

                   all          4         40      0.779      0.886      0.916      0.768

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     40/200      1.22G     0.4821     0.7486     0.8379        146        416: 0% ──────────── 0/4  0.4s

     40/200      1.22G     0.4732     0.6577     0.8372         77        416: 25% ━━━───────── 1/4 1.5it/s 0.6s<2.0s

     40/200      1.22G     0.4843     0.6384     0.8523         62        416: 50% ━━━━━━────── 2/4 2.5it/s 0.8s<0.8s

     40/200      1.22G     0.4814     0.6349     0.8489         67        416: 75% ━━━━━━━━━─── 3/4 3.3it/s 1.0s<0.3s

     40/200      1.22G     0.4814     0.6349     0.8489         67        416: 100% ━━━━━━━━━━━━ 4/4 4.1it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.6it/s 0.1s

                   all          4         40      0.779      0.886      0.916      0.768

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     41/200      1.22G     0.4848     0.6552     0.8367        110        416: 0% ──────────── 0/4  0.2s

     41/200      1.22G     0.4594     0.6608     0.8563         52        416: 25% ━━━───────── 1/4 1.3it/s 0.4s<2.3s

     41/200      1.22G     0.4847     0.6624     0.8507        129        416: 50% ━━━━━━────── 2/4 2.3it/s 0.7s<0.9s

     41/200      1.22G     0.4933     0.6583      0.849         61        416: 75% ━━━━━━━━━─── 3/4 3.1it/s 0.9s<0.3s

     41/200      1.22G     0.4933     0.6583      0.849         61        416: 100% ━━━━━━━━━━━━ 4/4 4.7it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.8it/s 0.4s

                   all          4         40      0.805      0.912       0.92      0.752

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     42/200      1.22G     0.5087     0.6945     0.8309        141        416: 0% ──────────── 0/4  0.4s

     42/200      1.22G     0.4873     0.6459     0.8382         92        416: 25% ━━━───────── 1/4 1.4it/s 0.6s<2.1s

     42/200      1.22G      0.486      0.628     0.8411         59        416: 50% ━━━━━━────── 2/4 2.6it/s 0.8s<0.8s

     42/200      1.22G     0.4724     0.6298     0.8316         60        416: 75% ━━━━━━━━━─── 3/4 2.9it/s 1.0s<0.3s

     42/200      1.22G     0.4724     0.6298     0.8316         60        416: 100% ━━━━━━━━━━━━ 4/4 3.9it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.7it/s 0.1s

                   all          4         40      0.805      0.912       0.92      0.752

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     43/200      1.22G     0.6031     0.6597     0.8504         64        416: 0% ──────────── 0/4  0.2s

     43/200      1.22G      0.538     0.6379     0.8473        102        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<2.0s

     43/200      1.22G     0.4994     0.6147     0.8307         90        416: 50% ━━━━━━────── 2/4 2.5it/s 0.6s<0.8s

     43/200      1.22G     0.5012     0.6222     0.8302         96        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.8s<0.3s

     43/200      1.22G     0.5012     0.6222     0.8302         96        416: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.0it/s 0.3s

                   all          4         40      0.833      0.953       0.92      0.781

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     44/200      1.22G     0.4662     0.5976     0.8347         96        416: 0% ──────────── 0/4  0.2s

     44/200      1.22G     0.4616     0.6154     0.8312        126        416: 25% ━━━───────── 1/4 1.2s/it 0.6s<3.5s

     44/200      1.22G     0.4766     0.6282     0.8404         53        416: 50% ━━━━━━────── 2/4 1.5it/s 0.9s<1.3s

     44/200      1.22G     0.4735     0.6146     0.8399         77        416: 75% ━━━━━━━━━─── 3/4 2.6it/s 1.1s<0.4s

     44/200      1.22G     0.4735     0.6146     0.8399         77        416: 100% ━━━━━━━━━━━━ 4/4 3.7it/s 1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.7it/s 0.1s

                   all          4         40      0.833      0.953       0.92      0.781

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     45/200      1.22G     0.4836      0.627     0.8277         77        416: 0% ──────────── 0/4  0.2s

     45/200      1.22G      0.482     0.6252     0.8371        105        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.1s

     45/200      1.22G     0.5146     0.6242     0.8427        114        416: 50% ━━━━━━────── 2/4 2.4it/s 0.6s<0.8s

     45/200      1.22G     0.4976     0.6111     0.8442         56        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.8s<0.3s

     45/200      1.22G     0.4976     0.6111     0.8442         56        416: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.4it/s 0.4s

                   all          4         40      0.843      0.961      0.939      0.816

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     46/200      1.22G     0.4945     0.5933     0.8744         85        416: 0% ──────────── 0/4  0.2s

     46/200      1.22G     0.4563     0.5722     0.8569         91        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<2.0s

     46/200      1.22G     0.4642     0.5894     0.8447        116        416: 50% ━━━━━━────── 2/4 2.6it/s 0.6s<0.8s

     46/200      1.22G     0.4693     0.5809      0.836         59        416: 75% ━━━━━━━━━─── 3/4 3.5it/s 0.8s<0.3s

     46/200      1.22G     0.4693     0.5809      0.836         59        416: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.9it/s 0.1s

                   all          4         40      0.843      0.961      0.939      0.816

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     47/200      1.22G     0.6139     0.6175     0.8924         59        416: 0% ──────────── 0/4  0.2s

     47/200      1.22G     0.5609     0.5948     0.8827         75        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<1.9s

     47/200      1.22G     0.5439     0.6072     0.8719        128        416: 50% ━━━━━━────── 2/4 2.5it/s 0.6s<0.8s

     47/200      1.22G     0.5314     0.6014     0.8647         90        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.8s<0.3s

     47/200      1.22G     0.5314     0.6014     0.8647         90        416: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.5it/s 0.4s

                   all          4         40       0.88      0.931      0.939       0.77

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     48/200      1.22G     0.5536     0.5683     0.8532        106        416: 0% ──────────── 0/4  0.2s

     48/200      1.22G     0.5347      0.603     0.8493         83        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.2s

     48/200      1.22G     0.5184     0.5882     0.8493         67        416: 50% ━━━━━━────── 2/4 2.5it/s 0.6s<0.8s

     48/200      1.22G     0.5016     0.5805     0.8462         96        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.8s<0.3s

     48/200      1.22G     0.5016     0.5805     0.8462         96        416: 100% ━━━━━━━━━━━━ 4/4 4.9it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.6it/s 0.1s

                   all          4         40       0.88      0.931      0.939       0.77

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     49/200      1.22G     0.4704     0.5707     0.8523        107        416: 0% ──────────── 0/4  0.2s

     49/200      1.22G     0.4878      0.567     0.8222        105        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<2.0s

     49/200      1.22G     0.5306     0.6059     0.8371         65        416: 50% ━━━━━━────── 2/4 2.5it/s 0.6s<0.8s

     49/200      1.22G     0.5273     0.6003     0.8353         75        416: 75% ━━━━━━━━━─── 3/4 3.8it/s 0.8s<0.3s

     49/200      1.22G     0.5273     0.6003     0.8353         75        416: 100% ━━━━━━━━━━━━ 4/4 5.3it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.2it/s 0.5s

                   all          4         40      0.909      0.931      0.943      0.773

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     50/200      1.22G     0.5539     0.6259     0.8529         87        416: 0% ──────────── 0/4  0.2s

     50/200      1.22G     0.5046      0.626     0.8382         65        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.8s

     50/200      1.22G     0.5077     0.5925     0.8433        100        416: 50% ━━━━━━────── 2/4 2.7it/s 0.6s<0.7s

     50/200      1.22G       0.51     0.5837     0.8429         99        416: 75% ━━━━━━━━━─── 3/4 2.8it/s 0.9s<0.4s

     50/200      1.22G       0.51     0.5837     0.8429         99        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.4it/s 0.1s

                   all          4         40      0.909      0.931      0.943      0.773

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     51/200      1.22G     0.4561     0.5545     0.8374         73        416: 0% ──────────── 0/4  0.2s

     51/200      1.22G     0.4622     0.6267     0.8449        153        416: 25% ━━━───────── 1/4 1.1s/it 0.5s<3.3s

     51/200      1.22G     0.4537      0.618     0.8335         49        416: 50% ━━━━━━────── 2/4 2.1it/s 0.7s<0.9s

     51/200      1.22G     0.4635     0.5883     0.8325         77        416: 75% ━━━━━━━━━─── 3/4 3.2it/s 0.9s<0.3s

     51/200      1.22G     0.4635     0.5883     0.8325         77        416: 100% ━━━━━━━━━━━━ 4/4 4.4it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.4it/s 0.4s

                   all          4         40      0.911      0.963      0.945      0.767

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     52/200      1.22G     0.4133     0.6164     0.8648         68        416: 0% ──────────── 0/4  0.2s

     52/200      1.22G      0.427     0.5933     0.8573         61        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     52/200      1.22G     0.4322     0.5695     0.8485        106        416: 50% ━━━━━━────── 2/4 2.7it/s 0.6s<0.8s

     52/200      1.22G     0.4507     0.5724     0.8414        117        416: 75% ━━━━━━━━━─── 3/4 2.8it/s 0.9s<0.4s

     52/200      1.22G     0.4507     0.5724     0.8414        117        416: 100% ━━━━━━━━━━━━ 4/4 4.4it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.9it/s 0.1s

                   all          4         40      0.911      0.963      0.945      0.767

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     53/200      1.22G     0.4581     0.5629     0.8334         83        416: 0% ──────────── 0/4  0.2s

     53/200      1.22G     0.5447     0.5621     0.8532         66        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     53/200      1.22G     0.5132     0.5429     0.8441         82        416: 50% ━━━━━━────── 2/4 2.6it/s 0.6s<0.8s

     53/200      1.22G     0.4923     0.5643     0.8431        121        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.8s<0.3s

     53/200      1.22G     0.4923     0.5643     0.8431        121        416: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.5it/s 0.4s

                   all          4         40      0.919      0.988      0.945      0.775

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     54/200      1.22G     0.5624     0.5207     0.8453         87        416: 0% ──────────── 0/4  0.2s

     54/200      1.22G       0.53     0.5548     0.8352        134        416: 25% ━━━───────── 1/4 1.1s/it 0.5s<3.2s

     54/200      1.22G     0.4967     0.5446     0.8343         64        416: 50% ━━━━━━────── 2/4 2.2it/s 0.7s<0.9s

     54/200      1.22G     0.4774     0.5498     0.8319         67        416: 75% ━━━━━━━━━─── 3/4 3.2it/s 0.9s<0.3s

     54/200      1.22G     0.4774     0.5498     0.8319         67        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.1it/s 0.1s

                   all          4         40      0.919      0.988      0.945      0.775

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     55/200      1.22G     0.4665     0.5377     0.8527        119        416: 0% ──────────── 0/4  0.2s

     55/200      1.22G     0.4868     0.5573     0.8414         55        416: 25% ━━━───────── 1/4 1.5s/it 0.7s<4.4s

     55/200      1.22G     0.5022     0.5598     0.8381         73        416: 50% ━━━━━━────── 2/4 2.0it/s 0.9s<1.0s

     55/200      1.22G     0.5118     0.5633     0.8338        105        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 1.1s<0.3s

     55/200      1.22G     0.5118     0.5633     0.8338        105        416: 100% ━━━━━━━━━━━━ 4/4 3.8it/s 1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.3it/s 0.4s

                   all          4         40       0.93      0.988      0.944      0.814

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     56/200      1.22G     0.4187     0.5327     0.8192        113        416: 0% ──────────── 0/4  0.2s

     56/200      1.22G     0.4814     0.5661     0.8274         76        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<2.0s

     56/200      1.22G     0.4761     0.5543     0.8272         82        416: 50% ━━━━━━────── 2/4 2.7it/s 0.6s<0.8s

     56/200      1.22G     0.4534     0.5431     0.8248         81        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.8s<0.3s

     56/200      1.22G     0.4534     0.5431     0.8248         81        416: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.1it/s 0.1s

                   all          4         40       0.93      0.988      0.944      0.814

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     57/200      1.22G     0.5055     0.5749     0.8125        108        416: 0% ──────────── 0/4  0.4s

     57/200      1.22G     0.4951     0.5398     0.8349         91        416: 25% ━━━───────── 1/4 1.3it/s 0.6s<2.2s

     57/200      1.22G     0.4723     0.5435     0.8295         90        416: 50% ━━━━━━────── 2/4 2.4it/s 0.8s<0.8s

     57/200      1.22G     0.4719     0.5345      0.834         63        416: 75% ━━━━━━━━━─── 3/4 3.3it/s 1.0s<0.3s

     57/200      1.22G     0.4719     0.5345      0.834         63        416: 100% ━━━━━━━━━━━━ 4/4 4.1it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.7it/s 0.4s

                   all          4         40      0.912      0.988      0.977      0.868

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     58/200      1.22G     0.4729     0.4859     0.8389         94        416: 0% ──────────── 0/4  0.2s

     58/200      1.22G     0.4651     0.4975     0.8252         95        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     58/200      1.22G     0.4689     0.5184      0.831         90        416: 50% ━━━━━━────── 2/4 2.6it/s 0.6s<0.8s

     58/200      1.22G     0.4805     0.5148     0.8455         72        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.7s<0.3s

     58/200      1.22G     0.4805     0.5148     0.8455         72        416: 100% ━━━━━━━━━━━━ 4/4 5.4it/s 0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.8it/s 0.1s

                   all          4         40      0.912      0.988      0.977      0.868

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     59/200      1.22G     0.4548     0.4893     0.8186         82        416: 0% ──────────── 0/4  0.2s

     59/200      1.22G     0.4416     0.4973     0.8189         92        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     59/200      1.22G     0.4264     0.5062     0.8197        107        416: 50% ━━━━━━────── 2/4 2.6it/s 0.6s<0.8s

     59/200      1.22G     0.4498     0.5062     0.8291         71        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.8s<0.3s

     59/200      1.22G     0.4498     0.5062     0.8291         71        416: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.7it/s 0.4s

                   all          4         40      0.963      0.903      0.968      0.858

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     60/200      1.22G     0.3775     0.5176     0.8044         76        416: 0% ──────────── 0/4  0.2s

     60/200      1.22G     0.4353     0.5018     0.8217        111        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<2.0s

     60/200      1.22G     0.4257     0.5023     0.8232         84        416: 50% ━━━━━━────── 2/4 2.0it/s 0.7s<1.0s

     60/200      1.22G     0.4315     0.5111     0.8168         81        416: 75% ━━━━━━━━━─── 3/4 3.1it/s 0.9s<0.3s

     60/200      1.22G     0.4315     0.5111     0.8168         81        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.9it/s 0.1s

                   all          4         40      0.963      0.903      0.968      0.858

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     61/200      1.22G     0.4604     0.5055     0.8195         72        416: 0% ──────────── 0/4  0.2s

     61/200      1.22G     0.4967     0.5269     0.8363         77        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<2.0s

     61/200      1.22G     0.4748     0.5082     0.8265         87        416: 50% ━━━━━━────── 2/4 2.6it/s 0.6s<0.8s

     61/200      1.22G     0.4687     0.5033     0.8216        116        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.8s<0.3s

     61/200      1.22G     0.4687     0.5033     0.8216        116        416: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.7it/s 0.4s

                   all          4         40      0.934       0.89      0.968       0.83

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     62/200      1.22G     0.4409     0.4816     0.8318        106        416: 0% ──────────── 0/4  0.2s

     62/200      1.23G     0.4388     0.4897     0.8149        104        416: 25% ━━━───────── 1/4 1.2it/s 0.5s<2.5s

     62/200      1.22G     0.4432     0.5117     0.8275         64        416: 50% ━━━━━━────── 2/4 2.3it/s 0.7s<0.9s

     62/200      1.22G     0.4597     0.5113     0.8338         78        416: 75% ━━━━━━━━━─── 3/4 3.1it/s 0.9s<0.3s

     62/200      1.22G     0.4597     0.5113     0.8338         78        416: 100% ━━━━━━━━━━━━ 4/4 4.7it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.4it/s 0.1s

                   all          4         40      0.934       0.89      0.968       0.83

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     63/200      1.22G     0.4575     0.5197     0.8252        101        416: 0% ──────────── 0/4  0.3s

     63/200      1.22G     0.4556     0.5093     0.8279         92        416: 25% ━━━───────── 1/4 1.5it/s 0.5s<2.0s

     63/200      1.22G     0.4464     0.5054     0.8213         87        416: 50% ━━━━━━────── 2/4 2.5it/s 0.7s<0.8s

     63/200      1.22G     0.4372      0.495     0.8227         72        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.9s<0.3s

     63/200      1.22G     0.4372      0.495     0.8227         72        416: 100% ━━━━━━━━━━━━ 4/4 4.4it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.5it/s 0.4s

                   all          4         40       0.93      0.976      0.977      0.819

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     64/200      1.22G     0.4363     0.4869     0.8068        115        416: 0% ──────────── 0/4  0.2s

     64/200      1.22G     0.4553     0.4953     0.8327         64        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     64/200      1.22G     0.4394     0.4851     0.8283        109        416: 50% ━━━━━━────── 2/4 2.6it/s 0.6s<0.8s

     64/200      1.22G     0.4455     0.4975     0.8283         63        416: 75% ━━━━━━━━━─── 3/4 3.5it/s 0.8s<0.3s

     64/200      1.22G     0.4455     0.4975     0.8283         63        416: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.7it/s 0.1s

                   all          4         40       0.93      0.976      0.977      0.819

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     65/200      1.22G      0.513     0.5449     0.8276         68        416: 0% ──────────── 0/4  0.2s

     65/200      1.22G     0.4754     0.4982       0.82         91        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<1.9s

     65/200      1.22G     0.4841     0.5052     0.8368        106        416: 50% ━━━━━━────── 2/4 2.5it/s 0.6s<0.8s

     65/200      1.22G     0.4668      0.494     0.8354         86        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.8s<0.3s

     65/200      1.22G     0.4668      0.494     0.8354         86        416: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.5it/s 0.4s

                   all          4         40      0.925      0.988      0.977      0.849

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     66/200      1.22G     0.4816     0.4931     0.8387         62        416: 0% ──────────── 0/4  0.2s

     66/200      1.22G     0.4926     0.5625     0.8444        159        416: 25% ━━━───────── 1/4 1.1s/it 0.5s<3.3s

     66/200      1.22G     0.4571     0.5402     0.8341         86        416: 50% ━━━━━━────── 2/4 2.2it/s 0.7s<0.9s

     66/200      1.22G     0.4435     0.5392     0.8306         45        416: 75% ━━━━━━━━━─── 3/4 2.5it/s 1.0s<0.4s

     66/200      1.22G     0.4435     0.5392     0.8306         45        416: 100% ━━━━━━━━━━━━ 4/4 3.9it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.2it/s 0.1s

                   all          4         40      0.925      0.988      0.977      0.849

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     67/200      1.22G     0.4586     0.5378     0.8423         55        416: 0% ──────────── 0/4  0.2s

     67/200      1.22G     0.4324     0.5177     0.8339        114        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.1s

     67/200      1.22G     0.4274     0.5044     0.8303         97        416: 50% ━━━━━━────── 2/4 1.9it/s 0.7s<1.0s

     67/200      1.22G     0.4733     0.5036     0.8401         86        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 0.9s<0.3s

     67/200      1.22G     0.4733     0.5036     0.8401         86        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.6it/s 0.4s

                   all          4         40      0.926          1      0.979      0.885

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     68/200      1.22G     0.3943     0.4798     0.8043         66        416: 0% ──────────── 0/4  0.3s

     68/200      1.22G     0.4238     0.4829     0.8146        106        416: 25% ━━━───────── 1/4 1.5it/s 0.5s<2.0s

     68/200      1.22G     0.4435     0.4863     0.8192        114        416: 50% ━━━━━━────── 2/4 2.6it/s 0.7s<0.8s

     68/200      1.22G     0.4195     0.4787      0.819         66        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.9s<0.3s

     68/200      1.22G     0.4195     0.4787      0.819         66        416: 100% ━━━━━━━━━━━━ 4/4 4.4it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.4it/s 0.1s

                   all          4         40      0.926          1      0.979      0.885

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     69/200      1.22G     0.5194     0.5117     0.8508         67        416: 0% ──────────── 0/4  0.2s

     69/200      1.22G     0.5024     0.4963     0.8493         94        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<2.0s

     69/200      1.22G     0.4541     0.4845     0.8454         91        416: 50% ━━━━━━────── 2/4 2.8it/s 0.6s<0.7s

     69/200      1.22G     0.4482     0.4884     0.8472         99        416: 75% ━━━━━━━━━─── 3/4 3.6it/s 0.7s<0.3s

     69/200      1.22G     0.4482     0.4884     0.8472         99        416: 100% ━━━━━━━━━━━━ 4/4 5.4it/s 0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.5it/s 0.4s

                   all          4         40      0.948      0.993      0.995      0.895

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     70/200      1.22G     0.4522     0.4477     0.8401         77        416: 0% ──────────── 0/4  0.2s

     70/200      1.22G     0.4874     0.4903     0.8286        134        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     70/200      1.22G     0.4648     0.4804     0.8181         81        416: 50% ━━━━━━────── 2/4 2.7it/s 0.6s<0.7s

     70/200      1.22G     0.4898     0.5021     0.8335         60        416: 75% ━━━━━━━━━─── 3/4 3.5it/s 0.8s<0.3s

     70/200      1.22G     0.4898     0.5021     0.8335         60        416: 100% ━━━━━━━━━━━━ 4/4 5.3it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.5it/s 0.1s

                   all          4         40      0.948      0.993      0.995      0.895

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     71/200      1.22G     0.4392     0.5462     0.7973         85        416: 0% ──────────── 0/4  0.2s

     71/200      1.22G     0.4206     0.5261     0.8085         60        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     71/200      1.22G     0.4403     0.5062     0.8169        104        416: 50% ━━━━━━────── 2/4 2.6it/s 0.6s<0.8s

     71/200      1.22G     0.4366     0.4983     0.8169        102        416: 75% ━━━━━━━━━─── 3/4 3.5it/s 0.8s<0.3s

     71/200      1.22G     0.4366     0.4983     0.8169        102        416: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.1it/s 0.3s

                   all          4         40      0.977      0.988      0.995      0.861

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     72/200      1.22G     0.4699     0.4714     0.8682         70        416: 0% ──────────── 0/4  0.2s

     72/200      1.22G     0.4545     0.4648     0.8511         87        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.2s

     72/200      1.22G     0.4515     0.4673     0.8437        130        416: 50% ━━━━━━────── 2/4 1.9it/s 0.7s<1.0s

     72/200      1.22G     0.4667       0.47     0.8387         65        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 0.9s<0.3s

     72/200      1.22G     0.4667       0.47     0.8387         65        416: 100% ━━━━━━━━━━━━ 4/4 4.4it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.8it/s 0.1s

                   all          4         40      0.977      0.988      0.995      0.861

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     73/200      1.22G     0.3881     0.4935     0.7929         66        416: 0% ──────────── 0/4  0.2s

     73/200      1.22G     0.3932     0.4864     0.8139         76        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     73/200      1.22G     0.4344     0.4839     0.8337        105        416: 50% ━━━━━━────── 2/4 2.6it/s 0.6s<0.8s

     73/200      1.22G     0.4444     0.4792     0.8311        103        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.8s<0.3s

     73/200      1.22G     0.4444     0.4792     0.8311        103        416: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.7it/s 0.4s

                   all          4         40      0.939       0.99      0.995      0.821

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     74/200      1.22G     0.5125     0.5051     0.8401        124        416: 0% ──────────── 0/4  0.2s

     74/200      1.22G     0.4813     0.4958     0.8338        107        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     74/200      1.22G     0.4454     0.5588     0.8432         28        416: 50% ━━━━━━────── 2/4 2.1it/s 0.7s<1.0s

     74/200      1.22G     0.4539     0.5419     0.8515         93        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 0.9s<0.3s

     74/200      1.22G     0.4539     0.5419     0.8515         93        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.6it/s 0.1s

                   all          4         40      0.939       0.99      0.995      0.821

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     75/200      1.22G     0.5162     0.4863     0.8388        128        416: 0% ──────────── 0/4  0.2s

     75/200      1.22G      0.461     0.5282     0.8259         53        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     75/200      1.22G     0.4393     0.5063     0.8261         87        416: 50% ━━━━━━────── 2/4 2.6it/s 0.6s<0.8s

     75/200      1.22G     0.4426     0.4892     0.8241         84        416: 75% ━━━━━━━━━─── 3/4 3.4it/s 0.8s<0.3s

     75/200      1.22G     0.4426     0.4892     0.8241         84        416: 100% ━━━━━━━━━━━━ 4/4 5.1it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.9it/s 0.3s

                   all          4         40      0.935      0.995      0.979      0.784

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     76/200      1.22G     0.3938     0.5041     0.8234         49        416: 0% ──────────── 0/4  0.2s

     76/200      1.22G     0.3788     0.4942     0.8277        103        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.1s

     76/200      1.22G     0.3818      0.467     0.8238         76        416: 50% ━━━━━━────── 2/4 2.6it/s 0.6s<0.8s

     76/200      1.22G     0.3987     0.4727     0.8196        123        416: 75% ━━━━━━━━━─── 3/4 2.8it/s 0.9s<0.4s

     76/200      1.22G     0.3987     0.4727     0.8196        123        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.8it/s 0.1s

                   all          4         40      0.935      0.995      0.979      0.784

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     77/200      1.22G     0.4338     0.4634     0.8258         90        416: 0% ──────────── 0/4  0.2s

     77/200      1.22G     0.4217     0.4554      0.817         73        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     77/200      1.22G     0.4411     0.4665     0.8232        133        416: 50% ━━━━━━────── 2/4 2.0it/s 0.7s<1.0s

     77/200      1.22G     0.4681      0.481     0.8414         55        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 0.9s<0.3s

     77/200      1.22G     0.4681      0.481     0.8414         55        416: 100% ━━━━━━━━━━━━ 4/4 4.3it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.2it/s 0.3s

                   all          4         40      0.921          1      0.979      0.813

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     78/200      1.22G     0.4241     0.4881     0.8397         95        416: 0% ──────────── 0/4  0.2s

     78/200      1.22G     0.4084     0.4571     0.8235        106        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     78/200      1.22G     0.4095     0.4618     0.8205         59        416: 50% ━━━━━━────── 2/4 2.7it/s 0.6s<0.7s

     78/200      1.22G      0.423     0.4584     0.8313         92        416: 75% ━━━━━━━━━─── 3/4 3.6it/s 0.8s<0.3s

     78/200      1.22G      0.423     0.4584     0.8313         92        416: 100% ━━━━━━━━━━━━ 4/4 5.3it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.5it/s 0.1s

                   all          4         40      0.921          1      0.979      0.813

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     79/200      1.22G      0.468     0.4787     0.8511         56        416: 0% ──────────── 0/4  0.2s

     79/200      1.22G     0.4799     0.4578     0.8524        103        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.2s

     79/200      1.22G     0.4532     0.4516     0.8409        122        416: 50% ━━━━━━────── 2/4 1.9it/s 0.7s<1.1s

     79/200      1.22G     0.4413     0.4614     0.8366         71        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 0.9s<0.3s

     79/200      1.22G     0.4413     0.4614     0.8366         71        416: 100% ━━━━━━━━━━━━ 4/4 4.4it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.4it/s 0.3s

                   all          4         40      0.984      0.994      0.995      0.887

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     80/200      1.22G      0.497     0.4498     0.8186         93        416: 0% ──────────── 0/4  0.2s

     80/200      1.22G     0.4466     0.4444     0.8144        133        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     80/200      1.22G     0.4201     0.4524     0.8197         57        416: 50% ━━━━━━────── 2/4 2.7it/s 0.6s<0.7s

     80/200      1.22G     0.4205     0.4498     0.8236         69        416: 75% ━━━━━━━━━─── 3/4 3.6it/s 0.8s<0.3s

     80/200      1.22G     0.4205     0.4498     0.8236         69        416: 100% ━━━━━━━━━━━━ 4/4 5.3it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.1it/s 0.1s

                   all          4         40      0.984      0.994      0.995      0.887

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     81/200      1.22G     0.4413     0.5463     0.8086         41        416: 0% ──────────── 0/4  0.3s

     81/200      1.22G     0.4365     0.4941     0.8118        114        416: 25% ━━━───────── 1/4 1.5it/s 0.5s<1.9s

     81/200      1.22G     0.4175     0.4921     0.8158        118        416: 50% ━━━━━━────── 2/4 2.5it/s 0.7s<0.8s

     81/200      1.22G     0.4344     0.4828     0.8277         79        416: 75% ━━━━━━━━━─── 3/4 2.8it/s 1.0s<0.4s

     81/200      1.22G     0.4344     0.4828     0.8277         79        416: 100% ━━━━━━━━━━━━ 4/4 3.9it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.0it/s 0.3s

                   all          4         40      0.984      0.997      0.995      0.894

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     82/200      1.22G     0.4247     0.4455     0.8202        105        416: 0% ──────────── 0/4  0.2s

     82/200      1.22G     0.4735     0.4613     0.8337         93        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<1.9s

     82/200      1.23G     0.4935     0.4762     0.8378         78        416: 50% ━━━━━━────── 2/4 2.3it/s 0.6s<0.9s

     82/200      1.21G     0.5198     0.4826       0.84         75        416: 75% ━━━━━━━━━─── 3/4 2.8it/s 0.9s<0.4s

     82/200      1.21G     0.5198     0.4826       0.84         75        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.8it/s 0.1s

                   all          4         40      0.984      0.997      0.995      0.894

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     83/200      1.24G     0.4244     0.4938     0.8247         61        416: 0% ──────────── 0/4  0.3s

     83/200      1.24G     0.4672     0.4912     0.8169         90        416: 25% ━━━───────── 1/4 1.1it/s 0.6s<2.7s

     83/200      1.22G     0.4727       0.49     0.8267        130        416: 50% ━━━━━━────── 2/4 2.0it/s 0.8s<1.0s

     83/200      1.21G     0.4632     0.4899     0.8183         71        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 1.0s<0.3s

     83/200      1.21G     0.4632     0.4899     0.8183         71        416: 100% ━━━━━━━━━━━━ 4/4 4.0it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.8it/s 0.4s

                   all          4         40      0.977          1      0.995      0.877

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     84/200      1.22G     0.4877     0.5021     0.8157        135        416: 0% ──────────── 0/4  0.4s

     84/200      1.22G     0.4469     0.4822     0.8293         93        416: 25% ━━━───────── 1/4 1.5it/s 0.6s<2.0s

     84/200      1.22G     0.4329     0.4659     0.8248         81        416: 50% ━━━━━━────── 2/4 2.6it/s 0.7s<0.8s

     84/200      1.22G     0.4476     0.4798     0.8235         43        416: 75% ━━━━━━━━━─── 3/4 2.8it/s 1.0s<0.4s

     84/200      1.22G     0.4476     0.4798     0.8235         43        416: 100% ━━━━━━━━━━━━ 4/4 3.8it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.8it/s 0.1s

                   all          4         40      0.977          1      0.995      0.877

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     85/200      1.22G     0.3727     0.5234     0.8115         36        416: 0% ──────────── 0/4  0.3s

     85/200      1.22G     0.3943     0.5216     0.8178        144        416: 25% ━━━───────── 1/4 1.1s/it 0.6s<3.2s

     85/200      1.24G     0.4451     0.5008     0.8193        111        416: 50% ━━━━━━────── 2/4 2.1it/s 0.8s<0.9s

     85/200      1.24G      0.459     0.4949     0.8255         61        416: 75% ━━━━━━━━━─── 3/4 3.2it/s 1.0s<0.3s

     85/200      1.24G      0.459     0.4949     0.8255         61        416: 100% ━━━━━━━━━━━━ 4/4 3.9it/s 1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.8it/s 0.4s

                   all          4         40       0.96      0.995      0.995       0.86

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     86/200      1.21G     0.4204     0.5435      0.918         36        416: 0% ──────────── 0/4  0.2s

     86/200      1.23G     0.4308     0.5164     0.8916        110        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<2.0s

     86/200      1.24G     0.4448     0.5101     0.8694        126        416: 50% ━━━━━━────── 2/4 2.6it/s 0.6s<0.8s

     86/200      1.24G     0.4733     0.4994     0.8642         80        416: 75% ━━━━━━━━━─── 3/4 3.2it/s 0.8s<0.3s

     86/200      1.24G     0.4733     0.4994     0.8642         80        416: 100% ━━━━━━━━━━━━ 4/4 5.0it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.4it/s 0.1s

                   all          4         40       0.96      0.995      0.995       0.86

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     87/200      1.22G     0.4911     0.4419     0.8287         85        416: 0% ──────────── 0/4  0.2s

     87/200      1.22G     0.4456     0.4302     0.8339         84        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<2.0s

     87/200      1.22G     0.4735     0.4525     0.8394        125        416: 50% ━━━━━━────── 2/4 2.5it/s 0.6s<0.8s

     87/200      1.22G     0.4649     0.4596     0.8418         57        416: 75% ━━━━━━━━━─── 3/4 3.5it/s 0.8s<0.3s

     87/200      1.22G     0.4649     0.4596     0.8418         57        416: 100% ━━━━━━━━━━━━ 4/4 5.2it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.8it/s 0.4s

                   all          4         40      0.954      0.966      0.995      0.866

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     88/200      1.22G     0.4455     0.4972     0.8506         71        416: 0% ──────────── 0/4  0.2s

     88/200      1.22G     0.4799     0.4705     0.8617        101        416: 25% ━━━───────── 1/4 1.5it/s 0.4s<2.0s

     88/200      1.22G     0.4601     0.4527      0.847         98        416: 50% ━━━━━━────── 2/4 2.5it/s 0.6s<0.8s

     88/200      1.21G     0.4468     0.4466      0.846         81        416: 75% ━━━━━━━━━─── 3/4 3.2it/s 0.8s<0.3s

     88/200      1.21G     0.4468     0.4466      0.846         81        416: 100% ━━━━━━━━━━━━ 4/4 4.7it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.7it/s 0.1s

                   all          4         40      0.954      0.966      0.995      0.866

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     89/200      1.23G     0.3869     0.4212     0.8201        102        416: 0% ──────────── 0/4  0.3s

     89/200      1.24G     0.4416     0.4238     0.8253        104        416: 25% ━━━───────── 1/4 1.4it/s 0.5s<2.2s

     89/200      1.24G     0.4525     0.4443     0.8257         79        416: 50% ━━━━━━────── 2/4 2.4it/s 0.7s<0.8s

     89/200      1.24G     0.4631     0.4694     0.8217         67        416: 75% ━━━━━━━━━─── 3/4 3.5it/s 0.9s<0.3s

     89/200      1.24G     0.4631     0.4694     0.8217         67        416: 100% ━━━━━━━━━━━━ 4/4 4.6it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.2it/s 0.3s

                   all          4         40      0.955      0.994      0.995      0.856

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     90/200      1.24G      0.559     0.5038     0.8601        111        416: 0% ──────────── 0/4  0.2s

     90/200      1.24G     0.5073     0.4712      0.833         86        416: 25% ━━━───────── 1/4 1.7it/s 0.3s<1.8s

     90/200      1.24G     0.5315      0.484     0.8274         52        416: 50% ━━━━━━────── 2/4 2.8it/s 0.5s<0.7s

     90/200      1.24G     0.5291     0.4776     0.8395        103        416: 75% ━━━━━━━━━─── 3/4 3.6it/s 0.7s<0.3s

     90/200      1.24G     0.5291     0.4776     0.8395        103        416: 100% ━━━━━━━━━━━━ 4/4 5.6it/s 0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.8it/s 0.1s

                   all          4         40      0.955      0.994      0.995      0.856

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     91/200      1.24G     0.5035     0.4689     0.8528         98        416: 0% ──────────── 0/4  0.2s

     91/200      1.24G     0.4463     0.4573     0.8382         73        416: 25% ━━━───────── 1/4 1.6it/s 0.4s<1.9s

     91/200      1.24G     0.4293     0.4722     0.8257         60        416: 50% ━━━━━━────── 2/4 2.7it/s 0.6s<0.7s

     91/200      1.24G     0.4464     0.4707     0.8344        120        416: 75% ━━━━━━━━━─── 3/4 2.9it/s 0.9s<0.3s

     91/200      1.24G     0.4464     0.4707     0.8344        120        416: 100% ━━━━━━━━━━━━ 4/4 4.6it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.1it/s 0.3s

                   all          4         40      0.978          1      0.995      0.854

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     92/200      1.24G     0.4145     0.4629     0.8253         62        416: 0% ──────────── 0/4  0.2s

     92/200      1.24G     0.4771     0.4725     0.8468        103        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.2s

     92/200      1.24G     0.4582     0.4535     0.8378         93        416: 50% ━━━━━━────── 2/4 2.4it/s 0.6s<0.9s

     92/200      1.24G     0.4614     0.4493     0.8351         94        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 0.9s<0.3s

     92/200      1.24G     0.4614     0.4493     0.8351         94        416: 100% ━━━━━━━━━━━━ 4/4 4.7it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.8it/s 0.1s

                   all          4         40      0.978          1      0.995      0.854

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     93/200      1.24G     0.3833     0.4513     0.8332        101        416: 0% ──────────── 0/4  0.2s

     93/200      1.24G      0.453     0.4464      0.832         90        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.2s

     93/200      1.24G     0.4662     0.4541     0.8246        106        416: 50% ━━━━━━────── 2/4 2.3it/s 0.7s<0.9s

     93/200      1.24G     0.4473     0.4491     0.8264         55        416: 75% ━━━━━━━━━─── 3/4 3.1it/s 0.9s<0.3s

     93/200      1.24G     0.4473     0.4491     0.8264         55        416: 100% ━━━━━━━━━━━━ 4/4 4.6it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.8it/s 0.5s

                   all          4         40      0.971          1      0.995      0.873

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     94/200      1.24G     0.4212     0.4059     0.8133         95        416: 0% ──────────── 0/4  0.2s

     94/200      1.24G     0.4116     0.4253     0.8045         79        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.1s

     94/200      1.24G     0.4245     0.4245     0.8092        108        416: 50% ━━━━━━────── 2/4 2.4it/s 0.7s<0.8s

     94/200      1.24G     0.4283     0.4221     0.8102         70        416: 75% ━━━━━━━━━─── 3/4 3.1it/s 0.9s<0.3s

     94/200      1.24G     0.4283     0.4221     0.8102         70        416: 100% ━━━━━━━━━━━━ 4/4 4.6it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.0it/s 0.1s

                   all          4         40      0.971          1      0.995      0.873

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     95/200      1.24G     0.4012      0.413       0.83        115        416: 0% ──────────── 0/4  0.2s

     95/200      1.24G     0.4899     0.4479      0.841         98        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.1s

     95/200      1.22G     0.4894     0.4533     0.8395         92        416: 50% ━━━━━━────── 2/4 2.2it/s 0.7s<0.9s

     95/200      1.22G     0.4582     0.4439     0.8412         47        416: 75% ━━━━━━━━━─── 3/4 2.2it/s 1.1s<0.4s

     95/200      1.22G     0.4582     0.4439     0.8412         47        416: 100% ━━━━━━━━━━━━ 4/4 3.6it/s 1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.7it/s 0.6s

                   all          4         40      0.955      0.997      0.995      0.877

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     96/200      1.22G     0.4056     0.4052     0.8195        100        416: 0% ──────────── 0/4  0.2s

     96/200      1.22G     0.4188     0.4243     0.8098         89        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.2s

     96/200      1.22G     0.4518     0.4209     0.8227        111        416: 50% ━━━━━━────── 2/4 2.4it/s 0.7s<0.8s

     96/200      1.22G     0.4542     0.4405     0.8154         52        416: 75% ━━━━━━━━━─── 3/4 3.3it/s 0.8s<0.3s

     96/200      1.22G     0.4542     0.4405     0.8154         52        416: 100% ━━━━━━━━━━━━ 4/4 4.7it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.1it/s 0.1s

                   all          4         40      0.955      0.997      0.995      0.877

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     97/200      1.22G     0.3816     0.4031     0.8257         81        416: 0% ──────────── 0/4  0.2s

     97/200      1.22G     0.4098     0.4203     0.8146        102        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.1s

     97/200      1.22G     0.4291     0.4251      0.818        139        416: 50% ━━━━━━────── 2/4 1.7it/s 0.9s<1.2s

     97/200      1.22G     0.4449     0.4774     0.8183         30        416: 75% ━━━━━━━━━─── 3/4 1.6it/s 1.5s<0.6s

     97/200      1.22G     0.4449     0.4774     0.8183         30        416: 100% ━━━━━━━━━━━━ 4/4 2.6it/s 1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.9it/s 0.5s

                   all          4         40      0.939      0.979      0.995      0.869

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     98/200      1.22G     0.4464     0.4116     0.8209         90        416: 0% ──────────── 0/4  0.2s

     98/200      1.22G      0.505     0.4449     0.8382         89        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.1s

     98/200      1.22G     0.4957     0.4433     0.8343         79        416: 50% ━━━━━━────── 2/4 2.4it/s 0.6s<0.8s

     98/200      1.22G      0.457     0.4347     0.8308         94        416: 75% ━━━━━━━━━─── 3/4 3.1it/s 0.9s<0.3s

     98/200      1.22G      0.457     0.4347     0.8308         94        416: 100% ━━━━━━━━━━━━ 4/4 4.7it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.7it/s 0.1s

                   all          4         40      0.939      0.979      0.995      0.869

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     99/200      1.22G     0.5029     0.4222     0.8391         85        416: 0% ──────────── 0/4  0.2s

     99/200      1.22G     0.4864     0.4352     0.8335         65        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.2s

     99/200      1.22G     0.4838     0.4328     0.8333         84        416: 50% ━━━━━━────── 2/4 2.3it/s 0.7s<0.9s

     99/200      1.22G     0.4782      0.436     0.8308        117        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 0.9s<0.3s

     99/200      1.22G     0.4782      0.436     0.8308        117        416: 100% ━━━━━━━━━━━━ 4/4 4.6it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.6it/s 0.6s

                   all          4         40      0.972      0.933      0.944      0.788

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    100/200      1.21G     0.3847      0.423     0.7893         64        416: 0% ──────────── 0/4  0.2s

    100/200      1.24G      0.397     0.4407     0.8081        135        416: 25% ━━━───────── 1/4 1.3it/s 0.5s<2.3s

    100/200      1.23G     0.4044     0.5331     0.8238         28        416: 50% ━━━━━━────── 2/4 2.3it/s 0.7s<0.9s

    100/200      1.21G     0.4196      0.508     0.8212        124        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 0.9s<0.3s

    100/200      1.21G     0.4196      0.508     0.8212        124        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.0it/s 0.1s

                   all          4         40      0.972      0.933      0.944      0.788

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    101/200      1.23G     0.4837     0.4484     0.8547        107        416: 0% ──────────── 0/4  0.2s

    101/200      1.23G     0.4525     0.4305      0.831        112        416: 25% ━━━───────── 1/4 1.4it/s 0.5s<2.2s

    101/200      1.23G     0.4595     0.4206     0.8278         96        416: 50% ━━━━━━────── 2/4 2.3it/s 0.7s<0.9s

    101/200      1.23G      0.437     0.4476     0.8331         37        416: 75% ━━━━━━━━━─── 3/4 2.0it/s 1.3s<0.5s

    101/200      1.23G      0.437     0.4476     0.8331         37        416: 100% ━━━━━━━━━━━━ 4/4 3.0it/s 1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.9it/s 0.5s

                   all          4         40      0.965      0.933      0.925      0.754

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    102/200      1.22G     0.4654     0.4494     0.8327         82        416: 0% ──────────── 0/4  0.2s

    102/200      1.22G     0.4797     0.4413     0.8275        127        416: 25% ━━━───────── 1/4 1.5s/it 0.7s<4.5s

    102/200      1.22G     0.5216     0.4619      0.831         65        416: 50% ━━━━━━────── 2/4 1.9it/s 0.9s<1.1s

    102/200      1.22G     0.4949     0.4524     0.8317         78        416: 75% ━━━━━━━━━─── 3/4 2.8it/s 1.1s<0.4s

    102/200      1.22G     0.4949     0.4524     0.8317         78        416: 100% ━━━━━━━━━━━━ 4/4 3.6it/s 1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.2it/s 0.1s

                   all          4         40      0.965      0.933      0.925      0.754

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    103/200      1.22G     0.4429     0.4529     0.8232        130        416: 0% ──────────── 0/4  0.2s

    103/200      1.22G     0.4174     0.4483     0.8188         61        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.2s

    103/200      1.22G     0.4305     0.4388     0.8184        100        416: 50% ━━━━━━────── 2/4 2.3it/s 0.7s<0.9s

    103/200      1.22G     0.4373     0.4543     0.8191         61        416: 75% ━━━━━━━━━─── 3/4 3.7it/s 0.8s<0.3s

    103/200      1.22G     0.4373     0.4543     0.8191         61        416: 100% ━━━━━━━━━━━━ 4/4 4.9it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.6it/s 0.6s

                   all          4         40      0.954      0.933      0.938      0.789

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    104/200      1.22G     0.4113     0.4103     0.8251        103        416: 0% ──────────── 0/4  0.2s

    104/200      1.22G      0.449      0.443     0.8434        121        416: 25% ━━━───────── 1/4 1.3it/s 0.5s<2.3s

    104/200      1.22G     0.4502     0.4367     0.8451         76        416: 50% ━━━━━━────── 2/4 2.3it/s 0.7s<0.9s

    104/200      1.22G     0.4286     0.4352     0.8355         52        416: 75% ━━━━━━━━━─── 3/4 3.1it/s 0.9s<0.3s

    104/200      1.22G     0.4286     0.4352     0.8355         52        416: 100% ━━━━━━━━━━━━ 4/4 4.6it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.1it/s 0.1s

                   all          4         40      0.954      0.933      0.938      0.789

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    105/200      1.22G     0.4766     0.4385     0.8216         73        416: 0% ──────────── 0/4  0.2s

    105/200      1.22G     0.4466      0.444     0.8254         79        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.1s

    105/200      1.22G     0.4622     0.4335     0.8291        114        416: 50% ━━━━━━────── 2/4 2.3it/s 0.7s<0.9s

    105/200      1.22G     0.4407      0.431     0.8239         86        416: 75% ━━━━━━━━━─── 3/4 2.9it/s 0.9s<0.3s

    105/200      1.22G     0.4407      0.431     0.8239         86        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.6it/s 0.6s

                   all          4         40      0.955      0.933      0.952      0.825

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    106/200      1.22G     0.4047     0.4274     0.8444         82        416: 0% ──────────── 0/4  0.2s

    106/200      1.22G     0.4103     0.4226      0.824         99        416: 25% ━━━───────── 1/4 1.3it/s 0.5s<2.3s

    106/200      1.22G     0.4172     0.4126     0.8142        104        416: 50% ━━━━━━────── 2/4 2.3it/s 0.7s<0.9s

    106/200      1.22G     0.4282     0.4132     0.8201         65        416: 75% ━━━━━━━━━─── 3/4 3.1it/s 0.9s<0.3s

    106/200      1.22G     0.4282     0.4132     0.8201         65        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.7it/s 0.1s

                   all          4         40      0.955      0.933      0.952      0.825

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    107/200      1.22G     0.4265     0.4746     0.8385         72        416: 0% ──────────── 0/4  0.2s

    107/200      1.22G     0.4619     0.4643     0.8309         85        416: 25% ━━━───────── 1/4 1.2it/s 0.5s<2.4s

    107/200      1.22G     0.4626     0.4457     0.8293         77        416: 50% ━━━━━━────── 2/4 2.2it/s 0.7s<0.9s

    107/200      1.22G     0.4725     0.4435     0.8334        117        416: 75% ━━━━━━━━━─── 3/4 2.9it/s 0.9s<0.3s

    107/200      1.22G     0.4725     0.4435     0.8334        117        416: 100% ━━━━━━━━━━━━ 4/4 4.4it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.4it/s 0.7s

                   all          4         40      0.968      0.933      0.973      0.866

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    108/200      1.22G     0.4331     0.4231      0.795         83        416: 0% ──────────── 0/4  0.2s

    108/200      1.23G     0.4173     0.4613     0.7955         36        416: 25% ━━━───────── 1/4 1.3it/s 0.5s<2.2s

    108/200      1.25G     0.4163     0.4451     0.8019        101        416: 50% ━━━━━━────── 2/4 2.8it/s 0.6s<0.7s

    108/200      1.25G     0.4302     0.4451     0.8066        132        416: 75% ━━━━━━━━━─── 3/4 3.2it/s 0.9s<0.3s

    108/200      1.25G     0.4302     0.4451     0.8066        132        416: 100% ━━━━━━━━━━━━ 4/4 4.6it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.2it/s 0.1s

                   all          4         40      0.968      0.933      0.973      0.866

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    109/200      1.25G     0.3949     0.4178     0.8001         87        416: 0% ──────────── 0/4  0.2s

    109/200      1.25G     0.4766     0.4327     0.8119        138        416: 25% ━━━───────── 1/4 1.6s/it 0.7s<4.9s

    109/200      1.25G     0.4764     0.4294     0.8297         82        416: 50% ━━━━━━────── 2/4 1.7it/s 1.0s<1.2s

    109/200      1.25G     0.4689     0.4436      0.841         45        416: 75% ━━━━━━━━━─── 3/4 1.9it/s 1.4s<0.5s

    109/200      1.25G     0.4689     0.4436      0.841         45        416: 100% ━━━━━━━━━━━━ 4/4 2.8it/s 1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.0it/s 0.5s

                   all          4         40      0.877      0.983      0.976      0.878

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    110/200      1.24G     0.3925     0.3903     0.8077         82        416: 0% ──────────── 0/4  0.2s

    110/200      1.22G     0.4308     0.4014     0.8183         80        416: 25% ━━━───────── 1/4 1.3it/s 0.4s<2.3s

    110/200      1.24G     0.4134     0.4012     0.8196         69        416: 50% ━━━━━━────── 2/4 2.3it/s 0.6s<0.9s

    110/200      1.22G     0.4245     0.4222     0.8272        121        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 0.8s<0.3s

    110/200      1.22G     0.4245     0.4222     0.8272        121        416: 100% ━━━━━━━━━━━━ 4/4 4.8it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.3it/s 0.1s

                   all          4         40      0.877      0.983      0.976      0.878

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    111/200      1.24G     0.4989     0.3973     0.8386        126        416: 0% ──────────── 0/4  0.2s

    111/200      1.24G     0.4407     0.3944     0.8266         69        416: 25% ━━━───────── 1/4 1.3it/s 0.5s<2.4s

    111/200      1.24G     0.4196     0.3984     0.8173        103        416: 50% ━━━━━━────── 2/4 2.2it/s 0.7s<0.9s

    111/200      1.21G     0.4462     0.4191     0.8192         54        416: 75% ━━━━━━━━━─── 3/4 2.9it/s 0.9s<0.3s

    111/200      1.21G     0.4462     0.4191     0.8192         54        416: 100% ━━━━━━━━━━━━ 4/4 4.3it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.7it/s 0.6s

                   all          4         40      0.909      0.986      0.977      0.872

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    112/200      1.22G     0.3804     0.3878     0.8162         82        416: 0% ──────────── 0/4  0.2s

    112/200      1.22G     0.4128     0.4123     0.8259         79        416: 25% ━━━───────── 1/4 1.4it/s 0.4s<2.2s

    112/200      1.24G     0.4175      0.411     0.8213        128        416: 50% ━━━━━━────── 2/4 2.3it/s 0.7s<0.9s

    112/200      1.24G     0.4368     0.4215     0.8337         63        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 0.9s<0.3s

    112/200      1.24G     0.4368     0.4215     0.8337         63        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.8it/s 0.1s

                   all          4         40      0.909      0.986      0.977      0.872

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    113/200      1.22G     0.5021     0.4313     0.8268         99        416: 0% ──────────── 0/4  0.2s

    113/200      1.22G     0.4784     0.4277     0.8235        128        416: 25% ━━━───────── 1/4 1.3it/s 0.5s<2.3s

    113/200      1.22G     0.4544     0.4509     0.8213         46        416: 50% ━━━━━━────── 2/4 2.3it/s 0.7s<0.9s

    113/200      1.22G      0.443       0.44     0.8192         79        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 0.9s<0.3s

    113/200      1.22G      0.443       0.44     0.8192         79        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.8it/s 0.4s

                   all          4         40      0.938      0.988      0.977      0.862

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    114/200      1.21G     0.3831     0.5214     0.8314         34        416: 0% ──────────── 0/4  0.4s

    114/200      1.23G     0.4076     0.4666     0.8274         96        416: 25% ━━━───────── 1/4 1.4it/s 0.7s<2.2s

    114/200      1.23G     0.4274     0.4556     0.8236         93        416: 50% ━━━━━━────── 2/4 2.3it/s 0.9s<0.9s

    114/200      1.21G     0.4278     0.4577     0.8217        129        416: 75% ━━━━━━━━━─── 3/4 3.3it/s 1.1s<0.3s

    114/200      1.21G     0.4278     0.4577     0.8217        129        416: 100% ━━━━━━━━━━━━ 4/4 3.8it/s 1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.6it/s 0.1s

                   all          4         40      0.938      0.988      0.977      0.862

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    115/200      1.23G     0.4323     0.4065     0.8251         92        416: 0% ──────────── 0/4  0.2s

    115/200      1.23G     0.4075     0.4119     0.8272         79        416: 25% ━━━───────── 1/4 1.4it/s 0.5s<2.2s

    115/200      1.23G     0.4258     0.4376     0.8298         89        416: 50% ━━━━━━────── 2/4 2.8it/s 0.6s<0.7s

    115/200      1.23G     0.4127     0.4243     0.8236         91        416: 75% ━━━━━━━━━─── 3/4 3.3it/s 0.8s<0.3s

    115/200      1.23G     0.4127     0.4243     0.8236         91        416: 100% ━━━━━━━━━━━━ 4/4 4.7it/s 0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.0it/s 0.5s

                   all          4         40      0.939      0.985      0.977      0.856

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    116/200      1.23G     0.3652     0.4429     0.8188         90        416: 0% ──────────── 0/4  0.2s

    116/200      1.23G     0.3899     0.4213     0.8214        101        416: 25% ━━━───────── 1/4 1.4it/s 0.5s<2.2s

    116/200      1.23G     0.4129     0.4281     0.8236         77        416: 50% ━━━━━━────── 2/4 2.4it/s 0.7s<0.8s

    116/200      1.23G     0.4099     0.4194     0.8273         84        416: 75% ━━━━━━━━━─── 3/4 3.1it/s 0.9s<0.3s

    116/200      1.23G     0.4099     0.4194     0.8273         84        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.7it/s 0.1s

                   all          4         40      0.939      0.985      0.977      0.856

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    117/200      1.23G     0.5062     0.4717     0.8235         90        416: 0% ──────────── 0/4  0.2s

    117/200      1.23G     0.4409     0.4436     0.8283         80        416: 25% ━━━───────── 1/4 1.3it/s 0.5s<2.4s

    117/200      1.24G     0.4368     0.4373     0.8163         99        416: 50% ━━━━━━────── 2/4 2.1it/s 0.7s<0.9s

    117/200      1.24G      0.421     0.4373     0.8179         82        416: 75% ━━━━━━━━━─── 3/4 2.8it/s 0.9s<0.4s

    117/200      1.24G      0.421     0.4373     0.8179         82        416: 100% ━━━━━━━━━━━━ 4/4 4.3it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.1it/s 0.5s

                   all          4         40      0.889      0.993      0.973      0.852

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    118/200      1.22G     0.4082     0.4205     0.8219         68        416: 0% ──────────── 0/4  0.2s

    118/200      1.22G     0.4321     0.4481     0.8207        163        416: 25% ━━━───────── 1/4 1.6s/it 0.7s<4.7s

    118/200      1.22G     0.4396     0.4381     0.8187         84        416: 50% ━━━━━━────── 2/4 2.4it/s 0.8s<0.8s

    118/200      1.22G     0.4089     0.4376     0.8124         37        416: 75% ━━━━━━━━━─── 3/4 3.1it/s 1.1s<0.3s

    118/200      1.22G     0.4089     0.4376     0.8124         37        416: 100% ━━━━━━━━━━━━ 4/4 3.8it/s 1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.8it/s 0.1s

                   all          4         40      0.889      0.993      0.973      0.852

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    119/200      1.22G     0.3869     0.4155     0.8212        103        416: 0% ──────────── 0/4  0.2s

    119/200      1.22G     0.4099     0.4206     0.8378         98        416: 25% ━━━───────── 1/4 1.3it/s 0.5s<2.2s

    119/200      1.22G     0.4099     0.4153     0.8338         85        416: 50% ━━━━━━────── 2/4 2.2it/s 0.7s<0.9s

    119/200      1.22G     0.3871     0.4071     0.8297         66        416: 75% ━━━━━━━━━─── 3/4 3.0it/s 0.9s<0.3s

    119/200      1.22G     0.3871     0.4071     0.8297         66        416: 100% ━━━━━━━━━━━━ 4/4 4.5it/s 0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.8it/s 0.6s

                   all          4         40      0.958      0.929      0.952      0.842

EarlyStopping: Training stopped early as no improvement observed in last 50 epochs. Best results observed at epoch 69, best model saved as best.pt.
To update EarlyStopping(patience=50) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

119 epochs completed in 0.055 hours.

Optimizer stripped from /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/v2/detect/coins_v2/weights/last.pt, 6.2MB

Optimizer stripped from /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/v2/detect/coins_v2/weights/best.pt, 6.2MB

Validating /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/v2/detect/coins_v2/weights/best.pt...

Ultralytics 8.4.47 🚀 Python-3.12.7 torch-2.11.0 MPS (Apple M3 Pro)

Model summary (fused): 73 layers, 3,006,623 parameters, 0 gradients, 8.1 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.5s/it 1.5s

                   all          4         40      0.949      0.993      0.995      0.895

                   100          2         10      0.963          1      0.995      0.876

                  1000          2          4      0.944          1      0.995      0.902

                   200          3         17      0.882          1      0.995      0.906

                    50          3          3          1      0.965      0.995      0.896

                   500          2          6      0.955          1      0.995      0.895

Speed: 0.3ms preprocess, 145.3ms inference, 0.0ms loss, 64.3ms postprocess per image

Results saved to /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/v2/detect/coins_v2

Entrenamiento finalizado.

## 2. Persistencia del mejor checkpoint

In [3]:
best_pt = RUNS_DIR / "detect" / RUN_NAME / "weights" / "best.pt"
last_pt = RUNS_DIR / "detect" / RUN_NAME / "weights" / "last.pt"
assert best_pt.exists(), f"No se encontró {best_pt}"
shutil.copy2(best_pt, MODEL_DIR / "best.pt")
if last_pt.exists():
    shutil.copy2(last_pt, MODEL_DIR / "last.pt")
print("Pesos copiados a:", MODEL_DIR)
for p in sorted(MODEL_DIR.iterdir()):
    print("  -", p.name, f"({p.stat().st_size / 1024 / 1024:.1f} MB)")

Pesos copiados a: /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/model/v2
  - best.pt (5.9 MB)
  - last.pt (5.9 MB)

## 3. Métricas finales sobre VALID y TEST

In [4]:
best_model = YOLO(str(MODEL_DIR / "best.pt"))

def metrics_to_row(m, split):
    return {
        "split": split,
        "precision": float(m.box.mp),
        "recall": float(m.box.mr),
        "mAP@0.5": float(m.box.map50),
        "mAP@0.5:0.95": float(m.box.map),
    }

val_metrics = best_model.val(
    data=str(DATA_YAML), split="val", device=DEVICE, imgsz=IMG_SIZE,
    project=str(RUNS_DIR / "detect"), name=f"{RUN_NAME}_val", exist_ok=True, plots=True,
)
test_metrics = best_model.val(
    data=str(DATA_YAML), split="test", device=DEVICE, imgsz=IMG_SIZE,
    project=str(RUNS_DIR / "detect"), name=f"{RUN_NAME}_test", exist_ok=True, plots=True,
)

df_metrics = pd.DataFrame([
    metrics_to_row(val_metrics, "valid"),
    metrics_to_row(test_metrics, "test"),
]).set_index("split")
df_metrics.to_csv(REPORTS / "metrics_summary.csv")
df_metrics.round(4)

Ultralytics 8.4.47 🚀 Python-3.12.7 torch-2.11.0 MPS (Apple M3 Pro)

Model summary (fused): 73 layers, 3,006,623 parameters, 0 gradients, 8.1 GFLOPs

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1677.4±109.2 MB/s, size: 71.5 KB)

val: Scanning /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_v2/valid/labels.cache... 4 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 4/4 4.2Mit/s 0.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 18.0it/s 0.1s

                   all          4         40      0.949      0.993      0.995      0.895

                   100          2         10      0.963          1      0.995      0.876

                  1000          2          4      0.944          1      0.995      0.902

                   200          3         17      0.882          1      0.995      0.906

                    50          3          3          1      0.965      0.995      0.896

                   500          2          6      0.955          1      0.995      0.895

Speed: 0.3ms preprocess, 2.6ms inference, 0.0ms loss, 2.1ms postprocess per image

Results saved to /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/v2/detect/coins_v2_val

Ultralytics 8.4.47 🚀 Python-3.12.7 torch-2.11.0 MPS (Apple M3 Pro)

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 224.0±81.1 MB/s, size: 72.9 KB)

val: Scanning /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_v2/test/labels... 4 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 4/4 2.1Kit/s 0.0s

val: New cache created: /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/dataset_v2/test/labels.cache

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.8it/s 0.6s

                   all          4         26      0.922          1      0.995        0.9

                   100          3          8      0.945          1      0.995      0.906

                  1000          1          2      0.883          1      0.995       0.92

                   200          3          9      0.928          1      0.995      0.902

                    50          3          3      0.971          1      0.995      0.852

                   500          3          4      0.881          1      0.995       0.92

Speed: 0.3ms preprocess, 3.5ms inference, 0.0ms loss, 34.7ms postprocess per image

Results saved to /Users/ccepeda/Documents/Personales/Maestria/SistemaRecomendacion/runs/v2/detect/coins_v2_test

       precision  recall  mAP@0.5  mAP@0.5:0.95
split
valid     0.9487   0.993    0.995        0.8950
test      0.9216   1.000    0.995        0.8999

## 4. Métricas por clase (sobre VALID)

In [5]:
names = best_model.names
p_cls = val_metrics.box.p
r_cls = val_metrics.box.r
ap50 = val_metrics.box.ap50
ap = val_metrics.box.ap.mean(axis=1) if val_metrics.box.ap.ndim > 1 else val_metrics.box.ap
ids = val_metrics.box.ap_class_index

df_cls = pd.DataFrame({
    "class": [names[int(i)] for i in ids],
    "precision": np.round(p_cls, 4),
    "recall":    np.round(r_cls, 4),
    "mAP@0.5":   np.round(ap50, 4),
    "mAP@0.5:0.95": np.round(ap, 4),
})
df_cls.to_csv(REPORTS / "metrics_per_class_valid.csv", index=False)
df_cls

  class  precision  recall  mAP@0.5  mAP@0.5:0.95
0   100     0.9631  1.0000    0.995        0.8756
1  1000     0.9440  1.0000    0.995        0.9016
2   200     0.8815  1.0000    0.995        0.9065
3    50     1.0000  0.9652    0.995        0.8960
4   500     0.9549  1.0000    0.995        0.8955

## 5. Inferencia de ejemplo sobre TEST con desglose monetario

La clase `modenas` (id=5) suma 0 COP — se considera moneda genérica de denominación desconocida.

In [6]:
import yaml
with open(DATA_YAML) as f:
    cfg = yaml.safe_load(f)
_names = cfg["names"]
if isinstance(_names, dict):
    _names = [_names[i] for i in sorted(_names)]
VALUE_COP = {i: (int(n) if str(n).isdigit() else 0) for i, n in enumerate(_names)}

test_dir = ROOT / "dataset_v2" / "test" / "images"
test_imgs = sorted(test_dir.iterdir())
n = len(test_imgs)
cols = 2; rows = (n + cols - 1) // cols
fig, axes = plt.subplots(rows, cols, figsize=(12, 5 * rows))
axes = np.array(axes).reshape(-1)
for ax, img_path in zip(axes, test_imgs):
    pred = best_model.predict(
        source=str(img_path), conf=0.25, imgsz=IMG_SIZE, device=DEVICE, verbose=False,
    )[0]
    counts = {}
    total_cop = 0
    for cls_id in pred.boxes.cls.cpu().numpy().astype(int):
        nm = pred.names[int(cls_id)]
        counts[nm] = counts.get(nm, 0) + 1
        total_cop += VALUE_COP.get(int(cls_id), 0)
    annotated = pred.plot()
    ax.imshow(annotated[:, :, ::-1])
    summary = " · ".join(f"{k}: {v}" for k, v in sorted(counts.items())) or "(sin detecciones)"
    ax.set_title(f"{img_path.name[:30]}\n{summary}\nTOTAL = {total_cop} COP", fontsize=9)
    ax.axis("off")
for ax in axes[n:]:
    ax.axis("off")
plt.tight_layout()
plt.savefig(REPORTS / "test_inference.png", dpi=120)
plt.show()

## 6. Resumen y siguientes pasos

Al terminar este notebook:
- `model/v2/best.pt` — modelo listo para exportar a ONNX en Fase 3.
- `reports/v2/metrics_*.csv` — métricas reportables en la tesis.
- `runs/v2/detect/coins_v2/` — curvas de pérdida, matriz de confusión, predicciones del split valid (`val_batch0_pred.jpg`).

Próximos pasos:
- Fase 3: re-exportar a ONNX con `imgsz=416` y reemplazar `app/public/models/coin-detector.onnx`.
- Validar latencia en la app (objetivo: ≥10 FPS en gama media).
- Si la latencia sigue insuficiente, considerar quantización INT8.